### ISSUE TITLE
Data presented only includes MAC for format 5 tag (one time only)

### ISSUE THREAD

**Issue by DG12** [ruuvi/com.ruuvi.station.ios#100]
Not sure when this tag, in the refrigerator, was last seen by station.ios but I think since new database structure.
How did it get MAC address and not any measurements?
![RuuviFridgeNoMesasuments](https://user-images.githubusercontent.com/2365961/87094711-5be02100-c20d-11ea-9f69-11d9a2892aa1.png)
A few seconds later all is well
![RuuviFridgeWithData](https://user-images.githubusercontent.com/2365961/87094716-5e427b00-c20d-11ea-8f27-70667fe617a8.jpeg)

**Comment by rinat-enikeev** [comment]
I could have heard advertisement with MAC included. And when you opened settings it was out of range.

**Comment by DG12** [comment]
Haven't ever seen this again.
