### ISSUE TITLE
Fix sensor view icons

### ISSUE THREAD

**Issue by sini-maaria** [ruuvi/com.ruuvi.station.ios#1001]
- Make the icons smaller
- Alert icon: 
* 100% opacity when the alert is on
* 50% icon when the alert is off
* 100% icon with animation when the alert is active

<img width="693" alt="Screenshot 2022-07-12 at 9 05 04" src="https://user-images.githubusercontent.com/19531763/178424368-f33da27e-24eb-491e-bacf-d96f7a398516.png">
<img width="700" alt="Screenshot 2022-07-12 at 9 05 17" src="https://user-images.githubusercontent.com/19531763/178424399-39adcc81-caea-4817-a128-25adb1057d2a.png">

**Comment by sini-maaria** [comment]
The icons could be even smaller.
(Don't mind the different gear icon, let's change it at some point.)

Image: Old icons on the left and the example how they should look. On the right is the current size.

<img width="1037" alt="Screenshot 2022-09-19 at 11 56 03" src="https://user-images.githubusercontent.com/19531763/190982878-9696aa68-45b5-4f42-b99a-4053cc889b7a.png">

**Comment by priyonto** [comment]
The touch targets are same. Just the icons are smaller now. I am hoping it would be okay. But, you can share feedback when it's pushed.

**Comment by sini-maaria** [comment]
They still don't seem to fit the row. Of course this is close enough, but if it is not a big task, please make them a bit smaller.

<img width="563" alt="Screenshot 2022-10-18 at 12 48 17" src="https://user-images.githubusercontent.com/19531763/196397232-4d540c5f-b954-40de-a687-64b549ccbe6d.png">

**Comment by priyonto** [comment]
I think it's because of the icon size/aspect ratio. Mostly the height is clipped a little on the top. If we make the height smaller, the icons will look quite small on the larger models like Pro Max one.

**Comment by DG12** [comment]
Spreading  them a little farther apart would be helpful.
