### ISSUE TITLE
Tag name doesn't display until app is closed and restarted.

### ISSUE THREAD

**Issue by DG12** [ruuvi/com.ruuvi.station.ios#101]
OK I deleted the app and reinstalled it.

I took the first tag and went to the tag settings to rename it. After 4 attempts I decided to close the app and restart it.
now the new name is shown.

**Comment by rinat-enikeev** [comment]
It was a bug with tag renaming. Should be fixed with upcoming Public Beta release.

**Comment by DG12** [comment]
Fixed in 0.6.3(1)
