### ISSUE TITLE
Add account deletion option

### ISSUE THREAD

**Issue by priyonto** [ruuvi/com.ruuvi.station.ios#1019]
To comply with Apple's guidelines- 
https://developer.apple.com/news/?id=12m75xbj

**Comment by markoaamunkajo** [comment]
@priyonto I requested deletion confirmation email on iOS app and opening it from Mac Mail app opens following URL:
https://station.ruuvi.com/verify-delete?token=8WQ9

Error: 404 not found

<img width="458" alt="Screenshot 2022-10-11 at 16 48 44" src="https://user-images.githubusercontent.com/50437378/195057703-88f2c89d-41af-4636-af4a-cd5e04060fdf.png">

**Comment by priyonto** [comment]
Since tapping on the delete account sends email, the app side is working well. I have created a related issue on Ruuvi Cloud repo. Closing this one.
