### ISSUE TITLE
Adding a new sensor doesn't always show tag page once selected

### ISSUE THREAD

**Issue by DG12** [ruuvi/com.ruuvi.station.ios#102]
From the add a sensor configuration screen, selecting a tag doesn't always show the panel for the tag selected. I actually didn't think the tag was added.

**Comment by rinat-enikeev** [comment]
Do you mean the Discover (add a sensor) screen is not always closing? Any hint for steps to reproduce?

**Comment by rinat-enikeev** [comment]
@DG12 please kindly help us with Steps To Reproduce

**Comment by DG12** [comment]
No longer a problem as of 0.7(73)
