### ISSUE TITLE
Implement '/check' endpoint for checking whether tag is claimed by someone else

### ISSUE THREAD

**Issue by priyonto** [ruuvi/com.ruuvi.station.ios#1022]
- Tag settings screen

**Comment by laurijamsa** [comment]
Is this something we need to implement only on iOS and client side only? Or backend?

**Comment by priyonto** [comment]
@laurijamsa The endpint is already implemented on the cloud. We have to implement the endpoint on the client side only now. At this moment, we only know the users masked email after a failed claim operation. This implementation will show the owners email upfront on the settings page.

**Comment by markoaamunkajo** [comment]
QA passed

**Comment by markoaamunkajo** [comment]
Sorry accidentally closed iOS card instead of Android..

**Comment by priyonto** [comment]
According to the discussion: We agreed to take a bit of time to discuss it more and implement it later. This is also related to the feature of force claiming a tag by the 'real' owner.

**Comment by markoaamunkajo** [comment]
@priyonto This is implemented and works on Android, let's add it to iOS too. Make sure it works exactly same as in Android:
When sensor is already claimed by another user don't even let user to access claim sensor page and check and show owner email immediately.

**Comment by markoaamunkajo** [comment]
QA passed
