### ISSUE TITLE
Clear/sync buttons even visible even this phone has never heard a single bluetooth message from this cloud sensor shared to me

### ISSUE THREAD

**Issue by laurijamsa** [ruuvi/com.ruuvi.station.ios#1027]
And when I press sync, I get this error message: ident_ios": "UnexpectedError.callbackErrorAndResultAreNil"

<img width="969" alt="image" src="https://user-images.githubusercontent.com/1311912/181245675-78a26b40-bc1e-43ea-8af8-177d3ad73afa.png">

**Comment by DG12** [comment]
same as issue #1036 ?

**Comment by markoaamunkajo** [comment]
QA passed
