### ISSUE TITLE
sync  "Both callback result and error are nil" on connecting ... (312) defect

### ISSUE THREAD

**Issue by DG12** [ruuvi/com.ruuvi.station.ios#1036]
sync to 
66A9 both... nil (restart app, shutdown/start iPhone, no help )
20BC  connecting.,,.,,.,.,  never timeout.
0981 success: 07-19 12:24 to 07-29 12:19
230E 1,2,3..zip,zip, 317 stall! Cancel. Next attempt "Synchronizing..." stall, kill app
24C2  zip, zip,...594,643,440,480,701,723,743,753,000,819,841,843,15nn... zip, zip, success ( Why slow down between 59x and 14nn)
4D15 zip, zip 564,594,629,652,676,694,721,726,758,784,807,.. zip, zip (as with 24C@2 ( Why slow down between 564 and 8nn ?)
Bluetooth was already enabled.
Signed in as DG@cccu.us (owner)

**Comment by DG12** [comment]
Unable to duplicate at this time. Perhaps it’s fixed

**Comment by DG12** [comment]
Occurred again 66A9 ( its one of my favorites)

**Comment by priyonto** [comment]
Is the tag has latest firmware?

**Comment by DG12** [comment]
SW: Ruuvi FWv3.31.1+debug
Should that matter?

**Comment by priyonto** [comment]
Yes, older fws had some issues but 3.31 should be working well. But,  the slow down issue is expected at the current latest firmware. We discussed about it and planning for a firmware update to improve that experience.

**Comment by DG12** [comment]
I would think that station IOS should never report this regardless of what the tag does.

**Comment by priyonto** [comment]
I did not understand what you meant here!

**Comment by DG12** [comment]
Station should either intercept or  check args this and display some "user friendly message".

**Comment by priyonto** [comment]
The error message popping shouldn't be there. So, yes, I will be checking that out.

**Comment by DG12** [comment]
Thanks

**Comment by DG12** [comment]
It is not that important. But it should be on the list.

**Comment by markoaamunkajo** [comment]
Unable to reproduce in latest build
