### ISSUE TITLE
export (and data table) contains excessive data points (312) - defect

### ISSUE THREAD

**Issue by DG12** [ruuvi/com.ruuvi.station.ios#1037]
Time periods between data points varies from 15 minutes to more than one per second!

36,595 rows !

[http://mybeacons.info/Porch_0981_20220729-1220.ods.gz](http://mybeacons.info/Porch_0981_20220729-1220.ods.gz) 
includes delta time column, TX power column removed (date/time in rows 12-17 manually altered )
 
[http://mybeacons.info/Porch_0981_20220729-1220.csv.gz](http://mybeacons.info/Porch_0981_20220729-1220.csv.gz) 

Notice rows 36,389-36,403 are missing RSSI, X,Y,Z movemeant count, sequence

**Comment by laurijamsa** [comment]
The latest builds have enhancements on these things. Closing this one. Please let us know if you notice similar issues in the future.
