### ISSUE TITLE
Enjoying Ruuvi Station ? does not submit (313)

### ISSUE THREAD

**Issue by DG12** [ruuvi/com.ruuvi.station.ios#1046]
After rating 5 stars and tapping submit, nothing happens.

Should I rate it only 4 stars? :-
![ratingDOesntSubmit](https://user-images.githubusercontent.com/2365961/182146829-525e8b7e-d6d7-4fee-b9da-81fcb1640bb8.jpeg)
)

**Comment by priyonto** [comment]
That's because it is a dev build. Rating can be submitted only on the App store build :)
