### ISSUE TITLE
export icon should be on graph screen - improvment

### ISSUE THREAD

**Issue by DG12** [ruuvi/com.ruuvi.station.ios#1047]
The Sensor Settings screen has the export icon but that does not export the settings.

The icon to export data points should be with the display of the data points.

**Comment by priyonto** [comment]
A discussion has taken place on this, and it's under consideration with some other major improvements.

**Comment by laurijamsa** [comment]
This has been implemented on Android already. Same design will be migrated to iOS too. Closing this issue.
