### ISSUE TITLE
Make tags return to normal state after GATT sync is terminated before completion

### ISSUE THREAD

**Issue by priyonto** [ruuvi/com.ruuvi.station.ios#1053]
More on this card shared here: #1035

**Comment by markoaamunkajo** [comment]
Implement same way as on Android.

**Comment by markoaamunkajo** [comment]
@priyonto 

First time returning to normal state took about few seconds
Second time about 40 seconds

Do you have ideas if this can be reliably returned to normal state in few seconds?

**Comment by markoaamunkajo** [comment]
When terminated by user action looks like it waits for about 10 seconds before returning to normal state. This is good.
