### ISSUE TITLE
tap sometimes does not respond (314)

### ISSUE THREAD

**Issue by DG12** [ruuvi/com.ruuvi.station.ios#1056]
Some sensors respond immediately after first tab but,
others (example 4D15) require as many as 9 taps 1 second apart before opening settings screen.

I cannot not find any correlation as to blue tooth updates, cloud updated or virtual tags.

**Comment by priyonto** [comment]
Hi, would you be able to attach a screen record, please? Thank you.

**Comment by DG12** [comment]
https://user-images.githubusercontent.com/2365961/185712889-2764ead2-aed1-49b0-9049-ec00a5e5dcb4.mp4
This is a new symptom as of 1.3.0(314)
4D15 and 230E and 22AB are within blue tooth range
No connection to gateway (i.e. cell & wifi are off) but they also usually do not respond.

**Comment by priyonto** [comment]
Thank you. We will investigate this.

**Comment by DG12** [comment]
I just had the same problem tapping on menu ( I.e. add new, app settings , about, …

**Comment by DG12** [comment]
One of the recent versions  368? 369? no longer exhibit this problem ! YES!!

Also battery usage seems significantly ++ reduced! .
