### ISSUE TITLE
Highlight the alerting value as WebUI does

### ISSUE THREAD

**Issue by ojousima** [ruuvi/com.ruuvi.station.ios#1058]
See also: https://feedback.ruuvi.com/posts/99/sensor-settings-page-for-alerting-sensor-should-highlight-offending-alert

**Comment by laurijamsa** [comment]
Closed Android's similar issue and will close this one too. https://github.com/ruuvi/com.ruuvi.station/issues/772

We're aiming to add a highlight color on the the upcoming dashboard new layout too. Also Android's updated sensor settings page is aimed to be implemented on the iOS too.
