### ISSUE TITLE
Hide the add new virtual sensor part from the app

### ISSUE THREAD

**Issue by laurijamsa** [ruuvi/com.ruuvi.station.ios#1062]
We're planning to deprecate the virtual sensor feature step by step by first making it not possible to add new ones. This feature has no many users and we've received feedback about confusions where users think that they're adding a Ruuvi sensor but instead they added a virtual one. Some users are instead confused that virtual sensors show different temperature than Ruuvis do.

<img width="373" alt="image" src="https://user-images.githubusercontent.com/1311912/186649365-e75c394f-1351-419b-be8f-e718b44a5bd1.png">

**Comment by DG12** [comment]
I like and use virtual sensors all the time.

Perhaps an app setting to permit them (initially disabled ) would be better, especially since they are already implemented.

**Comment by markoaamunkajo** [comment]
QA passed but have to remember to check migration.

**Comment by markoaamunkajo** [comment]
Checked with TF build, QA passed
