### ISSUE TITLE
with Database from 1.3.0(314) , using app 1.2.1(304) cannot add sensor.

### ISSUE THREAD

**Issue by DG12** [ruuvi/com.ruuvi.station.ios#1063]
After having version 1.3.0(304) running. Install 1.2.1(304) from appStore.

Attempt to add is quietly ignored.

reported by user Aki
I was alet to duplicate this (at least once)

Might this be an attempt to access the database without checking for exceptions?

**Comment by laurijamsa** [comment]
I think we don't need to support downgrading from dev builds, so this issue can be closed. If you think that the problem is something else, please let us know.
