### ISSUE TITLE
Cannot signin 1.3.0(314) - serious defect

### ISSUE THREAD

**Issue by DG12** [ruuvi/com.ruuvi.station.ios#1065]
I am at home, good wifi connection , -50dBm.

tap signin
enter email
request code
received email
enter code

spin, spin, spin

https://user-images.githubusercontent.com/2365961/187115352-3a29405e-411f-481b-aead-a5dd2220907b.mp4

Cannot cancel, must kill app.

Restart app, works ok!

kill, restart app, enter code, spin,inip,spin, works!

logout,
kill, restart app, ...enter code, spin,spin,spin,spin,spin,spin,spin, finally works.

**Comment by priyonto** [comment]
I have tested it in an average connection, and it looks like it is working as expected. 
But, I can think of a couple of reasons why it was happening to you. 

1. The network was not consistently reliable but you mentioned it was good. 
2. You had a good amount of cloud sensors added to your account. When a user logs in, all the cloud sensors alongside 10 days of history are fetched and stored on the local database. That takes time and shows the spinner. And if the connection is weak that can longer than expected.

**Comment by priyonto** [comment]
@markoaamunkajo Please check on your end, if it's not reproducible please close it.

**Comment by DG12** [comment]
Best connection ever at -50dBm.
Anyway closing until it happens again.
