### ISSUE TITLE
neither sign out nor sign in is displayed - defect (314)

### ISSUE THREAD

**Issue by DG12** [ruuvi/com.ruuvi.station.ios#1066]
Normally 
if not signed offers signin
If signed in shows login and offers sign out

See attached with has neither:

![ruuviNotSingedNorOff](https://user-images.githubusercontent.com/2365961/187284966-f3d247ca-0faf-4a25-a2ae-2468edd3d068.PNG)

Normal signed in:
![ruuviSignedIn](https://user-images.githubusercontent.com/2365961/187286492-93ea5034-cc08-462f-b90e-af3328f80e95.PNG)

Normal signed out:
![ruuviSIgnedOut](https://user-images.githubusercontent.com/2365961/187287064-c83fd1bd-f820-4763-a760-bf4425422426.jpeg)

**Comment by markoaamunkajo** [comment]
Still appears in 1.3.0(317)

![IMG_BDE04C92A531-1](https://user-images.githubusercontent.com/50437378/194793647-318eed1f-7b85-46d4-be89-8d9e40adb2fe.jpeg)

**Comment by laurijamsa** [comment]
My Ruuvi Account link is there so all is good @markoaamunkajo

**Comment by markoaamunkajo** [comment]
Ah my bad I forgot it's new menu item

**Comment by DG12** [comment]
"Sign in" is now on "main" screen.
Once user has signed in, "Sign in"  becomes "My Ruuvi Account".
"Sign out" is included on "My Ruuvi Account".

**Comment by priyonto** [comment]
Closing this one as this is working on the current dev build.
