### ISSUE TITLE
Incorrect analysis of firmware version - 1.3.0(314) - defect - minor

### ISSUE THREAD

**Issue by DG12** [ruuvi/com.ruuvi.station.ios#1067]
In situations where iPhone is at periphery of BT range, the app says firmware is"very old" for a while but eventually shows "v3.31.1+default".

Perhaps better wording would be "undetermined".

**Comment by laurijamsa** [comment]
This isn't an iOS issue. We'll consider the wording on https://github.com/ruuvi/station.localization/blob/dev/station.localization.json and may make changes later on. Closing.
