### ISSUE TITLE
Attempting to get  latest available Ruuvi Firmware version - times out 

### ISSUE THREAD

**Issue by DG12** [ruuvi/com.ruuvi.station.ios#1068]
After a very long :"The request timed out"

(I thought this used to work)

**Comment by priyonto** [comment]
Is the tag in range?

**Comment by DG12** [comment]
Tag is .5 meters away.

**Comment by laurijamsa** [comment]
We haven't been able to reproduce. Please let us know if you can reproduce this issue with the latest builds.
