### ISSUE TITLE
sync stalls -  - defect

### ISSUE THREAD

**Issue by DG12** [ruuvi/com.ruuvi.station.ios#1069]
tag 230E is .5 meters away, receiving BT updates every 2,1 0 multiple sub zero intervals.
tapping cancel reports :
"history downloading via Bluetooth connection is in progress.Please wait:
![230E_Sync_0948](https://user-images.githubusercontent.com/2365961/188467281-2634189c-a001-4000-af84-73d4f656202f.PNG)
![230E_sync_0956](https://user-images.githubusercontent.com/2365961/188467312-cd6af780-8205-4e4a-aa02-df303ac559ca.PNG)

OK returns to stalled condition

++++++++++++++++++++++++++++++
 Next attempt stalls reading history .. 54
++++++++++++++++++++++++++++++
Next attempt stalls Synchronizing.
must kill app
++++++++++++++++++++++++++++++
next time display graph is delayed 5-6 seconds.
stalls syncing
++++++++++++++++++++++++++++++
next time display graph is delayed 6-7 seconds.
stalls syncing
++++++++++++++++++++++++++++++
next time CLEAR, sun c connecting, connecting, ...time out after 30 seconds.
Android successfully syncs.
+++++++++++++++++++++++++=
next time CLEAR 
readings added to graph ever few(?) seconds.
SYNC success
export already has 31 entries
"Date","Temperature (°F)","Humidity (%)","Pressure (inHg)",RSSI (dBm),Acceleration X (g),Acceleration Y (g),Acceleration Z (g),"Voltage (V)","Movement Counter" (movements),"Measurement Sequence Number","TX Power" (dBm)
"2022-09-05 10:11:46",79.45,100.00,29.64,,,,,,,,
"2022-09-05 10:16:47",77.13,100.00,29.64,,,,,,,,
"2022-09-05 10:17:57",76.49,100.00,29.64,-49,0.260,0.084,0.968,2.756,7,146,4
"2022-09-05 10:18:00",76.46,100.00,29.64,-47,0.260,0.076,0.972,2.756,7,147,4
"2022-09-05 10:18:02",76.45,100.00,29.64,-47,0.248,0.076,0.960,2.756,7,148,4
"2022-09-05 10:18:04",76.42,100.00,29.64,-53,0.252,0.084,0.968,2.756,7,149,4
"2022-09-05 10:18:07",76.41,100.00,29.64,-51,0.256,0.080,0.964,2.756,7,150,4
"2022-09-05 10:18:12",76.37,100.00,29.64,-46,0.252,0.080,0.964,2.756,7,152,4
"2022-09-05 10:18:15",76.34,100.00,29.64,-47,0.252,0.076,0.960,2.756,7,153,4
"2022-09-05 10:18:17",76.32,100.00,29.64,-47,0.260,0.080,0.960,2.756,7,154,4
"2022-09-05 10:18:20",76.30,100.00,29.64,-47,0.252,0.072,0.964,2.756,7,155,4
"2022-09-05 10:18:23",76.29,100.00,29.64,-47,0.256,0.080,0.960,2.756,7,156,4
"2022-09-05 10:18:27",76.24,100.00,29.64,-47,0.256,0.072,0.968,2.756,7,158,4
"2022-09-05 10:18:30",76.23,100.00,29.64,-47,0.252,0.080,0.964,2.756,7,159,4
"2022-09-05 10:18:35",76.18,100.00,29.64,-46,0.264,0.076,0.968,2.756,7,161,4
"2022-09-05 10:18:38",76.16,100.00,29.64,-48,0.264,0.076,0.960,2.756,7,162,4
"2022-09-05 10:18:40",76.14,100.00,29.64,-47,0.260,0.076,0.968,2.756,7,163,4
"2022-09-05 10:18:46",76.10,100.00,29.64,-47,0.252,0.076,0.972,2.756,7,165,4
"2022-09-05 10:18:48",76.08,100.00,29.64,-50,0.256,0.076,0.968,2.756,7,166,4
"2022-09-05 10:18:51",76.06,100.00,29.64,-41,0.256,0.080,0.964,2.756,7,167,4
"2022-09-05 10:18:54",76.05,100.00,29.64,,0.260,0.068,0.972,2.756,7,169,4
"2022-09-05 10:19:04",75.96,100.00,29.64,-47,0.256,0.076,0.964,2.760,7,173,4
"2022-09-05 10:19:09",75.93,100.00,29.64,-48,0.260,0.076,0.972,2.760,7,175,4
"2022-09-05 10:19:12",75.91,100.00,29.64,-52,0.252,0.072,0.964,2.760,7,176,4
"2022-09-05 10:19:15",75.89,100.00,29.64,-53,0.256,0.076,0.964,2.760,7,177,4
"2022-09-05 10:19:17",75.87,100.00,29.64,-56,0.260,0.080,0.964,2.760,7,178,4
"2022-09-05 10:19:19",75.86,100.00,29.64,-59,0.264,0.076,0.964,2.760,7,179,4
"2022-09-05 10:19:22",75.84,100.00,29.64,-57,0.252,0.076,0.960,2.760,7,180,4
"2022-09-05 10:19:25",75.83,100.00,29.64,-46,0.256,0.080,0.960,2.760,7,181,4
"2022-09-05 10:19:27",75.80,100.00,29.64,-49,0.252,0.080,0.960,2.760,7,182,
+++++++++++++++++++++++++++++++++++++++++++++++
Graph now shows data from before 1:00AM 08/28 and beyond 1:00AM 09/05
Must have gotten update from CLoud.
![image](https://user-images.githubusercontent.com/2365961/188470960-bfa0db04-7bbe-468d-9876-19e5666dc9d2.png)
+++++++++++++++++++++++++++++++++++++++++++++
sync connecting,,,,,,,sync, success !
next sync connecting ,,,,,,,,,,,,,,,,,, time out after 30 seconds.
+++++++++++++++++++++++++++++++++++++++++++++
next sync connecting,,,,,,,,,,,,,,,,,,,,, time out after 30 seconds.
+++++++++++++++++++++++++++++++++++++++++++++
next sync    synchronizing ... , , , , , , , , , , , , , , ,,, ,,,,  , , , 
+++++++++++++++++++++++++++++++++++++++++++++

I'm falling asleep here.
"Only an idiot keeps doing the same thing and expects a different result" :-(
but different things are happening!!

Disable WIFI
Clear, wait  while graph continues to update, now shows. 10:54 .. 10:59
graph continues to update noe 10:54 .. 11:02 but still reading ... 7
cancel does cancel

sync. synchronizing ,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,(each  ','  is about 1 second) ,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,     ,
graph now shows. 10:54 .. 10:05

tap gear, sensor settings appears, tap thermometer: Are you sure?...

abort downloading!

SYNC reading history ... 7.  stall.  graph continues to update

**Comment by laurijamsa** [comment]
Can you reproduce this with the latest build? So far, we haven't seen this problem. If you can, could you please share a video?

**Comment by markoaamunkajo** [comment]
Waiting for your comment @DG12

**Comment by DG12** [comment]
I have not had to kill the app lately. 

The problem with sync stalling continues. 
I cannot get a successful sync on most of my tags. Some nearby some at the edge of radio range.
++++
For this session (11/28/22 A) I will 
0) Restart the iPhone XS
1) Remove app and install (323) .
2) Disable wifi
3) Start the app. 
4) Add 1 tag.
5) Wait 5 minutes to accumulate advertisments
6) sync
Video to follow.

**Comment by DG12** [comment]
VIdeo
http://mybeacons.info/20221128_230e.html

**Comment by markoaamunkajo** [comment]
@DG12 I was unable to open your video link.

For me the stalling is not an issue unless sensor is far beyond the -90dB. In attached video you can see different dB range sensors being added and then attempted a scan.

https://drive.google.com/file/d/1lGDrtMHBMvrMWXqDsF5WQoQHiXXgwHS4/view?usp=share_link

Is your experience somewhat different?

**Comment by DG12** [comment]
Sorry aggressive cleanup just yesterday.
I'l either retrieve it from backup or create a new one.
This happens to me nearly all the time.
It seems that once a packet is missed, either there is no timeout or a new request needs to be issued.

**Comment by DG12** [comment]
An aside:>Can you explain why  counter runs at extremely varying speeds. Sometimes it runs so fast that you cannot even watch the numbers. In the same sync there are seconds between counts zoommm, 43,49,69,64,101,zoomzooom573,..574,..575,..578.,631,666,zoooommmmmm, 
Have you seen this ? Should I add a video?

**Comment by markoaamunkajo** [comment]
@priyonto might be able to explain this and yes it happens to me too, typically around 500 block.

**Comment by DG12** [comment]
Put a ruuvi in the refrigerator. This severely attenuates the radio but you can change that by opening the door.

**Comment by DG12** [comment]
Sync Still stalls in (327)

**Comment by priyonto** [comment]
This issue was not addressed on 327. I would suggest to wait few more days for this. We have some critical issues to fix first. :)

**Comment by markoaamunkajo** [comment]
This is such an interesting case. I can see this behaving differently on different fw even. On Android trying to sync this specific sensor is stopping at 1250 exactly.

![IMG_0814](https://user-images.githubusercontent.com/50437378/218638465-aa1bb61c-05f8-4703-a2a0-0c1a9f0ff155.PNG)
![IMG_0813](https://user-images.githubusercontent.com/50437378/218638472-703cdbc3-e319-4e0f-95b8-3c5171cf0114.PNG)

**Comment by ojousima** [comment]
> An aside:>Can you explain why counter runs at extremely varying speeds.

This is related to Bluetooth Connection Length Extension. 
Tag sends data as much as it can until something breaks the connection in interval and then it has to wait for the next interval.

**Comment by ojousima** [comment]
> This is such an interesting case. I can see this behaving differently on different fw even. On Android trying to sync this specific sensor is stopping at 1250 exactly @andreevdenis

1250 would be a flash page boundary, It makes me think that flash itself might have questionable data. That should be cleared in sensor reboot though

**Comment by markoaamunkajo** [comment]
Customer reported having same experience, issue isn't cleared by moving closer to sensor when performing GATT sync.

**Comment by markoaamunkajo** [comment]
Investigated as firmware issue.
