### ISSUE TITLE
GRDB.PersistenceError error 0 on latest iOS app store release

### ISSUE THREAD

**Issue by alexhk** [ruuvi/com.ruuvi.station.ios#107]
I have been using RuuviStation for a long time, but this is the first time I run into problems.

This error pops up in an endless loop on version 0.6 on the app store, making it impossible to use the app.

If I start it with Bluetooth off, I can access the app and the error doesn't show until I open the settings of a sensor and close it again.
 
![image](https://user-images.githubusercontent.com/1495412/89121361-847ed200-d4be-11ea-8b1a-d847adc8dea5.png)

**Comment by rinat-enikeev** [comment]
Hi @alexhk. I'm super sorry. Could you please give some more details? Is it persistent across app reinstalls?

**Comment by rinat-enikeev** [comment]
This error indicates that the library GRDB can't open the database.

**Comment by alexhk** [comment]
I can try to uninstall and re-install, but I have 20+ sensors and all manually named.
Give me a few mins.

**Comment by alexhk** [comment]
I deleted the app and started adding my tags again. It seems to work.

Stupid iOS with their UUID, now I need to walk around the place and add the sensors one by one, as RuuviStation doesn't allow sorting the tags once they are added and I can't identify them by the UUID only.

**Comment by rinat-enikeev** [comment]
@alexhk I'm very sorry you've faced database error... Feature request for reordering the tags noted! 

THank you very much for the feedback.

**Comment by alexhk** [comment]
No problems @rinat-enikeev !
I found another issue, repeated twice (deleted Ruuvi Station again and started all over).

I am adding the first 4 sensors. Every time I add one I rename it 1, 2, 3 etc .
The 5th one shows up with Ruuvi 55AE. I rename it to 5. Now that's where things go wrong. It renames the 4th sensor instead of the 5th one and the 5th one stays Ruuvi 55AE. Don't ask me what's going on. As said, after adding 21 sensors I started all over again since I thought I messed up somewhere, but it's the app :/

Now here is where it gets interesting. I keep going and add no. 6, then rename it to "6". It again renames the 4th one to 6. Not the 5th, not the 6th.

I then deleted all the sensors, except no. 1. After closing the app and restarting it, now the one left (no.1) showed up as 4. And it is actually no. 4, not just no. 1 renamed as 4.

And yes, I had enough sleep and enough coffee. It's not me. Apologies for the mess on this Sunday.

I guess I'll have to wait for another update or setup betas again in Testflight if that's still being done.

Alex

**Comment by rinat-enikeev** [comment]
Finally we managed to reproduce. Steps: 

1. Uninstall app 
2. Set one RuuviTag with firmware version 2.5.9 to data format 3 mode
3. Install the app and add the RuuviTag from [2]
4. Upgrade firmware on RuuviTag

Expected: all goes well
Actual: continuous errors

Reason: we handled migration but didn't caught the case when tag is added with data format 3 mode to Realm and then upgrades firmware. 

The fix is here: https://github.com/ruuvi/com.ruuvi.station.ios/pull/121.

**Comment by soinipe** [comment]
Reproduced similar way as others after tag firmware update to 2.5.9. Tested 0.6.1(18)  on [TestFlight](https://f.ruuvi.com/t/ruuvi-station-ios-public-beta-join-testflight/3192/18) when already had been falling into this problem with store version (SW version 0.6). Same endless loop problem, error keeps popping up and need to kill app.

Powered off the tag due excessive error messages. Tried to delete the problematic tag but it cannot be deleted. Renaming pops up the very same error. Killing application / reboot phone/tag did not help. I removed and re-installed application, rand added tags, looks ok. Very good, helps a lot that app shows now a few bytes from BT address, I was very lucky that had already addresses listed manually.

I wonder if it is another bug that you cannot delete tag for which you have not received data (temperature value is "-"). For this kind of tag the setting wheel is disabled. I had one lost tag with "-" and could not edit that either.

**Comment by markoaamunkajo** [comment]
1. Install app (I tested with 0.6.1(20)
2. Add tag with firmware 2.5.9 running in df3 mode
3. Update firmware to 3.29.3 with nRF connect
4. Open app and it's giving GRDB
5. Updated app to 0.6.2(5) tag is giving GRDB error

Moving back for reinvestigation

**Comment by rinat-enikeev** [comment]
0.6.3(1) in TF

**Comment by markoaamunkajo** [comment]
QA passed
