### ISSUE TITLE
Rounding on Y axis leads to big errors

### ISSUE THREAD

**Issue by laurijamsa** [ruuvi/com.ruuvi.station.ios#1070]
This video of toggling between 3 separate screenshots describes the issue better than thousand words:

https://user-images.githubusercontent.com/1311912/189322283-1e3c00c2-de87-47e4-b98a-81da0a19b5df.mov

**Comment by priyonto** [comment]
@markoaamunkajo Need your help on this one. I was not able to reproduce the issue. Please try on your end too. Also we not have much information since it's user feedback. Thanks.

**Comment by markoaamunkajo** [comment]
@priyonto I cannot reproduce this yet on latest dev build. I can see rounding happening in the video though. Is it possible that this is some old build?

**Comment by markoaamunkajo** [comment]
Reproduced. This will be fixed with new implementation for scaling Y-axis in charts
