### ISSUE TITLE
Plan the roadmap for dropping DF3 tags support from iOS app

### ISSUE THREAD

**Issue by priyonto** [ruuvi/com.ruuvi.station.ios#1071]

**Comment by DG12** [comment]
Since the code is already present for format 03 is there a reason to "officially" drop support??

**Comment by laurijamsa** [comment]
We discussed with Marko that next steps on this could be to first send in app messages to all users who have old dataformat sensors on their apps telling to update. But before doing so, issue #1128 has to be completed.

**Comment by markoaamunkajo** [comment]
Closed with card https://github.com/ruuvi/com.ruuvi.station.ios/issues/1508
User will get update nag every time when opening sensor card.
