### ISSUE TITLE
Chart select baseline points incorrectly 01:00 instead 00:00

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station.ios#1072]
Description:

Chart is selecting baseline points incorrectly, possibly due to summertime daylight saving settings.

Refer to same issue on Android board: https://github.com/ruuvi/com.ruuvi.station/issues/778

**Comment by andreevdenis** [comment]
@priyonto my fix:
https://github.com/ruuvi/com.ruuvi.station/commit/c7ad81139124c9f91bce4fe3bacabc221fb30ce0
We should consider daylight saving for proper timeline. I didn't seen this issue because we don't have daylight saving here locally.

**Comment by priyonto** [comment]
Thank you @andreevdenis , I will make the same changes in iOS too. :)

**Comment by markoaamunkajo** [comment]
QA passed
