### ISSUE TITLE
Investigate the lagging and performance issues across the app

### ISSUE THREAD

**Issue by priyonto** [ruuvi/com.ruuvi.station.ios#1078]
- Card and tag settings pages have noticeably higher lagging than other pages.

**Comment by priyonto** [comment]
@rinat-enikeev Suggested moving the Ruuvi Cloud related implementations to the background thread. We will try implementing that for the cards page first.

**Comment by markoaamunkajo** [comment]
@priyonto on iPhone 7 and iPhone 6S Plus iOS 15.7 lag is starting to appear in few minutes swiping between sensor cards when app is kept on foreground.

**Comment by priyonto** [comment]
@markoaamunkajo Please test v2.0 to see if you notice similar performance issues.

**Comment by markoaamunkajo** [comment]
@priyonto 2.0 builds are performing well for me on iPhone SE and iPhone 14 Pro
