### ISSUE TITLE
Improve charts rendering speed and overall experience

### ISSUE THREAD

**Issue by priyonto** [ruuvi/com.ruuvi.station.ios#1081]
- Charts screen lags now when the full 10 days of data is rendered or when the draw dots are enabled with a good amount of measurements.

**Comment by priyonto** [comment]
Discussion on last week: 
We will disable the "Draw Dots" feature for specific devices since it's a heavy operation that takes a lot of CPU and memory resources and older devices cannot handle that. However, we will continue to improve the chart rendering performance overall.

**Comment by markoaamunkajo** [comment]
@priyonto When I signed in to cloud I always get dots in my charts. How do we define which devices get them?

**Comment by priyonto** [comment]
Showing dots from cloud issue is fixed but that build is mot yet pushed. I am expecting it to push tomorrow.

**Comment by markoaamunkajo** [comment]
QA passed
