### ISSUE TITLE
Graph refreshes every 30 +/- seconds - (315) - defect

### ISSUE THREAD

**Issue by DG12** [ruuvi/com.ruuvi.station.ios#1085]
Display graph "delays" for several seconds. Then graph appears.
Leaving the graph exposed for any of several ruuvi tags.
Suddenly, after 30 seconds +'- the screen blanks, graph lines appear then a few seconds the graph appears.
The [video](http://mybeacons.info/220929_graphRefreshesHyperVideo.html) is from an android in "hyperlapse" which shows a few minutes is several seconds.

**Comment by markoaamunkajo** [comment]
This is working for me, moving to done

**Comment by markoaamunkajo** [comment]
Reopened, it seems it doesn't work reliably, check attached video
For the case when it seemingly was working I was logged into Ruuvi Cloud and added local BT sensor.

https://user-images.githubusercontent.com/50437378/195967682-337fb55c-7a78-4272-92b6-6176bbfe8d41.mov


https://user-images.githubusercontent.com/50437378/195967690-3a026e5d-4916-4a80-a21a-db17e9d1146a.mov

**Comment by markoaamunkajo** [comment]
@priyonto 
1.3.0(319)
Logged into cloud, in mixed mode, then added one local BT sensor


Looks like if I have local sensor and I first make GATT sync and then Clear the chart I get no new dots drawn on the chart at all, even if I exit chart screen to sensor card screen and back. If I kill app I get new data drawn into chart.

**Comment by priyonto** [comment]
I am closing this card since the original issue is fixed. I have created #1121 to work on the newly reported issue.
