### ISSUE TITLE
Developer Mode required. 316

### ISSUE THREAD

**Issue by DG12** [ruuvi/com.ruuvi.station.ios#1092]
Release build (316) requires developer mode enabled.
How do I do that?

![image](https://user-images.githubusercontent.com/2365961/194725550-56f47bf6-48c1-4300-a73a-6ee9bbbfa6b0.png)

PS 
Firebase App Distribution requires deleting. app AND DATA.

**Comment by priyonto** [comment]
This is an iOS 16 setting. Please follow this: 
https://developer.apple.com/documentation/xcode/enabling-developer-mode-on-a-device
<img width="981" alt="Screenshot 2022-10-08 at 11 08 54 PM" src="https://user-images.githubusercontent.com/24395776/194727903-2dcbecd2-ac8c-4419-8bf3-53696078301c.png">

**Comment by DG12** [comment]
Thanks.

UGH! Apple is trying to cripple all of us.
Bad guys are winning because good guys cannot get anything done.

**Comment by priyonto** [comment]
Not sure what you mean, but closing this one :D
