### ISSUE TITLE
Scale Y-axis to logical values

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station.ios#1095]
Description:

Currently X-axis implementation uses logical zoom grid values 1h, 30 minutes, 15 minutes, 10 minutes, etc. but Y-axis doesn't lock to logical grid values both in iOS and Android apps.

Apps should follow same implementation as on Web, where logical grid values are used already.

<img width="1436" alt="webui example 2" src="https://user-images.githubusercontent.com/50437378/195969911-0ed04b46-3446-47bc-bbb2-8240e70a3ca1.png">
<img width="1428" alt="webui example 1" src="https://user-images.githubusercontent.com/50437378/195969913-a9c26b10-66ca-48cc-b18b-564edc698832.png">

**Comment by DG12** [comment]
Does this include re-scaling the Y-axis as newly arriving data exceeds the current y-max or y-min. Should this be a separate issue?
Currently the entire x-axis is re-scaled as data is received, that's a good thing.
The x-axis is not, that not. a good thing.
Example current y-min is 24 new data starts being received at 23, 22... graph is truncated at the 24 limit. See attached screen shot.

![Y-axis_needs_rescaling_max_and_min](https://user-images.githubusercontent.com/2365961/206904267-262824a0-9a3b-4d93-92ec-a8d70841b119.PNG)

**Comment by markoaamunkajo** [comment]
@priyonto 2.1.0(368), iPhone 14 Pro
I see some overlapping and cut values

![Image](https://user-images.githubusercontent.com/50437378/232367436-14bddd48-5e54-457d-8feb-8740cac94b35.jpg)

**Comment by markoaamunkajo** [comment]
@priyonto too many characters are being shown for pressure and it breaks the layout.

![Image](https://user-images.githubusercontent.com/50437378/233893105-2527f9a4-94df-49e0-833f-301bdaa02ec0.jpg)
