### ISSUE TITLE
Show cursor value on screen (just like on Android)

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station.ios#1097]
Description:

Webui supports dragging mouse over chart and showing precise values under chart area as "Time and value".

Let's implement this to iOS and Android apps for showing precise timestamp and values when long tap on screen.
Example: Time 15:32:14 Temperature (20 °C)

![cursor_time_value](https://user-images.githubusercontent.com/50437378/195970872-f0cbe780-6181-4b04-9bfa-9d0025c5b4c5.jpg)

Web implementation:
<img width="477" alt="Screenshot 2022-10-15 at 12 36 58" src="https://user-images.githubusercontent.com/50437378/195970802-0500e64f-e865-4146-a55d-ae966d2e893b.png">

https://user-images.githubusercontent.com/50437378/195970586-c8eddcb2-93ee-4a59-a980-1c4b287ed360.mov

**Comment by laurijamsa** [comment]
Android has a date stamp. Are you testing against an old Android build?

**Comment by markoaamunkajo** [comment]
Oh, looks like 1.15.9 with updated translations doesn't show date. Will fix the description.

**Comment by markoaamunkajo** [comment]
@priyonto

2.0.0.(334)

Currently the cursor tooltip has ability to go hiding like this:
![hiding](https://user-images.githubusercontent.com/50437378/217202286-ffe03410-a5f7-438a-9b16-5946e82a1dc6.jpg)

Let's instead hide it same way as on Android since it's cleaner.

https://user-images.githubusercontent.com/50437378/217201760-c0ad5ff2-56a9-49bd-869b-f65a6fef0070.mp4

**Comment by markoaamunkajo** [comment]
QA passed
