### ISSUE TITLE
Unification: show latest value in chart ()

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station.ios#1098]
Description:

We recently added showing last recorded value in charts inside parenthesis in Android app.
Let's bring this to iOS app as well.

![lastrecordedvalue](https://user-images.githubusercontent.com/50437378/195971200-407a47ec-d5a5-46b3-a511-d0208c960dde.jpg)

Note also task about showing cursor value on long tap https://github.com/ruuvi/com.ruuvi.station.ios/issues/1097

**Comment by markoaamunkajo** [comment]
2.0.0(331) Last value in chart doesn't respect resolution or localisation.

**Comment by priyonto** [comment]
Fixed on #1097
