### ISSUE TITLE
Sound Alerts

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station.ios#1100]
Description:

Implement same way as on Android
Card: https://github.com/ruuvi/com.ruuvi.station/issues/819

(Push alert settings will be handled on other card, this only for sound and settings)

**Comment by priyonto** [comment]
iOS is a bit different than the Android. According to the discussion we will implement a settings option for sounds that will show a page with list of custom sounds, starting with system and then Ruuvi sounds.

**Comment by markoaamunkajo** [comment]
Add placeholder string for Notification settings link 
"You can also adjust Notification settings under iOS Settings -> Notifications"

**Comment by markoaamunkajo** [comment]
QA passed
