### ISSUE TITLE
App freezing

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station.ios#1102]
Description:

1.3.0(318)  iPhone 7, iOS 15.7

During testing I kept my device long time in Background setting page while making a card.
Then I noticed that app started behaving very badly - cannot move between cards, very sluggish to open chart view.

https://user-images.githubusercontent.com/50437378/195974024-6d6b2d7c-aa2c-4a00-b915-b4fb6771da8f.mov

My settings are
Signed into cloud, Cloud mode on
Chart settings: display all data in chart disabled
Background: data logging interval disabled

**Comment by priyonto** [comment]
I have investigated this for a couple of hours. I noticed a decrease in performance for sure but the charts load normally for me in different conditions like opening the app from the background, from the inactive state, or when in the foreground with the settings page open. 

The issue for me was sliding the card was not happening smoothly. And based on the performance benchmarking it seems that's related to the performance issue/lagging we were reported earlier. I am afraid this is not an issue with a simple fix. It's related to #1078.

**Comment by priyonto** [comment]
Closing this one. Will follow up this issue on #1078
