### ISSUE TITLE
Update GRDB to the latest version and update Ruuvi Reactor module accordingly

### ISSUE THREAD

**Issue by priyonto** [ruuvi/com.ruuvi.station.ios#1117]

**Comment by priyonto** [comment]
The upgrade will require breaking changes to the app architecture, which is not necessary at this moment. The threading issues are sorted. Closing this one. Will perhaps revisit it if required at some point.

**Comment by rinat-enikeev** [comment]
2.6.1

**Comment by markoaamunkajo** [comment]
Went through app on my devices and didn't find any apparent issues. Build is sent to beta.
