### ISSUE TITLE
Advertisements dropping points

### ISSUE THREAD

**Issue by priyonto** [ruuvi/com.ruuvi.station.ios#1121]
More about this on #1085

**Comment by markoaamunkajo** [comment]
2.0 cannot reproduce for now.

**Comment by markoaamunkajo** [comment]
No crash in (356) but charts still keeps disappearing. This card was mentioned so adding comment here.

**Comment by markoaamunkajo** [comment]
Kept app in foreground and collected advertisements for quite some time, for me I didn't spot any issues.
I will still try to keep an eye open for missing charts.

**Comment by markoaamunkajo** [comment]
Added and removed a lot of sensors and I cannot see how charts would get missing anymore.
QA passed for me
