### ISSUE TITLE
Alerts are not throttled

### ISSUE THREAD

**Issue by ojousima** [ruuvi/com.ruuvi.station.ios#1122]
Please see https://github.com/ruuvi/ruuvi-network-serverless/issues/238, since this is popups in app my guess is that this is iOS and not backend related?

**Comment by priyonto** [comment]
Thanks. This seems like an iOS issue. I will work on that.

**Comment by priyonto** [comment]
Failed to reproduce it on my end. 

@markoaamunkajo Please check on your end too. Will close if we can't reproduce it.

**Comment by markoaamunkajo** [comment]
I cannot reproduce with AppStore version. Moving this to done without findings.
