### ISSUE TITLE
Show full firmware version number including the variant

### ISSUE THREAD

**Issue by priyonto** [ruuvi/com.ruuvi.station.ios#1131]

**Comment by markoaamunkajo** [comment]
@priyonto I am seeing "+default" already with 3.31.1
Is this what we discussed at meeting?

**Comment by priyonto** [comment]
@markoaamunkajo  No, this is not done on the app side yet. The API we are using doesn't return full version and it was discussed to @ojousima. I need more instruction for this task. 

Using this one on the iOS app: https://api.github.com/repos/ruuvi/ruuvi.firmware.c/releases/latest

**Comment by markoaamunkajo** [comment]
Discussed in meeting @priyonto will test out some ideas. Unassigning myself for now.

**Comment by markoaamunkajo** [comment]
QA passed
