### ISSUE TITLE
Add Buy Ruuvi Sensors button to Add a New Sensor page

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station.ios#1137]
Description:

Let's add Buy Ruuvi Sensors button to bottom of Add a New Sensor page same as on Android

Remember to use correct URL's according to Language

![buybutton](https://user-images.githubusercontent.com/50437378/200993262-22bccffc-3139-45ca-8477-402335ec82aa.jpg)

**Comment by hakunti** [comment]
Can we add this UTM tag to the link: ?utm_campaign=app_ua&utm_medium=referral&utm_source=ios

**Comment by markoaamunkajo** [comment]
@priyonto issue opened for @andreevdenis to check these together with you
https://github.com/ruuvi/station.localization/issues/108

**Comment by markoaamunkajo** [comment]
QA passed
