### ISSUE TITLE
Connection and cascaded alerts in sensor settings

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station.ios#1140]
Description:

1. Currently if user is in connected mode we hide Connection and Alerts sections from Sensor Settings if user has added same sensor on another iOS Ruuvi Station. We also show Very Old under Firmware on another Ruuvi Station because of this.

Let's instead keep them visible and show information for user why alerts or connection is not available when trying to enable pairing.

2. Cascade Alert Settings so they are opening when tap on arrow and are editable even when alert is not enabled and sensor is not in paired mode.

- alerts disabled info button will be removed
- alerts are editable even when not paired or alert enabled
- check localization file doesn't have old strings

![pairing-not-paired_cascade](https://user-images.githubusercontent.com/50437378/201457901-b0a84b94-5e44-43a6-8e41-60730a55adcd.jpg)

There is another card for Keep connection related popups https://github.com/ruuvi/station.localization/issues/106

**Comment by priyonto** [comment]
@markoaamunkajo The message seems not right to me. 

// Only one iOS device can be paired to Ruuvi Station at a time// - is that correct? Should it be RuuviTag instead of Ruuvi Station?

**Comment by laurijamsa** [comment]
> Should it be RuuviTag instead of Ruuvi Station?

Correct. Shouldn't be Ruuvi Station. Use "Ruuvi sensor" instead.

**Comment by laurijamsa** [comment]
my suggestion to show the connection status:

![image](https://user-images.githubusercontent.com/1311912/201521195-08054e35-7b6f-4bc2-9b1b-b998c8c72c94.png)

The "..." would be repeated like ., .., ... so that user knows it is still trying to do something and didn't die. Timeout could be 10 sec and if timeouting, show the fail popup.

**Comment by markoaamunkajo** [comment]
@priyonto 1.3.1(322)

Looks like the alert icon statuses are not implemented yet. Could you add similar to Android?

![Android_icons](https://user-images.githubusercontent.com/50437378/203535920-04913929-701a-435e-93c0-79a1b06b0c8d.jpg)
![iOS_icons](https://user-images.githubusercontent.com/50437378/203535942-98230c64-b218-418d-8dc6-6739ddeab43e.jpeg)

**Comment by markoaamunkajo** [comment]
@priyonto 1.31.(323) the bell icon triggers inconsistently and with wrong icon sometimes (the alarming bell icon not shown for example)
https://user-images.githubusercontent.com/50437378/204176314-f9a544b4-3f01-4e7d-8a6d-a8465c8a0f9b.mov

**Comment by priyonto** [comment]
@markoaamunkajo, Me and @laurijamsa agreed to skip adding the android like alert bell in this version since this needs more time. Aiming to include it in the next update. I have put the current progress behind a flag for now.

**Comment by markoaamunkajo** [comment]
Ok closing this issue.
