### ISSUE TITLE
App presents nice chart, then no-data chart, then nice chart, then no-data chart,...

### ISSUE THREAD

**Issue by DG12** [ruuvi/com.ruuvi.station.ios#1143]
When app is very slow presenting chart, anxious user taps thermometer location several times seconds apart.  After xx seconds the chart is presented. After yy seconds a blank chart is presented. This repeats.

Is it possible that these taps are buffered such that when chart finally finished it starts over

**Comment by markoaamunkajo** [comment]
Related to #1078 
Closing as duplicate
