### ISSUE TITLE
Sign off in case when token gets expired

### ISSUE THREAD

**Issue by andreevdenis** [ruuvi/com.ruuvi.station.ios#1145]
When we receive ER_UNAUTHORIZED from cloud during sync -> app should sing off and open sign in screen

https://github.com/ruuvi/com.ruuvi.station/issues/858

**Comment by markoaamunkajo** [comment]
I think I need Otso to help with this.

**Comment by markoaamunkajo** [comment]
QA passed iOS

**Comment by priyonto** [comment]
Reopened. Need more testing.

**Comment by priyonto** [comment]
@markoaamunkajo Passed to you. 📦

**Comment by markoaamunkajo** [comment]
Need Otso to help test this

**Comment by markoaamunkajo** [comment]
Restested, works
