### ISSUE TITLE
YAFPP- Yet Another Floating Point Problem - temperature alert limit 9.9999999999948 -1.3.0(321)

### ISSUE THREAD

**Issue by DG12** [ruuvi/com.ruuvi.station.ios#1148]
![image](https://user-images.githubusercontent.com/2365961/202749151-4ce4feda-b163-4b23-911f-be5f2777c92b.png)

**Comment by laurijamsa** [comment]
How to reproduce?

**Comment by DG12** [comment]
FYI I didn't intentionally try to find a failing case. I just tried to set a Fahrenheit I was concerned about.

Reproduce by set for Fahrenheit. set alert at min30, max 38.
All looks fine. go back to sensor screen. 
Go back to alerts and alert when less than 29.999...9947 and 38.00...0001

**Comment by priyonto** [comment]
Thanks will check.

**Comment by priyonto** [comment]
> I deleted version (321) and installed Version (320), it does not have this problem.
In build 320 we did not have floating point alert adjustment settings, only full numbers. I was expecting minor issues from 321. Will check on that. Thanks.

**Comment by markoaamunkajo** [comment]
QA passed
