### ISSUE TITLE
CSV export ; headings need quotes -(321) - minor

### ISSUE THREAD

**Issue by DG12** [ruuvi/com.ruuvi.station.ios#1156]
:
"Date","Temperature (°F)","Humidity (%)","Pressure (inHg)",**RSSI (dBm)**,**Acceleration X(g)**,**Acceleration Y (g)**,**Acceleration Z (g)**,"Voltage (V)","Movement Counter" (movements),"Measurement Sequence Number","TX Power" (dBm)

Inconsistency confuses Libre Office mightly
 imports as:

![image](https://user-images.githubusercontent.com/2365961/203158337-3146ee05-2138-4d94-b618-1d6c4233e6b6.png)

![image](https://user-images.githubusercontent.com/2365961/203158167-87516d95-3b1f-4ee0-8f8b-707d954d4a6b.png)

**Comment by laurijamsa** [comment]
You need to use use only commas as separators, not spaces + tabs + semicolons + commas.

**Comment by DG12** [comment]
This may in fact be related to "separator options" including "space".
