### ISSUE TITLE
Show time format based on system settings on widget

### ISSUE THREAD

**Issue by priyonto** [ruuvi/com.ruuvi.station.ios#1165]

**Comment by markoaamunkajo** [comment]
@priyonto looks like region is not set correctly for time yet (separator)

Region: Finland, Time format 9.00
Region: US, Time format 9:00

![IMG_9789](https://user-images.githubusercontent.com/50437378/204179095-2e27980d-c7e6-4e99-abc9-cbd3e909adde.PNG)

![IMG_9790](https://user-images.githubusercontent.com/50437378/204179062-067e7cc6-f3bd-4a0b-a666-7475990408b9.PNG)

**Comment by markoaamunkajo** [comment]
QA passed

**Comment by DG12** [comment]
Outstanding. Didn't even know that there was a widget on IOS.
