### ISSUE TITLE
1.3.1(323) Gatt sync texts overlapping

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station.ios#1169]
Description:

tested on iPhone 14 Pro, iOS 16.1.1

Spotted this during testing that text is overlapping during sync.

![IMG_9787](https://user-images.githubusercontent.com/50437378/204177391-d6ea54d3-b3d0-4e2f-95cb-21f5d2334ea3.PNG)
![IMG_9786](https://user-images.githubusercontent.com/50437378/204177422-390224be-8ebc-41cc-a0e7-e3d0cf8691a3.PNG)

**Comment by markoaamunkajo** [comment]
@priyonto Still exists in 1.3.1(324)

https://user-images.githubusercontent.com/50437378/205794350-59a56b64-9700-4726-88f2-1b00581fe469.mov

**Comment by priyonto** [comment]
@markoaamunkajo Weird, can't reproduce it on my side. Any specific steps?

**Comment by DG12** [comment]
Try being at the edge of reception.
Attached BB12 RSSI:-91

![image](https://user-images.githubusercontent.com/2365961/206220650-11061e32-274e-4ac9-ada5-aa739930b337.png)

**Comment by markoaamunkajo** [comment]
@priyonto I made multiple sync attempts repeatedly and yes my sensors are also further away same as DG12.

**Comment by markoaamunkajo** [comment]
QA passed
