### ISSUE TITLE
logging in looses some recent advertised data - defect (323)

### ISSUE THREAD

**Issue by DG12** [ruuvi/com.ruuvi.station.ios#1170]
Went into the field and synced "swamp 450a" retrieving data from  
2022-11-19 09:52:07, .. 2022-11-29 09:44:59.   2891 rows
Charts shows 11/21 - 11-29.
![image](https://user-images.githubusercontent.com/2365961/204892532-b0b69be9-1fc6-4472-b23b-fe5644c7cde2.png)

Logged in and now only data from 2022-11-20 15:11:10,.. 2022-11-29 09:48:00,  2544 rows
 is available.
Chart only shows 11/28 -11/29
![image](https://user-images.githubusercontent.com/2365961/204892896-0d7cd5de-478a-407f-a55f-cbd22307a983.png)

This tag has not been within range of gateway since 2022-05-03T08:30:01

**Comment by DG12** [comment]
Additional information:
Sync data was from 2022-11-19 09:52:07 until 2022-11-29 09:40:27

17 points were from advertisements from 2022-11-29 09:42:42 until 09:44:59

All 351 entries from 2022-11-19 09:52:07 through 2022-11-20 15:06 are no longer in the history on the iPhone.

**Comment by markoaamunkajo** [comment]
Asked more information from dev.

**Comment by DG12** [comment]
More current video example

https://user-images.githubusercontent.com/2365961/208168724-35024303-d0aa-42c6-9c78-94ad5f6f6ba0.mp4

**Comment by markoaamunkajo** [comment]
I did some comparison tests for exploring this further
@priyonto 

Downloaded local BT sensor data using:

Advertisement data
[Ruuvi B6EF_20230202-1201_advertisement.csv](https://github.com/ruuvi/com.ruuvi.station.ios/files/10565156/Ruuvi.B6EF_20230202-1201_advertisement.csv)

Synced from sensor
[Ruuvi B6EF_20230202-1203_synced.csv](https://github.com/ruuvi/com.ruuvi.station.ios/files/10565155/Ruuvi.B6EF_20230202-1203_synced.csv)


Advertisement data
[Ruuvi 510E_20230202-1220_Xmax_advertisement.csv](https://github.com/ruuvi/com.ruuvi.station.ios/files/10565154/Ruuvi.510E_20230202-1220_Xmax_advertisement.csv)

Synced from Ruuvi Cloud
[Xmax_20230202-1223_Ruuvi_Cloud.csv](https://github.com/ruuvi/com.ruuvi.station.ios/files/10565153/Xmax_20230202-1223_Ruuvi_Cloud.csv)

**Comment by DG12** [comment]
@markoaamunkajo
Thank you for investigating this issue.
I think you correctly understand what's happening.

**Comment by markoaamunkajo** [comment]
Fixed in 2.0.0(311)
@DG12 in next major update.
