### ISSUE TITLE
1.3.1(324) Lockscreen widget: list unresponsive after repeated taps

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station.ios#1180]
Description:

User signed into Ruuvi Cloud and he has both own gateway and sensors as well as shared sensors in his account.
He adds one sensor to his lockscreen widget and is able to change it during edit.

Then during last edit he taps repeatedly before list opens. Now he cannot choose anything from opened list. Also Cancel button is not reacting to tap.

https://user-images.githubusercontent.com/50437378/205792496-373458f5-7307-486f-87ee-24f5398a1c79.mov

**Comment by priyonto** [comment]
@markoaamunkajo  This seems more like iOS 16/lockscreen widget bug, not Ruuvi Station bug. Because the list selection or the cancel button tap this comes by default, we don't have control on that. Would you be able to do a device restart and check to reproduce it?

**Comment by markoaamunkajo** [comment]
@priyonto retested and this issue remains after restarting. I'm assuming we should close this as "wont fix"
