### ISSUE TITLE
Add Ruuvi Cloud plan information on the My Ruuvi Account page

### ISSUE THREAD

**Issue by laurijamsa** [ruuvi/com.ruuvi.station.ios#1181]
Same as on Android (specs will be available here:

https://github.com/ruuvi/com.ruuvi.station/issues/884

**Comment by markoaamunkajo** [comment]
@priyonto description has been updated to Android card

**Comment by priyonto** [comment]
Reference: https://github.com/ruuvi/ruuvi.cloud.js/issues/158

**Comment by markoaamunkajo** [comment]
Closing this issue for now as topic is moved to internal discussion.
