### ISSUE TITLE
Improve About / Help page

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station.ios#1183]
Description:

Improve About Help page
Layout
Structure
Links to support articles etc

Issue for Android https://github.com/ruuvi/com.ruuvi.station/issues/886

**Comment by priyonto** [comment]
@laurijamsa @markoaamunkajo  I have checked the Android app, and it seems like only difference is iOS doesn't have the privacy policy section. Is that all for this task?

**Comment by markoaamunkajo** [comment]
Yes looks like the ident is missing from iOS. Let's add it.

**Comment by markoaamunkajo** [comment]
QA passed
