### ISSUE TITLE
Remove BT sensor when connected and add it again - no chart icon

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station.ios#1184]
Description:

1.3.1(324)

User added 3.31.1 sensor to Ruuvi Station and enabled paired mode, then deleted sensor from the app.

Actual: now when user adds same sensor again the charts icon has disappeared from sensor page.

https://user-images.githubusercontent.com/50437378/206673721-16c11a7a-01a6-4798-82b4-8efeb0f5fb8c.mov

**Comment by priyonto** [comment]
@markoaamunkajo  No luck reproducing it on my side. Tried it several times, works well for me. My guess is it's unexpected BT issue. Because logically nothing changed for handling chart button visibility in this build. Please try to reproduce it and let me know if there's any fixed way to reproduce it.

**Comment by markoaamunkajo** [comment]
I cannot reproduce either but I did see it, it should be figured out.

**Comment by markoaamunkajo** [comment]
Discussed in meeting yesterday @priyonto will try if status could be detected before (same as firmware check)

**Comment by markoaamunkajo** [comment]
QA passed

**Comment by priyonto** [comment]
@markoaamunkajo I applied a patch but I am not entirely convinced that this patch will work reliably all the time. This is actually related to #1121, which is entirely complex issue involving the BT connection pipeline. I will probably dig into that after 2.0 release.

**Comment by markoaamunkajo** [comment]
I cannot reproduce in 2.0.0(331)
