### ISSUE TITLE
History cannot be cleared (325) - defect

### ISSUE THREAD

**Issue by DG12** [ruuvi/com.ruuvi.station.ios#1188]
Well not exactly. Clearing history surely works, that's good.

If the ruuvi is within wifi range and has been within gateway range, after a few seconds the history is repopulated!

**Comment by DG12** [comment]
If I might offer an (seems to me to be  a relatively) easy solution:
Leave history alone, rather create an item  a something like **OldestHistoryToShow** .
Store now() there when user does a (clear).
Although not necessary, synchronization not needed and not dependent on the cloud station could update that variable to the cloud to reduce transmission time.

 Also set a bias for movement counter so displays as zero until the next change.

**Comment by markoaamunkajo** [comment]
Will be handled on cloud side with ability to delete cloud history in the future.
