### ISSUE TITLE
Unify colors with Android/Ruuvi brand

### ISSUE THREAD

**Issue by sini-maaria** [ruuvi/com.ruuvi.station.ios#1203]
- All blue buttons and blue icons: #35AD9F
- Also graph colors should be changed.

From:
<img width="386" alt="Screenshot 2022-12-23 at 12 10 08" src="https://user-images.githubusercontent.com/19531763/209317572-46e001ef-f5a3-4315-82a0-8f23995886ef.png">

To:
<img width="377" alt="Screenshot 2022-12-23 at 12 09 01" src="https://user-images.githubusercontent.com/19531763/209317556-e205859d-33b3-4047-9c9e-5568e6f484a9.png">

**Comment by sini-maaria** [comment]
Add the same color for the alert slider.

**Comment by sini-maaria** [comment]
Graph color specs can be found here: https://github.com/ruuvi/com.ruuvi.station/issues/790

fill: #46cab9, 0.3
line: #34ad9f

**Comment by sini-maaria** [comment]
Add also the same transparent layer behind graphs as there is on Android app.
#001D1B, 30%

**Comment by markoaamunkajo** [comment]
I have no further comments to this card, moving to done. @sini-maaria can reopen if needed.
