### ISSUE TITLE
Unify charts with Android

### ISSUE THREAD

**Issue by priyonto** [ruuvi/com.ruuvi.station.ios#1212]

**Comment by priyonto** [comment]
@markoaamunkajo 

1. Did not implement it due to priority of other urgent issues. Created a separate card for this one. I will have to revisit this later probably. (#1238)

2. This is android app. Looks like we are using different strings for pressure and humidity in different places like offset correction and alerts/charts. Should it be unified everywhere or this is expected?  

![IMG_20230206_205510](https://user-images.githubusercontent.com/24395776/217072152-8c79fa3f-77bd-4ee3-9192-088f69b0ebdf.png)

**Comment by markoaamunkajo** [comment]
@priyonto 2. looks like humidity is used in lots of places in app etc, I will go through strings for 2.1. Keeping this in my queue.
