### ISSUE TITLE
Improve lock screen widget UI

### ISSUE THREAD

**Issue by priyonto** [ruuvi/com.ruuvi.station.ios#1214]
Mockup to follow:

![photo1674649803](https://user-images.githubusercontent.com/24395776/214928991-c267e4b7-97e2-46cf-8a26-1e935b4dac75.jpeg)

**Comment by sini-maaria** [comment]
Almost perfect. 

The circle looks a bit too tight so let's do a couple of adjustments:
1. Reduce the font size a bit on title and add padding to the sides.
2. Move the °C tiny bit closer to the measurement.

Original design on the left side:
<img width="209" alt="Screenshot 2023-02-01 at 12 02 43" src="https://user-images.githubusercontent.com/19531763/216012234-36d3d05e-c492-4d67-8a88-0866163d298f.png">

**Comment by sini-maaria** [comment]
Looks good, thanks!
