### ISSUE TITLE
Unify colours: Popup boxes are using Blue Cancel and OK buttons

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station.ios#1226]
Description:

We didn't put any emphasis on popup box styling in designs but I think this should be discussed. This seems to be a system colour.

![popups_styling](https://user-images.githubusercontent.com/50437378/216880221-6a6f7984-ca86-4e6e-99e8-0d7cfc5b7b86.jpg)

Main card: https://github.com/ruuvi/com.ruuvi.station.ios/issues/1203

**Comment by priyonto** [comment]
It is a system color. @sini-maaria and I discussed about this a while back before starting the branding color applying task. The issue with this one is depending on how we want it to look like. If we want similar to android we will have to go basically built a custom alert view and change all existing default popups. That's a lot of work. But, we can probably change the button color/blue tint and keep and default style, that could be comparatively easier.

**Comment by markoaamunkajo** [comment]
Moved to proposals

**Comment by markoaamunkajo** [comment]
Looks like this is commonly used in various apps, closing this as will not implement
