### ISSUE TITLE
Unify charts: Stuck in success message after sync

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station.ios#1227]
Description:

2.0.0(331), iPhone 14 Pro, iOS 16.3 

I got single incident where after syncing chart over Bluetooth got stuck in Success message and I couldn't abort. Not sure if this is reproducable but I consider it a minor case.

Edit: reproduced

![success_1](https://user-images.githubusercontent.com/50437378/216880948-3d319560-70f3-4d6b-817a-6fab689da38a.jpeg)
![success_2](https://user-images.githubusercontent.com/50437378/216880944-83933ad2-9301-428b-964c-72c269453d9e.jpeg)

Main card: https://github.com/ruuvi/com.ruuvi.station.ios/issues/1212

**Comment by priyonto** [comment]
@markoaamunkajo I could not reproduce the issue yet but found a potential hole, fixed it. Please test on the next build if you can reproduce.

**Comment by markoaamunkajo** [comment]
Not seen in latest build, QA passed
