### ISSUE TITLE
Sensor settings: Background selection has many Ruuvi eye backgrounds

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station.ios#1228]
Description:

2.0.0(331)

Selecting background from default images has 4 different Ruuvi eye backgrounds, whereas Android only uses 1.
Let's reduce the number of Ruuvi eye backgrounds to 1.

Also check which one is the correct one to use for default sensor background from @sini-maaria 

![IMG_174603588A65-1](https://user-images.githubusercontent.com/50437378/216882322-e2c2f425-e36e-40cb-a405-2911e6c7fbab.jpeg)

**Comment by priyonto** [comment]
Kept only second eye image like android.

**Comment by markoaamunkajo** [comment]
QA passed
