### ISSUE TITLE
Add last measurement time and source at the bottom of charts page

### ISSUE THREAD

**Issue by priyonto** [ruuvi/com.ruuvi.station.ios#1238]

**Comment by markoaamunkajo** [comment]
@priyonto 

Let's try to unify with Android, there are minor differences between Android and iOS charts page.
Also, check if there is possibility to scale the chart box height maybe on smaller iPhone models.
I don't think we have many small screen iPhone users though.

We will make bigger improvements at later point.


![Image](https://github.com/ruuvi/com.ruuvi.station.ios/assets/50437378/7da2f759-bbfe-4f4e-b867-8d914a91029a)

**Comment by markoaamunkajo** [comment]
QA passed
