### ISSUE TITLE
Flickering Histogram Icon [0.6(36) with TagFW 3.29.0-RC5]

### ISSUE THREAD

**Issue by bchwtz** [ruuvi/com.ruuvi.station.ios#124]
The Histogram Icon (randomly) starts flickering when monitoring a tag with firmware 3.29.0-RC5. The problem persists after a reboot and the flickering seems to be synchronized to the heartbeat signal (roughly once per second). See the gif for details.

![ruuvi-station-flickering](https://user-images.githubusercontent.com/35465162/94962342-94368900-04f6-11eb-9b41-e0b32010d0ab.gif)

```
Device: iPhone 6S
OS: iOS 14.0.1
App: Ruuvi Station 0.6(36)
Location: not determined
Photo Library: not determined
Camera: not determined
Notifications: authorized
```

**Comment by rinat-enikeev** [comment]
We will fix it with 3.29.1 FW and new build in Public Beta.

**Comment by bchwtz** [comment]
Could you explain what exactly caused the Problem in the Firmware?

**Comment by rinat-enikeev** [comment]
It advertises and heartbeats simultaneously
