### ISSUE TITLE
Translation fix: widget selector not translated

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station.ios#1241]
Description:

Widget selector doesn't have language strings in language file.

![IMG_524C3D7D60D2-1](https://user-images.githubusercontent.com/50437378/217138111-e6d84281-6856-4e97-8bc7-94c8bc64c244.jpeg)

Should be fixed in 2.0

**Comment by priyonto** [comment]
```
Widgets.Select.Sensor.title
Widgets.Sensor.Type.title
```

@markoaamunkajo Added two string on the localisation repo. Please update them and let me know. I will have to update the strings manually on the app side. Widgets doesn't support trivial localisation yet.

**Comment by markoaamunkajo** [comment]
Not yet fixed in 2.0.0(337)

![IMG_6EA8DF3F8F9E-1](https://user-images.githubusercontent.com/50437378/218362655-c90ab0dd-6ae2-4ab9-8578-ea1cc75503bf.jpeg)

**Comment by priyonto** [comment]
@markoaamunkajo I have added the translations. However, please note that only if device preferred language is changed, then widget configuration labels are localised, changing app language doesn't affect this. This is a system limitation.

**Comment by markoaamunkajo** [comment]
QA passed
