### ISSUE TITLE
Add new sign in page

### ISSUE THREAD

**Issue by priyonto** [ruuvi/com.ruuvi.station.ios#1249]

**Comment by markoaamunkajo** [comment]
@priyonto Improved strings for new sign in page

Also added one new ident to be used at bottom of page called "benefits_sign_in"

![sign_in_page](https://user-images.githubusercontent.com/50437378/219556020-c18b83d5-4d15-4e62-a1ff-5db3453b65e5.jpg)

**Comment by markoaamunkajo** [comment]
@priyonto Benefits page has also changed according to the screen below:

![benefits_page](https://user-images.githubusercontent.com/50437378/219568739-878c984e-af22-4191-a213-411bc600fadb.jpg)

**Comment by markoaamunkajo** [comment]
QA passed
