### ISSUE TITLE
Alert notification source settings (pn, email)

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station.ios#1255]
Description:

Add new under Alert Notifications menu item in App Settings

Alert source
- Mobile app push notification
- Email

Switch to enable/disable

![Alert_Notifications_page1](https://user-images.githubusercontent.com/50437378/228132302-8c3f7fac-2a36-4acf-839e-7496e41ef42e.jpg)

Hide Email Alerts and Push Alerts when user is not signed in.

![Alert_Notifications_page2](https://user-images.githubusercontent.com/50437378/228132316-d7a9c280-d5f8-46f4-ac46-29dfa71937cd.jpg)

Card for Android: https://github.com/ruuvi/com.ruuvi.station/issues/919

**Comment by markoaamunkajo** [comment]
Waiting for https://github.com/ruuvi/ruuvi.cloud.js/issues/219

**Comment by priyonto** [comment]
App side work is finished for this. Could be tested immediately as soon as backend is adjusted.

**Comment by DG12** [comment]
cosmetic: What is the alert sound? Could it be something else (anything else :-)

**Comment by markoaamunkajo** [comment]
Hmm @priyonto looks like the cloud sync is unable to handle this situation for switches:

- User set email and push alerts to disabled when signed in, then signed out and set both to enabled
- Then user signed in again, so both switches automatically disabled themselves

Maybe we should consider hiding these settings when user is not signed in?

**Comment by markoaamunkajo** [comment]
QA passed
