### ISSUE TITLE
Fix low battery and bell indicators

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station.ios#1260]
Description:

Use same indicators as on Android for low battery and bell alert indicators (dashboard, sensor card, sensor settings)
Ask correct svg's from Denis.

![ios_vs_Android](https://user-images.githubusercontent.com/50437378/218631929-7e1c4d27-9918-426b-948c-93e40efe070f.jpg)

**Comment by priyonto** [comment]
@markoaamunkajo This can be closed probably as discussed in DM.

**Comment by markoaamunkajo** [comment]
Correct, closing this issue
