### ISSUE TITLE
Increase font size for charts screen

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station.ios#1267]
Description:

Increase font size for chart screen for 2.0
Will include scalable fonts later in 2.1

**Comment by markoaamunkajo** [comment]
2.0.0(340) 

Not yet on this build. Not sure if I'm doing it wrong.
![IMG_0849](https://user-images.githubusercontent.com/50437378/219249143-4ab5f00c-c6a5-4efd-8d0f-344ffa61e856.PNG)
![IMG_0848](https://user-images.githubusercontent.com/50437378/219249153-a73b3237-c778-427e-97da-275fd8fc78af.PNG)

**Comment by priyonto** [comment]
@markoaamunkajo 

> 2.0.0(340)
> 
> Not yet on this build. Not sure if I'm doing it wrong. ![IMG_0849](https://user-images.githubusercontent.com/50437378/219249143-4ab5f00c-c6a5-4efd-8d0f-344ffa61e856.PNG) ![IMG_0848](https://user-images.githubusercontent.com/50437378/219249153-a73b3237-c778-427e-97da-275fd8fc78af.PNG)

This is font scaling, which is not supported on iOS. We planned it for 2.1. 

Also, the chart font size now is exactly same as the current production build. But, the font style is different. Earlier we had system font, now we have Mulish.

**Comment by markoaamunkajo** [comment]
QA passed
