### ISSUE TITLE
New Sign in: design fixes

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station.ios#1270]
Description:

Please follow the design for new sign in pages

![iOS_1](https://user-images.githubusercontent.com/50437378/219265430-539ac48c-8e97-4b26-87f3-ffe7bcbf993b.jpg)
![iOS_2](https://user-images.githubusercontent.com/50437378/219265426-8e8a377c-6746-4769-88c3-104a4440ac01.jpg)

Main card: https://github.com/ruuvi/com.ruuvi.station.ios/issues/1249

**Comment by sini-maaria** [comment]
Button here was white because it was supposed to work on light and dark mode. Now when we are going with only dark one, we can use the default button color (aqua).

**Comment by markoaamunkajo** [comment]
Ok, moving to done
