### ISSUE TITLE
Unification: Change downwards opening icon

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station.ios#1274]
Description:

Change downwards opening icon  "⌄"to match the Android and Web apps style everywhere in the app

Current:
![current](https://user-images.githubusercontent.com/50437378/219597890-a5b7bca9-dfc2-4ad6-a3ca-b418085aefbb.jpeg)

New:
![correct style](https://user-images.githubusercontent.com/50437378/219598015-d71d4129-82b9-49fa-ab44-790e7109b922.jpg)

**Comment by priyonto** [comment]
@markoaamunkajo Do we actually need this one? I at least don't think so since it doesn't go with iOS design language. Currently Web station also shows similar icon as iOS.

**Comment by markoaamunkajo** [comment]
Change arrows everywhere if exists, also including charts page so design matches with Android.

![Image](https://github.com/ruuvi/com.ruuvi.station.ios/assets/50437378/b480ca69-91b3-41ed-b634-3dee2e17f689)

**Comment by markoaamunkajo** [comment]
@priyonto comparing with Android these seem to be bigger at least on my iPhone 14 Pro

![Image](https://github.com/ruuvi/com.ruuvi.station.ios/assets/50437378/4b0cc819-0058-47c3-bcaa-61ffa7910499)

**Comment by markoaamunkajo** [comment]
QA passed
