### ISSUE TITLE
Chart settings initially all data - question -(343) 

### ISSUE THREAD

**Issue by DG12** [ruuvi/com.ruuvi.station.ios#1281]
If "enabling it may cause charts to update slowly" would the best initial user experience be better if it was initially off?

**Comment by markoaamunkajo** [comment]
@DG12 was this experienced as slow on your end when it was enabled? Just want to check...

**Comment by priyonto** [comment]
@markoaamunkajo I made it settings off by default since It could practically have impact on performance.

**Comment by DG12** [comment]
Thanks.
Haven't noticed slow charting lately.

**Comment by laurijamsa** [comment]
> I made it settings off by default since It could practically have impact on performance

We need to double check new user's experience when opening history graph view. If I remember correctly, we set the "show all data" to be on by default so that users who add a new sensor, can see some data drawn on the graphs when visiting the history view. @markoaamunkajo

**Comment by priyonto** [comment]
> 

Easy, Could change it back based on the decision made. But, I think the sensor history page would still show the downsampled data even if "show all data" is turned off by default. Previously we did not store all points when app was on foreground which probably had impact of this.

**Comment by DG12** [comment]
What is the alternative to displaying all data ?
Displaying every 5 datapoint ? Only hourly data points?
Seems like addition information would be helpful.

**Comment by markoaamunkajo** [comment]
@laurijamsa I see some data drawn on chart page in couple of seconds after adding it even when I don't have showing all data enabled

**Comment by markoaamunkajo** [comment]
Moving to done, the disabled setting works for this case as default.

**Comment by DG12** [comment]
Please reopen:
Seems that user should know :
What is the alternative to displaying all data ?
Displaying every 5 datapoint ? Only hourly data points?
Seems like addition information would be helpful.
