### ISSUE TITLE
Chart display says 10 days although less data its available - -(343)

### ISSUE THREAD

**Issue by DG12** [ruuvi/com.ruuvi.station.ios#1282]
The chart screen **selection** defaults to 10 days . 

This is confusing  as it suggests that that there are 10 days of data available initially. Even more confusing after a few (but less than 10) days 
A better, ie less deceptive default would be. 1 day.

This would also provide a better user experience once several days of dats is available.

**Comment by markoaamunkajo** [comment]
Closing with https://github.com/ruuvi/com.ruuvi.station.ios/issues/1606
