### ISSUE TITLE
chart cursor label shows incorrect date - defect -(343)

### ISSUE THREAD

**Issue by DG12** [ruuvi/com.ruuvi.station.ios#1283]
Today is Feb 18. Cursor shows 02/23. 
See screen shot.
![ChartCursorIncorrectDate](https://user-images.githubusercontent.com/2365961/219877501-44b90a75-8cfa-45af-aa00-8490d8b86b27.PNG)

Is this locale related?

**Comment by markoaamunkajo** [comment]
QA passed

**Comment by DG12** [comment]
Good but, X - axis is formatted 
%l:%M%p ,example 8:24 PM
cursor is 
%H:%M , example 20:24

**Comment by markoaamunkajo** [comment]
Looks like region US in global settings makes this
Default is supposedly 24h for all

Reopening

**Comment by markoaamunkajo** [comment]
QA passed
