### ISSUE TITLE
Change background to default image does not show selected - minor - (343)

### ISSUE THREAD

**Issue by DG12** [ruuvi/com.ruuvi.station.ios#1284]
When choosing an alternate image, there is no indication which image is currently selected, either a photo or default.

Tapping on an image presents a small popup at the bottom of the screen for (about) .3 seconds. 
There is no indication which image is selected.

**Comment by markoaamunkajo** [comment]
We don't specifically show the selected, maybe will be improved in future versions. Otherwise working as correct.
