### ISSUE TITLE
Swipe left on first sensor card to bring dashboard

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station.ios#1299]
Description:

User is on first sensor card and swipes left to go back to overview.

Actual:
Nothing happens

Expected:
Show dashboard

Android card: https://github.com/ruuvi/com.ruuvi.station/issues/941

**Comment by laurijamsa** [comment]
I think we need to consider adding this also on Android to keep the apps consistent. However, I'm not sure if Android users expect this to happen when swiping to the left? And if swiping left from the most left sensor card and view is going back to the dashboard, should user be able to return to the first sensor card by swiping to right on dashboard view?

**Comment by markoaamunkajo** [comment]
I remember on Android swipe was bringing app menu... have to recheck on that

**Comment by priyonto** [comment]
@markoaamunkajo @laurijamsa  Just want to clarify: Swiping left to go back is default iOS behaviour in general. If we are willing to bring that back I think we should bring it for all pages and implement default iOS experience, not just for cards page and for the first card. Having it on only one screen is likely to cause confusion among users.

**Comment by markoaamunkajo** [comment]
Compared few applications, and found this gesture is only default on something like Twitter. Let's close this for now, since we don't see the benefit from implementing it.
