### ISSUE TITLE
Landscape: charts view has lot of empty space

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station.ios#1301]
Description:

User reported that there is lot of empty space in the charts screen in the area marked using yellow.
For future consideration.

![yellow_space](https://user-images.githubusercontent.com/50437378/220804985-3d5b1f50-426d-442e-945f-270f29a3724c.jpeg)

**Comment by priyonto** [comment]
@sini-maaria @markoaamunkajo  Any thoughts on this one?

**Comment by markoaamunkajo** [comment]
Closing as we have future UI refresh for history view.
