### ISSUE TITLE
Make tapping on dashboard card forward to charts view by default

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station.ios#1302]
Description:

Make tapping on dashboard card forward to charts view by default and allow users to open these full image sensor card views from the "..." dropdown menu like it's already now available.

![dashboard](https://user-images.githubusercontent.com/50437378/220806655-6f2debe5-fcd3-4a52-b2e8-de17ce9614d0.jpeg)

Android card: https://github.com/ruuvi/com.ruuvi.station/issues/942

**Comment by priyonto** [comment]
This is buried under the feature flag(**Defaults**) now.

**Comment by markoaamunkajo** [comment]
@priyonto looks like it doesn't work. I enabled it on defaults and even killed app afterwards. I'm still forwarded to full image view not history view.

**Comment by markoaamunkajo** [comment]
@priyonto At this point it feels like we should think about implementing this later when we have swipe between sensor history views. For now, moving to proposals.

Let's keep the default as full image view and setting under defaults for now.

**Comment by markoaamunkajo** [comment]
Closing with https://github.com/ruuvi/com.ruuvi.station.ios/issues/1409
