### ISSUE TITLE
From chart: tap ⠇,  "export history( csv),  Clear View - question - 2.0.0 (350)

### ISSUE THREAD

**Issue by DG12** [ruuvi/com.ruuvi.station.ios#1303]
Tapping clear view shows:

Clear local history
Do you want to clear local stored historical data from the app? ...

Wording "clear view" seems inconsistent (?) with clear history

Then there is still 
History cannot be cleared (325) - defect #1188

**Comment by markoaamunkajo** [comment]
Added language fixes

**Comment by markoaamunkajo** [comment]
QA passed
