### ISSUE TITLE
Sharing reports "Already shared 1/10" - clarification needed

### ISSUE THREAD

**Issue by DG12** [ruuvi/com.ruuvi.station.ios#1308]
When sharing a sensor , Successfully shared always says 
already shared 1/10
![image](https://user-images.githubusercontent.com/2365961/221251252-7d424706-a1e8-4bb6-b36a-8b7afab038ab.png)

**Comment by DG12** [comment]
Oops. 
Perhaps better wording might be 

`Currently shared to 1 out of a maximum of 10 friends. `

Maybe no message is even needed?

**Comment by markoaamunkajo** [comment]
Improved in language file, moving to done.

**Comment by markoaamunkajo** [comment]
![IMG_24D9DDC9AC8C-1](https://user-images.githubusercontent.com/50437378/223598039-678397c3-6621-416f-ad5b-fefc5be33db1.jpeg)

@priyonto for some reason the text uses capitals in every word, should be fixed.

**Comment by markoaamunkajo** [comment]
QA passed
