### ISSUE TITLE
table of contents shows many sensors with no data 2.0.0 (351) - fluke ?

### ISSUE THREAD

**Issue by DG12** [ruuvi/com.ruuvi.station.ios#1311]
Many sensors with non data but NOT ALL.
After a second or 2 and no action on users part, all is fine again!

![noData 24C2+AD03](https://user-images.githubusercontent.com/2365961/221252907-479ddc2a-c192-4172-9230-abd7c7269e3f.PNG)
![nodata0981+450A+EC0F+22AB+24C2](https://user-images.githubusercontent.com/2365961/221252932-b49b562c-49d4-4a0f-82e7-26e791375f05.PNG)

**Comment by priyonto** [comment]
Edge case, did not see this one for a while. Will keep an eye on it.

**Comment by markoaamunkajo** [comment]
Closed issue, will reopen if spotted again
