### ISSUE TITLE
2.0.0 (354) Adding, connecting and removing BT sensor crashes app

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station.ios#1319]
Description:

App crash when adding 1 single BT sensor, pairing with BT, then removing sensor from app.
Also if I do the same when signed in and re-add same local BT sensor it is missing charts icon.
Reproduced on 2x iPhones using TF version 2.0.0(354)

https://user-images.githubusercontent.com/50437378/221453150-6f681a32-b008-43fc-9450-67d5d3199b9f.mov

https://user-images.githubusercontent.com/50437378/221453212-0c646d94-7a28-4382-9bf6-bdb601603082.mov

**Comment by priyonto** [comment]
Fixed the crash. The other issue is related to #1121. I will take care of all the BT issues together.

**Comment by markoaamunkajo** [comment]
QA passed
