### ISSUE TITLE
No RSSI but updates occur -

### ISSUE THREAD

**Issue by DG12** [ruuvi/com.ruuvi.station.ios#1321]
The RSSI field has only a dash, but sequence number increases (usually by exactly 2)!

https://user-images.githubusercontent.com/2365961/221471224-3d27f2cf-5532-485e-b0b1-00f7e74230ea.mp4

**Comment by markoaamunkajo** [comment]
When paired (receiving heartbeat data) RSSI is not updated.
This is limitation of iOS.
