### ISSUE TITLE
2.0.0(354) Shared sensor when app on foreground doesn't add sensor

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station.ios#1326]
Description:

User shared sensor to me when app was in foreground.

Actual: no new sensor card is created, no matter if cloud sync occurs. Only killing app will bring the new sensor card to the app.
Expected: create new sensor card when it's shared to me.

**Comment by laurijamsa** [comment]
Pressing home button and then bringing app back to foreground also isn't enough. Like Marko said, app has to be killed completely. On Android, only waiting when the app is on foreground is enough.

**Comment by markoaamunkajo** [comment]
QA passed
