### ISSUE TITLE
Sharing completely new sensor: should not be able to share when never seen by gw

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station.ios#1329]
Description:

New never seen sensor claimed.
Android: sharing button available, cannot add email address, email fields disappear.

iOS: sharing button available and can share sensor. Which is incorrect.

@priyonto Please discuss how Denis has implemented this, that sharing is impossible on Android

This is the view that user should see in this case:
![photo_2023-03-02 08 57 10](https://user-images.githubusercontent.com/50437378/222310997-873b3879-acd0-4427-83d4-04daeebe19c2.jpeg)

**Comment by priyonto** [comment]
> This means that it's also possible for users without a gateway to share sensor, so this should be a hotfix.

@markoaamunkajo  Did not understand this. Share more please?

**Comment by markoaamunkajo** [comment]
> > This means that it's also possible for users without a gateway to share sensor, so this should be a hotfix.
> 
> @markoaamunkajo Did not understand this. Share more please?


If a user is signed in to an account but doesn't own a Ruuvi Gateway he shouldn't be able to share a sensor.
"Only sensors within the range of your Ruuvi Gateway router can be shared."

**Comment by markoaamunkajo** [comment]
QA passed
