### ISSUE TITLE
New sensor with no history data in the cloud: settings is unaccessible

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station.ios#1330]
Description:

New sensor with no history data in the cloud: 
- dashboard menu item settings & alerts doesn't work
- full image view, cannot access settings using cog icon

Steps:
1. Add new never seen bluetooth sensor on one phone, when gateway is offline
2. Claim to Ruuvi Cloud
3. Start iOS app without permission to use Bluetooth
4. Try to go to three dots menu and Settings & Alerts OR cog wheel in full image view
5. Bingo - nothing happens!

**Comment by priyonto** [comment]
Postponed until we decide a better spec for this. Also this is related to #1329. Moving to backlog now.

**Comment by markoaamunkajo** [comment]
@priyonto moving back as high priority, we have multiple reports of users who cannot edit their sensor cards over the weekend.

**Comment by markoaamunkajo** [comment]
Discussed in dm

**Comment by markoaamunkajo** [comment]
Discussed in DM

**Comment by markoaamunkajo** [comment]
QA passed
