### ISSUE TITLE
Optimize cloud calls for free subscription sensors

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station.ios#1333]
No need to request history if current sensor/user plan doesn't support it.

Android card: https://github.com/ruuvi/com.ruuvi.station/issues/943
Web card: https://github.com/ruuvi/com.ruuvi.station.webui/issues/274

**Comment by priyonto** [comment]
Related #1345

**Comment by markoaamunkajo** [comment]
@priyonto does this card require action from you? Cloud doesn't return history for Free user.
Unification with Android is needed if not same experience.

**Comment by markoaamunkajo** [comment]
QA passed moving to done
