### ISSUE TITLE
Charts: Show Bluetooth download popup only first time

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station.ios#1335]
Description:

Reopened https://github.com/ruuvi/com.ruuvi.station/issues/873 to improve icon

When we get new icon implemented, show popup only first time and hide if was shown.
Reinstalling app popup will be shown again first time.

Android card: https://github.com/ruuvi/com.ruuvi.station/issues/937

**Comment by priyonto** [comment]
Completed as part of #1471
