### ISSUE TITLE
tapping share with a blank email address should report "Invalid (empty) email address" 2.0.0 (354) bug

### ISSUE THREAD

**Issue by DG12** [ruuvi/com.ruuvi.station.ios#1337]
oops.

Tapping share without entering an email address is ignored without message.
It should report Invalid email address, or better yet. Empty email address

**Comment by markoaamunkajo** [comment]
Invalid email address is shown on Android, let's do same on iOS.

**Comment by markoaamunkajo** [comment]
QA passed
