### ISSUE TITLE
"friends currently shared" does not display if no wifi/cell - 2.0.0 (354) - defect

### ISSUE THREAD

**Issue by DG12** [ruuvi/com.ruuvi.station.ios#1339]
If there is no wifi or cell connection, the sharing section that, would show those friends currently shared, does not display anything even if there are shared friends.

If connection is slow, for example if no wifi and poor cell access, the friends section does not display friends(or even  title) for some time and the suddenly the list of friends shows up. (Just as I start to type in a friends email)\

Perhaps initializing the list of friends section with the **title** and animated dots for the first entry would be less confusing to the user.

**Comment by markoaamunkajo** [comment]
Closing as will be handled on other card
