### ISSUE TITLE
Decimal separator for temperature and air pressure when English is Language should be dot - cosmetic -.7(21)

### ISSUE THREAD

**Issue by DG12** [ruuvi/com.ruuvi.station.ios#134]
Temperature is shown as nn,ff (comma).
Humidity is shown at nn.ff (dot)
Air pressure is shown as nn,ff (comma)

Should language be taken from iPhone Language in settings/general/language & region?
Should the choice of comma or dot as decimal separator also be taken from  settings/general/language & region?

I still would like to see humidity (which has limited accuracy) be displayed in integer.

**Comment by DG12** [comment]
Actually if the value is nn.00 it is displayed as an integer (YES!)
If the value is nn.f0 it is displayed with only tenths ( trailing zero is not shown)
It should be consistent.

Best way to solve I want xxx, you want yyyy is to make it an option!!

**Comment by rinat-enikeev** [comment]
@viikufa could you please take a look?

**Comment by markoaamunkajo** [comment]
QA passed

**Comment by DG12** [comment]
@markoaamunkajo Thanks for closing this issue for me.
