### ISSUE TITLE
UUID is not useful for user and should not be shown it - cosmetic  0.7(21)

### ISSUE THREAD

**Issue by DG12** [ruuvi/com.ruuvi.station.ios#135]
Is there any use for the UUID ?

**Comment by rinat-enikeev** [comment]
Yes, for 2.5.9 firmware in data format 3 mode there is no MAC known for iOS app.

**Comment by DG12** [comment]
UUID seems to be different for different devices for example 
ebc49873a5be4404b16b378a41d57ea3 MacBook from ruuvi-discovery
fb19aec7dd874ac7ad2768c7d1894b4e from iPhone ruuvi-station IOS

PS on the iPhone the UUID is 6 characters too long to display on the same line with the prefix 'UUID" so it ends with c7d18...

**Comment by DG12** [comment]
ruuvi tag MAC D250:3a:FE1A96 has different UUID on iPhone than shows on Mac laptop via Discovery

**Comment by andreevdenis** [comment]
@rinat-enikeev I can see MAC in iOS for 2.5.9 sensor

**Comment by rinat-enikeev** [comment]
> @rinat-enikeev I can see MAC in iOS for 2.5.9 sensor

Yes, for data format RAWv2. But the tag can broadcast data format 3 without MAC

**Comment by DG12** [comment]
But there is no advantage to setting it to format 03.

**Comment by rinat-enikeev** [comment]
let's hide it from Tag Settings

**Comment by markoaamunkajo** [comment]
QA passed
