### ISSUE TITLE
Tag name should adhere to user specified case - enhancement  0.6.3(1)

### ISSUE THREAD

**Issue by DG12** [ruuvi/com.ruuvi.station.ios#136]
If user specified tag name as "MyFavorite" it should not be displayed as "MYFAVORITE"

**Comment by rinat-enikeev** [comment]
But this is our UI/UX feature... Not a bug :)

**Comment by DG12** [comment]
This prevents using CamelCaseWhenNameing
See also issue #147

**Comment by rinat-enikeev** [comment]
https://feedback.ruuvi.com/posts/27/make-tag-names-case-sensitive

closing this issue moving discussion to feedback.

**Comment by DG12** [comment]
Finally corrected  3/20/23 :-)
