### ISSUE TITLE
Measure seq number goes to zero

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station.ios#1366]
Description:

Measure sequence number goes back  one , then corrects.
Data received via heartbeat and BT.
Measure seq number  reports

------------------------------------------
Device: iPhone XS Max
OS: iOS 16.3.1
App: Ruuvi Station 2.0.1(355)
Location: not determined
Photo Library: authorized
Camera: authorized
Notifications: authorized
------------------------------------------

**Comment by markoaamunkajo** [comment]
Not spotted in 2.0.1(359) but worth a check.

**Comment by laurijamsa** [comment]
Doesn't sound like a mobile app issue. Maybe firmware sends an old measurement sequence number in some cases (connected vs. advertisement)? @ojousima could you share your thoughts?

**Comment by ojousima** [comment]
Measure sequence rolls to zero after 2^16-2 and on reboot

**Comment by markoaamunkajo** [comment]
Ok this sounds like feature, closing this issue for now
