### ISSUE TITLE
Language fix suggestion

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station.ios#1368]
Description:

“Bluetooth download” should be “sensor history download…”

Similarly “Bluetooth download failed”
Should say “sensor history download  failed “

------------------------------------------
Device: iPhone XS Max
OS: iOS 16.3.1
App: Ruuvi Station 2.0.1(358)
Location: not determined
Photo Library: authorized
Camera: authorized
Notifications: authorized
------------------------------------------

**Comment by markoaamunkajo** [comment]
Will not change for now @DG12 because people are confused about downloading data from cloud and via local Bluetooth. Mention about Bt is there for a reason this time :)

**Comment by DG12** [comment]
I'm sure "**people** are confused about downloading data from cloud and via local Bluetooth".
Station is confused too %-( i.e.  which data to keep, which data to remove 1) observed data 2) sync'ed data 3) cloud data.

Note that the entire text box includes "local sensor data ..."
including **bluetooth** does not eliminate the possibility  that the data is not coming from the cloud :-)

Perhaps something like
Synchronizing historical data from local sensor.

Actually why is this confirmation even needed. See my comment regarding RSSI at issue#1367

PS There's plenty of room to change "Sync" to "Synchronize with sensor"

Please reopen.
