### ISSUE TITLE
Chart should include time of last received data  - enhancement 0.6.1(18)

### ISSUE THREAD

**Issue by DG12** [ruuvi/com.ruuvi.station.ios#137]
It would be h### helpful if the time of the last data point was included in the chart display.

**Comment by rinat-enikeev** [comment]
Could you please clarify by screenshot and simple drawing?

**Comment by DG12** [comment]
![RuuviStartEndExample](https://user-images.githubusercontent.com/2365961/99212430-027a9680-2799-11eb-904e-681b380aeff7.jpeg)

**Comment by DG12** [comment]
Smaller image:
![RuuviStartEndExample](https://user-images.githubusercontent.com/2365961/99212545-4a012280-2799-11eb-967a-391a52bca82f.jpeg)

**Comment by rinat-enikeev** [comment]
@andreevdenis let's discuss

**Comment by rinat-enikeev** [comment]
this is related to Android/iOS unification

**Comment by rinat-enikeev** [comment]
@andreevdenis could you please link the same issue on Android side with this issue.

**Comment by rinat-enikeev** [comment]
the timestamps should be more relevant, like 12:00 13:00 and 14:00 and so on

**Comment by markoaamunkajo** [comment]
QA passed
