### ISSUE TITLE
Cards get confused after visiting Dashboard

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station.ios#1370]
Description:

2.0.1(359)  iPhone 14 Pro

User is browsing sensor cards in Ruuvi Station app.
Everything looks normal until he visits dashboard and does the browsing again. First time duplicate amount of cards shown to me.

https://user-images.githubusercontent.com/50437378/224617229-f3e40562-84ac-4873-8f1b-d7f9fd0eb28e.mov

**Comment by priyonto** [comment]
@markoaamunkajo I had no luck reproducing it. Can you reproduce it reliably every-time?

**Comment by markoaamunkajo** [comment]
@priyonto not reliably. I saw it once again during testing, I'm not 100% sure if it's related to cloud sync.

**Comment by priyonto** [comment]
Can be considered as duplicate of #1382. Also, I don't think its duplicating the sensor cards. Its taking user to the first card in middle of swiping. I was able to reproduce it.

**Comment by markoaamunkajo** [comment]
Closing as duplicate
