### ISSUE TITLE
Shared sensor didn't sync to phone until I killed app

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station.ios#1371]
Description:

2.0.1(359)

User with free account added a sensor to Ruuvi Cloud on iPhone 1
Then shared this sensor to another user with free account

Sensor showed up in Ruuvi Station web for him
It didn't show up in Ruuvi Station on iPhone 2 for half an hour, user stayed on Dashboard
He then killed the app and sensor was synced and appeared to Ruuvi Station

https://user-images.githubusercontent.com/50437378/224620001-c35cfbf7-0e18-4fb2-932f-2abe390a50e6.mov

Related card: https://github.com/ruuvi/com.ruuvi.station.ios/issues/1340

**Comment by priyonto** [comment]
@markoaamunkajo I wasn't able to reproduce the issue but I found an issue where free plan sensors were not getting the latest measurements. Not sure if they are related but fixed but. I suggest you to test this and see if you can reproduce on the next build.

**Comment by markoaamunkajo** [comment]
QA passed
