### ISSUE TITLE
Firmware update no update needed upon check

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station.ios#1372]
Description:

Firmware reports current v3.29.0+default and  available is 3.31.1

Firmware page check result:
You are running the latest firmware no update needed.
-
Device: iPhone XS Max. OS: iOS 16.3.1
App: Ruuvi Station 2.0.1(358)
Location: Aruba   <<<<<<<<<<<<
Photo Library: authorized
Camera: authorized-

**Comment by priyonto** [comment]
@markoaamunkajo This is probably outdated. Should have been fixed in a couple of versions ago.

**Comment by markoaamunkajo** [comment]
Moving to done
