### ISSUE TITLE
Chart x axis label should be language consistent  - minor 0.7(21)

### ISSUE THREAD

**Issue by DG12** [ruuvi/com.ruuvi.station.ios#138]
Chart x axis with English set as language shows 

1:46AM
18/10

It should show
1:46AM
10/18

**Comment by rinat-enikeev** [comment]
@viikufa could you please take a look?

**Comment by viikufa** [comment]
> @viikufa could you please take a look? 
Ok

**Comment by viikufa** [comment]
resolved in https://github.com/ruuvi/com.ruuvi.station.ios/pull/189

**Comment by DG12** [comment]
Fixed in 0.6(24) closing

**Comment by viikufa** [comment]
resolved in station/Classes/Util/DateValueFormatter.swift
