### ISSUE TITLE
Firmware cannot be updated - you are running the latest

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station.ios#1384]
Description:

Firmware reports current v3.29.0+default and  available is 3.31.1
You are running the latest firmware no update needed.
-
Device: iPhone XS Max. OS: iOS 16.3.1
App: Ruuvi Station 2.0.1(358)
Location: Aruba   <<<<<<<<<<<<
Photo Library: authorized
Camera: authorized-

**Comment by markoaamunkajo** [comment]
I couldn't replicate yet.

**Comment by DG12** [comment]
With 361,  active sensor 4D15, 450A, 
 EC0F (SW Ruuvi FW v3.31.1+default:from NFC) 
 does not display current version, i.e. "-"

53F1,24C2 shows current as v3.31.1+default "you are running lastest'

latest available v3.31.1 (Which gets overwritten !)
attempt to update "you are running the latest...

**Comment by markoaamunkajo** [comment]
Retested with latest build, I don't spot any new issues, closing this card, will reopen if this issue still persists.
