### ISSUE TITLE
New sensor, no graph icon, sequence number 30000

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station.ios#1386]
Description:

New sensor. Never seen gateway. After 12 hrs ; sequence number 30,000+; no graph icon
------------------------------------------
Device: iPhone XS Max
OS: iOS 16.3.1
App: Ruuvi Station 2.0.1(358)
Location: Dominican Republic 🇩🇴
Photo Library: authorized. Camera: authorized. Notifications: authorized

**Comment by markoaamunkajo** [comment]
After several hours, 26,824(rolled over N times) still no graph icon or graph for 53F1. I believe never seen internet.

It might be helpful if  this feedback included last sensor ID, and its battery value.

DG12
------------------------------------------
Device: iPhone XS Max
OS: iOS 16.3.1
App: Ruuvi Station 2.0.1(359)
Location: Turks & Caicos  <<<<<<<<<
Photo Library: authorized
Camera: authorized
Notifications: authorized
------------------------------------------

**Comment by markoaamunkajo** [comment]
53F1 still no graph,, but wait! App settings default, show chart on dashboard card tap was off, change to on and graph shows but no icon!
DG12

------------------------------------------
Device: iPhone XS Max
OS: iOS 16.3.1
App: Ruuvi Station 2.0.1(359)
Location: somewhere in Caribbean <<<
Photo Library: authorized
Camera: authorized
Notifications: authorized
------------------------------------------

**Comment by DG12** [comment]
No owner ! 
After claiming ownership then graph icon is present\

**Comment by markoaamunkajo** [comment]
I saw the graph icon missing in some test case but I was able to bring the sensor back with graph icon when I removed sensor card and re-added same sensor later. Not sure what happened.
