### ISSUE TITLE
SSL error when attempting to update fw

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station.ios#1389]
Description:

Attempt to check firmware, SSL error.

More user friendly message is needed

------------------------------------------
Device: iPhone XS Max
OS: iOS 16.3.1
App: Ruuvi Station 2.0.1(358)
Location: not determined
Photo Library: authorized
Camera: authorized
Notifications: authorized
------------------------------------------

**Comment by markoaamunkajo** [comment]
I'm not sure if SSL is related but my firmware update definitely has problems. Fw update was attempted for 3.28.13 sensor and it seems that updating might be finished successfully on the sensor but app is stuck at "updating..." screen and it doesn't recognise new firmware that was uploaded in the sensor.

Sorry for long video (had courier deliver package in the middle of test!

https://user-images.githubusercontent.com/50437378/226251373-98bcabc6-1cf2-4290-b87c-bdde804dbbd3.MP4

**Comment by markoaamunkajo** [comment]
Update: confirmed with NFC reader the sensor is updated to 3.31.1+default but it won't update to the app.

**Comment by priyonto** [comment]
@markoaamunkajo the one you mentioned is known and fixed. Duplicate #1365 
Not sure what the SSL error is about.

**Comment by priyonto** [comment]
@markoaamunkajo Need more details on the SSL error. I can't find any reference of SSL in the DFU page.

**Comment by DG12** [comment]
I thought the message "SSL error."  was confusing and should be more informative. Guess I was right.

See also [Updating firmware doesn't complete issue#1385](https://github.com/ruuvi/com.ruuvi.station.ios/issues/1385)

**Comment by markoaamunkajo** [comment]
I didn't spot SSL error message yet during fw update testing but as a side note I believe renewing SSL's were discussed on Android side, maybe this could even be related @priyonto ?

**Comment by markoaamunkajo** [comment]
Retested with latest build, I don't spot any new issues, closing this card.
