### ISSUE TITLE
Sensor card name capitalization bug

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station.ios#1404]
Description:

iPhone SE
2.0.2 (363)

User adds new sensor card with default name.
Browsing the card in app shows

Dashboard: normal text
Sensor card: capitalised name
Sensor history: normal text

https://user-images.githubusercontent.com/50437378/228431492-88a16d58-6948-45a6-a982-28cb66acfdb6.mp4

**Comment by markoaamunkajo** [comment]
QA passed

**Comment by DG12** [comment]
I notice on this video, user taps multiple times before station responds!
I have reported this problem previously 
:-(
