### ISSUE TITLE
End of life for virtual sensors

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station.ios#1405]
Description:

End of life for virtual sensors
Virtual sensors will be disconnected also from old customers

Check from stats how many users are there using this feature

Maybe push message to users who still have virtual sensors in app

**Comment by markoaamunkajo** [comment]
@priyonto are we able to see number of users who have 1 or more virtual sensors?

**Comment by priyonto** [comment]
@andreevdenis Can help out I guess with this?

**Comment by priyonto** [comment]
> @priyonto are we able to see number of users who have 1 or more virtual sensors?

@andreevdenis Can help out I guess with this?

**Comment by andreevdenis** [comment]
Currently it's 213 users according to Firebase

**Comment by markoaamunkajo** [comment]
Ok 213 is still a lot, let's wait until number will go down. Keeping this in backlog until infinity.

**Comment by rinat-enikeev** [comment]
Inform users before 2.6.0 release about end of life of virtual sensors @markoaamunkajo

**Comment by rinat-enikeev** [comment]
alpha 2.5.2 (2312062210)

**Comment by markoaamunkajo** [comment]
Discuss next steps with Lauri

**Comment by rinat-enikeev** [comment]
with 2.5.2 (2312170000) you can add virtual sensors

**Comment by markoaamunkajo** [comment]
Installed to old iPhone SE, waiting for in app messages

**Comment by markoaamunkajo** [comment]
QA passed
