### ISSUE TITLE
SQlite error 19

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station.ios#1418]
Description:

Device: iPhone 14 Pro
OS: iOS 16.2
App: Ruuvi Station 2.0.0(354)
Location: not determined
Photo Library: not determined
Camera: not determined
Notifications: denied

User reported seeing SQlite error 19 when trying to add sensor on Add a New Sensor page.
Old issue: https://github.com/ruuvi/com.ruuvi.station.ios/issues/738

Now appearing in 2.x version after user moved to new iPhone and restored from backup.

![sqlite_error](https://user-images.githubusercontent.com/50437378/229389720-6f02bd6f-9169-4487-b53e-d783e60b6ee9.jpeg)

**Comment by markoaamunkajo** [comment]
Replied to customer to make clean install

**Comment by markoaamunkajo** [comment]
Typical case when this occurred was that user removed sensor and then tried to add it again, then error was shown.

**Comment by rinat-enikeev** [comment]
2.6.0 (2401061029)

**Comment by markoaamunkajo** [comment]
QA passed
