### ISSUE TITLE
Out of BT range error report

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station.ios#1419]
Description:

Attempt to update sensor which is out of BT range should be rejected with message similar to “That sensor is out of range and cannot be updated now”

If tag is not in BT range do not report “Your sensor does not report its version. Either you are not in BT range, just state “That sensor is out of range”
(( :-) PS it doesn’t matter where YOU are, matters where the sensor is. :-)

“DFU service is not found” is very user unfriendly

DG12
---------------------------------------
Device: iPhone XS Max
OS: iOS 16.3.1
App: Ruuvi Station 2.0.2(366)
Location: Cherry Hill, NJ USA
---------------------------------------

**Comment by markoaamunkajo** [comment]
![Image](https://user-images.githubusercontent.com/50437378/230516407-66fedd4d-c456-4b53-bbf9-a820c4257048.jpeg)

**Comment by markoaamunkajo** [comment]
Considered this but there are multiple scenarios where this error is shown and it's very descriptive. Typical case is that user has paired sensor to another iOS device and we are not able to receive firmware error.

**Comment by DG12** [comment]
Please reconsider.
I agree there are multiple scenarios of this (As the message states) and although very descriptive,
at least some of the cases can be isolated and a more precise message would be helpful for the user
