### ISSUE TITLE
Sync should report what it had and what it got  - enhancement 0.6.1(18)

### ISSUE THREAD

**Issue by DG12** [ruuvi/com.ruuvi.station.ios#143]
It would be very helpful, especially for tags with older firmware, if the sync operation reported
Before sync nn events
   oldest mm/dd hh:mm
  newest  mm/dd hh:mm
Sync retrieved nn events
  oldest  mm/dd hh:mm
  newest  mm/dd hh:mm

**Comment by rinat-enikeev** [comment]
@laurijamsa what do you think on adding this UX?

**Comment by laurijamsa** [comment]
This is something we'll consider on the new UX for sure. Most probably we'll come up with some more simple solution that would look not so designed for engineers only... Closing this.
