### ISSUE TITLE
Sensor data removal permission request for user

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station.ios#1436]
Description:

Description:

Allowing sensor data removal for user
Removing cloud data or leaving it together with sensor removal from app

Needs spec

Android issue: https://github.com/ruuvi/com.ruuvi.station/issues/960
Web issue: https://github.com/ruuvi/com.ruuvi.station.webui/issues/289
Cloud issue: https://github.com/ruuvi/ruuvi.cloud.js/issues/195

**Comment by priyonto** [comment]
Is this same as #1555 and #1552 ?

**Comment by markoaamunkajo** [comment]
Closing with https://github.com/ruuvi/com.ruuvi.station.ios/issues/1555
