### ISSUE TITLE
User should be able to select sensors to chart - enhancement 0.6.1(18)

### ISSUE THREAD

**Issue by DG12** [ruuvi/com.ruuvi.station.ios#144]
The user should be able to select which sensors to include in the charts.
As discussed in Ruuvi Slack many people are not interested in air pressure.
In some cases either the movement indicator or one of the accelerometer is more important.

**Comment by rinat-enikeev** [comment]
This is UX question, @laurijamsa what do you think about it?

**Comment by laurijamsa** [comment]
This feature is planned on the new UX design. Closing this issue.
