### ISSUE TITLE
Sensor card search

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station.ios#1447]
Description:

Add search for showing sensor cards in WebUI according to text search

- Search box at top of WebUI view:

Search box showing placeholder text "Search..." and magnifying glass icon
When user inputs text the magnifying glass changes to X
Tap on X will clear the text and search results

Make sure that the search box fits on mobile viewport
Optimise search to work in different dashboard views fast and efficiently

- Search logic:

User story:

User inputs text ie "cab" dashboard will automatically start showing only cards that contain the inputted text "cab"
Pressing enter deactivates the field but doesn't reset it. Keyword will be shown in field until cleared using X
Typical search wildcards and partials can be used
Other cards that are not matching search will be filtered out and not shown on dashboard
Dashboard selection will not reset search result (user can choose other view, other data or other day range) 
When user opens any card from search results in full sensor card view the search will not be reset, he should be able to return to search results after closing full sensor card view

**Comment by sini-maaria** [comment]
![Screenshot 2023-04-24 at 9 23 14](https://user-images.githubusercontent.com/19531763/233915438-71b815f2-d67f-4323-8ee0-a838644ffdf3.png)

**Comment by markoaamunkajo** [comment]
Wrong repository, closing this one
