### ISSUE TITLE
Display additional sensor data on main tag page - enhancement 0.6.1(18)

### ISSUE THREAD

**Issue by DG12** [ruuvi/com.ruuvi.station.ios#145]
There is much unused space on the main page of the tag display.
I would be helpful I many cases if additional sensor values were displayed there rather than the secondary page.
In particular X,Y,Z and movement counter.

**Comment by laurijamsa** [comment]
Thanks for the feedback. We're preparing a completely updated UX/UI design for the Ruuvi Station apps (Android & iOS). One of the many upcoming updates is related to this. Will close this one as it's not related on the code project itself and it's being handled already.
