### ISSUE TITLE
Add sensor setting: Unclaim ownership

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station.ios#1462]
Description:

Similar subpage as in Force Claim but when ownership is assigned to signed in account then 

Show arrow on Owner field after email address
Tap on arrow to forward to Unclaim page

![Image](https://user-images.githubusercontent.com/50437378/235576908-799763fb-5cda-4251-92d3-4af1d1a667b8.jpg)
![Image](https://user-images.githubusercontent.com/50437378/235576907-bc75e189-b53d-4430-9c4c-dbf4ae60e412.jpg)

Android card: https://github.com/ruuvi/com.ruuvi.station/issues/896

**Comment by markoaamunkajo** [comment]
QA passed

**Comment by priyonto** [comment]
@markoaamunkajo Translations were added after this build was created on firebase. Next build should be fine.

**Comment by markoaamunkajo** [comment]
QA passed
