### ISSUE TITLE
2.1.0(371) Movement alert bell triggers falls in loop after a while

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station.ios#1463]
Description:

Movement alert is not triggering bell icon on sensor cards in app. Only notification is shown.

Tested with local BT sensor.

**Comment by priyonto** [comment]
@markoaamunkajo I literally had no luck reproducing this on both of my devices.

**Comment by markoaamunkajo** [comment]
@priyonto Looks like this affects iPhone 14 Pro and not SE, also it doesn't affect your device. Maybe limited issue and shouldn't stop release at this point. Let's investigate again later. Moving to backlog for now.

**Comment by markoaamunkajo** [comment]
This card is still valid

**Comment by priyonto** [comment]
@markoaamunkajo Need  reproducing steps for this.

**Comment by markoaamunkajo** [comment]
@priyonto I have no idea how but this seems fixed on my iPhone 14 now. I don't recall us adding a fix for it though.
Closing this card.

**Comment by priyonto** [comment]
@markoaamunkajo: I fixed the loop but second point is not fix-able I think at least as of now, and Android is also same. 
The reason is the moment alert bell blinks, it gets reset with new measurement where old movement count == new movement count, which means no alert trigger.

**Comment by markoaamunkajo** [comment]
QA passed
