### ISSUE TITLE
Crash reports in Firebase

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station.ios#1473]
Description:

User signed out from Ruuvi Station and added local BT sensor
He is able to try to claim it, even he is not signed into Ruuvi Cloud.

2.1.0 (372)

This is likely causing crash, there will be another card for UX part.

**Comment by priyonto** [comment]
@markoaamunkajo Fixed the most critical one. Others are minor and can co-live for now. I will investigate them separately.

**Comment by markoaamunkajo** [comment]
QA passed
