### ISSUE TITLE
Scanning for sensors omits ones found previously 

### ISSUE THREAD

**Issue by DG12** [ruuvi/com.ruuvi.station.ios#1488]
Each pass of scanning for new sensors clears the list when it begins. This causes sensors at the edge of the radio range to be detected and displayed during pass n.
During pass n+1, n+2 they disappear (from the list, they are actually still there of course) and they should be "add_able".
They may be detected in pass n+m.

The list should only be cleared once when entering the scan card.

**Comment by markoaamunkajo** [comment]
When on Add a New Sensor card I retested the experience and two sensors closest to me never cleared from the list, one closer to the edge of radio range was getting added and removed. For me this experience is ok.
