### ISSUE TITLE
Gatt sync not working for local sensors

### ISSUE THREAD

**Issue by priyonto** [ruuvi/com.ruuvi.station.ios#1491]

**Comment by markoaamunkajo** [comment]
Spent some time testing repeated GATT syncing of sensors.
The general feeling is that once you add more sensors to the app and keep syncing them the beginning of the sync starts to slow down. One possible edge case spotted related to BT scanning sensor instead of downloading sync data.

**Comment by markoaamunkajo** [comment]
Kept syncing one sensor and I was able to reproduce the case when sensor stopped syncing and started to listen and store  sensor data again.

Steps:

Sync same sensor repeatedly, clear sensor data in between syncing. I was able to get to this state after maybe 10 syncs.


![Image](https://github.com/ruuvi/com.ruuvi.station.ios/assets/50437378/d55db7d1-e6df-478b-9068-878b3f621255)

**Comment by markoaamunkajo** [comment]
@priyonto This is likely not going to affect a lot of users (I hope), moved to next sprint.

**Comment by priyonto** [comment]
@markoaamunkajo Please do one more round testing when not in paired mode? Should at least give me some pointers. I am not blind and feeling stupid. No luck in reproducing any issue.

**Comment by markoaamunkajo** [comment]
Tested not paired mode, I see no differences.

But I finally now encountered this situation where no data was downloaded from sensor. The steps using iPhone SE were:

Added via bluetooth, claimed,  signed out and signed in to another account, force claimed via NFC,
Then trying to sync I didn't get any data from the sensor.

In the screenshot I see that it's showing Bluetooth icon and I didn't receive error for sensor being out from Bluetooth range, so I consider that this sensor somehow is seen via Bluetooth even I am in Cloud mode enabled.



![Image](https://github.com/ruuvi/com.ruuvi.station.ios/assets/50437378/01b16134-08e6-48b9-a1aa-a4995deb5837)

**Comment by markoaamunkajo** [comment]
I think this is going to be a forever card, moving it to backlog for now.

**Comment by priyonto** [comment]
@markoaamunkajo want to revisit this again? 💃

**Comment by markoaamunkajo** [comment]
Considering this is an edge case will not happen in real life user situation too often. If happens, can be resolved by reinstalling app.
