### ISSUE TITLE
Configuration option : active interval; duration 

### ISSUE THREAD

**Issue by DG12** [ruuvi/com.ruuvi.station.ios#15]
Since receiving packets is rather battery intense on the phone, it would be advantageous to have an "active interval" (or similar) setting. 

During each "active interval" station should stay active for "duration"

For example: interval is 10 minutes, duration is 10 seconds means that every 10 minutes packets would be received for 10 seconds.

This seems to wants to be a per tag configuration.

**Comment by rinat-enikeev** [comment]
If it is "per tag configuration", that means I need to keep scanner active if at least one tag is in active interval. Need to do more research about power consumption for working scanner to determine if it is not negligible power consumption benefit.

**Comment by rinat-enikeev** [comment]
closing as outdated, feel free to reopen if still relevant
