### ISSUE TITLE
virtual tag "Your location" not updated - information

### ISSUE THREAD

**Issue by DG12** [ruuvi/com.ruuvi.station.ios#150]
At home with good WiFi signal but connected to wrong access point!
Coincidently iPhone spontaneously switched to RuuviGateway B829 as access point.
Although gateway is configured to the correct WiFi access point it doesn't seem to forward packets.

I post this in case someone else encounters this problem.

**Comment by rinat-enikeev** [comment]
@DG12 we can't fix your internet connection remotely :) Please use correct WiFi.
