### ISSUE TITLE
Sensors in df3: show update firmware popups every time when accessing sensor settings page

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station.ios#1508]
Description:

When user has sensor with fw 2.5.9 and it's running in df3, we will show update popup every time user accesses this sensor settings page.

1. 

![Image](https://github.com/ruuvi/com.ruuvi.station.ios/assets/50437378/be70428c-0082-4430-8144-a2bc41d2d123)

If users chooses chancel, we weill show additional "are you sure" popup

2.

![Image](https://github.com/ruuvi/com.ruuvi.station.ios/assets/50437378/457a510b-16ae-4753-a575-92aaa372caa4)

**Comment by markoaamunkajo** [comment]
@priyonto if user switches between df5 mode and back to df3 he will not be shown popup again. It should be able to show popup again.

**Comment by markoaamunkajo** [comment]
@priyonto now it seems that popup is also shown on df5 mode. We don't want to show popup in df5 mode but always when in df3 mode.

**Comment by priyonto** [comment]
@markoaamunkajo Followed different approach. But, this may take a second or two to show the modal when sensor settings page is opened. But, it should be much more reliable in showing the modal than the old approach.

**Comment by markoaamunkajo** [comment]
QA passed
