### ISSUE TITLE
Firmware update is not possible if current version cannot be checked via GATT

### ISSUE THREAD

**Issue by laurijamsa** [ruuvi/com.ruuvi.station.ios#1517]
When trying to update 2.5.9 checking current version loader icon just keeps spinning and user cannot proceed. To be reproduced and timeout added needed. Unify timeouts with Android.

**Comment by markoaamunkajo** [comment]
@priyonto this gets still stuck (no timeout)  in 2.2.0(381)

![Image](https://github.com/ruuvi/com.ruuvi.station.ios/assets/50437378/f874bbe4-6cc5-4b19-892b-ee1f071aa9cb)

**Comment by markoaamunkajo** [comment]
QA passed
