### ISSUE TITLE
Movement alert generates multiple notifications

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station.ios#1519]
Description:

User is signed into Ruuvi cloud and cloud mode is disabled. He is using dev server in app. User switched pairing on on sensor settings page and started generating movement alerts by moving sensor.

Actual: multiple notifications are created.
Expected: newest should replace the older notification about same alert from same sensor. Also I see that (possibly) cloud alert doesn't have description in notification.

![Image](https://github.com/ruuvi/com.ruuvi.station.ios/assets/50437378/79a93b0f-618d-455e-968b-eed55c2414e3)

**Comment by markoaamunkajo** [comment]
Discussed in dm this is not fixable with our current methods.

**Comment by laurijamsa** [comment]
Could you explain better why this cannot be fixed and does this happen also for production server and other alerts than movement? @markoaamunkajo

**Comment by markoaamunkajo** [comment]
@laurijamsa 

`I think as of now we don't have a way to update a single notification value instead of generating multiple notifications from multiple trigger.  

Marko:
Ok, this is coming in iOS 16?

Priyonto:
Available on iOS 16 already, but the recommended use case for this is actually doesn't align with our use cases. Live activities are for limited time live things, such as a game of sports where scores are updated for a limited time, or an Uber food order where the order status changes within a certain period of time....`

**Comment by laurijamsa** [comment]
Hmm, sounds weird. Need to discuss about this more in some of our meetings. Reopening and assigning to us so that we will remember to check this.

**Comment by markoaamunkajo** [comment]
Adding link to documentation https://developer.apple.com/documentation/activitykit/displaying-live-data-with-live-activities

**Comment by markoaamunkajo** [comment]
Closing this since we now have setting for limiting alert notifications.
