### ISSUE TITLE
2.2.0(378) Bluetooth icon appearing to charts page when filtered sensor is in cloud mode

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station.ios#1521]
Description:

User added sensor to Gateway blacklist with MAC address (Gateway configurator)
Then he set in his Ruuvi Station Cloud mode Enabled

Now when he chooses to open this sensor card in history view from Dashboard he will see Bluetooth icon appearing and last updated time counting up.

https://github.com/ruuvi/com.ruuvi.station.ios/assets/50437378/91ef83ee-8824-4d6c-b034-ddb5ecec3534

**Comment by markoaamunkajo** [comment]
Moved to 2.3 it's considered edge case and fw not in production yet

**Comment by markoaamunkajo** [comment]
@priyonto 

I am testing this with Gateway firmware 1.14 that has sensor blacklisting feature.
I had this sensor running in Cloud mode, then went to Gateway settings and added it to blacklist.
Then switched to mixed mode and now when I go to charts page the sensor is updating via Bluetooth.

I actually think that this sensor should be updated via local Bluetooth everywhere in the app since app is in mixed mode and Bluetooth is enabled.

https://github.com/ruuvi/com.ruuvi.station.ios/assets/50437378/2d830e51-809c-4dcc-973d-682c657c97de

**Comment by priyonto** [comment]
@markoaamunkajo I can't really reproduce it with Lauri's suggestion (disconnecting the gateway from power). Not sure how its happening. Would be great if you try one more time and if still reproducible then navigate me how I can reproduce it as well with gateway and such.

**Comment by markoaamunkajo** [comment]
Now it's not seen again. Let's close this, will reopen if it pops up again.
