### ISSUE TITLE
Firebase seems to be unable to install versions before 374

### ISSUE THREAD

**Issue by DG12** [ruuvi/com.ruuvi.station.ios#1523]
Attempting to test regression issue .
![Cannot nstall](https://github.com/ruuvi/com.ruuvi.station.ios/assets/2365961/2d7ed037-5edc-4abe-824e-3a88ff7b9de5)

hopefully this can be corrected.

**Comment by priyonto** [comment]
Not a bug. The older versions are expired and can’t be installed anymore.

**Comment by DG12** [comment]
I was trying to do some regression testing, i.e.  I thought there was something that used to work. 
Maybe it would be useful if expiration was longer.
Expired versions should not be show. 

No big deal.

**Comment by priyonto** [comment]
Expiration of these builds depends on the distribution profiles from Apple,. They are valid for one 1 year. So, if any version is created when the profiles are around the end of life then its gets less liefetime. For example, the build we are pushing now will be available for around 1 year from now.
