### ISSUE TITLE
Update to the latest Firebase Cloud Messaging APIs and SDKs 

### ISSUE THREAD

**Issue by priyonto** [ruuvi/com.ruuvi.station.ios#1525]
Starting June 20, 2024 the legacy Firebase Cloud Messaging (FCM) APIs will be discontinued. We will have to update the app accordingly before that.

**Comment by priyonto** [comment]
This has dependency with cloud. Needs investigation.

**Comment by markoaamunkajo** [comment]
@priyonto what kind of depency is it on Cloud side? Or can it be updated without waiting?

**Comment by priyonto** [comment]
@markoaamunkajo This concerns mainly the cloud side. From app side, the changes I am expecting are minimum to close to none. But, I will update here if I get more information on this. So far, this is my understanding from the doc.

**Comment by markoaamunkajo** [comment]
Asked update from Otso

**Comment by ojousima** [comment]
AWS sent an email about it, the message was essentially "sit tight, we're working on it"

**Comment by ojousima** [comment]
Fixed on Cloud side.
