### ISSUE TITLE
Change new URL to dev environment

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station.ios#1532]
Description:

@priyonto 

We want to change the URL that is pointing to dev environment in Default menu setting.
Please confirm URL from @ojousima 

We'd like this change done to 2.2 build

**Comment by ojousima** [comment]
Should be in testnet.ruuvi.com, but I'm not sure if that routes properly. Let me know on Monday when the DNS has propagated

**Comment by markoaamunkajo** [comment]
Still showing SSL error when switching but I assume this is ok and we can fix it in the mix
What do you think @priyonto

**Comment by markoaamunkajo** [comment]
QA passed
