### ISSUE TITLE
Add more history length options to History page

### ISSUE THREAD

**Issue by laurijamsa** [ruuvi/com.ruuvi.station.ios#1537]
Description:

Let's add new options to view history length in history page.

Same as on the web ui:

<img width="307" alt="image" src="https://github.com/ruuvi/com.ruuvi.station/assets/1311912/9906dbd7-3849-49dd-85b0-b7dc1e051437">

Please use same strings as in webui.

Android card: https://github.com/ruuvi/com.ruuvi.station/issues/1052

**Comment by markoaamunkajo** [comment]
@priyonto 2.4.0(400) I managed to see 5 hours on the first install when I opened the chart and viewed it.
I was not able to reproduce. Is this possible?

**Comment by markoaamunkajo** [comment]
@priyonto can this be improved? I think when I choose for example 12 hours I was expecting to see the from 10 pm to 10 am but 10 am is not visible on the chart.

![Image](https://github.com/ruuvi/com.ruuvi.station.ios/assets/50437378/d12c775c-fac9-4842-9c77-f344c77dbe1c)

**Comment by markoaamunkajo** [comment]
2.4.0(406) @priyonto the chart seems to be loading views and it produces significant lag. Sometimes even the menu is not able to open.


https://github.com/ruuvi/com.ruuvi.station.ios/assets/50437378/3ef60089-6288-4c84-a8d4-a21d0952aef4

**Comment by priyonto** [comment]
@markoaamunkajo Assigned back to you according to the discussion in DM.

**Comment by markoaamunkajo** [comment]
@priyonto I think I finally understand what might be causing this. It's because my gateways were offline for a while and there is gap in the data.


![Image](https://github.com/ruuvi/com.ruuvi.station.ios/assets/50437378/4ead45ea-fddf-4c40-b86d-31ca7767638f)

**Comment by priyonto** [comment]
@markoaamunkajo Produced a similar situation like you by making the gateway offline. Still can't reproduce the issue.  
<img width="499" alt="Screenshot 2023-09-03 at 19 45 25" src="https://github.com/ruuvi/com.ruuvi.station.ios/assets/24395776/029592cb-a603-4f66-a453-711e65119cf3">
