### ISSUE TITLE
Scanning already added fw 3.31.1 sensor with NFC said old firmware version

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station.ios#1542]
Description:

User in cloud mode and has signed in to Ruuvi Station, he synced his sensors to iPhone and went to Add a new sensor page, scanned existing sensor with NFC and received report about old firmware version. This sensor has fw 3.31.1.

When user then checked sensor fw in sensor settings it is showing it's not detected. Switching to Bluetooth doesn't update firmware version shown on this page. Bluetooth icon was updated to sensor card.

If user tries to update firmware it says sensor is latest.

![Image](https://github.com/ruuvi/com.ruuvi.station.ios/assets/50437378/398ee26d-5bb7-42a4-a26b-6cfe4aebe9bc)

![Image](https://github.com/ruuvi/com.ruuvi.station.ios/assets/50437378/42f92961-d6ba-48e7-86e1-6cb9373ec960)

![Image](https://github.com/ruuvi/com.ruuvi.station.ios/assets/50437378/f106bd0a-73fb-47aa-b15a-6443af7fdb2b)

**Comment by priyonto** [comment]
@markoaamunkajo: Good find. The first part of the feedback, I could reproduce and will fix. 

Regarding the second part: We do check fw version ONLY after a sensor is added locally. That means when sensors are synced via login, the fw version is not visible or checked for sensors even if they are in the range of the device. 

There are a couple of efficient solutions I can think of now:

1. We check fw on sensor settings page open if there's no fw version available already.  
2. We update the fw version on the sensor settings page if user tries to update fw and get a response.

**Comment by markoaamunkajo** [comment]
QA passed
