### ISSUE TITLE
Improve Add a New Sensor page with info text

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station.ios#1543]
Description:

We need to add info text to show for user on Add a New Sensor page.
Note! This will replace the NFC text on this page.

     "ident_ios": "DiscoverTable.SectionTitle.Devices",
      "ident_android": "add_tag_title",

Please create a separate ident for iOS, because NFC string is slightly different from Android.

---

EN:
This page shows nearby Ruuvi sensors not yet added to the app. Tap a sensor to add it. 

Alternatively, you can add a sensor using NFC by selecting Add with NFC and touching it with your phone.

FI:
Tällä sivulla näet lähelläsi olevat Ruuvi-anturit, joita ei ole vielä lisätty sovellukseen. Lisää listattu anturi napauttamalla.

Voit vaihtoehtoisesti lisätä anturin sovellukseen NFC:llä napauttamalla Lisää NFC:llä painiketta ja koskettamalla sitä.

---

Important! Hide the "Alternatively.." text when NFC is not available on the device. Show text if it's available but disabled.

These should be two different strings in language file.

Also, bring the Buy Ruuvi Sensors button back to stay visible on the page.

![Image](https://github.com/ruuvi/com.ruuvi.station.ios/assets/50437378/0a68c0f2-2347-47cf-baba-b85b836f70c7)

**Comment by markoaamunkajo** [comment]
@priyonto is it possible to localise these elements? They come from the system?


![Image](https://github.com/ruuvi/com.ruuvi.station.ios/assets/50437378/c30c6755-c25d-4a25-9e41-ef06e01f5854)

**Comment by markoaamunkajo** [comment]
Will check spec again with Lauri

**Comment by priyonto** [comment]
@markoaamunkajo This comes from the system and I think it changes with system language.

**Comment by markoaamunkajo** [comment]
Moving to done because system language and we cannot help user here
