### ISSUE TITLE
Units and formatting from push

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station.ios#1544]
Description:

There are some differences in push alert formattings between Android and iOS.
Please check how these are handled in iOS app.

Please also add support for new boolean coming from API.

Android card: https://github.com/ruuvi/com.ruuvi.station/issues/1074

**Comment by markoaamunkajo** [comment]
![Image](https://github.com/ruuvi/com.ruuvi.station.ios/assets/50437378/37a094b8-01c6-4ba7-aba4-b02505e098b4)

![Image](https://github.com/ruuvi/com.ruuvi.station.ios/assets/50437378/bdad0a86-c684-4c94-af79-a754e0a458c0)

**Comment by priyonto** [comment]
Backend needs fixing for this.

**Comment by markoaamunkajo** [comment]
Waiting for @ojousima to give us boolean to use for receiving these from cloud. Please bug him if no news.

**Comment by priyonto** [comment]
Removed unit symbol from push message. Also added support for the boolean value. Field name communicated to Otso.

**Comment by markoaamunkajo** [comment]
QA passed for push messages, moved TestFlight to beta group
