### ISSUE TITLE
Aborted download should retain data that was downloaded

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station.ios#1550]
Description:

Aborted Cloud download should retain data that was downloaded

--

I am signed on, Ruuvi 53F1 is with me in Dublin airport.
Station says last updated 11 hours ago!
That Is time gateway last saw it.

------------------------------------------
Device: iPhone XS Max
OS: iOS 16.6
App: Ruuvi Station 2.3.0(387)
Location: not determined
Photo Library: not determined
Camera: authorized
Notifications: authorized
------------------------------------------

**Comment by DG12** [comment]
Did I describe 2 problems in one feedback? Sorry. I will submit a separate issue for: 

> I am signed on, Ruuvi 53F1 is with me in Dublin airport.
> Station says last updated 11 hours ago!
> That Is time gateway last saw it.

**Comment by priyonto** [comment]
@markoaamunkajo Aborted cloud download? What does it mean?

**Comment by DG12** [comment]
Observed:
I tapped Sync. 
Connecting.
Reading Bluetooth nnnn
Stall.
Attempt to sync immediately afterward retrieves little, if any data.
++++++
Example: 
Initial conditions:
Data in sensor includes data from Jul 1 through Jul 11.
Station Last Download was Jul 3 and so includes data through Jul 3.
Action:
1) Sync begins with Jul 3. 
2) Sync stalls or tag goes out of rang after station receives data from Jul 5.
3) Station (seems to) set "DateOfLastDownload" at Jul 11.
4) User taps sync mmediately and sync begins at Jul 11. Data from Jul 6 through Jul 10 never gets transferred to station.

**Comment by markoaamunkajo** [comment]
Closing this as we haven't received user feedback enough in order to rewrite sync logic.
