### ISSUE TITLE
Sensor previously reported by gateway, ignores advertisements - defect

### ISSUE THREAD

**Issue by DG12** [ruuvi/com.ruuvi.station.ios#1551]
I am signed on, Ruuvi 53F1 is with me in Dublin airport.
Station says last updated 11 hours ago!
That Is time gateway last saw it.

**Comment by priyonto** [comment]
Check if you have 'Cloud Mode' enabled.

**Comment by markoaamunkajo** [comment]
@DG12 was there Cloud Mode enabled for this one?

**Comment by markoaamunkajo** [comment]
Moving to done, case is cold
