### ISSUE TITLE
Remove sensor data after unclaim

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station.ios#1552]
Description:

We will ask user if he wants to delete sensor data from cloud during unclaim

![Image](https://github.com/ruuvi/com.ruuvi.station.ios/assets/50437378/4577c114-963c-487f-8f18-2b3089eb10c3)

Android card: https://github.com/ruuvi/com.ruuvi.station/issues/1065

**Comment by andreevdenis** [comment]
Can I suggest showing checkbox above Unclaim button with "Also remove this sensor's data from the Cloud"?

**Comment by laurijamsa** [comment]
Yeah, it is the (unwritten) plan :) So user would have an option to remove cloud data two ways: unclaim sensor or remove sensor. We'll create better specs before needing to start implementing this.

**Comment by priyonto** [comment]
This have slight dependency with cloud, cloud endpoint has to be adjusted with the settings.

**Comment by markoaamunkajo** [comment]
QA passed
