### ISSUE TITLE
Remove sensor redesign

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station.ios#1555]
Description:

We will redesign Remove sensor feature to forward user to subpage.

Notice that there is checkbox selection for removing also sensor history data.

![Image](https://github.com/ruuvi/com.ruuvi.station.ios/assets/50437378/f6e1bfd6-5b1d-4d8d-93c0-da01f6c5c2ac)

When user is not signed in, use the strings from popup on subpage.
When sensor is shared to you, use the strings from popup on subpage.

Android card: https://github.com/ruuvi/com.ruuvi.station/issues/1068

**Comment by priyonto** [comment]
@markoaamunkajo  This have slight dependency with cloud, cloud endpoint has to be adjusted with the settings.

**Comment by laurijamsa** [comment]
We have already discussed with Otso about this and agreed that it is ok to make 2 separate calls from the ui. One for removing the sensor and one for history data removal. And both should be already available in the api.

**Comment by priyonto** [comment]
We will have a separate description when user is not logged in. And we would hide the button for history removal.

**Comment by markoaamunkajo** [comment]
@priyonto here is the design for not signed in sensor removal.

![Image](https://github.com/ruuvi/com.ruuvi.station.ios/assets/50437378/2d4b9e8d-83cf-49a2-bc97-4dab8def754d)

**Comment by markoaamunkajo** [comment]
QA passed
