### ISSUE TITLE
Sync should indicate activity is continuing - 0.6.1(20) - enhancement

### ISSUE THREAD

**Issue by DG12** [ruuvi/com.ruuvi.station.ios#156]
If the tag has a lot of log data sync can take a long (3+minutes) time. There should be a progress indicator. Perhaps something like an overwriting number every 200(?) entries received least the user get bored and walk away or reset the app.

See https://github.com/ruuvi/ruuvi.firmware.c/issues/175

**Comment by DG12** [comment]
more important when sync fails to connect??

**Comment by rinat-enikeev** [comment]
closing as a duplicate of https://github.com/ruuvi/com.ruuvi.station.ios/issues/317
