### ISSUE TITLE
Change app welcome images

### ISSUE THREAD

**Issue by sini-maaria** [ruuvi/com.ruuvi.station.ios#1584]
1. Beaver with mailbox. (Old image had transparency on sensors.)
2. Last beaver

I will send you the new files.

![Screenshot 2023-08-03 at 10 36 05](https://github.com/ruuvi/com.ruuvi.station.ios/assets/19531763/d8b6fd74-7f25-4e59-8878-fafa5fa94b32)

**Comment by markoaamunkajo** [comment]
QA passed
