### ISSUE TITLE
Abort sync confirmation could be clearer. - nit

### ISSUE THREAD

**Issue by DG12** [ruuvi/com.ruuvi.station.ios#1588]
While Synchronizing, user **taps X, intending to abort**.

Popup says:
**"Are you sure?**
sometimes...."

choices are : 

Abort download

OK

Does "OK" indicate I am sure I want to abort? NO

Perhaps better wording would be:

Abort Download

Continue Download

**Comment by markoaamunkajo** [comment]
Discussed this but will not change for now.
