### ISSUE TITLE
Deep link button

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station.ios#1598]
Description:

We are looking into adding a button to open app from alert email.

Could we use Firebase dynamic link for button in email to redirect to app dashboard or what is suggested way in iOS?

Goal is to use same button for both mobile apps (iOS and Android).

**Comment by priyonto** [comment]
![Image](https://github.com/ruuvi/com.ruuvi.station.ios/assets/24395776/2fc3d513-5c4a-496a-be77-17ed9c7fdc67)

https://firebase.google.com/docs/dynamic-links

Firebase dynamic link is shutting down, we should not adopt this. We have to find alternatives.

**Comment by markoaamunkajo** [comment]
Discussed in meeting, moving to don
