### ISSUE TITLE
Synchronizing timeout not reliable

### ISSUE THREAD

**Issue by DG12** [ruuvi/com.ruuvi.station.ios#1599]
Attempt to sync to 230E.
Connecting, Synchronizing...

**Comment by markoaamunkajo** [comment]
Description:

User started sync and removed battery from sensor during sync, it doesn't timeout within many minutes.
User tried to sync next time without battery it is trying to connect to sensor "Connecting..." text is shown.

Let's improve reliability for these situations.

**Comment by DG12** [comment]
This also occurs when sensor is at then edge of radio reception, i.e. very low RSSI and not all, but some packets are not received.

**Comment by markoaamunkajo** [comment]
Compare with Android

**Comment by DG12** [comment]
Went visiting. Took 1 tag (4D15) along. Not logged in. RSSI between -93 and -83. Advertisements every 0-8 ago. Start sync , connecting, syncing stall at. Stall at 93. 10:47EDT. Now 10:55EDT still waiting.

**Comment by markoaamunkajo** [comment]
On Android it seems if I remove battery during sync there is no timeout.

**Comment by priyonto** [comment]
@markoaamunkajo We would probably need @ojousima's opinion here regarding what happens on the sensor fw side when tag loses connection in the middle of sync. And the timeout behaviour on the app side may depend on that.

**Comment by DG12** [comment]
Attempting to sync, after an abort, may be successful without interaction with the firmware. This means that the firmware is ready to begin again after a failure.

This problem can be duplicated with a ruuvi with RSSI less then about -80dB is placed on a MacBookPro keyboard then nearly closing the screen, as the aluminum case absorbs (or reflects?) the radio signal.

**Comment by markoaamunkajo** [comment]
@priyonto

I made tests for out of range by starting sync and driving my bike until I'm definitely out of range of BT

https://github.com/ruuvi/com.ruuvi.station.ios/assets/50437378/a91eabdd-cb26-4362-b47f-5aee578f5f71

There is no timeout occurring

When I arrived back to Bluetooth range of sensor, the app just starts to read new measurements



https://github.com/ruuvi/com.ruuvi.station.ios/assets/50437378/058ae689-08dc-4692-b9e3-ece00773b3a5

**Comment by markoaamunkajo** [comment]
Same test made by removing battery from sensor (instead of leaving Bluetooth range) yielded exactly same results.

**Comment by DG12** [comment]
The test by Marko with his (soon to be famous bike ride) shows exactly the defect.
The first video shows the download stuck at 30, with the latest advertisement 1 minute 37,.. ago.
The second one still shows the download at 30, it neither continues nor does it timeout (as it should), even though the app is receiving advertisements as seen by  1,2,3,0,1...seconds ago.

Please remove enhancement tag as this is definitely a defect.
Thank you.

**Comment by priyonto** [comment]
@markoaamunkajo Passed to you, set 60s as default timeout duration.

**Comment by markoaamunkajo** [comment]
@priyonto the popup text is bold. Not sure if similar is used anywhere. I think the popup should be:

Title: Download failed

Text: Bluetooth history download failed. Check that you're within Bluetooth range, your sensor has firmware that supports downloading and that the sensor is not paired with Bluetooth to another iOS device. Sensor connection is reserved for Ruuvi Station when using Bluetooth pairing in iOS.

Buttons:
Ok, Try again

![Image](https://github.com/ruuvi/com.ruuvi.station.ios/assets/50437378/64bcf2f3-0242-420a-a8c7-1a097cd8209e)

**Comment by DG12** [comment]
GREAT NEWS: test #1  time out occurred after sync transfered 153.
It took 5 minutes. 
Good news: test #2 time out occurred after sync hadn't even download any.

Sooner would be better.

Would be even better if, after sync got stuck and sensor returned within range, sync continued.
Test #3 sync completes successfully (-95dBm)
Test #4 sync completes really soon.
Test #5 sync completes really soon. (-96dBm less or more) !
Next test in 8 hours.

**Comment by DG12** [comment]
![image](https://github.com/ruuvi/com.ruuvi.station.ios/assets/2365961/ab2ad20b-1d30-43c8-9c0c-716facc74e38)

![image](https://github.com/ruuvi/com.ruuvi.station.ios/assets/2365961/35d3cb02-31c4-4b81-8009-f6a96535a715)

**Comment by DG12** [comment]
Please reopen 
Version 240607 1700 
230E  updates 0s ... 0..11s,0..1,0..11,0..8, 0..9, 0..8, 0..8, 0..7, 0..10,  ago
connects, syncs... 96    20:54, 20:55, 20:56, 20:57, 20:59 , 21:00

I give up , X sure ? Abort 
Golly this is great fun   =}:^(    cowboy hat frowning
Try again stalls at 137  21:01, 21:04
I give up already!
Glutton for punishment try gain stalls at 192 abort
Idiot : stalls at 46
PS not moving around.
