### ISSUE TITLE
Build fails due to missing Pods-station.debug.xcconfig

### ISSUE THREAD

**Issue by pentzin** [ruuvi/com.ruuvi.station.ios#16]
Build of station with Xcode 10.1 fails due to missing file:
Pods/Target Support Files/Pods-station.debug.xcconfig

@io53 Can you push it to master?

**Comment by pentzin** [comment]
I see that it was intentionally added to .gitignore in commit https://github.com/ruuvi/com.ruuvi.station.ios/commit/583d43a2e8b192fd48bb06f9556d91a4ece16289

# CocoaPods
#
# We recommend against adding the Pods directory to your .gitignore. However
# you should judge for yourself, the pros and cons are mentioned at:
# https://guides.cocoapods.org/using/using-cocoapods.html#should-i-check-the-pods-directory-into-source-control
#
Pods/

**Comment by pentzin** [comment]
Perhaps building instructions could be added to README.md or similar place if it's intended the project can't be built straight out of the box. Quoting from https://guides.cocoapods.org/using/using-cocoapods.html#should-i-check-the-pods-directory-into-source-control

> Benefits of checking in the Pods directory
After cloning the repo, the project can immediately build and run, even without having CocoaPods installed on the machine. There is no need to run pod install, and no Internet connection is necessary.

**Comment by io53** [comment]
Yes build instructions should definitely be added to the readme, thanks for the heads up.
Did you get it to build?
