### ISSUE TITLE
Graph only 2 scales across all time periods - 2.4.0(3909) - defect

### ISSUE THREAD

**Issue by DG12** [ruuvi/com.ruuvi.station.ios#1601]
Changing date range shows same graph from 1 hour through 4 days (8 time periods) and
a different graph for date ranges 5, 6 and 10 days
<img width="1345" alt="graphScalsIncorrectly" src="https://github.com/ruuvi/com.ruuvi.station.ios/assets/2365961/1b1a7c1f-7c3e-4a94-a450-9234500f0980">

**Comment by markoaamunkajo** [comment]
Related to card https://github.com/ruuvi/com.ruuvi.station.ios/issues/1537

**Comment by markoaamunkajo** [comment]
Cannot reproduce this issue.
Also we will implement a new viewport called All which will improve this experience.
