### ISSUE TITLE
graph  min=max=avg < current  2.4.0(399) - defect

### ISSUE THREAD

**Issue by DG12** [ruuvi/com.ruuvi.station.ios#1602]
Graph shows 
Min 71.0 Max 71.0 average 71.0 
temperature (72'F)

Yet Another Floating Point Problem?
![Min=Max=Avg_NE_current](https://github.com/ruuvi/com.ruuvi.station.ios/assets/2365961/2ddbf80a-0e67-4811-86e6-ba99ee51d98b)

**Comment by priyonto** [comment]
@DG12  The 72F is the latest measurement. The min max average is from the visible area. I don't see any defect here.

**Comment by DG12** [comment]
I would expect Max and avg to include current value.
It looks odd to see the current value greater than the max.
I would expect  
```
Min 71 Avg 71 max 72
current 72

```
Over what range is min,avg and max?
All data or only data displayed or something else



PS It's just me but I like the order to be min,avg,max

**Comment by laurijamsa** [comment]
I haven't tried this on iOS myself yet but according to the screenshot it seems that something is wrong as in the visible area max is not 71 but something else. We need more testing @markoaamunkajo

**Comment by markoaamunkajo** [comment]
@priyonto in this case if there is only 1 datapoint shown on graph, we should show "-" instead of "inf"


![IMG_6EAB817A8BF2-1](https://github.com/ruuvi/com.ruuvi.station.ios/assets/50437378/4e2dc184-334d-461c-b968-02646562c8e4)

**Comment by markoaamunkajo** [comment]
Reproduced.
The resolution setting in app settings is set to 1F degree.

Resolution setting should affect only live data. Min max avg should not be rounded.


![IMG_D375CF239336-1](https://github.com/ruuvi/com.ruuvi.station.ios/assets/50437378/fce75d70-6a57-4060-8707-6b1e93401f41)
![IMG_036A718EE67F-1](https://github.com/ruuvi/com.ruuvi.station.ios/assets/50437378/da857906-93ae-4310-bfc9-efeaa54da6d3)

**Comment by DG12** [comment]
Using hundredths for average may not be good for pressure in inHg since actual resolution in hundredths is the usual resolution used.

Using hundredths for humidity min, average and max is not good when user has specified 1% resolution.
 
Perhaps for average, using 1 more digit than user specified in settings for that resolution would be best (?). 

Since min and max are **actual** live readings they should use resolution user **specified**.

.
<img width="1165" alt="Furnace-220831-220930" src="https://github.com/ruuvi/com.ruuvi.station.ios/assets/2365961/755b436b-1859-4ac3-b2fd-b9c280fe2deb">


.

(Signed: Mr. "Don't uses to much precision" :-)

**Comment by priyonto** [comment]
Fixed the issues @markoaamunkajo reported. Further improvements will be done upon discussion.

**Comment by markoaamunkajo** [comment]
QA passed
