### ISSUE TITLE
Login code field should not accept special characters

### ISSUE THREAD

**Issue by DG12** [ruuvi/com.ruuvi.station.ios#1603]
Attempting to sigin , enter email address, immediately check inbox, find code for attempt 1 hour ago.
Enter old code reports

```
Error
The operation couldn't be
completed. (RuuviCloud.Ruuvi-
CloudError error 0.) 
```

![codeOperationErr](https://github.com/ruuvi/com.ruuvi.station.ios/assets/2365961/c2a1b5be-107c-4061-ac85-167646d5a3bb)

**Comment by markoaamunkajo** [comment]
@priyonto can this error be improved or is it coming from cloud?

**Comment by priyonto** [comment]
@markoaamunkajo Need investigation. Not sure yet.

**Comment by DG12** [comment]
Rare. previous occurrence issue #1603

**Comment by markoaamunkajo** [comment]
Reproduced trying with emoji in code field.
Let's block adding such special characters to this field and it should solve this issue.



![Image](https://github.com/ruuvi/com.ruuvi.station.ios/assets/50437378/0ab5312c-6b35-48ca-955b-92147b0f776a)

**Comment by priyonto** [comment]
@markoaamunkajo Note: Looking at the original description of the issue, the fix of not accepting special char will no fix the og issue. That seems to be an issue to handle from cloud side though. Or at least we need a different message and localised string for the error thrown on invalid code enter.

**Comment by markoaamunkajo** [comment]
@priyonto I think this fix should probably also restrict äöá and similar characters, I am still receiving same error.

**Comment by markoaamunkajo** [comment]
QA passed
