### ISSUE TITLE
login: entering incorrect code says "expired" 2.4.0 - defect-low priority

### ISSUE THREAD

**Issue by DG12** [ruuvi/com.ruuvi.station.ios#1604]
Attempting to login, after entering email, entering code incorrectly (could be spelling mistake of actual received code) reports

`Token is expired.`

All three platforms (IOS, Android and web) process this incorrectly. Perhaps the cloud is sending the wrong error code.

https://github.com/ruuvi/com.ruuvi.station.ios/assets/2365961/531f44b2-709d-4df7-8342-82cd49818aac

This is an attempt to clarify issue: 
Sign in: activation code error confusion 1.1.1(288) - nuisance #893

**Comment by priyonto** [comment]
@markoaamunkajo This issue should go to cloud repo I think.

**Comment by markoaamunkajo** [comment]
Added to cloud side

**Comment by DG12** [comment]
This has been "added to cloud side" . What repo would that be?

I still encounter this problem frequently ( as I upgrade to pre-release versions of station frequently and my email is rather slow)
