### ISSUE TITLE
Deep linking in email URL

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station.ios#1621]
Description:

Discuss with @ojousima about format for deep linking to open sensor card from email in iOS app.

https://github.com/ruuvi/ruuvi.cloud.js/issues/389

**Comment by priyonto** [comment]
@markoaamunkajo : You can test this with tapping this link: 
https://station.ruuvi.com/mobile

**Comment by markoaamunkajo** [comment]
@priyonto didn't work for me yet, not on devstation either. It opens Apache file server in browser

**Comment by markoaamunkajo** [comment]
@priyonto station.ruuvi.com is saying "hello" to me.
Does it need some extra functionality that is not yet implemented in order to open app?

**Comment by markoaamunkajo** [comment]
Discussed on channel, looks like with correct prod url it worked perfectly. Closing this card as completed.
