### ISSUE TITLE
Test sync queue features

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station.ios#1626]
Description:

User signed in, user on settings page and makes a change when internet goes offline

1. User kills app, is the setting saved locally and does it update new setting to cloud when user reopens app.

2. User leaves page, but doesn't kill app, is the changed setting updated to cloud when internet is back.

App on background
App on foreground

Test these on Android as well

**Comment by markoaamunkajo** [comment]
If setting was not saved to cloud
Showing error message to try again

Is it confusing if it's correct, but experience is incorrect.
Should we not save locally if we couldn't save settings to cloud.

**Comment by markoaamunkajo** [comment]
@priyonto I managed to make calibration setting ghost me in app.
Steps:

1. Set airplane mode on, clear calibration
2. Kill app, set airplane mode off
3. Start app again, go to calibration setting page, the old setting is shown briefly


https://github.com/ruuvi/com.ruuvi.station.ios/assets/50437378/f0d60ecd-7014-42c1-9b61-9b215f22aec8

**Comment by priyonto** [comment]
@markoaamunkajo I tried with multiple devices and several times. I had no luck reproducing it yet.

**Comment by markoaamunkajo** [comment]
Not seen anymore, closing this issue.
