### ISSUE TITLE
Use decimal separator based on system locale

### ISSUE THREAD

**Issue by viikufa** [ruuvi/com.ruuvi.station.ios#163]
Need to use decimal separator same as in system locale. 

![image](https://user-images.githubusercontent.com/13885861/102686813-e6d93480-420b-11eb-9d0e-2373c18a0810.png)
![image](https://user-images.githubusercontent.com/13885861/102686816-f0fb3300-420b-11eb-9680-cbcce0bd115b.png)
![image](https://user-images.githubusercontent.com/13885861/102686819-fbb5c800-420b-11eb-9b42-1db6ca902828.png)
![image](https://user-images.githubusercontent.com/13885861/102686826-096b4d80-420c-11eb-9c4a-f545771c65d3.png)

![image](https://user-images.githubusercontent.com/13885861/102686839-1720d300-420c-11eb-9da0-ad7b6afcb8fe.jpeg)
![image](https://user-images.githubusercontent.com/13885861/102686841-20aa3b00-420c-11eb-9066-0e3d3d599a4d.jpeg)

**Comment by DG12** [comment]
See issue #134

**Comment by markoaamunkajo** [comment]
0.6.2(2) QA passed
