### ISSUE TITLE
Organising sensor cards by drag and drop

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station.ios#1632]
Description:

We want to allow users to arrange cards on dashboard view.

Organise cards by force tap and then Drag & Drop.

We will use API to sync the card position on dashboard.
Save cards position to user profile in database, not to sensor settings.

- If custom ordering, then adding new sensor card will add to first position (top)
- If no custom ordering, then adding new sensor card will add to alphabetic position

If custom ordering, hide from naming sensors the string that says Sensors will adjust to alphabetical order.
If new sensor added it will go to first position if custom ordering is used.

**Comment by priyonto** [comment]
@markoaamunkajo Depends. The spec probably needs to be a bit more clear. 
For example, are we going to have both alphabetic sorting and manual sorting (by drag and drop)? And depending on this answer have to plan the flow. So, its hard to answer estimation right away. 

Regarding the challenge, yes, somewhat. But, we will need more investigation to confirm.

**Comment by markoaamunkajo** [comment]
@priyonto let's hide the menu from this view, it makes the experience confusing.

![Image](https://github.com/ruuvi/com.ruuvi.station.ios/assets/50437378/cd751174-95a5-404a-b9db-6583c298a00a)

**Comment by markoaamunkajo** [comment]
@priyonto 

If user minimises app when he is on sensor card or history view and order is changed, then sync happens when app is opened again, the sensor card or history view doesn't reflect the changed order (check arrows) until user visits dashboard.

https://drive.google.com/file/d/15Pbzc1k5pbZ2J4M-utyYM3cWs1fprJcM/view?usp=sharing

**Comment by markoaamunkajo** [comment]
@priyonto I see that it's possible for local sensors to be randomly placed to either first or the last in the list of sensors when adding them.

I reset the ordering to alphabetical order just before adding these sensors.



https://github.com/ruuvi/com.ruuvi.station.ios/assets/50437378/2676cc17-41a4-4ab4-b589-1d267133c537

**Comment by markoaamunkajo** [comment]
Discussed in DM this is a rare occurrence and may happen during sync. User is still able to move the sensor card to desired location so this is a minor inconvenience. Will pass this card for now since the feature is working otherwise perfectly and we will fix it if we receive feedback from users.
