### ISSUE TITLE
Reports Bluetooth is not enabled but updates continue - 2.10.0(240803 1605)

### ISSUE THREAD

**Issue by DG12** [ruuvi/com.ruuvi.station.ios#164]
See attached screen shots showing 2 different readings even though reports bluetooth is not enabled. Only action taken was to tap OK and app continued as normal
![BluetoothNotEnabled2](https://user-images.githubusercontent.com/2365961/103118492-2608ea80-463d-11eb-9efa-70038aadc388.PNG)
![BluetoothNotEnabled1](https://user-images.githubusercontent.com/2365961/103118493-26a18100-463d-11eb-9d22-ef966f6b5bc2.PNG)

This is the first time I have seen this since this version was released.

**Comment by ojousima** [comment]
As a side note, I've seen the data update continue after disabling BLE from phone. I think I saw this after update to Android 11, but I'm not sure if that's related.

**Comment by DG12** [comment]
Not seen in 0.6.(24) closing

**Comment by priyonto** [comment]
@DG12 Please provide more information with reproduce step.

**Comment by DG12** [comment]
This may be a different symptom of or related to #923

**Comment by markoaamunkajo** [comment]
I have not seen this in my app, but please look at card https://github.com/ruuvi/com.ruuvi.station.ios/issues/2116

It's very like related to some sort of silent Bluetooth crash (iOS?) over a longer period of time with a lot of sensors.
Will continue investigation on that card.
