### ISSUE TITLE
Automate versioning and change log generation through github actions

### ISSUE THREAD

**Issue by priyonto** [ruuvi/com.ruuvi.station.ios#1649]
Original task: #807

**Comment by rinat-enikeev** [comment]
@priyonto please review current flow [single commit message for firebase builds] and suggest improvements if needed

**Comment by priyonto** [comment]
Looks fine to me. One nice thing to have would be for release builds, if we can generate the changelogs from last tag to latest commit. Otherwise, I think this card can be closed.

**Comment by rinat-enikeev** [comment]
This would need waiting until TestFlight processes the build, waisting time on GH Actions agents. I would avoid it for now

cc: @priyonto
