### ISSUE TITLE
Saves Tx power from advertisements and exports them. Should Be RSSI - 0.6.3(1) - correction

### ISSUE THREAD

**Issue by DG12** [ruuvi/com.ruuvi.station.ios#165]
While recording data from advertisements Tx power seems to be saved and RSSI doesn't seem to be saved. Export includes Tx power but should include RSSI.

**Comment by rinat-enikeev** [comment]
that's the limitation of listening to heartbeats (they RSSI is not in the packet). closing

**Comment by DG12** [comment]
Can this please be revisited?
I believe RSSI is stored in the database.
