### ISSUE TITLE
Sensor screen shows 0seconds ; no graph shows 4+minutes ; 4.2.1(412) defect ; rare 

### ISSUE THREAD

**Issue by DG12** [ruuvi/com.ruuvi.station.ios#1668]
I looked at the sensor page it showed 0 seconds i.e. just updated.
Tapped graph shows no data updated 4 min 45 seconds.
![stationIOS0Seconds](https://github.com/ruuvi/com.ruuvi.station.ios/assets/2365961/1a9d9dc2-69e3-498a-9f75-b2fd532e9a15)

**Comment by priyonto** [comment]
@markoaamunkajo Please test it on the latest build. I could not reliably reproduce it on the latest build.

**Comment by DG12** [comment]
Since it's rare and I cannot duplicate it, closing for now.
Will reopen if it occurs again.
