### ISSUE TITLE
logout from cloud : only 2 sensors remain ; 4.3.1(412) defect ; minor

### ISSUE THREAD

**Issue by DG12** [ruuvi/com.ruuvi.station.ios#1669]
Although I would like to see all remain,

I thought all would be removed.

Sometimes 1 sometimes 2 remain.

![logout_2remain](https://github.com/ruuvi/com.ruuvi.station.ios/assets/2365961/814d6c78-df1e-4ee1-9fa4-d52b6fdea3c6)

**Comment by priyonto** [comment]
Only the locally address sensors remain. The sensors added from the cloud after login gets removed after logout.

**Comment by DG12** [comment]
10 added sensors "off line" sensors.
Sign in 19 sensor are displayed most with pictures, most say 1 min ago.
sign out 4D15 and 53F1 remain. 
more testing to follow.

**Comment by priyonto** [comment]
10 sensors are completely local sensors? Not claimed to the cloud?

**Comment by DG12** [comment]
10  "off line" sensors are also on the cloud.
+++++
Continuing from 1:44PM EDT.
iPhone is 4 meters away from gateway.
Custom photos applied to 4D15(RSSI -83) and 53F1(RSSI -88), they are both are actively updated by advertisements.
Sign in, both 4D15 and 53F1 show "new photos" and are being updated via bluetooth. 
ALL others updated by gateway !
Example "450A fromt door" 5m from iPhone, 8m from gateway **does not report RSSI**, and is only updated by gateway. Similarly "Attic fan main 24C2", "Ruuvi 20BC Garage door", "ruuvi 22AB", "Ruuvi 6E29", "Tesla charger Ruuvi 230E", "Traveling Ruuvi 9FE9".
Others are out of range.
+++++
Claim ownership of "Ruuvi 4D15" and "Ruuvi 53F1" and

"450A Fromt door" already owned by me and shared to DGerman(also me)
"Attic fan main Ruuvi 5A79" already owned not shared.

station IOS now stuck
continuing.

**Comment by markoaamunkajo** [comment]
@priyonto finally figured this one out.

Steps:
1. User is signed into Ruuvi Station, then logs out.
2. User adds a new local BT sensor.
3. Unexisting sensors are shown on dashboard briefly.

Let's fix showing those sensors and this issue should be then gone.

https://github.com/ruuvi/com.ruuvi.station.ios/assets/50437378/f3813923-74f2-41eb-a3c9-aedb852dc65c

**Comment by DG12** [comment]
fixed as of (417)
