### ISSUE TITLE
get login code:  CloudError 0 ; 2.4.1(412) ; defect : rare

### ISSUE THREAD

**Issue by DG12** [ruuvi/com.ruuvi.station.ios#1670]
Attempt to login produced 
Error
The Operation couldn't be
completed. (RuuciCloud.Ruuvi-
CloudError error(0)
![loginCode_CloudError 0](https://github.com/ruuvi/com.ruuvi.station.ios/assets/2365961/929efad2-cfa8-4140-bcde-b1c03a061d95)

**Comment by priyonto** [comment]
@DG12 What are the steps to reproduce it? 
@markoaamunkajo This one should probably go to cloud repo.

**Comment by DG12** [comment]
To duplicate simply attempt to login, get code and type first character of code.

As listed as rare it is difficult to duplicate.

Too bad error:0 isn't more helpful.

**Comment by markoaamunkajo** [comment]
Closing with https://github.com/ruuvi/com.ruuvi.station.ios/issues/1603

**Comment by DG12** [comment]
Occurred again  4/01/24 2.7.0(2403311418) attempting to "enter code" 10 minutes after requested. 
tried again and got expired.
