### ISSUE TITLE
CSV export time format should be ISO with timezone

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station.ios#1678]
Description:

CSV export time format should be ISO with timezone
Let's add this to the export filename.

![Image](https://github.com/ruuvi/com.ruuvi.station.webui/assets/50437378/ab336542-2596-4c78-8e09-fb40e7b28067)

Android card: https://github.com/ruuvi/com.ruuvi.station/issues/1124
Web card: https://github.com/ruuvi/com.ruuvi.station.webui/issues/331

**Comment by markoaamunkajo** [comment]
@priyonto we decided to go with the full ISO format sorry.


Filename example: Friiz_2023-10-30T10:43:14+07:00

**Comment by priyonto** [comment]
@markoaamunkajo Slight problem here, on iOS file name can't have colon (:) in the name. Its replaced by '/'. We can have name without colon. For example: `RuuviTag_2023-10-30T185727+0100`

**Comment by markoaamunkajo** [comment]
@priyonto let's remove the lines as separator too and format like this:

RuuviTag_20230210T113000+0300

**Comment by markoaamunkajo** [comment]
QA passed
