### ISSUE TITLE
Sensors known by gateway no longer updated by advertisements - 414 - defect

### ISSUE THREAD

**Issue by DG12** [ruuvi/com.ruuvi.station.ios#1686]
When logged in, only points in the database are shown and updated every 5 minutes.

Advertisements are no longer displayed.

Sensors which are at the periphery of the radio range of the gateway may be seen rarely, perhaps dependent on weather(?), don't get updated in the app by advertisements.
Similarly, sensors which are relocated from time to time, with use not logged in, have their data not displayed when logged in.

**Comment by laurijamsa** [comment]
Are you sure that the cloud mode is not enabled in the app settings?

**Comment by DG12** [comment]
OOPS settings;RuuviCloud; Cloud mode [ o]  I didn't know there was such a thing.
