### ISSUE TITLE
Alert description decimal symbol not localising

### ISSUE THREAD

**Issue by priyonto** [ruuvi/com.ruuvi.station.ios#1687]
Showing dot instead of comma when needed

**Comment by markoaamunkajo** [comment]
@priyonto Now min/max/avg not localizing with comma

![Image](https://github.com/ruuvi/com.ruuvi.station.ios/assets/50437378/b967c5cd-a94e-4f6a-a331-5d09a7ddb924)

**Comment by markoaamunkajo** [comment]
QA passed
