### ISSUE TITLE
MM/DD and DD/MM localization feature is missing on the graphs (?)

### ISSUE THREAD

**Issue by laurijamsa** [ruuvi/com.ruuvi.station.ios#169]
User feedback: 

"The per-device time-value graphs do not appear to honor iOS system level localization preferences. US localization convention is that dates are written MM/DD, however I'm currently seeing DD/MM euro style dates."

**Comment by DG12** [comment]
See also issue #138

**Comment by viikufa** [comment]
fixed in https://github.com/ruuvi/com.ruuvi.station.ios/pull/189/files

**Comment by viikufa** [comment]
close as duplicate of https://github.com/ruuvi/com.ruuvi.station.ios/issues/138
