### ISSUE TITLE
Switching between gateway and bt icon makes box contents jump on dashboard

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station.ios#1699]
Description:

Contents moving up when gateway icon is present.

Expected: should keep items in same alignment.

https://github.com/ruuvi/com.ruuvi.station.ios/assets/50437378/0f6cdcca-eef4-4f53-99a2-1cacaeb8a546

**Comment by priyonto** [comment]
@markoaamunkajo Not sure what will be optimal solution here. I remember mentioning it when we were having two different sized icons for BT and Gateway. We should have icons with same dimension here.

**Comment by laurijamsa** [comment]
Yes, please make all the icons equal size.

**Comment by sini-maaria** [comment]
Icons (Bluetooth and Gateway) should have the same height. Width of the area should be flexible and text content should be aligned right next to the icon. (See example on Android.)

**Comment by priyonto** [comment]
@sini-maaria Icon size in Android looks like this for me, where gateway icon is twice the size of BT icon in terms of width. Do we want the same on iOS too? I remember having a discussion a while back where the icon size were not same and we wanted them same. 

 
![Screenshot_20231107-202204_Ruuvi Station](https://github.com/ruuvi/com.ruuvi.station.ios/assets/24395776/ac013431-226f-4053-8f7e-d72d151c4058)

**Comment by markoaamunkajo** [comment]
QA passed
