### ISSUE TITLE
0.6.1(20) Need mechanism to clear log - deficiency 

### ISSUE THREAD

**Issue by DG12** [ruuvi/com.ruuvi.station.ios#170]
There needs to be a command from RuuviStation to clear the logged data in the RuuviTag
see https://github.com/ruuvi/ruuvi.firmware.c/issues/190

**Comment by ojousima** [comment]
Let's keep this discussion at firmware side, and if it gets implemented we can reopen this issue.

**Comment by DG12** [comment]
in fact:
No mechanism to clear log should be provided - informational see firmware.c/issues/190
