### ISSUE TITLE
Widget sensor list not always updating

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station.ios#1705]
Description:

User reported that adding and editing widget doesn't always load the sensor list.
I reproduced this issue on iPhone 14 Pro with same steps when trying to select list too fast. I'm assuming it's not completely loaded at this point.

https://github.com/ruuvi/com.ruuvi.station.ios/assets/50437378/549db6d0-973a-4881-b924-eb1816f17b6d

**Comment by priyonto** [comment]
@markoaamunkajo Closing this as per discussion. Let's try to improve this while working on comple widgets.
