### ISSUE TITLE
Adopt  new widget API for Xcode 15

### ISSUE THREAD

**Issue by priyonto** [ruuvi/com.ruuvi.station.ios#1714]

**Comment by markoaamunkajo** [comment]
@priyonto I see placeholder texts shown in widget here

![Image](https://github.com/ruuvi/com.ruuvi.station.ios/assets/50437378/04bca8c3-a0a8-4bcd-b012-655a0b582d30)

![Image](https://github.com/ruuvi/com.ruuvi.station.ios/assets/50437378/93ece906-beb0-4055-b92e-9f6d99b10e47)

**Comment by markoaamunkajo** [comment]
@priyonto now when I tried to open the sensor list I get this error

![Image](https://github.com/ruuvi/com.ruuvi.station.ios/assets/50437378/78e7c140-e9eb-476d-bf3b-cc34c7811db2)

**Comment by markoaamunkajo** [comment]
QA passed
