### ISSUE TITLE
App updates too rapidly =

### ISSUE THREAD

**Issue by DG12** [ruuvi/com.ruuvi.station.ios#1722]
I believe this is a long time issue causing various problems including rapid batter drain.

When monitoring a sensor at -73 dBM, via BLE advertisments (not logged in) the updated  seconds ago flashes between 0 and 1 at a 327ms rate. Well maybe not but it surely updates more often than once per second. There are only 3 other sensors currently configured.

Does the app refresh with EVERY advertisement? 
Is there any delay/sleep after update before next update? 
Should there be ?

**Comment by DG12** [comment]
That is, a period during which, blue tooth advertisements are ignored. 
Many environments have very very many devices some either not Ruuvi or ruuvi and not configured to a particular station device.

**Comment by markoaamunkajo** [comment]
I think that happens here is that sensor is receiving both heartbeats and advertisements in connected mode. 
Information regarding heartbeats here: https://docs.ruuvi.com/communication/bluetooth-connection/nordic-uart-service-nus/heartbeat-transmissions

**Comment by markoaamunkajo** [comment]
Closing as answered

**Comment by DG12** [comment]
No sensors are connected(paired).



Please reopen.

**Comment by markoaamunkajo** [comment]
Discussed in DM with @priyonto

**Comment by priyonto** [comment]
@DG12 Could you share your latest observation on this issue?

**Comment by markoaamunkajo** [comment]
Hi @DG12 need your input on this case. We are unsure what exactly happens when app is updated "too rapidly".
With standard firmware the RuuviTag broadcasts advertisements in pretty frequent interval, 1.5 seconds if I remember correctly, and your mobile device is able to pick up a number of these, not all of them. If you have RuuviTag paired to Ruuvi Station with Bluetooth, then app may receive an advertisement every now and then. If this "glitch" is observable then we'd be happy to discuss it further if it should be addressed, but to me this seems like possibly not fixable.

**Comment by DG12** [comment]
I should have attached a video.
I have logged out. AD03, 20BC, 23DE, 3B86 and 53F1 remain !
AD03 is in refrigerator (aka Faraday cage )and therefore reception is normally poor but controllable.
Interval based on nRFconnect/scanner
3B86,1.3sec;   53F1,1
Not configured in ruuvi station but within range:
24C2,1.3sec; BB12,1.2; 4D15,1.3; 450A,1.3; 230E,.92
Additional devices at 
.3,.2,.2,.2,.1,.1,.2,.03,.3,2.,.2,2.,2.,.3,.08,2.,2.,2.,2.,.1,.5,.2,.0.2,

**Comment by laurijamsa** [comment]
Did they remain because they weren't claimed by the account? If yes, it is like it is designed to work. The signing out was probably due to the cloud issue we experienced earlier today.

**Comment by laurijamsa** [comment]
Reopened because did not understand why you closed it.

**Comment by markoaamunkajo** [comment]
Logged out sensor issue has not been seen recently.
Does this issue still occur to you occasionally @DG12 ?

**Comment by markoaamunkajo** [comment]
Closing as not seen recently.
