### ISSUE TITLE
All data is not shown in sensor settings page

### ISSUE THREAD

**Issue by DG12** [ruuvi/com.ruuvi.station.ios#173]
It seems that the more info section shows  only data  received since it is exposed.
Data for RuuviTags with low update frequency or only are within range infrequently show  --
Last data received should be displayed.

**Comment by DG12** [comment]
![moreInfo--](https://user-images.githubusercontent.com/2365961/105930604-e3f60e80-6017-11eb-8cf4-7607a581ec9f.jpg)

**Comment by laurijamsa** [comment]
Let's try to replicate. If cannot, close.

**Comment by markoaamunkajo** [comment]
I cannot replicate. Something seems off with this sensor @DG12 I see only one calibration setting for humidity, app would show calibration for all available sensors onboard.

**Comment by DG12** [comment]
I cannot duplicate this issue at this time. Should it re-occur, I will re-open or and new issue.
