### ISSUE TITLE
Add locatisations automatically from localisation repo to the modules/frameworks

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station.ios#1736]
Description:

How do you bring new localisation strings to builds?
Is it automated?

**Comment by priyonto** [comment]
Yes, CI does that on build steps, directly bring the latest version from repo at the time of building. However, it used to clone dev branch for obvious reasons until now. We need to adjust the workflow to pull master going forward.

**Comment by markoaamunkajo** [comment]
Let's adjust the workflow and automate it.

**Comment by priyonto** [comment]
@markoaamunkajo We make the builds already from the repo in build steps for actions. But, we need to get the modules automate the localisation from repo.
