### ISSUE TITLE
Add option to upgrade firmware for df3 sensors when added via NFC

### ISSUE THREAD

**Issue by rinat-enikeev** [ruuvi/com.ruuvi.station.ios#1748]
Problem: if tag scanned with NFC is in df3 mode, we simply don't allow adding it to the app. 

Solution: instead, give option to upgrade firmware on this tag. 

Steps: prepare df3 mode tag. Scan with NFC from `Discover` screen. Select "Firmware Update" option. 

Expected: firmware update is finished. If you scan with NFC again - you see latest firmware installed. 

Please also check UX and give recommendation on what needs to be improved.  

<img src="https://github.com/ruuvi/com.ruuvi.station.ios/assets/722716/fbc09a7c-0b3e-487f-ba35-9e02ac98ac83" width=320/>

**Comment by rinat-enikeev** [comment]
firebase app distribution 2.5.2 (2312062210)

**Comment by markoaamunkajo** [comment]
QA passed
