### ISSUE TITLE
Unification: use radio buttons or similar in the settings

### ISSUE THREAD

**Issue by DG12** [ruuvi/com.ruuvi.station.ios#175]
When setting the unit, the setting currently in effect should be highlighted

**Comment by viikufa** [comment]
Nice case. We can use checkmark at the right side for this.

**Comment by rinat-enikeev** [comment]
unify UI with Android (radio buttons or rows). @andreevdenis let's discuss

**Comment by laurijamsa** [comment]
Assigning to Marko to check and provide a better spec. If not valid anymore in the latest build, close.

**Comment by laurijamsa** [comment]
iOS currently:
![image](https://user-images.githubusercontent.com/1311912/158511213-848f8f88-00dd-4a6f-a911-ecfc7015eb9a.png)
![image](https://user-images.githubusercontent.com/1311912/158511230-d062ca60-20fd-41a2-8c27-966d6ba1b91a.png)
Android:
![image](https://user-images.githubusercontent.com/1311912/158511380-2722f328-75f8-4315-8408-14743e11e1dc.png)

Let's unify this a bit more with Android. Radio buttons would be the obvious option but quick googling told me that radio buttons are not available natively on iOS so probably a table like this should be used:

https://ux.stackexchange.com/questions/78872/what-is-the-ios-alternative-to-a-radio-button
![image](https://user-images.githubusercontent.com/1311912/158511790-d98d4248-9bf1-42c0-ba3d-7632212c6290.png)

But if radio buttons are available, let's use them.

**Comment by priyonto** [comment]
You are right. Radio buttons are not natively available on iOS. However it can be done I believe with some tweaks and customization. Checkbox are available default but on the right side.

**Comment by andreevdenis** [comment]
In my opinion it's better to respect platform specifics.

**Comment by markoaamunkajo** [comment]
@laurijamsa looks like platform specific to use checkmarks, maybe this can be left alone?

**Comment by DG12** [comment]
Checkmarks look good.

If you wanted to go "unified"( across IOS, Android, Web) how about simply **bold**.

I think it's fine the way it is.
