### ISSUE TITLE
Grey out RSSI alert when user is not signed in

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station.ios#1751]
Description:

RSSI alert should be greyed out when user is not signed in to Ruuvi Station.
It's considered reliable only when used with Ruuvi Gateway.

**Comment by markoaamunkajo** [comment]
@priyonto I think this solution doesn't work as is, since any Bluetooth sensor will get ownership from cloud and controls become active. I don't know if "signed in user with Gateway" can be detected, I think when Cloud mode disabled it would jump between sources too. Ideas?


https://github.com/ruuvi/com.ruuvi.station.ios/assets/50437378/66d4aa0c-203e-4b01-84c3-7e3b3bea15a6

**Comment by priyonto** [comment]
@markoaamunkajo Ball is on your court again chief.

**Comment by DG12** [comment]
Is it clear to the user that RSSI is only based on reception at a gateway?
How are multiple gateways handled? 

All other data is from the sensor and may be seen via the iPhone. Does the user expect that if the sensor is within range of iPhone (and updating data via BLE) an alert will occur if the sensor (and the iPhone) move out of range of the gateway.

**Comment by markoaamunkajo** [comment]
@priyonto there is an edge case when user has enabled RSSI alert and then unclaims sensor it will leave alert enabled and it will trigger. Should be set to disabled in this case.

https://github.com/ruuvi/com.ruuvi.station.ios/assets/50437378/8f824b88-a3e2-4b43-9306-93f2e7e6f61a

**Comment by markoaamunkajo** [comment]
QA passed
