### ISSUE TITLE
min/max/avg needs update after timeframe change - 2.5.2 2312062210 -defect

### ISSUE THREAD

**Issue by DG12** [ruuvi/com.ruuvi.station.ios#1758]
Check a sensor at 12hours  see very nice graph. nice max/min/avg
change to 1 day and min/max/avg not updated.
![image](https://github.com/ruuvi/com.ruuvi.station.ios/assets/2365961/b7126d28-f25d-4ae0-bb94-7b9696a728d8)

**Comment by markoaamunkajo** [comment]
I cannot reproduce this issue, if this can be reproduced, please reopen again.

**Comment by DG12** [comment]
Start with small time range. 
Then change to longer period.

Please reopen.
![image](https://github.com/ruuvi/com.ruuvi.station.ios/assets/2365961/e0de031b-f1e1-4a35-9930-b4ea7a02ec5f)

**Comment by DG12** [comment]
@markoaamunkajo Please reopen

**Comment by laurijamsa** [comment]
Reopened. We will take a look soon.

**Comment by DG12** [comment]
Thanks,I didn't think it would be as hard as that. 
But then again it's never easy!

**Comment by markoaamunkajo** [comment]
Reproduced changing between 3, 12 hours and 1 day, and indeed it goes off when changing to bigger timeframe.

![Image](https://github.com/ruuvi/com.ruuvi.station.ios/assets/50437378/cf405d10-5429-42ca-861c-bd9b5a1f0197)
![Image](https://github.com/ruuvi/com.ruuvi.station.ios/assets/50437378/315a68a7-d223-42bc-96f8-4c31f8406264)
![Image](https://github.com/ruuvi/com.ruuvi.station.ios/assets/50437378/be6dead3-0ebd-417f-8a80-42335b32e580)

**Comment by markoaamunkajo** [comment]
QA passed
