### ISSUE TITLE
sync/export  incorrectly claiming data going back 2 1/2 months - .7(21) - defect

### ISSUE THREAD

**Issue by DG12** [ruuvi/com.ruuvi.station.ios#176]
sync/export has 159 points going back 2 1/2 months
I don't think so.

file attached as txt since GitHub doesn't like CSV 
[Ruuvi 06DC-210118-0817.csv.txt](https://github.com/ruuvi/com.ruuvi.station.ios/files/5830398/Ruuvi.06DC-210118-0817.csv.txt)

**Comment by rinat-enikeev** [comment]
Hi @DG12, is this still relevant? Which firmware (longmem)?

**Comment by DG12** [comment]
I will check into this and report back.

**Comment by rinat-enikeev** [comment]
Please feel free to reopen if still relevant.
