### ISSUE TITLE
Syncing takes   to long to time out - .7(21) & 0.6(24)- defect 

### ISSUE THREAD

**Issue by DG12** [ruuvi/com.ruuvi.station.ios#177]
Although the time message says "after 60" seconds, it is much longer.

**Comment by rinat-enikeev** [comment]
please give it a chance to fail :) is this still relevant?

**Comment by DG12** [comment]
Yes. I had it happen yesterday. I will duplicate and provide additional info.

**Comment by markoaamunkajo** [comment]
Nice, thanks!

**Comment by rinat-enikeev** [comment]
Please feel free to reopen if still relevant.
