### ISSUE TITLE
2.5.2 Changing app language doesn't actually change it

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station.ios#1779]
Description:

User made clean install of 2.5.2
Signed in to the app
Then went to app settings and changed language from English to Finnish

Language didn't change in app

https://github.com/ruuvi/com.ruuvi.station.ios/assets/50437378/b5c37c78-6143-42f1-b2ae-9cad38a397b2

**Comment by rinat-enikeev** [comment]
2.5.2 (2312152251)

**Comment by markoaamunkajo** [comment]
QA passed
