### ISSUE TITLE
help/about screen "RUUVI STATION" font is inconsistent with the rest of the app - .7(21) & 0.6.3(1) - nit

### ISSUE THREAD

**Issue by DG12** [ruuvi/com.ruuvi.station.ios#178]
There are actually 2 titles on the help/about screen , a smaller oe at the top edge in the normal(?) ruuvi font and icon but the addition one in the center with tall lettering is odd(?)

**Comment by rinat-enikeev** [comment]
@laurijamsa what do you think about the fonts on About screen? Do we want to tune them?

**Comment by laurijamsa** [comment]
I have no access to iPhone. Assigning to Marko. Marko, if you think no need for adjustments, close the issue please.

**Comment by markoaamunkajo** [comment]
@laurijamsa No need for adjustments. I believe we possibly fixed something related to this earlier.

![IMG_5647](https://user-images.githubusercontent.com/50437378/119849675-069d2300-bf37-11eb-8271-2d2c68fe9b77.PNG)
![IMG_5648](https://user-images.githubusercontent.com/50437378/119849645-000eab80-bf37-11eb-8232-8ca3621e7853.PNG)
