### ISSUE TITLE
Investigate why iOS doesn't show the data for cloud-based df3 sensor

### ISSUE THREAD

**Issue by rinat-enikeev** [ruuvi/com.ruuvi.station.ios#1780]
Steps: 
- claim df3 tag from Android
- login in and sync from iOS 

Expected: 
Data is shown
Actual: 
Only background

**Comment by rinat-enikeev** [comment]
reason why iOS doesn't sync df3 tag claimed on Android is: 

network parser expected >30 count for data, which has only 21. 

`02010611FF9904033C1658C4990038FFF003F80AFF`

fixing in Ruuvi BTKit.

**Comment by rinat-enikeev** [comment]
2.5.2 (2312181908)

**Comment by markoaamunkajo** [comment]
QA passed
