### ISSUE TITLE
df3 sensors: Add a new sensor update firmware popup

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station.ios#1781]
Description:

We need to add a popup to Add a new sensor page when user tries to add a df3 format sensor to the app.

Popup will only show an firmware update option and no ability to add the sensor to the app.

Popup text ENGLISH:

Title: Update firmware
Text: This firmware version is no longer supported. Update your Ruuvi sensor firmware now to be able to add this sensor to Ruuvi Station.

Button: Update firmware

Popup text FINNISH:

Title: Päivitä laiteohjelmisto
Text: Tämä laiteohjelmistoversio ei ole enää tuettu. Päivitä Ruuvi-anturin laiteohjelmisto ensin, jotta voit lisätä anturin Ruuvi Station -sovellukseen.

Button: Päivitä laiteohjelmisto

Forward user to firmware update without adding sensor card.

**Comment by rinat-enikeev** [comment]
2.5.2 (2312161712)

**Comment by markoaamunkajo** [comment]
QA passed
