### ISSUE TITLE
Sync request: Confirm with user if radio signal is too weak.

### ISSUE THREAD

**Issue by DG12** [ruuvi/com.ruuvi.station.ios#1783]
There is no hope that synchronization will be successful if RSSI is very low (like < 91 ).
Tell the user it isn't going to work for this sensor at this time because then signal is too weak. 

Maybe ask them to confirm that they really want to try)

**Comment by markoaamunkajo** [comment]
Fix has been added coming out in next beta.

**Comment by DG12** [comment]
What is the threshold? I tried to sync with RSSI (none shown), -98,-94,-94,-97.
I have not seen anything like "signal too weak" . 
Sync connects and starts but does not complete. After (**too long** ) a while.

PS,updated 3s ,5s, 2s, 0s, 2s, 1, 0, 0,...

version 2.6.0(2401312032)

**Comment by laurijamsa** [comment]
I reopened this. What's the rssi logic behind the new "fix"? Different (especially Android) phone models report totally different rssi numbers and I'm not quite sure is it possible to decide according to rssi numbers even on Apple devices that is the signal strength really too low or not.

**Comment by markoaamunkajo** [comment]
This card was lost in the done queue for a while. For what I see there is timeout and popup telling user that sync was unsuccessful

![Image](https://github.com/user-attachments/assets/ef43e9c0-204a-44c6-ab3c-d467e0e30385)

**Comment by DG12** [comment]
Perhaps an app setting : "minimum RSSI for sync", defaulted to something like -95. If user wants to ignore warning they can try anyway or maybe move closer. 

Is there any experience of values for phones other than my iPhons Xs that are too low to sync?

**Comment by markoaamunkajo** [comment]
The issue with showing a notification in this case is that the RSSI can fluctuate quite a lot for any reason, lot of Bluetooth traffic, channel selection, obstacles, interference...so it would not be always reliable.

**Comment by markoaamunkajo** [comment]
Closing this as it's not considered any changes are needed. We will go through logic later.
