### ISSUE TITLE
Always show two decimals in e.g temperature instead of dropping trailing zeros  

### ISSUE THREAD

**Issue by wellu** [ruuvi/com.ruuvi.station.ios#179]
Temperature, and other such units, should be shown in two decimal accuracy. So given e.g the temp being -2.6 Celcius it should be shown as -2,60 and not -2,6 like in the screenshot.

Easy to fix, should I make a PR?

![image](https://user-images.githubusercontent.com/2076593/105041823-26de4200-5a6c-11eb-9f87-b3b4e86c4f91.png)

**Comment by wellu** [comment]
Same problem with other units as seen here.

![image](https://user-images.githubusercontent.com/2076593/105042442-ef23ca00-5a6c-11eb-97d9-bf5f1a8ff0fb.png)
![image](https://user-images.githubusercontent.com/2076593/105042511-0367c700-5a6d-11eb-8355-643ae3065cdd.png)

**Comment by DG12** [comment]
See Also Issue #134

**Comment by viikufa** [comment]
fixed in https://github.com/ruuvi/com.ruuvi.station.ios/pull/189

**Comment by DG12** [comment]
Fixed in 0.6.2(4)

**Comment by markoaamunkajo** [comment]
QA passed
