### ISSUE TITLE
NotificationService localisation

### ISSUE THREAD

**Issue by rinat-enikeev** [ruuvi/com.ruuvi.station.ios#1805]
Test localisation for push notifications. 

Known issues: 

- [x] movement is not localised 
- [ ] offline is not localised 

Please also provide a specification if it is possible to get "offline" alerts and how to localise them if true.

**Comment by rinat-enikeev** [comment]
2.5.2 (2312192028)

**Comment by markoaamunkajo** [comment]
I am not receiving temperature push notifications for my sensor now with pro account.

**Comment by rinat-enikeev** [comment]
This is because for `alpha` builds we are using `sandbox` PN environment. You can check manually by


> if you wanna efficiently QA 1805, you can shake your device, try to get push notifications token by pressing on gear icon at the bottom, open on desktop PN [console](https://icloud.developer.apple.com/dashboard/home/teams/4MUYJ4YYH4), configure [or copy my] PN and send it to your device by specifying your PN token in the field. 

> NB: on console please select lowercased com.ruuvi.station project at the left top

<img src="https://github.com/ruuvi/com.ruuvi.station.ios/assets/722716/a73d327c-300c-4aa5-8c44-a06164361dbe" width=320/>

**Comment by rinat-enikeev** [comment]
OR wait until I make a production ready TestFlight build

**Comment by rinat-enikeev** [comment]
waiting for https://github.com/ruuvi/station.localization/pull/178 to cook a TestFlight build @markoaamunkajo

**Comment by rinat-enikeev** [comment]
TestFlight 2.6.0 [2312202023] should deliver PNs from production environment @markoaamunkajo

**Comment by markoaamunkajo** [comment]
@rinat-enikeev Please format the notification to show complete text instead of "..."

![Image](https://github.com/ruuvi/com.ruuvi.station.ios/assets/50437378/0fbf7ac3-3b39-498b-b406-4cfcad416cee)

**Comment by markoaamunkajo** [comment]
Closing this as we will not make custom solution at this point.
