### ISSUE TITLE
Show alert triggered range with alert colour

### ISSUE THREAD

**Issue by DG12** [ruuvi/com.ruuvi.station.ios#1818]
Description:

Show alert triggered range with alert colour in alert settings.

When setting an alert, specifying a range when the value is OUTSIDE of desired values the graphic is confusing.

Currently 
![image](https://github.com/ruuvi/com.ruuvi.station.ios/assets/2365961/97667f7f-2ed4-4613-bfdf-4731715161cc)

This does show that the acceptable (non-alert) range is in the green area and states that the alert triggers when less than 37 or greater than 101.
This minor modification, highlighting the alert ranges, would be clearer

Design:

![Image](https://github.com/ruuvi/com.ruuvi.station.ios/assets/50437378/145e9faa-fcce-4a05-8183-698d329aa974)

Thank you for your consideration.
Although this issue is submitted against station IOS it applies to all station applications.

**Comment by markoaamunkajo** [comment]
Thanks for the feedback @DG12 we have decided to implement this to all platforms.

**Comment by markoaamunkajo** [comment]
Updated design to the description

**Comment by markoaamunkajo** [comment]
Sorry updated design once more @rinat-enikeev

**Comment by markoaamunkajo** [comment]
QA passed
