### ISSUE TITLE
0.7(21) Syncing network tags shows result of stored measurements -1

### ISSUE THREAD

**Issue by viikufa** [ruuvi/com.ruuvi.station.ios#182]
Description:

User checks his about page has 50 stored measurementsUser signs in to network, he has couple of new cards now in Ruuvi Station. He then syncs data from a tag on charts page -> popup telling 50 measurements was added is shownHe then goes to about page and sees 99 stored measurements

Where did the 1 measurement go?

**Comment by rinat-enikeev** [comment]
wasn't able to reproduce

**Comment by markoaamunkajo** [comment]
Cannot reproduce in 0.7(21)
