### ISSUE TITLE
chart page : current value has unnecessary parenthesis  -cosmetic - nit

### ISSUE THREAD

**Issue by DG12** [ruuvi/com.ruuvi.station.ios#1824]
_is_
Humidity **(**82%**)** 
_Should be_
Humidity 82%

Is it necessary to include "**Humidity**" as it is implied with the **%**?
**Temperature** implied with degrees C, **Pressure** ?

Additionally consider the 2 lines  min, max, average and current value are right aligned frequently obscuring the most recent graph line.
![image](https://github.com/ruuvi/com.ruuvi.station.ios/assets/2365961/f43fade1-1f24-4408-9075-528972cd74d0)

A better view would be a single line, left justified. Graph line possibly obscured on left side is from an undefined time in the past.

![image](https://github.com/ruuvi/com.ruuvi.station.ios/assets/2365961/364cd3d5-648a-42bf-937c-01af52dd0664)

**Comment by markoaamunkajo** [comment]
Closing, because we are planning to redesign this page.
