### ISSUE TITLE
Avoid showing "Sign In" prompt if user has zero sensors and is logged in

### ISSUE THREAD

**Issue by rinat-enikeev** [ruuvi/com.ruuvi.station.ios#1828]
Steps: 
1. User has zero sensors
2. User logs in

Expected: 
<img src="https://github.com/ruuvi/com.ruuvi.station.ios/assets/722716/12f4e118-ab01-4eaa-9ccd-c3946e7f3a68" width=320/>+

Actual: 
- prompt to sign in

**Comment by rinat-enikeev** [comment]
2.6.0 (2401011332)

**Comment by rinat-enikeev** [comment]
the "sign in" button is shown until user logs in at least once. Not sure if it is aligned with android

**Comment by rinat-enikeev** [comment]
Thanks to @priyonto the spec was found here https://github.com/ruuvi/com.ruuvi.station.ios/issues/1634. 

2.6.0 (2401011510)

**Comment by markoaamunkajo** [comment]
QA passed
