### ISSUE TITLE
App crash on signout with mixed sensors

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station.ios#1836]
Description:

2.6.0 (2401021648)

User adds a bunch of sensors and pairs them with BT.
Then signs in to his account.
After signing in he decides to sign out.
App crashes.

iPhone 14 Pro

https://github.com/ruuvi/com.ruuvi.station.ios/assets/50437378/7d826aa1-eeba-4a16-ad8e-6a94efbdf1dc

iPhone SE

https://github.com/ruuvi/com.ruuvi.station.ios/assets/50437378/ee845be2-d026-4295-b88a-429c6dad5cc2

**Comment by rinat-enikeev** [comment]
2.6.0 (2401061029)

**Comment by markoaamunkajo** [comment]
QA passed
