### ISSUE TITLE
Mac: 0.7(20) Sync is broken

### ISSUE THREAD

**Issue by viikufa** [ruuvi/com.ruuvi.station.ios#184]
Description:

0.7(20) Mac, Macbook Pro Retina 2015, MacOS Catalina 10.15.7

User added tags with fw 3.29.1 and 3.28.13 and chooses Sync in graphs

Actual:Sync tries to execute for 60 seconds and gives error "Failed to serve in 60 seconds"

Expected:Sync and collect tag data to card

**Comment by DG12** [comment]
Genuine iPhone also. with "Ruuvi FW v3.39.3+default" station IOS .7(21)

See also Issue #177

**Comment by DG12** [comment]
broken in .0.6.(24)
