### ISSUE TITLE
Update Firmware from nRF use case

### ISSUE THREAD

**Issue by rinat-enikeev** [ruuvi/com.ruuvi.station.ios#1840]
Steps: 
1. Add df5 2.5.9 firmware sensor to the Ruuvi Station app
2. Ensure you've got some advertisements 
3. Close Ruuvi Station
4. Upgrade firmware with nRF connect
5. Open Ruuvi Station app

Actual: 
App doesn't show advertisements 

Expected: 
App is listening to the sensor

Reason behind: 
The firmware update process changes UUID of the RuuviTag visible to the app. Fix ensures that if UUID for given MAC was changed, it is being respected on Ruuvi Station app

**Comment by rinat-enikeev** [comment]
2.6.0 (2401061145)

**Comment by markoaamunkajo** [comment]
@rinat-enikeev looks like after updating the sensor card still doesn't show charts icon. History view opens normally from dashboard.

![Image](https://github.com/ruuvi/com.ruuvi.station.ios/assets/50437378/c977a905-84f7-4c13-8424-6a246729ef19)

**Comment by rinat-enikeev** [comment]
2.6.0 (2401102048)

**Comment by markoaamunkajo** [comment]
QA passed
