### ISSUE TITLE
Don't support transferring Ruuvi Station data on device change

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station.ios#1848]
Description:

User gets a new iOS device and makes data transfer.
We decided that we will not support transferring app data to avoid issues.

No unclaimed sensors
No claimed sensors
No sign in tokens

**Comment by rinat-enikeev** [comment]
firebase  2.6.0 (2401092059)

**Comment by markoaamunkajo** [comment]
No straightforward way to test this, moving to done and will add mention to documentation.
