### ISSUE TITLE
Show last seen date on widget

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station.ios#1850]
Description:

User has sensor in widget that has been seen long time ago.
iOS widget currently shows time.

Expected:
Show date if not today, same as in Android.

![Image](https://github.com/ruuvi/com.ruuvi.station.ios/assets/50437378/e0ae4da9-d152-48fa-9475-94d739cc352c)

**Comment by rinat-enikeev** [comment]
firebase  2.6.0 (2401092059)

**Comment by markoaamunkajo** [comment]
QA passed
