### ISSUE TITLE
Post for BTKit publisher and updates [draft]

### ISSUE THREAD

**Issue by rinat-enikeev** [ruuvi/com.ruuvi.station.ios#1862]

**Comment by rinat-enikeev** [comment]
https://ruuvi.github.io/BTKit/tutorials/meetbtkit/

**Comment by rinat-enikeev** [comment]
also updated "About" section in https://github.com/ruuvi/BTKit. Previous link was leading to "article was deleted"

**Comment by markoaamunkajo** [comment]
I liked it, very easy to understand content.

**Comment by markoaamunkajo** [comment]
Update article to Ruuvi Blog, dm'd Rinat

**Comment by markoaamunkajo** [comment]
Closing this as inactive
