### ISSUE TITLE
Firebase user properties

### ISSUE THREAD

**Issue by viikufa** [ruuvi/com.ruuvi.station.ios#187]

**Comment by DG12** [comment]
Can you please expand on what this is since attempting to view changes in git is meaningless.

**Comment by markoaamunkajo** [comment]
Anything to QA @viikufa ?

**Comment by viikufa** [comment]
@DG12 It's metrics for anonymous statistics where we can see which an app features users use.

**Comment by markoaamunkajo** [comment]
Ok moving to done
