### ISSUE TITLE
0.6.2(4) Pressure has percentage shown after value

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station.ios#190]
Description:

Percentage symbol is shown attached to value on sensor card view.
Please remove percentage indicator.

![pressure_english](https://user-images.githubusercontent.com/50437378/105960251-87463280-60af-11eb-8453-8dbc9153fe9a.jpg)

**Comment by DG12** [comment]
Actually percent symbol is extraneous and should be removed, please revise issue title.

**Comment by markoaamunkajo** [comment]
Lol you are right, edited

**Comment by markoaamunkajo** [comment]
QA passed
