### ISSUE TITLE
Unit for relative humidity not shown in app settings 2.6.0

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station.ios#1909]
Description:

% seems to be missing in units from App Settings

![Image](https://github.com/ruuvi/com.ruuvi.station.ios/assets/50437378/db78721d-213d-443d-9f64-1681f26e8629)

**Comment by rinat-enikeev** [comment]
should be fixed with https://github.com/ruuvi/station.localization/pull/196

**Comment by markoaamunkajo** [comment]
QA passed
