### ISSUE TITLE
0.6.2(4) Sensor card: Kelvin formatting is broken on languages

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station.ios#191]
Description:

User selected Kelvin as temperature unit, when he chooses any other language than English Kelvin unit is shown with "Kk"
![IMG_4825](https://user-images.githubusercontent.com/50437378/105960520-eb68f680-60af-11eb-8f8c-a31415b7c7a4.PNG)

**Comment by viikufa** [comment]
need to add tests for different units with each locale

**Comment by markoaamunkajo** [comment]
And actually this is same for Fahrenheit in RU

**Comment by markoaamunkajo** [comment]
QA passed
