### ISSUE TITLE
Switch is showing wrong colour when disabled 2.6.0

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station.ios#1910]
Description:

When entering a page that has disabled switch, at first it shows disabled with enabled colour.
In video you will see it starts to follow correct colour only after switching.

https://github.com/ruuvi/com.ruuvi.station.ios/assets/50437378/d6910661-65dc-4b74-a1f5-eff7b516b9c5

**Comment by rinat-enikeev** [comment]
fixed in https://github.com/ruuvi/com.ruuvi.station.ios/pull/1915

**Comment by markoaamunkajo** [comment]
QA passed
