### ISSUE TITLE
User logged out signed in to another account and added sensor with NFC it shows menu doesn't add sensor 2.6.0

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station.ios#1912]
Description:

User signed out from Ruuvi Station then signed in with another account.
When adding new sensor with NFC it now shows  popup for 3.31 fw sensor, doesn't add sensor to app.
But also the popup doesn't have add a sensor button.

Expected: should add sensor card right away no popup

![Image](https://github.com/ruuvi/com.ruuvi.station.ios/assets/50437378/1ecbe60e-37c7-4194-b3b8-949b19fd310a)

**Comment by rinat-enikeev** [comment]
TODO: @rinat-enikeev compare the logic with Android and do the same.

**Comment by rinat-enikeev** [comment]
The popup didn't have an "Add a Sensor" button. For sure it wasn't the 2.7.9 firmware with df3.

**Comment by rinat-enikeev** [comment]
This [screenshot] means sensor was already added. I tried with the provided steps and wasn't able to reproduce.

**Comment by rinat-enikeev** [comment]
I believe it is just in the list, not deleted after sign out.

**Comment by markoaamunkajo** [comment]
@rinat-enikeev 2.6.0 (2402061941)

Did same steps as described, this sensor is not in the currently signed in users list of sensors, but it was in the list of previously signed in user.

In this case user should get sensor card created right away after NFC scan, no popup.

![Image](https://github.com/ruuvi/com.ruuvi.station.ios/assets/50437378/a0ece4ca-3d70-49dc-bd1a-bece08ddd50c)

**Comment by markoaamunkajo** [comment]
Now has add a new sensor button.
