### ISSUE TITLE
User signed out and signed in to another account sensor delete menu shows wrong text

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station.ios#1913]
Description:

User signed out from Ruuvi Station and signed in to another account, then added sensor to Ruuvi Station.
In Delete Sensor page he now sees text that this sensor was shared to him, but this is not true.

https://github.com/ruuvi/com.ruuvi.station.ios/assets/50437378/85d6da32-6bc8-4f42-8aac-ae0b71bad8cb

**Comment by laurijamsa** [comment]
Do we have the same glitch on Android?

**Comment by markoaamunkajo** [comment]
I checked Android and couldn't see same happening for me.

**Comment by rinat-enikeev** [comment]
So good news is that I was able to reproduce. 
Bad news - it is not a small task as we must review how do we store ownership of a sensor on app side. 

I mean, [here](https://github.com/ruuvi/com.ruuvi.station.ios/blob/f1ec6d18cfce531418d1792a9e9340f7c127c232/Apps/RuuviStation/Sources/Classes/Presentation/Modules/Dashboard/Home/Interactor/DashboardInteractor.swift#L80-L80) we do set `isOwner` to false if the sensor is already owned by somebody else: 

```swift
sSelf.ruuviPool.update(ruuviTag
                    .with(owner: owner)
                    .with(isOwner: owner == sSelf.ruuviUser.email))
```

And [here](https://github.com/ruuvi/com.ruuvi.station.ios/blob/f1ec6d18cfce531418d1792a9e9340f7c127c232/Apps/RuuviStation/Sources/Classes/Presentation/Modules/TagSettings/Submodules/Removal/Presenter/SensorRemovalPresenter.swift#L36-L36) we have been assuming that if user is not the owner of a sensor - it is shared. 

I will carefully review what does it mean: `isOwner`, `isCloud`, `isClaimed` and try to fix the issue on the ontology layer. 

cc: @priyonto

**Comment by markoaamunkajo** [comment]
QA passed
