### ISSUE TITLE
0.7.21 Network sensor fetched data on Android but not on iOS

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station.ios#192]
Description:

User logged to network build on Android and iOS devices 

marko@ruuvi.com has 2 sensors,Ankka and Sorsa, which were synced to both devices
Android receives data to both sensor card but iOS shows "-" for second card named Sorsa
Pressing sync button in menu doesn't fetch data.

![Image from iOS (19)](https://user-images.githubusercontent.com/50437378/106128110-b6cd6b80-6191-11eb-9261-142f01db171f.png)
![Screenshot_20210128-174828_Ruuvi Station](https://user-images.githubusercontent.com/50437378/106128140-baf98900-6191-11eb-9778-70f25eb63cc0.jpg)

**Comment by rinat-enikeev** [comment]
wasn't able to reproduce, maybe it was fixed during development

**Comment by markoaamunkajo** [comment]
Fixed during development moving to done
