### ISSUE TITLE
2.6 Remove sensor with remove cloud history app returned to sensor settings and didn't remove sensor

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station.ios#1922]
Description:

Lauri's iPhone SE iOS 16.7.2

Another potential issue: I removed a sensor and I checked "remove also cloud history" and after doing it, app returned to sensor setting page and it did not remove the sensor. Second try removed it.

**Comment by markoaamunkajo** [comment]
I have not been able to reproduce this. It could be a slow network related issue.

**Comment by rinat-enikeev** [comment]
Wasn't able to reproduce

**Comment by markoaamunkajo** [comment]
Closing this card since not able to reproduce. Will reopen if it pops up again.
