### ISSUE TITLE
Switching between history page flashes previous chart on screen

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station.ios#1930]
Description:

Spotted this issue when switching between normal and empty chart the page flashes chart briefly on screen.
Could this be improved?

https://github.com/ruuvi/com.ruuvi.station.ios/assets/50437378/2240ade3-6e21-49b5-9cad-9c1041b6615b

**Comment by rinat-enikeev** [comment]
nice catch! fixed in https://github.com/ruuvi/com.ruuvi.station.ios/pull/1941

**Comment by rinat-enikeev** [comment]
for fixes please check the latest builds in Firebase, the build notes are relevant

**Comment by markoaamunkajo** [comment]
QA passed
