### ISSUE TITLE
Builds from main should have PN working alongside debug features

### ISSUE THREAD

**Issue by priyonto** [ruuvi/com.ruuvi.station.ios#1933]
Currently push notifications do not work on Alpha builds. With new workflow, the builds produced from `main` branch should meet below specs:

1. Push notifications should work. 
2. FLEX should be available. 
3. `Defaults` settings under main settings `must be` available.
4. Analytics event `should not` be triggered.

**Comment by rinat-enikeev** [comment]
2.6.1

**Comment by rinat-enikeev** [comment]
this is for Firebase builds

**Comment by markoaamunkajo** [comment]
QA passed
