### ISSUE TITLE
Bluetooth connected icon shown after GATT sync although user in Cloud Mode - minor

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station.ios#1934]
Description:

User has Cloud mode enabled for sensor and his gateway is offline for past 20 minutes.
He goes to sensor card and does a Bluetooth GATT sync.
After sync the last source icon changes to Bluetooth connected.

Expected: Icon should switch back to gateway but it will only be changed if user exits history page.

https://github.com/ruuvi/com.ruuvi.station.ios/assets/50437378/7d1ee605-d46d-4d91-ad35-448489729d5a

**Comment by laurijamsa** [comment]
Hmm. Do I understand something differently? If latest datapoint is collected thru Bluetooth, why the icon should change back to Gateway icon?

**Comment by rinat-enikeev** [comment]
@markoaamunkajo if you are talking about this label [see screenshot], then same question as @laurijamsa asks: 

> by spec it's showing latest record datasource icon, and for GATT sync it is BT, as expected



<img src="https://github.com/ruuvi/com.ruuvi.station.ios/assets/722716/8c01f794-f318-4737-9948-9b902de8e270" width=320/>

**Comment by markoaamunkajo** [comment]
Hmm you are probably right about this one. Then it is correct behavior, closing this card.
