### ISSUE TITLE
0.7(21) Network sensor doesn't load whole history

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station.ios#195]
Description:

User has signed into network on Android and iOS devices, he has two sensors
Two sensor cards are created, first sensor card has charts history updated but it doesn't match with Android network sensor history, iOS history is much shorter

![Screenshot_20210128-183923_Ruuvi Station](https://user-images.githubusercontent.com/50437378/106134115-af5d9080-6198-11eb-90b9-80722c7cead5.jpg)
![Image from iOS (20)](https://user-images.githubusercontent.com/50437378/106134131-b2f11780-6198-11eb-95d8-63c8aaa37378.png)

**Comment by viikufa** [comment]
change network limit to 5000

**Comment by markoaamunkajo** [comment]
Discussed with @viikufa moving back to his queue

**Comment by markoaamunkajo** [comment]
Still exists in 0.7(21)
Comparing same network sensor with Android shows chart data between 15.5.-25.5., on iOS only 21.5.-25.5.
Tested changing Chart Duration from defaults and killing app, no effect.


![iOS](https://user-images.githubusercontent.com/50437378/119481503-fc372980-bd7c-11eb-874d-5b6e20fc6649.PNG)
![Android](https://user-images.githubusercontent.com/50437378/119481550-0b1ddc00-bd7d-11eb-9536-0aa71c6945c1.jpg)

**Comment by rinat-enikeev** [comment]
did migrate `chartDurationHours` to 240h.

**Comment by markoaamunkajo** [comment]
0.7(73) Clean install. I see defaults with 240h duration, but it makes no difference to what is showed in charts. Today I see 22.5.-26.5. data on same sensor.

**Comment by markoaamunkajo** [comment]
QA passed
