### ISSUE TITLE
Unify low battery indicator

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station.ios#1952]
Description:

Use same low battery indicator as on Android. Use the same svg so that both dark and light themes work correctly. If you don't know where to find, ask from Sini-Maaria.

![Image](https://github.com/ruuvi/com.ruuvi.station.ios/assets/50437378/7f24223f-0356-4015-9ebd-c881ffb98f3b)

**Comment by priyonto** [comment]
No unification needed as discussed on the meeting.
