### ISSUE TITLE
2.6.1 adding sensor with NFC shows correct and incorrect popup

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station.ios#1956]
Description:

User was adding sensor cards with NFC and for some reason two sensors with same firmware version showed different popups. I have flashed these sensor cards with devkit.

![Image](https://github.com/ruuvi/com.ruuvi.station.ios/assets/50437378/3149014f-1553-463d-8065-54210234e579)
![Image](https://github.com/ruuvi/com.ruuvi.station.ios/assets/50437378/4afca542-91ee-47aa-949b-3061dc453fd1)

**Comment by rinat-enikeev** [comment]
so the steps are: 
- be fast, add via NFC while the Bluetooth list is almost empty and doesn't contain this (most likely) longlife tag

**Comment by markoaamunkajo** [comment]
Other sensors adding seems to work ok but longlife is painfully slow. Discussed on channel.

**Comment by markoaamunkajo** [comment]
Adding separate issue about longlife reading being slow on 3.31.2rc1+longlife
