### ISSUE TITLE
Sensor card showing - C when last measurement was -19.88

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station.ios#1958]
Description:

This sensor has some issue and it's being investigated on Cloud side.
https://github.com/ruuvi/ruuvi.cloud.js/issues/430

Last measurement is from 6 days ago.

Sensor card showing  - C when last measurement was -19.88. User should see all last measured sensor values.
History view shows correct last measurement for temp but chart view is broken.

[Mokki.Kitchen_20240215T111403+0700.csv](https://github.com/ruuvi/com.ruuvi.station.ios/files/14307628/Mokki.Kitchen_20240215T111403%2B0700.csv)

**Comment by priyonto** [comment]
@markoaamunkajo Can this sensor be shared to me?

**Comment by priyonto** [comment]
@markoaamunkajo I am not sure what happened on this card. Right now I am seeing there's no temp data coming from the cloud, on iOS it shows `-` but on android it shows `0.00`, and on Web station I can see `-163.84` somehow. Could you please test again and share more info if possible?

**Comment by markoaamunkajo** [comment]
@priyonto I see same for this sensor card, maybe this situation has now somehow changed after 10 days with no battery on the sensor?

Underneath in example is what this sensor card *should* show (last known measurement value, last seen timestamp)
![Image](https://github.com/ruuvi/com.ruuvi.station.ios/assets/50437378/371b3aa5-1dbf-422b-87ce-5263b295a22c)


We know at this point that this is a really old sensor in the cloud and it is showing very old datapoint that is likely not even real, it's some kind of an error. Maybe that is what causes the "-" to be shown.

**Comment by priyonto** [comment]
@markoaamunkajo When there's no data available iOS shows `-`. Should we do otherwise in that case? 

But regardless I am not sure what to do regarding the issue.

**Comment by markoaamunkajo** [comment]
Closing, investigated on Cloud side
