### ISSUE TITLE
BLE or not, icon blinking

### ISSUE THREAD

**Issue by DG12** [ruuvi/com.ruuvi.station.ios#1959]
What's it mean

https://github.com/ruuvi/com.ruuvi.station.ios/assets/2365961/f5f2bb85-745d-43e5-a4e7-5f8555998d7a

**Comment by markoaamunkajo** [comment]
This was related to time not updating according to Advertisements and Heartbeat and has been resolved on another card.

**Comment by DG12** [comment]
This is still occurring as of 2.7.0(2403311418)
