### ISSUE TITLE
Add synchronizing info during network sync

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station.ios#196]
Description:

Please add to sensor card bottom left corner text "Synchronizing" with animated three dots
This will be shown on network sensor cards when sync is in progress.

**Comment by DG12** [comment]
PLEASE do not use a self running animation. That would indicate activity even if the connection  gets broken.
Rather change the presentation "manually" as the transfer continues.

**Comment by rinat-enikeev** [comment]
make it same as android

**Comment by markoaamunkajo** [comment]
QA passed
