### ISSUE TITLE
Zooming is not synchronised like it is on Android

### ISSUE THREAD

**Issue by laurijamsa** [ruuvi/com.ruuvi.station.ios#198]
This is a user feedback. Not tested by me. But basically user experience should be te same on the both Android and iOS and seems that currently it is not.

![image](https://user-images.githubusercontent.com/1311912/106229238-bc719280-621f-11eb-9f89-be866c98aca7.png)

Device: iPad 6th Gen (WiFi+Cellular)
OS: iOS 14.2
App: Ruuvi Station 0.6.1(20)

**Comment by markoaamunkajo** [comment]
0.7(73)

User makes clean install, downloads sensor data from network.
Actual: User zooms into random spot in charts, timelines are not staying in sync.

https://user-images.githubusercontent.com/50437378/119851129-5c25ff80-bf38-11eb-83df-39eb948e7477.MP4

**Comment by rinat-enikeev** [comment]
this feature is not ready for Beta, so I've hidden it under feature toggle

**Comment by markoaamunkajo** [comment]
Synced zooming QA passed. Made another card for units almost not fitting to charts view.
