### ISSUE TITLE
Update Crashlytics SDK's to support release monitoring

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station.ios#1989]
Description:

Let's update Firebase SDK's to support release monitoring feature

https://firebase.google.com/docs/release/release-monitoring#required-sdk-versions

Android card: https://github.com/ruuvi/com.ruuvi.station/issues/1224

**Comment by rinat-enikeev** [comment]
should already work (10.20.0 currently)

**Comment by markoaamunkajo** [comment]
Confirmed, works
