### ISSUE TITLE
Allow closing Add New Sensor page to show empty page and access to menu

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station.ios#199]
Description:

Currently Ruuvi Station Network build doesn't allow access to Ruuvi Network login if user doesn't have any devices (or understand to add virtual sensor).

Please allow minimizing Add New Sensor page (after onboarding, no sensors) and show Add Sensors placeholder page like in Android app. This way user is able to access hamburger menu and signin to Ruuvi Network.

**Comment by rinat-enikeev** [comment]
should be same as android

**Comment by markoaamunkajo** [comment]
QA passed
