### ISSUE TITLE
User updated from broken 2.6.x build to 2.7 and still sees last measurement glitch

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station.ios#1990]
Description:

Iphone 13 mini
Ios 17.3.1

User updated Ruuvi Station from 2.6.3 to 2.7.0 and still sees the last measurement date stamp showing between current and historical value.

This user contacted us through Telegram and can provide more information if needed. Ask me for his contact.

https://github.com/ruuvi/com.ruuvi.station.ios/assets/50437378/bbca31a1-5860-4e24-8011-6c4200e799ac

**Comment by rinat-enikeev** [comment]
please help us to reproduce it (steps)

**Comment by markoaamunkajo** [comment]
Duplicate of #2005
