### ISSUE TITLE
Alerts occur too frequently - defect -2.7.0(2403012040)

### ISSUE THREAD

**Issue by DG12** [ruuvi/com.ruuvi.station.ios#1992]
On the hour, "Ruuvi BB12 water inlet" starts reporting Temperature is too low. At 08:09:55,08:11:55,08:12:34, 08:13:51, 8:15:54, 08:17:55, 08:19:55, 08:21:54,08:23:55

i.e every 2 minutes (+/-)

Sometimes only

> Ruuvi Station      now
> Notification

Occasionally 2 
![6 05](https://github.com/ruuvi/com.ruuvi.station.ios/assets/2365961/ec51f35c-b782-482e-ac4e-ed987a30842a)
![6 03](https://github.com/ruuvi/com.ruuvi.station.ios/assets/2365961/37e95e5e-86bf-4ba4-94ff-5b5d6f00bd72)
![5 14](https://github.com/ruuvi/com.ruuvi.station.ios/assets/2365961/6f5847f1-0291-42b1-bb5d-b711f3a7c081)
![5 11](https://github.com/ruuvi/com.ruuvi.station.ios/assets/2365961/ee34ce1d-c97b-413f-b74d-a21822c4cc32)
![4 22](https://github.com/ruuvi/com.ruuvi.station.ios/assets/2365961/588c39fb-7c4c-49c7-943a-0bfb9c8d85f6)
![4 21](https://github.com/ruuvi/com.ruuvi.station.ios/assets/2365961/9505042d-5790-4ceb-a35d-8f488d2c75b2)
![4 16](https://github.com/ruuvi/com.ruuvi.station.ios/assets/2365961/b092269c-be8e-4486-8892-dc1342aa7f96)

**Comment by markoaamunkajo** [comment]
We now have setting for Bluetooth alert to show alert only 1 time per hour, this card is solved with this solution.
