### ISSUE TITLE
Redesign text layouts for history view

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station.ios#1994]
Description:

We want to change the layout of the existing 3 charts in history view to this style to improve readability of chart.

This would work well with alert limits in charts.

![Image](https://github.com/ruuvi/com.ruuvi.station/assets/50437378/b556e6c9-75da-438f-90fa-8152bf1092f2)

Android card: https://github.com/ruuvi/com.ruuvi.station/issues/1225

**Comment by DG12** [comment]
I'd like to suggest "latest" value be last in the list i.e where the "latest" point on the graph is.

The others: min (smallest) leftmost(by the smallest X values), average between the min and the max (which its value will be) and Max toward the larger x values.

At the bottom of each graph, with the x scale.

What does "Ka" **Mean** ?
1) acid-ionization constant.
2) absorption rate constant Ka is a value used in pharmacokinetics: the rate at which a drug enters into the system
3) number of non-synonymous substitutions at a DNA site

or is it just **mean** 🤔

**Comment by laurijamsa** [comment]
Ka is a shortened version of "keskiarvo" which means an average.

I think the latest could be the last one like you suggested. The second suggestion about changing the order from min-max-average to min-average-max feels not like an enhancement so I wouldn't change it for now.

I have commented these same things on the Android card as well: https://github.com/ruuvi/com.ruuvi.station/issues/1225

**Comment by markoaamunkajo** [comment]
QA passed
