### ISSUE TITLE
2.7 beta feedback sensor setting reports not saved to cloud but user looks like not signed in

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station.ios#1995]
Description:

In App Store Connect feedback I found one report related to 2.7.0 app hanging when trying to save sensor settings change to cloud. In screenshot it looks like ownership is not shown in sensor settings and sensor is in connected mode.

For some reason sensor sharing is shown for user on sensor settings page. And when user changes setting it shows the toast for saving to cloud.

I tried multiple ways to get into this mode but I am not able to get settings tried to be saved to cloud in my tests yet.

![Image](https://github.com/ruuvi/com.ruuvi.station.ios/assets/50437378/c47efe53-d0e5-447a-9746-f6dc425e1488)

@rinat-enikeev could you please check the Xcode entry in App Store Connect for this. It doesn't look critical but good to fix if reason is found.

**Comment by markoaamunkajo** [comment]
Asked additional information from user via email.

**Comment by rinat-enikeev** [comment]
also check the switch goring oout of screen

**Comment by markoaamunkajo** [comment]
User has not responded

**Comment by markoaamunkajo** [comment]
If no resolution for this bug let's move to backlog.

**Comment by markoaamunkajo** [comment]
Will retry to reproduce this bug. It's some sort of edge case.

**Comment by markoaamunkajo** [comment]
This cannot be reproduced. My only assumption at this point is that maybe there was issue with server, but it cannot be easily tested. Closing this as it was never seen again.
