### ISSUE TITLE
Add support for XLSX export

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station.ios#1997]
Description:

Add support for XLXS export

**Comment by markoaamunkajo** [comment]
@priyonto looks like when dew point is selected for humidity it doesn't reflect on CSV or XLXS file on iOS.

![Image](https://github.com/user-attachments/assets/c40fe2b6-5eae-4bb6-b00d-8acee07b99f5)

**Comment by priyonto** [comment]
@markoaamunkajo Isn't it so that for dew point we show the same unit as temperature unit?

**Comment by markoaamunkajo** [comment]
Yes, but hmm for some reason it didn't reflect changes for me yesterday. I don't know what happened. Will retest.

**Comment by markoaamunkajo** [comment]
Maybe I got confused, I spent some time testing and this works for me, moving to done.
