### ISSUE TITLE
Add "Beta" to Ruuvi Network signin

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station.ios#200]
Description:

Please add "Beta" to Ruuvi Network Signin menu item, so people know that network product is an early beta.

See beta in screenshot

**Comment by markoaamunkajo** [comment]
<img width="93" alt="Screenshot 2021-01-30 at 16 18 28" src="https://user-images.githubusercontent.com/50437378/106352565-d215b380-6316-11eb-9df1-0ce5a0eccd0e.png">

**Comment by rinat-enikeev** [comment]
check android and make it look the same

**Comment by markoaamunkajo** [comment]
QA passed
