### ISSUE TITLE
welcome graph example needs update to include  min/max/avg  cosmetic

### ISSUE THREAD

**Issue by DG12** [ruuvi/com.ruuvi.station.ios#2001]
![image](https://github.com/ruuvi/com.ruuvi.station.ios/assets/2365961/ce5040bd-56e8-49df-85f4-55c4ba8b4bd5) ![image](https://github.com/ruuvi/com.ruuvi.station.ios/assets/2365961/3d7208c6-76db-4ae7-b1d9-27440446b70b)

**Comment by laurijamsa** [comment]
Thanks for the report. We are doing more visual updates later on and these welcome slides will be updated after that. Closing the issue.
