### ISSUE TITLE
Google Analytics consents

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station.ios#2009]
Description:

Both apps have some issues with Google Analytics with proper consents.

![Image](https://github.com/ruuvi/com.ruuvi.station/assets/50437378/20cd65dd-d9d7-4f3a-9e0d-03541d8759e2)

**Comment by priyonto** [comment]
We need to comply this asap otherwise we will not be able to push build to AppStore.

**Comment by markoaamunkajo** [comment]
Nothing to do, moving this to done.
