### ISSUE TITLE
Redesign Network Signin

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station.ios#201]
Description:

Replace current network signin screen with new version.
Design example should be adapted to current onboarding colour scheme for now.

Steps:

1. Signin menu button will show an information popup, then forwards to signin page.
2. Signin screen redesign.

See attached example screenshots.

<img width="257" alt="Popup" src="https://user-images.githubusercontent.com/50437378/106353737-5409da80-631f-11eb-8a12-66e2f9ef06d2.png">

<img width="372" alt="New signin" src="https://user-images.githubusercontent.com/50437378/106353614-6cc5c080-631e-11eb-8c0e-784b42301f84.png">

**Comment by rinat-enikeev** [comment]
compare with android and make it look the same.

**Comment by markoaamunkajo** [comment]
0.7(62) Clean install, iPhone 7, iOS 14.5.1
Network signin is successful but after code screen no sensor cards are created. Sensor cards will be only created and synced once user selects sync button from main menu.

Expected: create sensor cards after successful signin.

**Comment by markoaamunkajo** [comment]
QA passed
