### ISSUE TITLE
Tags with slash in name cannot be exported

### ISSUE THREAD

**Issue by ojousima** [ruuvi/com.ruuvi.station.ios#202]
> I had named a tag "keittiö/kuisti" or something like that with a slash. When I tried to sync it, I got error "Folder 'kuisti-2021-01-31-0011.csv' does not exist". After replacing the slash with a dash the sync was successful.

**Comment by ojousima** [comment]
More generally, input fields in app must be sanitized.

**Comment by markoaamunkajo** [comment]
QA passed
