### ISSUE TITLE
Add checkbox to onboarding to approve terms / privacy

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station.ios#2022]
Description:

We need to let users decide if they approve or decline terms/privacy policy in order to use Ruuvi Station app.
We will force users to see the onboarding screens when they install this new version.

There are 3 different scenarios: 

New user, who just installed app
Old user, who updates app and is not signed in
Old user, who updates app and is signed in

1. We will show on last page of the onboarding (before sign up/sign in) checkbox for approving terms & conditions.

Note:
New user will see last page with string: onboarding_thats_it
Signed in user will see last page with string: onboarding_thats_it_already_signed_in

2. Grey out Next button if terms checkbox is unchecked. If user checked checkbox and selected Next, we will allow to continue to Benefits screen.
3. Terms and conditions will be a link that opens in default browser. Link: https://ruuvi.com/privacy/
If old user updates app, we will show onboarding once to user, so he will need to approve terms & conditions in order to use the app. If user is signed in, we will skip sign in / sign up screens and land him on home screen.

![Image](https://github.com/ruuvi/com.ruuvi.station/assets/50437378/bd8cf9a8-6a1f-4a5e-8dd8-ce4cf620065d)

![Image](https://github.com/ruuvi/com.ruuvi.station/assets/50437378/02ae3b71-9e8d-4814-9c56-3dc54bf7a432)

We we will write to sentence to approving terms and conditions mention that
- User approves terms and conditions and privacy policy
- User approves collecting statistics and crash reports anonymously to improve service

Android card: https://github.com/ruuvi/com.ruuvi.station/issues/1257
Web: https://github.com/ruuvi/com.ruuvi.station.webui/issues/414

**Comment by markoaamunkajo** [comment]
QA passed

**Comment by markoaamunkajo** [comment]
@priyonto let's rather center the box and text/link on this screen.

![Image](https://github.com/ruuvi/com.ruuvi.station.ios/assets/50437378/b6aae4f5-6637-4a09-a7ad-84d1292657e8)

**Comment by markoaamunkajo** [comment]
Waiting for translations to be merged

**Comment by priyonto** [comment]
Reopened: New spec for improvements:

1. Follow the below image, add two checkbox. Unticking the analytics should disable sending the analytics to firebase. 
2. Remove the subtitle from the last page. 
3. Show last page when user already is not fresh installing the app. 

![photo1719563872](https://github.com/ruuvi/com.ruuvi.station.ios/assets/24395776/9b9d4345-14bd-4041-be95-d25c245015a6)

**Comment by markoaamunkajo** [comment]
QA passed
