### ISSUE TITLE
App crashing periodically for user with lots of sensors

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station.ios#2024]
Description:

User reported that iOS app is crashing periodically (almost every night)
He has quite a big database, 23 sensors, db size is big

BG scan is enabled, 5 min interval
User is Cloud user (indicating that he has Gateway), Cloud mode is enabled

![Image](https://github.com/ruuvi/com.ruuvi.station.ios/assets/50437378/f944457b-ad34-4001-9bb0-854d70205524)

**Comment by markoaamunkajo** [comment]
Further details from user:

![Image](https://github.com/ruuvi/com.ruuvi.station.ios/assets/50437378/e6789290-7d73-424f-8241-46c575f947e9)

- BT devices typically connected: Bluetooth earphones, Oura Gen3 activity monitor
- Uses StandBy mode typically in the night (iPhone charging, sideways to switch to StandBy screen)

**Comment by markoaamunkajo** [comment]
Testing StandBy mode with Ruuvi Widget, different configurations

**Comment by markoaamunkajo** [comment]
@priyonto report from other user experiencing crash too.

os 17.4.1 (practically always the latest)
iPhone 15 Pro Max

Version 2.7.0(2403012040)
Added sensors: 28
Number of locally stored measurements: 212,147
Database size: 50.7 MB

Ruuvi gw is used in house 1, cottage 2.
There are 13 tags at home and 13 at the cottage (these are all registered to my e-mail in Ruuvi cloud)
in addition, there are a couple of tags in the application that are not mine, these are often not in GW's range

BT accessories, what do you mean by these, in general that there are other paired BT jobs on the phone? If so, you can find these 😄 Apple watch, a couple of airpods, some other headphones, a couple of cars, a Tesla key and something I probably forgot.

One widget is on the desktop on the phone.

iOS standby mode is not used when charging phone

There aren't any special situations where I've noticed that falling, although now that I've paid special attention to it, I haven't encountered any of them. I can let you know as soon as it comes again, if I recognize something in it that I specifically did. Usually the crash has happened when I've had the phone in my pocket/charger etc. for a longer time and when I open the phone it pops up that the screw application has crashed, do you want to send a report.

**Comment by markoaamunkajo** [comment]
User mentioned that there are some sensors that used to have old firmware and they were updated. Maybe this is related to old df3.

**Comment by markoaamunkajo** [comment]
Asked one of the users to reinstall app to see if this would be caused by some migration issue.

**Comment by markoaamunkajo** [comment]
Suggested both to try with chart setting show all datapoints switched to disabled, since there are a lot of locally stored datapoints.

**Comment by markoaamunkajo** [comment]
User reported that his crashes have gone away after updating firmware for old sensor.
His version is 2.7.x so somehow I believe that this version maybe didn't drop old df3 version tag and it caused problems.


Is there any clue in here to investigate @priyonto ?
If not, then I already agreed with user we can close this issue since problem as disappeared.

**Comment by priyonto** [comment]
We can't reproduce it as of now and have no idea what could cause those. We will reopen it if it comes back and we get a proper reproduce step.
