### ISSUE TITLE
charting should acknowledge when it starts 2.8 minor

### ISSUE THREAD

**Issue by DG12** [ruuvi/com.ruuvi.station.ios#2025]
When charting 10 days with 1 minute sample interval is (10x24x60)
14,400 data points. 
This causes disturbing delay.
Simple solution:  as soon as charting starts display "Charting..."

https://github.com/ruuvi/com.ruuvi.station.ios/assets/2365961/33c977b0-0d88-457e-a1a1-368593517f25

**Comment by markoaamunkajo** [comment]
Very interesting behavior, since Bluetooth looks like it's not getting updated at all over multiple seconds. I have not seen this yet on my SE.

**Comment by markoaamunkajo** [comment]
@DG12 this is related to your device situation somehow, mine starts charting immediately via Bluetooth on standard firmware. Closing this as I have not spotted this in tests.
