### ISSUE TITLE
No sleep for alert if notification dismissed from notifications center

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station.ios#203]
Description:

Remove ability to make alerts sleep for 1 hour when notification dismissed by swipe and clear from notifications center.
Do we have ability to turn off a specific alert from notification? That would be nice.

This card is for unification with Android

**Comment by rinat-enikeev** [comment]
I set to 15 seconds and added ability to mute to 1 hour.

**Comment by rinat-enikeev** [comment]
TF 0.6.3(2)

**Comment by markoaamunkajo** [comment]
QA passed
