### ISSUE TITLE
Cannot access sensor settings if no data

### ISSUE THREAD

**Issue by laurijamsa** [ruuvi/com.ruuvi.station.ios#204]
Our user reported this issue: https://twitter.com/joneskoo_yx/status/1356700624709181442

**Comment by DG12** [comment]
From twitter:" iOS app needs some loving update. Can’t remove a sensor with no data (gear does nothing), can’t arrange sensors, can’t see all sensors in one view. Maybe ok if you have one, not 9."

**Comment by viikufa** [comment]
@markoaamunkajo 

steps to reproduce this bug:
1) add a connectable sensor
2) turn off bluetooth
3) open the chart scene and clear data
4) unload application from the memory
5) start application again and try to open the tag settings scene

**Comment by markoaamunkajo** [comment]
Agreed to fix popup for error when trying to remove disconnected sensor.
Made pull request for en, fi, sv strings, RU needs to be edited

**Comment by viikufa** [comment]
resolved in https://github.com/ruuvi/com.ruuvi.station.ios/pull/209

**Comment by markoaamunkajo** [comment]
QA passed
