### ISSUE TITLE
Charting time period should be sensor specific - significant -

### ISSUE THREAD

**Issue by DG12** [ruuvi/com.ruuvi.station.ios#2044]
Currently setting the time period is a global setting.

Changing the time period must be sensor specific.

Setting the time period for sensor xxxx to 7 days should not affect other sensors

See related issue #2042 too many data points cause crash.

**Comment by markoaamunkajo** [comment]
Imho setting viewport size for each chart adds also unnecessary complexity for user. Too many datapoints issue should be handled obviously.

**Comment by DG12** [comment]
In my experience, having the default starting the same and allowing user to change on a sensor basis is easy to understand. Perhaps you experience is more typical for the average user.😋

**Comment by markoaamunkajo** [comment]
We will not implement sensor card based viewports at this point.

**Comment by DG12** [comment]
Oh Well
