### ISSUE TITLE
update firmware, ,low batterey: no way out - minor 

### ISSUE THREAD

**Issue by DG12** [ruuvi/com.ruuvi.station.ios#2046]
Adding a sensor with "old" firmware suggests update.
Station determines battery is low. Suggests replace battery. Only option is OK.
Returns to Start update process, the replace battery. 
swiping around eventually gets out.

**Comment by markoaamunkajo** [comment]
Exit on this page is from the arrow, I believe the whole process goes in this window which user can exit.

![Image](https://github.com/ruuvi/com.ruuvi.station.ios/assets/50437378/dcc978aa-f07c-43db-a385-4b237a2b590a)
