### ISSUE TITLE
Do not simplify (drop data points) the graphs so aggressively

### ISSUE THREAD

**Issue by laurijamsa** [ruuvi/com.ruuvi.station.ios#205]
Some users have complained about this. Should unify these things with Android and iOS. Let's agree about the actual default settings on this issue before implementing any fixes.

**Comment by rinat-enikeev** [comment]
@laurijamsa @viikufa  any decision on this issue (drop data points interval)?

**Comment by laurijamsa** [comment]
Discussion is planned to take place in here: https://github.com/ruuvi/com.ruuvi.station/issues/369

Closing this issue. Please create a new one once specs are locked and something can be implemented.

**Comment by rinat-enikeev** [comment]
we need to unify the experience on iOS with Android

**Comment by markoaamunkajo** [comment]
QA passed
