### ISSUE TITLE
Unify stored data history length with Android

### ISSUE THREAD

**Issue by laurijamsa** [ruuvi/com.ruuvi.station.ios#206]
RuuviTag firmware 3.29.3's memory spec says:

"History size on the firmware is 3500 temperature + pressure + humidity data points. History is logged in the firmware once in ~5 minutes, for a total memory length of 12 days."

Currently, the mobile apps' history is limited to 72 hours (and iOS had a bug that stored longer to the RAM). Now, we should unify the apps and allow longer GATT history sync.

One possible way to handle this would be not to limit the history length on the mobile apps by days but instead by data points (for example 10k). But then we'd need some kind of a calendar approach on the browsing and maybe some quick zooming level buttons like "1 day, 1 week, full history". But we'll need these things anyways later when Ruuvi Network with cloud history becomes available.

So, this issue is not an assignment just yet. Let's decide first how to implement this so that it'll be ready for the future, too.

**Comment by andreevdenis** [comment]
Why is limiting by data points is only possible way? 10k of points can be anything: 1 day of data or 1 week

**Comment by DG12** [comment]
Different uses, i.e. intervals, should take advantage of available memory regardless of the time period covered.

**Comment by rinat-enikeev** [comment]
> and iOS had a bug that stored longer to the RAM

Also the bug mentioned in the description should be fixed in this task.

**Comment by rinat-enikeev** [comment]
The final decision is to store 10 days of GATT max.

**Comment by DG12** [comment]
Why present an artificial limit rather than use all available memory.
Ten days (of time) will contain very few data points if the logging_interval is every minute and the RuuviTag is left in the field for more than a month.

**Comment by rinat-enikeev** [comment]
you can play with Defaults in 0.6.3(3), the 0.6.3(4) is a Release Candidate.

**Comment by rinat-enikeev** [comment]
@markoaamunkajo you can set "Pruning Offset Hours" to 1 hour to limit the history length from 10 days to 1 hour and ensure that the shown interval is 1 hour.

**Comment by markoaamunkajo** [comment]
QA passed
