### ISSUE TITLE
Signout operation successful but  (almost) no way back! --improvment minor-

### ISSUE THREAD

**Issue by DG12** [ruuvi/com.ruuvi.station.ios#2061]
After logging out user is left weith
![image](https://github.com/ruuvi/com.ruuvi.station.ios/assets/2365961/8c22fdbd-7e32-49a0-90f7-7749e2efd004)

Doesn't seem to be a way out.
but if you slide it goes a way(I think)

**Comment by laurijamsa** [comment]
Hmm, interesting. This has used to work well before. Can you reproduce this?

**Comment by DG12** [comment]
User misunderstanding.
OOPs

**Comment by DG12** [comment]
Wait a second, down arrow  \/   is not effective. only way out is swipe DOWN

**Comment by DG12** [comment]
nothing can be tapped
