### ISSUE TITLE
Wrong background colour used for error text on FW update page

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station.ios#2063]
Description:

User has light theme selected, tries to do firmware update but ends up in error.

Actual: background colour is off for light theme

![Image](https://github.com/ruuvi/com.ruuvi.station.ios/assets/50437378/b8ef747f-ba55-4fac-91df-45b425fbf5df)

**Comment by priyonto** [comment]
@markoaamunkajo This string is coming from iOS DFU Library. But, I fixed the background color issue.

**Comment by markoaamunkajo** [comment]
QA passed
