### ISSUE TITLE
Improve Sign-In logic by offloading history fetching

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station.ios#2067]
Tasks: 

- Do not fetch full history on Sign-In. 
- Fetch the sensor history only when history page is opened. 
- (Optionally) Make a different implementation where history fetching is completed in the background after signing in is finished.

**Comment by markoaamunkajo** [comment]
@priyonto I was recommended this app called Proxyman by Alexey to track iOS traffic and decrypt SSL.
Looks like I am able to get both 400 errors and 500 errors.

Maybe this would be something on app side to check?

Dev

![Image](https://github.com/user-attachments/assets/ec43b0c4-1f65-4f1a-84d6-dc06014f5771)

Prod



![Image](https://github.com/user-attachments/assets/b7bd5cea-f775-4d40-9a32-5c6a65c34a4c)


![Image](https://github.com/user-attachments/assets/ac290162-6254-433b-b76e-8c097ded9c25)


![Image](https://github.com/user-attachments/assets/e96e0caa-ee1e-4359-9f1e-5d7ffe5f81fa)

**Comment by priyonto** [comment]
@markoaamunkajo I tested further and it is likely a server side problem. I got the `/sensor-dense` to fail several times randomly on production, while testnet seemed fine. At the same time I don't have that many sensors or data on testnet. Discussed a few things with @ojousima too in DM. And, I don't think its a connection issue either. 

Also, fixed the `400` error issue, that was on app side.

**Comment by priyonto** [comment]
@markoaamunkajo This can be closed if its tested enough as 500 error will be handled as part of #2094

**Comment by markoaamunkajo** [comment]
Considered done, logs are showing it is working differently.
