### ISSUE TITLE
Show in settings if alert is currently muted

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station.ios#207]
Description:

We are able to set alerts to timeout in notification center, but we don't actually indicate that anywhere. Let's show which alerts are snoozed in tag settings

This is styled in Android as follows

Mute bell - time until muted

![Screenshot 2021-02-05 at 20 05 07](https://user-images.githubusercontent.com/50437378/107037315-7b641a00-67ed-11eb-9837-3cf4551135b9.png)

**Comment by rinat-enikeev** [comment]
@markoaamunkajo in order to QA 0.6.3(2) build on internal TestFlight, I would recommend to set 

- Alerts Interval
- Alerts Mute Interval
- Web Alerts Interval

to minimal values on Defaults screen.

**Comment by markoaamunkajo** [comment]
QA passed
