### ISSUE TITLE
Force claim sensor via NFC -Forbidden - 240702 2051 

### ISSUE THREAD

**Issue by DG12** [ruuvi/com.ruuvi.station.ios#2075]
Attempt to claim sensor IO am holding via NFC reports forbidden.

PS NFCtools scans tag immediately, ruuv)i station needs to be convinced (i.e. stroked back and forth
![image](https://github.com/ruuvi/com.ruuvi.station.ios/assets/2365961/23b36509-9a9a-468f-8244-220def1c0cbd)

**Comment by markoaamunkajo** [comment]
So far I couldn't reproduce. Maybe sensor is paired to another app?

**Comment by markoaamunkajo** [comment]
I think I reproduced the same scenario @DG12 . I scanned another RuuviTag, not the one that was assigned to this sensor card and received Forbidden error.

![Image](https://github.com/ruuvi/com.ruuvi.station.ios/assets/50437378/fd3b73bc-69b6-4d78-aa93-7510306163a2)
