### ISSUE TITLE
Add ability to mute for hour in notification center

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station.ios#208]
Description:

We are removing clear to snooze alert for 1 hour, so we need to add mute for 1 hour button to notification center.

See design example from Android

![Screenshot 2021-02-05 at 20 11 13](https://user-images.githubusercontent.com/50437378/107037897-54f2ae80-67ee-11eb-9a11-b6d86c77659e.png)

**Comment by rinat-enikeev** [comment]
@markoaamunkajo in order to QA 0.6.3(2) build on internal TestFlight, I would recommend to set 

- Alerts Interval
- Alerts Mute Interval
- Web Alerts Interval

to minimal values on Defaults screen.

**Comment by markoaamunkajo** [comment]
QA passed
