### ISSUE TITLE
Fix error when trying to force claim sensor

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station.ios#2083]
Description:

User tries to force claim different sensor than the sensor card that he is on.

Actual: Error: Forbidden
Expected: You are scanning a different RuuviTag (same as in Android)

This string appears not to be in language file.

Android card:  https://github.com/ruuvi/com.ruuvi.station/issues/1282

**Comment by laurijamsa** [comment]
Is it hardcoded in the Android app? If yes, should be fixed and localised. @andreevdenis

**Comment by andreevdenis** [comment]
**claim_wrong_sensor_scanned** ident of this string in localization

**Comment by markoaamunkajo** [comment]
QA passed
