### ISSUE TITLE
Sensor settings;  alerts : signal strength at gaterway seems to have little if any value - cosmetic

### ISSUE THREAD

**Issue by DG12** [ruuvi/com.ruuvi.station.ios#2084]
1) Cannot set signal strength alert  (dBm) by keying in min/max. 
When setting min a - (negate) wide button appears above the numeric keypad (a Good Thing). 
Tapping MAX, and the - (negate)  disappears.
See attached image.

2) Slide bar is too wide. IOS thinks you want to swipe left or right.

3) Initial **default** should be more realistic like -100  ... -30 (Not -105 .. 0)

4) Relative Signal Strength Indicator is referred to as RSSI in "more info" and in export. 
"Signal Strength " should be RSSI to be consistent.

5) Placing max above min is more intuitive.

6) wording:Using this alert... is too dim and too small!

![image](https://github.com/user-attachments/assets/54436980-ca03-4af6-a154-4163fa28f41c)
![image](https://github.com/user-attachments/assets/e54d6e6e-e1c6-4c69-b1da-70b56edc090a)

**Comment by markoaamunkajo** [comment]
@priyonto there is no minus key in the max field and it makes it difficult to use.
I think there is a good usability point, maybe we should fill minus to fields by default or alternatively add the minus key to max field keyboard.

https://github.com/user-attachments/assets/c629f2e0-05c8-4136-9e3a-908c93e583c8

**Comment by DG12** [comment]
Please reconsider even having a max RSSI limit. Seems pretty useless to me.

**Comment by priyonto** [comment]
Added '-' for maximum value.

**Comment by markoaamunkajo** [comment]
QA passed
