### ISSUE TITLE
Point terms and privacy policy URL to section with mobile apps details

### ISSUE THREAD

**Issue by laurijamsa** [ruuvi/com.ruuvi.station.ios#2085]
Description:

Point terms and privacy policy URL to section with mobile apps details

Links to use:

All languages except Finnish: https://ruuvi.com/privacy/#apps
Finnish: https://ruuvi.com/fi/tietosuoja/#apps

**Comment by markoaamunkajo** [comment]
Added to localisation file and made pull request.
