### ISSUE TITLE
Point terms and privacy policy URL to section with mobile apps details

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station.ios#2086]
Description:

Point terms and privacy policy URL to section with mobile apps details
This is shown in the consent checkbox text

Links to use:

All languages except Finnish: https://ruuvi.com/privacy/#apps
Finnish: https://ruuvi.com/fi/tietosuoja/#apps

**Comment by laurijamsa** [comment]
Closed as a duplicate to #2085
