### ISSUE TITLE
Humidity value from GATT on 2in1 sensor

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station.ios#2092]
Description:

RuuviTag Pro 2in1 with firmware 3.33.0 + default

Humidity value added for RuuviTag Pro 2in1 sensor when reading sensor history from tag using GATT sync.

User downloaded measurement history to Ruuvi Station from RuuviTag Pro 2in1 sensor and it included humidity values "-0.01", but this sensor model doesn't have onboard humidity sensor, so value is reported through an error.

[RuuviTag 2in1 External_SYNC_ 20240723T101650+0700.csv](https://github.com/user-attachments/files/16344915/RuuviTag.2in1.External_SYNC_.20240723T101650%2B0700.csv)

This issue doesn't exist on Android

**Comment by priyonto** [comment]
@markoaamunkajo I made a blink fix as I don't have access to 2in1 pro sensor right now but hope the fix will sort the issue, if not please let me know.

**Comment by markoaamunkajo** [comment]
QA passed
