### ISSUE TITLE
Hotfix: handle 500 errors in app

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station.ios#2094]
Description:

We have found that 500 errors can cause surprising issues in apps, we need to handle those in apps.

**Comment by priyonto** [comment]
Whats implemented:

- Retry once in case of error in sensor dense endpoint from sign in flow.
- For next error show a dialog and clear previous session on OK tap so that user can start again.

**Comment by markoaamunkajo** [comment]
Will continue with this card once Otso is back, we need to setup dev to spit 500 errors

**Comment by markoaamunkajo** [comment]
QA passed
