### ISSUE TITLE
Signout but 3 sensors remain - 240803 16-05 defect minor

### ISSUE THREAD

**Issue by DG12** [ruuvi/com.ruuvi.station.ios#2110]
After signing out, immediately 6E29, AD03 and 3B86 remain.

Only 6E29 is in range.
![image](https://github.com/user-attachments/assets/a6695db0-99ab-491e-b58f-66d13085bee6)

**Comment by priyonto** [comment]
Range doesn't matter here since when you added those sensors they were in range. These are locally added sensor, hence they will start here even if you sign out from the app.
