### ISSUE TITLE
Test Bluetooth connected mode with a lot of sensors

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station.ios#2116]
Description:

Test connected mode with lot of sensors if any issues

**Comment by markoaamunkajo** [comment]
Movement alert and move the sensors, see that connection is still active

**Comment by DG12** [comment]
How many is "a lolt" ?

**Comment by markoaamunkajo** [comment]
> How many is "a lot" ?

I think a pile of sensors will be sufficient amount here 😄

**Comment by DG12** [comment]
And "a lot" of other bluetooth devices too?

**Comment by markoaamunkajo** [comment]
Yesterday tried iPhone 14 with 14 sensors but got no results until I had to resort to testing other things too soon. Today I have same sensors running on another phone, bg interval set to 10 seconds and not touching it, hopefully I will get some results in couple of days.

**Comment by markoaamunkajo** [comment]
I experienced iPhone SE losing connections to all of the paired devices after leaving it untouched over the weekend. I think this needs more investigation, maybe there is some silent crash in Bluetooth.

Now I had app running for 24 hours, the connections were still on and everything worked in the app, so I need to leave this device untouched for few days before checking again.

**Comment by markoaamunkajo** [comment]
I have reproduced the Bluetooth background scanning issue over the weekend and collected data to another card: https://github.com/ruuvi/com.ruuvi.station.ios/issues/2142

**Comment by markoaamunkajo** [comment]
I believe the most significant things are now tested on this card, closing for now.
