### ISSUE TITLE
Signing up: "almost there" remains behind "benefits"  cosmetic  240819 1725

### ISSUE THREAD

**Issue by DG12** [ruuvi/com.ruuvi.station.ios#2123]
I noticed a little bit of the  "almost there" window peaking behind the "benefits"
I had to slide benefits down to see the "almost there" window .

Of course this only happens during sign-**UP**

Not sure if this is a cosmetic issue or
something more troubling

![image](https://github.com/user-attachments/assets/46d798de-f56f-4831-8b4d-935f8a94f084)

**Comment by markoaamunkajo** [comment]
It's because these two parts are split into two. Yes it seems counter-intuitive, maybe we will improve this in the future, moving to proposals for now.
