### ISSUE TITLE
AirPressure alert setting ignores attempt to set min - defect- outlier

### ISSUE THREAD

**Issue by DG12** [ruuvi/com.ruuvi.station.ios#2136]
Attempt to set min alert (by keyboard) to 14.70  results in no change and **no error message**

![image](https://github.com/user-attachments/assets/c8d6cf12-9fc2-483e-b936-f8a735c0bd0f)

![image](https://github.com/user-attachments/assets/d2118759-9c63-4f76-9640-0ea3c7217c09)

Error message should be produced

**Comment by markoaamunkajo** [comment]
It's because min limit is hPa 500 which converts to 14.76 so you cannot save value that is lower.
For background I think this is an OS styling thing, so we probably cannot change it.

**Comment by DG12** [comment]
Seems like an error message should be presented.
