### ISSUE TITLE
air pressure alert setting range too large - user interface improvement.  

### ISSUE THREAD

**Issue by DG12** [ruuvi/com.ruuvi.station.ios#2137]
The air pressure range is  14.00 -  34.00 inHg

This is quite unrealistic since 19.82" at 10,000 feet and the
highest was 1083.8mb = hPa (32.00 inHg) at Agata, Siberia, Russia

Making adjustment by slider more difficult than necessary

Min should be 20.00 max 32.00 inHg.

**Comment by laurijamsa** [comment]
This is not an iOS issue but a wider user experience decision. We will discuss about this internally and we will open separate issue tickets if we decide to make changes. Thanks for the idea.
