### ISSUE TITLE
Alarm: fires every minute   - defect  (backend issue?)

### ISSUE THREAD

**Issue by DG12** [ruuvi/com.ruuvi.station.ios#2146]
Alarm, in this case humidity, fires every minute.

![image](https://github.com/user-attachments/assets/f7b84787-5487-44c2-af4e-5c7323431e05)

image shows data seen by webstation.
<img width="1298" alt="humSeenByWebStation" src="https://github.com/user-attachments/assets/f9e4b326-772e-45b2-9eb9-5c0c5daea54c">

**Comment by laurijamsa** [comment]
Are you in range of your RuuviTag and is your iOS backgeound scanning set to 1min and is the "Limit alert notifications" setting set to off? If so, this is expected.

**Comment by DG12** [comment]
I am in range. 
Don't know about other settings since I deleted app and data to install latest version.

This is one of those things that if you understand the internals the system it makes sense. However, even though I am very familiar with the system, it was a surprise to me.

I did not expect the alarms were coming from the app.
Do emails come from the backend?

**Comment by laurijamsa** [comment]
Backend is sending email alerts, yes. Closing the issue because as far as I can see, there is no bug.
