### ISSUE TITLE
App crash when moved sensor card on dashboard

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station.ios#2149]
Description:

I experienced a weird behaviour when moving sensor card from the bottom towards top of dashboard.

First I started dragging card up and the haptic feedback was working, then it all of a sudden stopped working and suddenly sensor card appeared at the top of dashboard. Then I scrolled down and saw there were empty slots on dashboard. Shortly after this the app crashed.

After crash sensor card was at position 3 from the top. I didn't record the first part of the event but the gaps and crash is on the video. I was unable to reproduce it immediately after, I already had custom ordering on dashboard.

https://github.com/user-attachments/assets/a2a0a3ad-9505-4f19-b376-f2c4dff38c3d

**Comment by priyonto** [comment]
@markoaamunkajo I am curious how you ended up with blank space in dashboard. I believe that is the reason for the crash. It was not supposed to show you any blank area. I could not reproduce it either yet.

**Comment by markoaamunkajo** [comment]
Currently this is not reproducable, will continue teesting

**Comment by markoaamunkajo** [comment]
Not being able to reproduce, moving this to done and will reopen if it happens again
