### ISSUE TITLE
Sensor offset calibration

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station.ios#215]
Description:

Remove old Humidity calibration feature in Sensor Settings.

Add new Offset Calibration feature under Calibration in Sensor Settings and rename Calibration menu item to Offset Calibration. This feature will enable user to set custom offset for:

Temperature
Relative Air Humidity
Air Pressure (hPa)

1. Offset will be converted accordingly if other global unit is selected in App Settings ie Celsius -> Kelvin
2. Temperature, Relative Air Humidity, Air Pressure hPa will be only supported for offset

Every Offset Calibration page has:

1. Description text (to be added later)
2. Original measured value (updated live)
3. Target value (default empty with description text "Add", not updated live), Offset in parenthesis (updated live)

CSV export will show calibrated values (as is currently with humidity).

<img width="315" alt="Screenshot 2021-02-20 at 13 55 56" src="https://user-images.githubusercontent.com/50437378/108586815-635ecf80-7383-11eb-95f9-dd17f8824b4d.png">

<img width="308" alt="Screenshot 2021-02-20 at 13 42 45" src="https://user-images.githubusercontent.com/50437378/108586801-4de9a580-7383-11eb-8cf7-3070d6279a6b.png">

**Comment by DG12** [comment]
See also important information at RuuviStation issue 274

**Comment by markoaamunkajo** [comment]
0.7(70)
Check how the relative humidity changes in a strange way on iOS. Then compare it with Android.

https://user-images.githubusercontent.com/50437378/119362892-67c6bb80-bcd7-11eb-9032-fa92f5a722b4.mov


https://user-images.githubusercontent.com/50437378/119362946-78773180-bcd7-11eb-87c2-4d71d6fbff30.mp4

**Comment by markoaamunkajo** [comment]
QA passed
