### ISSUE TITLE
Prototyping for UUID and C5 Firmware

### ISSUE THREAD

**Issue by priyonto** [ruuvi/com.ruuvi.station.ios#2151]

**Comment by markoaamunkajo** [comment]
Charts issue fixed.

**Comment by markoaamunkajo** [comment]
Running tests over the weekend

**Comment by markoaamunkajo** [comment]
@priyonto there are duplicates in CSV files, this test was done with 1 minute background interval.

[Ruuvi 97CB_20240924T83712+0700.csv](https://github.com/user-attachments/files/17106882/Ruuvi.97CB_20240924T83712%2B0700.csv)
[Ruuvi 9259_20240924T83656+0700.csv](https://github.com/user-attachments/files/17106883/Ruuvi.9259_20240924T83656%2B0700.csv)
[Ruuvi 6D43_20240924T83635+0700.csv](https://github.com/user-attachments/files/17106884/Ruuvi.6D43_20240924T83635%2B0700.csv)

**Comment by priyonto** [comment]
@markoaamunkajo As per @ojousima Its a fw issue.

**Comment by markoaamunkajo** [comment]
Connected and non-connected test examples attached

[Ruuvi CB4B_20241014T100830+0700.csv](https://github.com/user-attachments/files/17358969/Ruuvi.CB4B_20241014T100830%2B0700.csv)
[Ruuvi CB4B_20241014T095737+0700.csv](https://github.com/user-attachments/files/17358968/Ruuvi.CB4B_20241014T095737%2B0700.csv)

**Comment by markoaamunkajo** [comment]
Moving this card to done.
