### ISSUE TITLE
Try to force claim 2.5.9 sensor in df5 and it causes multiple issues

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station.ios#2153]
Description:

User added 2.5.9 sensor running in df5 format

This caused numerous issues trying to claim and force claim sensor using both NFC and BT

![Image](https://github.com/user-attachments/assets/4bffcbe8-e8d3-459b-89cc-14e6d499aba5)
![Image](https://github.com/user-attachments/assets/9ba5532a-8d00-445e-8569-e00d7514d4fd)

https://github.com/user-attachments/assets/9899bb07-af8e-4324-a174-484b6a6b5359

**Comment by laurijamsa** [comment]
2.5.9 firmware supports dataformat 5 which is totally ok to add

**Comment by markoaamunkajo** [comment]
Could be old faulty sensor, will try to flash to newer sensor and see if it still exists

**Comment by markoaamunkajo** [comment]
Turns out, not faulty sensor. New B8 sensor flashed with 2.5.9 and df5, trying to force claim. Errors happen. Moving to check with dev.

https://github.com/user-attachments/assets/120dc306-6deb-404f-94f2-adcbf3352b82

**Comment by markoaamunkajo** [comment]
Possibly related to this issue @priyonto https://github.com/ruuvi/ruuvitag_fw/issues/139

**Comment by priyonto** [comment]
@markoaamunkajo I am not sure, could not test yet. But, looking at the video it seems App could not connect to the tag when entered into bootloader mode.

**Comment by markoaamunkajo** [comment]
I get error forbidden now, I saw the multiple errors once before.
This was discussed elsewhere and it is probably unfixable, since firmware related. Will just inform users to first update fw and then try again.
