### ISSUE TITLE
iPad fixes

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station.ios#2155]
Description:

Some things are not working correctly for Ruuvi Station iPad and some weird layout things.

![Image](https://github.com/user-attachments/assets/b1aacfcf-dbf6-4bea-9f42-f77bb7fcf615)
![Image](https://github.com/user-attachments/assets/94d56b4a-212e-4c39-a646-c53a28c8aac7)
![Image](https://github.com/user-attachments/assets/f02a1da5-3e29-449c-8322-cd171e0f70f5)

**Comment by markoaamunkajo** [comment]
The G still gets cut on the history view screen "ago"

![Image](https://github.com/user-attachments/assets/3c5c50fe-f052-4eed-8025-80b7dc1561f3)

**Comment by priyonto** [comment]
@markoaamunkajo I don't understand the issue on sign in screen? If you are thinking about the size of it, it was supposed to be like this I believe considering its a modal on iPhone too.

**Comment by markoaamunkajo** [comment]
This works for me, QA passed.
