### ISSUE TITLE
Graph summary line (min/max/avg) SOMETIMES gets overwritten - defect- 241012 1534

### ISSUE THREAD

**Issue by DG12** [ruuvi/com.ruuvi.station.ios#2172]
Graph summary line (min/max/avg) only on ADCE gets overwritten on 2,3,9 days !
It in temperature alert state. Only displaying Temperature. last update0,1,2,0,1,0
![Ruuvi_overwrite](https://github.com/user-attachments/assets/48709381-bb31-494a-9010-017621cf4f3e)

**Comment by markoaamunkajo** [comment]
Tried to reproduce this for a while, had no success with sensor being first in the cards, same name, alert active, same resolution.
Will try this again.

**Comment by markoaamunkajo** [comment]
Layout changes in upcoming version will fix this issue.
