### ISSUE TITLE
Unify last updated font size

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station.ios#2175]
Description:

Last updated font size is good on Dashboard card
Let's update font to same size elsewhere (history view, full card).

![Image](https://github.com/user-attachments/assets/ec41d079-a391-4c0a-8fb4-966aa285bf11)

Android card: https://github.com/ruuvi/com.ruuvi.station/issues/1335

**Comment by markoaamunkajo** [comment]
QA passed

**Comment by markoaamunkajo** [comment]
Sini-Maaria: it should be same size as "movements" text

**Comment by priyonto** [comment]
Updated at text size is correct. I have modified the low battery text and icon size as per comments from feedback.

**Comment by markoaamunkajo** [comment]
QA passed
