### ISSUE TITLE
Add support for new dataformat

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station.ios#2176]
Description:

Add support for new dataformat

**Comment by priyonto** [comment]
Background scanning support for the new fw is not added yet. It has dependency on the firmware side and awaiting fixes there.

**Comment by priyonto** [comment]
Known issue: Background scanning and pairing don't work now due to fw limitation. For similar reason local push notifications also doesn't work.

**Comment by markoaamunkajo** [comment]
All values checked updating on latest measurement / alert settings

**Comment by markoaamunkajo** [comment]
QA passed
