### ISSUE TITLE
Chart missing "latest" value - defect - 2412011902 + 2412072018

### ISSUE THREAD

**Issue by DG12** [ruuvi/com.ruuvi.station.ios#2201]
Fresh install. Many sensors set up from gateway.
Min,max,avg show but no latest on any sensor
![ruuvi-no-latest copy](https://github.com/user-attachments/assets/ce1bc28a-0a95-4238-9fab-c86dde039b63)
15 minutes later no better.
shutdown / restart no better.

**Comment by markoaamunkajo** [comment]
I have tried multiple different possibilities here and have not managed to reproduce this issue.

**Comment by DG12** [comment]
@markoaamunkajo Please post a chart from an iPhone.

**Comment by markoaamunkajo** [comment]
https://github.com/user-attachments/assets/d2340557-6093-4036-9398-f6f33a53ad37

Tested again with 2412072018, clean install, sign in, test themes, it will not happen for me.
@DG12 What device are you checking this with? Is it happening consistently to you?

**Comment by markoaamunkajo** [comment]
Still not able to reproduce this one.

**Comment by markoaamunkajo** [comment]
This must be related to some internal version, I haven't spotted it, so I will close this card and if it is seen again, will be happy to reopen and investigate.

**Comment by DG12** [comment]
looks OK now 2.13.0(2412121751)
