### ISSUE TITLE
chart highlights data points in orange - 2412021915 enquery

### ISSUE THREAD

**Issue by DG12** [ruuvi/com.ruuvi.station.ios#2206]
new "feature" ?
Area above and below data point graph and zero is filled in with "lightSeaGreen" (?)
![ruuviGraphHighlights](https://github.com/user-attachments/assets/c2c816e4-8e0a-4756-a457-397f03a7de3d)

**Comment by markoaamunkajo** [comment]
@DG12 yes this feature is not yet in production, alert range would be filled with colour if it worked. Now it doesn't work and it's known issue. Closing this as it's double.
