### ISSUE TITLE
Crash in Charts: AxisRendererBase.swift - Line 119

### ISSUE THREAD

**Issue by rinat-enikeev** [ruuvi/com.ruuvi.station.ios#221]
See steps to reproduce (requires coding) here: https://github.com/danielgindi/Charts/issues/4028#issuecomment-714592659

**Comment by rinat-enikeev** [comment]
STR: 
1. enable downsampling 
2. start furiously tapping on charts icon

**Comment by rinat-enikeev** [comment]
0.6.3(4)

**Comment by markoaamunkajo** [comment]
QA passed
