### ISSUE TITLE
0.6.3(2) Alert notifications spitting out constantly when in bg

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station.ios#227]
Description:

User set alerts, went to mute couple of alerts from notification center and left app running in background

User has clean install of 0.6.3(2) from TF, single RuuviTag and 1 virtual tag

Settings
Foreground
Save advertisements 5 mins
Load and save from web Every 20 mins

Background
Data logging interval Every 5 mins
Read RSSI Every 10 secs

Alerts are activated as follows

RuuviTag:
Temperature C
Dew Point C
Air Pressure (hPa) (set to mute for 1 hour)

Virtual Tag
Temperature C (set to mute for 1 hour)
Dew Point C

**Comment by markoaamunkajo** [comment]
Removed all set alerts and tested with 1 alert, connected tag, temperature C, looks like I get alert in notification center roughly every 20 seconds

**Comment by rinat-enikeev** [comment]
@markoaamunkajo on iOS we can't keep notification inside Notification Center same way as Android does. 

That's why I've decided to make 15 seconds interval (configurable in Defaults with name "Alerts Interval"). 

If you mute the alert for 1 hour - it will be muted for 1 hour. If not - it will trigger every 15 seconds. 

If you have suggestions about different UX - please share :)

**Comment by markoaamunkajo** [comment]
I would love to see a longer interval (btw I cannot access Defaults menu) for the build release that's all. Is there a some sort of maximum limit we can adjust the notification to or could we give user ability to set the time?

**Comment by rinat-enikeev** [comment]
I've set alerts interval to 30 seconds by default. 

If we want to add it to settings, we can do it together with https://github.com/ruuvi/com.ruuvi.station.ios/issues/229.

**Comment by rinat-enikeev** [comment]
0.6.3(4)

**Comment by markoaamunkajo** [comment]
Discussed in meeting, we will use background -> data logging interval in App Settings since it makes sense also for user point of view and no need to provide another set of controls in the app.

**Comment by markoaamunkajo** [comment]
QA passed
