### ISSUE TITLE
0.7(21) Use decimal separator based on system locale #163 -Regression error 

### ISSUE THREAD

**Issue by DG12** [ruuvi/com.ruuvi.station.ios#232]
0.6.3(6) ok . I am confused about versions. 
This morning I had 0.7(21). Checked TestFlight it has 0.6.3(6) French also
This had been fixed Jan 12 with version 0.6.2(2) .
See #163 see also See issue #134 and #138

**Comment by DG12** [comment]
Looks fixed in version 0.7(22)

**Comment by markoaamunkajo** [comment]
Export service don't use number formatter, otherwise all good, moving to done
