### ISSUE TITLE
Show an icon depending on where the most recent data came from

### ISSUE THREAD

**Issue by laurijamsa** [ruuvi/com.ruuvi.station.ios#236]
Option 1: Via Ruuvi Gateway

Option 2: Bluetooth (broadcast)

Option 3: Bluetooth (connected, currently available only on iOS)

Option 4: From OpenWeatherMap (Virtual sensors, currently available only on iOS)

![image](https://user-images.githubusercontent.com/1311912/114691985-6900e200-9d42-11eb-8302-42050652b7f8.png)

Icons are attached on the ZIP file. Use 50% transparency on the icons. Align to right (same as the text).

[icons.zip](https://github.com/ruuvi/com.ruuvi.station/files/6310004/icons.zip)

**Comment by markoaamunkajo** [comment]
0.7(70) It seems that the gateway icon shows only once in the app. If I minimise app and try to sync I no longer see gateway icon, so I am unaware where the data comes from.

**Comment by rinat-enikeev** [comment]
Hey Marko! Here are the steps to show the Gateway icon: 

Preconditions: the tag is in range, also sending data to network. 

1. Enable bluetooth
2. Open app
3. See an advertisement icon 
4. Disable bluetooth (on the iPhone)
5. Wait until Gateway sends data to network (approx 2 minutes)
6. Synchronize manually

Expected and actual: you can see the gateway icon. 

Alt: go outdoors and sync :) You should see gateway icon if and only if the `record date` received from Network is more recent than the record received via Bluetooth. 

https://user-images.githubusercontent.com/722716/119623645-d2840e00-be21-11eb-84ed-71e0ef8e4bd4.MP4

**Comment by markoaamunkajo** [comment]
OK I see. It can be a bit confusing sometimes due to the sync saying it's synchronized although new data wasn't collected. But ok it seems to work as explained. Moving to done.
