### ISSUE TITLE
Show experimental features by shake device

### ISSUE THREAD

**Issue by viikufa** [ruuvi/com.ruuvi.station.ios#242]

**Comment by markoaamunkajo** [comment]
Made clean install 0.7(21) and it signed me into network, imported my network tags, all without showing network feature in menu. Also I shake device just once to bring the experimental features, it should require shaking multiple times, it's too easy for user to get this shown by accident.

**Comment by markoaamunkajo** [comment]
New solution in 0.7(62) moving to done.
