### ISSUE TITLE
About/help page various issues - 0.7(22) - cosmetic

### ISSUE THREAD

**Issue by DG12** [ruuvi/com.ruuvi.station.ios#243]
OPERATIONS MANUAL link at the end of the paragraph incorrectly go to ruuvi.com/support
TROUBLESHOOTING  link at the end of the paragraph incorrectly go to ruuvi.com/support
Get More Sensors should link to. https://ruuvi.com/ruuvitag#ruuvitag

MORE TO READ should be spaced farther apart as it is currently difficult to select one of the 4 links.

Information at the bottom needs update i.e. it currently presents:
About. tagsCount.text
About.MeasurmentsCount.text
About.DatabaseSize.text

**Comment by rinat-enikeev** [comment]
could you please submit feedback on https://feedback.ruuvi.com and we will vote for it.
