### ISSUE TITLE
App settings:Choosing alternate language can be very difficult to correct - 0.7(22) - user error (?)

### ISSUE THREAD

**Issue by DG12** [ruuvi/com.ruuvi.station.ios#244]
I thought the language setting was based on the global iPhone setting.

Just for fun (not) I changed language in the app to Russian (I think).
Now I wish I knew how to spell language in Russian!

OK so don't do that!

**Comment by rinat-enikeev** [comment]
Language is "Язык" in Russian :) It's a common UX pattern. Closing for now.
