### ISSUE TITLE
App Settings ; choosing other than English  has some English - 0.7(73) - minor defect

### ISSUE THREAD

**Issue by DG12** [ruuvi/com.ruuvi.station.ios#245]
Minor for me, I don't even speak French.

**Comment by DG12** [comment]
Unite de temperature
Celsius, Fahrenheit, Kelvin ??

Unite de pression
is hectopascal 
SB hehtopascal (as per google translate anyway)

Parametres avances
CHARTS

Parametres d usine
Alerts Mute interval

Of course brings up safari with English web page.

**Comment by rinat-enikeev** [comment]
it's task about checking the localisations. I believe we have reviewed them recently, closing for now. The texts are here. 

Please feel free to open a Pull Request to the localisation repo: https://github.com/ruuvi/station.localization/tree/dev
