### ISSUE TITLE
Virtual Sensor : Language switch to Pусский, back to another, sensor name  stays Pусский - 0.7(22) -  minor defect

### ISSUE THREAD

**Issue by DG12** [ruuvi/com.ruuvi.station.ios#250]
On the virtual sensor page,
Once the user switchs language to русский (i.e. Russian) the  sensor name stays in Russian even after
switching back to another language.

Ok don't do that! :-)

**Comment by rinat-enikeev** [comment]
the `names` of the sensor are not localised. The app can be localised, but not names.
