### ISSUE TITLE
chart/history : graph shows less data than export - 0.7(22) - defect

### ISSUE THREAD

**Issue by DG12** [ruuvi/com.ruuvi.station.ios#252]
After 19 hours (iPhone off or out of range part of the time) export shows 10 samples but chart/graph appears to show less. 
Timestamps from CSV:
04-20 17:27
04-20 17:29
04-20 18:41
04-20 18:46
04-20 18:51
04-21 12:06
04-21 12:11
04-21 12:16
04-21 12:21
04-21 12:26

![image](https://user-images.githubusercontent.com/2365961/115590648-35bcd680-a29f-11eb-89a2-04c0bf0acff9.png)

**Comment by laurijamsa** [comment]
Closing. Please reopen if you can still reproduce with the latest testflight build.
