### ISSUE TITLE
Replace signal strength with movement counter and vice versa

### ISSUE THREAD

**Issue by laurijamsa** [ruuvi/com.ruuvi.station.ios#254]
Let's bring the movement counter info on the card view. Move the signal strength info to under More Info section on sensor settings view.

One reason we delayed creating issue about this swap is that the movement counter rolls over to 0 after it has reached 255 and this may confuse users. And for this reason we're planning to introduce informational popup tip boxes when user taps any of the variables (temperature, humidity, pressure, movement) on the card view. But we'll have a separate issue task about that.

Find icon for the movement counter attached:

[movement_icons.zip](https://github.com/ruuvi/com.ruuvi.station.ios/files/6395808/movement_icons.zip)

**Comment by markoaamunkajo** [comment]
QA passed
