### ISSUE TITLE
No graph available for active RuuviTag - 0.7(57) - defect

### ISSUE THREAD

**Issue by DG12** [ruuvi/com.ruuvi.station.ios#259]
No graph and not upload icon either.

![E4CE updating no graph](https://user-images.githubusercontent.com/2365961/117841396-06203f00-b24b-11eb-89fd-57219c7f4f1a.jpeg)

**Comment by rinat-enikeev** [comment]
What do you mean by `active` RuuviTag? If the firmware is not connectable (version is less than 3), the chart button isn't shown.

**Comment by DG12** [comment]
An active RuuviTaf is one that was seen 2 s ago as per screenshot
😕

**Comment by rinat-enikeev** [comment]
Let's show the Graph button but show an alert "Upgrade firmware" to see the charts.

**Comment by DG12** [comment]
This is a "bluetooth only" RuuviTag as it is not owned.
Charting should be available from advertisments received since RuuviStationIOS was started.

**Comment by DG12** [comment]
![d18b_Androis_withGraph](https://user-images.githubusercontent.com/2365961/124392062-acc01380-dcc1-11eb-9b63-209215816eb2.png)
![d18b_Androis_withGraph](https://user-images.githubusercontent.com/2365961/124392064-b0ec3100-dcc1-11eb-82d5-b8cc25678a49.png)

**Comment by laurijamsa** [comment]
I believe this is already fixed in the latest build and we're showing the graph icon even if sensor is not advertising as a connectable one. If not, please reopen.
