### ISSUE TITLE
Exported CSV filename replaces colon with slash - 0.7(58) - defect

### ISSUE THREAD

**Issue by DG12** [ruuvi/com.ruuvi.station.ios#268]
When exporting RuuviTag named E9:38:3F...  file is named E9/38/3F...

I don't know how a RuuviTag got named by its MAC ?

Other tag named Ruuvi EC:0F is exported by name Ruuvi EC/0F-210513-1310.

It would be nice if spaces were replaced with underscores.

**Comment by rinat-enikeev** [comment]
should be fixed in https://github.com/ruuvi/com.ruuvi.station.ios/issues/253
