### ISSUE TITLE
RuuviTagHeartbeatDaemon: Cannot detect new RuuviTag added

### ISSUE THREAD

**Issue by mobilegurudevelopment** [ruuvi/com.ruuvi.station.ios#276]
Step to reproduce:
1. Clean install new app.
2. Add new RuuviTag.
3. `RuuviTagHeartbeatDaemon` can detect new RuuviTag added, 
Actual Result: observe function to `ruuviTagReactor` is not called.
Expected Result: observe function to `ruuviTagReactor` is called.

Note: this issue happens sometime on my device (iPhone 8 Plus, OS 14.5), tried 10 times, got this issue 2 times

**Comment by DG12** [comment]
What's a heartbeat daemon?

**Comment by mobilegurudevelopment** [comment]
> What's a heartbeat daemon?

It's background worker that listen RuuviTag data, insert to db and update Alert

**Comment by rinat-enikeev** [comment]
@mobilegurudevelopment could you reproduce it in `Release` mode? I think it is related to `Debug` mode.

**Comment by rinat-enikeev** [comment]
Please feel free to reopen if still a problem
