### ISSUE TITLE
minor "improvements" to Tag Settings detail screen

### ISSUE THREAD

**Issue by DG12** [ruuvi/com.ruuvi.station.ios#28]
The symbol at the top left "V"( like down),  seems to want to be a "<" (like back)

In an effort to expose additional fields without needing to swipe up,
The "NAME" band seems redundant and unnecessary.
The "MORE INFORMATION" band seems redundant and unnecessary.
The "CALIBRATION" and "Humidity" band (which I totally object to anyway) could be 
changed to "CALIBRATE HUMIDITY"
Reduce that space between to "REMOVE THIS RUUVITAG" and the bottom of the screen.

IMHO "DataFormat" and "TX power" is the least interesting (and most static) and might be better as the last items.

Perhaps acceleration X,Y Z (in degrees) might fit all on one line (when held portrait)

Movement sequence number might include a thousands separator

**Comment by rinat-enikeev** [comment]
Good proposal, but we decided not to change the UI for now.
