### ISSUE TITLE
Currently not possible to rename or delete Network sensor if you offline

### ISSUE THREAD

**Issue by andreevdenis** [ruuvi/com.ruuvi.station.ios#285]
Task in Android: https://github.com/ruuvi/com.ruuvi.station/issues/346

We can do without internet connection and be sure that it will be synced to Network when internet will be available these actions:
rename sensor
change sensor background
delete sensor (unclaim will be performed)
update offset for sensor
change application settings

These actions NEED internet connection at the time of perform:
claim sensor
share sensor

**Comment by markoaamunkajo** [comment]
0.7(76) Delete sensor in airplane mode and sync with network is not working as expected.


Uploading Delete_sensor.mov…

**Comment by markoaamunkajo** [comment]
It could be also possible that adjusting temp units, humidity units and pressure units and syncing them might not be working. In my test I have 1 network sensor, I go to airplane mode, change units, disable airplane mode, sync, delete app and reinstall app. When network data is synced and sensor card is created it shows "-" for all values.

**Comment by rinat-enikeev** [comment]
> It could be also possible that adjusting temp units, humidity units and pressure units and syncing them might not be working. In my test I have 1 network sensor, I go to airplane mode, change units, disable airplane mode, sync, delete app and reinstall app. When network data is synced and sensor card is created it shows "-" for all values. When I wait and resync network my sensor data is downloaded, but App units will not change.

for settings and offset calibration sync with cloud there are separate tasks https://github.com/ruuvi/com.ruuvi.station.ios/issues/284 https://github.com/ruuvi/com.ruuvi.station.ios/issues/286 that are not implemented yet

**Comment by markoaamunkajo** [comment]
QA passed
