### ISSUE TITLE
Save application settings to Network

### ISSUE THREAD

**Issue by andreevdenis** [ruuvi/com.ruuvi.station.ios#286]
We have different settings in Android and iOS, but at least for temperature/pressure/humidity units we should use same names and values

**Comment by andreevdenis** [comment]
What I save from Android side:

BACKGROUND_SCAN_MODE
BACKGROUND_SCAN_INTERVAL
UNIT_TEMPERATURE (C, F, K)
UNIT_HUMIDITY (0 - Relative, 1 - Absolute, 2 - Dew point)
UNIT_PRESSURE (0 - Pa, 1 - hPa, 2 - mmHg, 3 - inHg)
DASHBOARD_ENABLED (true/false)
CHART_SHOW_ALL_POINTS (true/false)
CHART_DRAW_DOTS (true/false)
CHART_VIEW_PERIOD (Int - days)

At this point we can change something here if you don't like naming or used values @rinat-enikeev

**Comment by rinat-enikeev** [comment]
I did only Temperature / Humidity / Pressure units. I think other settings should be per-device.

**Comment by markoaamunkajo** [comment]
QA passed
