### ISSUE TITLE
Eliminate previous version of humidity calibration

### ISSUE THREAD

**Issue by rinat-enikeev** [ruuvi/com.ruuvi.station.ios#293]
By migrating offset from UserDefaults to SQLIte.

**Comment by rinat-enikeev** [comment]
@markoaamunkajo please review the migration process (calibrate with previous build and mechanism, and update the app). 

Users who did the Salt calibration must have the offset migrated.

**Comment by markoaamunkajo** [comment]
Migration tested and passed QA
