### ISSUE TITLE
After waking up, incorrectly complains bluetooth not enabled 

### ISSUE THREAD

**Issue by DG12** [ruuvi/com.ruuvi.station.ios#3]
On some occasions when waking up the iPhone from sleep, station reports Bluetooth is not enabled.
Clicking OK and updates continue.

**Comment by io53** [comment]
Do you know if bluetooth actually is disabled or does the app falsely report that?

**Comment by DG12** [comment]
I pretty sure that it was incorrectly reported.
I haven't see this lately.

**Comment by rinat-enikeev** [comment]
@DG12 shall we close this issue?

**Comment by DG12** [comment]
I can no longer reproduce this issue, consider it fixed.
