### ISSUE TITLE
Sensor out of range for xxx days now report N/A

### ISSUE THREAD

**Issue by DG12** [ruuvi/com.ruuvi.station.ios#30]
Pervious version retained and displayed sensors even if no data had been received for a long time. 

This was useful in understanding when remotely placed sensors were last visited.

Please revert to the previous operation.

**Comment by rinat-enikeev** [comment]
Do you mean "show last known value"? It will be shown, just let the app remember the last value. And yes, the db schema was changed, that's why after install you don't see values from previous version. This also was done to avoid charts with gaps.

**Comment by DG12** [comment]
Remove and Add new sensor may be necessary.
