### ISSUE TITLE
0.7(70) Background image from gallery doesn't update to sensor settings view

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station.ios#303]
Description:

IPhone 7, iOS 14.5.1

User Installed 0.7(70) and signed into network, one network sensor was synchronised and card created. He then goes to sensor settings and picks a background  image from gallery.

Actual:
Image is not showing in sensor settings view. When settings is closed the image shows on sensor card and after opening sensor settings again the image is finally shown.

Also similar experience with local sensors. I even received error Sensor not found with local sensor.

Expected:
Show image on sensor settings after choosing.

https://user-images.githubusercontent.com/50437378/119359261-a35f8680-bcd3-11eb-9b75-a5bab05b9742.mov

**Comment by rinat-enikeev** [comment]
This should be fixed by adding "uploading indicator UX" to the upload an image feature.

**Comment by mobilegurudevelopment** [comment]
please add my email for testing: `successmichal@gmail.com`. I tried to login but get `Token is expired` on app and web
![image](https://user-images.githubusercontent.com/12468652/119438364-3935f880-bd4a-11eb-9794-bac69ce8dce7.png)

**Comment by markoaamunkajo** [comment]
0.7(76) Adding new local sensor and taking photo to upload as background image will show error: Sensor not found. After that the background image is updated to views but keeps uploading to sensor settings background area.

**Comment by markoaamunkajo** [comment]
https://user-images.githubusercontent.com/50437378/120200960-19716980-c24f-11eb-9a33-449ec2baa0a1.mov

**Comment by markoaamunkajo** [comment]
0.7(78) If user trying to change bg for network sensor (also choose from default bg) in airplane mode it will not be successful.

https://user-images.githubusercontent.com/50437378/120308480-58aac380-c2fe-11eb-92df-857caeeaec74.MP4

**Comment by markoaamunkajo** [comment]
0.7(80)

Two bugs left:
1. When user uploads photo to bg from camera to network tag the Sensor settings view keeps the upload percentage. User can make it go away by tapping on image area.
2. User trying to replace background image from default images doesn't change it to sensor card view. User can make it refresh new image by killing app and returning to view.

Examples in attached videos:

Uploading RPReplay_Final1622778126.mov…



https://user-images.githubusercontent.com/50437378/120743050-6c367400-c522-11eb-98b4-f308e7205b66.mov

**Comment by rinat-enikeev** [comment]
@andreevdenis is it correct that we are not storing `default` background index on the cloud?

**Comment by andreevdenis** [comment]
Yes, it is correct

**Comment by rinat-enikeev** [comment]
> 1. When user uploads photo to bg from camera to network tag the Sensor settings view keeps the upload percentage. User can make it go away by tapping on image area.

This is done intentionally. Consider user started uploading image and killed the app during the process (low internet connection speed). If open app after that - the change BG buttons will be unavailable forever. So I've added `clear progress` feature. 

> 2. User trying to replace background image from default images doesn't change it to sensor card view. User can make it refresh new image by killing app and returning to view.

This is a nice catch! Fixed

> Btw I also see that the default bg image that was swapped on iPhone is not reflected on Android. Tried installing both apps and resync with network they have different background images. I'm assuming this is because of iOS version.

We are not storing `default` backgrounds in the Cloud. If you want it to be done, please let us know :)

**Comment by markoaamunkajo** [comment]
1. OK agreed on the solution
2. QA passed

Default backgrounds are ok, just didn't know about it.Looks like if I clear bg to default I can keep it photo on iOS if I like and it will not sync unless I will upload an image on Android or new image on iOS.
I call this card QA passed.
