### ISSUE TITLE
0.7(70) Sensor calibration data not synced to and from network

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station.ios#304]
Description:

User sets calibration settings for 2 sensors that are connected to network, then syncs network and after that uninstalls and reinstalls app.

Actual: Offset calibration is not downloaded from network.
Expected: Offset calibration should be synced to and from network.

**Comment by andreevdenis** [comment]
See task #284

**Comment by rinat-enikeev** [comment]
closing this (duplicate of #284)
