### ISSUE TITLE
0.7(70) Network syncing on Android and iOS devices - iOS couldn't update and lied about syncing

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station.ios#305]
Description:

User has Android 1.5.19 installed and network user signed in. Same user installs 0.7(70) to iPhone and signs in as same network user.

Network account has 2 network sensors. User syncs network on both devices. At some point iOS stops updating sensor card data although sync process completes as successful. This issue can only be resolved by killing app, on next opening network data was synced again normally.

**Comment by markoaamunkajo** [comment]
https://user-images.githubusercontent.com/50437378/119367957-add24e00-bcdc-11eb-8f43-075c8b4dcc4e.mov

**Comment by markoaamunkajo** [comment]
0.7(73)I thought I had it working for a while, even saw the gateway sync icon and everything. But after restarting app it now seems to do the same thing and gateway icon is also lost. Not sure if there is a limitation to how many times network data can be synced. On my sensor settings page data source also shows network all the time although it clearly is getting data from local via bluetooth.

Sorry about long video, I hope it explains the experience better.


https://user-images.githubusercontent.com/50437378/119597313-f8ea7f00-be0a-11eb-9ef5-513b3cce74e9.mov

**Comment by rinat-enikeev** [comment]
The Tag Settings page is displaying the "Data received via" `Network` and this is the source of confusion. Will fix.

**Comment by rinat-enikeev** [comment]
Please check the following Test Case: 

1. bluetooth is off - sync via network and see gateway icon
2. check tag settings - `Network`
3. enable bluetooth - see `advertisement` on tag settings
4. connect and see `heartbeat` in tag settings

https://user-images.githubusercontent.com/722716/120162908-510df080-c212-11eb-9e8a-86f99ea91452.MP4

**Comment by markoaamunkajo** [comment]
QA passed
