### ISSUE TITLE
0.7(70) Network doesn't sync App Settings

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station.ios#306]
Description:

Android version syncs from and to network following (common with iOS) settings:
Background scanning settings (Scanning on/off, Data logging interval)
Temperature Unit
Humidity Unit
Pressure Unit

There are also other settings that Android is syncing from and to network, which could be worth discussion:
Chart settings (Display all data in chart, Draw dots in chart, Chart history view period)

**Comment by andreevdenis** [comment]
It's task #286

**Comment by rinat-enikeev** [comment]
closing (duplicate of #286)
