### ISSUE TITLE
export needs name in first row, format of time  minor improvement

### ISSUE THREAD

**Issue by DG12** [ruuvi/com.ruuvi.station.ios#31]
I think it would be nice if instead of the string "Date" (?) the data contained, in the header the name the tag.

date/time string is formatted for influxdb(?) 2019-11-17T17:31:56.303Z,
Would be better formatted as 2 fields without training Z for spread sheets accepting CSV;'s
 
More important than exporting temperature in 3 different scales and seems excessive, (But why not?)

**Comment by rinat-enikeev** [comment]
date time is ISO8601.

**Comment by DG12** [comment]
Oh I should have guessed something like that.

**Comment by rinat-enikeev** [comment]
@DG12 please check 0.4(37)

**Comment by DG12** [comment]
First row now contains tagName.
Thanks
