### ISSUE TITLE
GATT syncing progress status numbers - Unify with Android

### ISSUE THREAD

**Issue by DG12** [ruuvi/com.ruuvi.station.ios#317]
I suggested in Issue #143 
 Sync should report what it had and what it got - enhancement 0.6.1(18) #143

in addition, Please don't just say. Synchronizing. Instead report progress. for example:

- syncing 
- syncing connecting to mutteri
- syncing connected to mutteri
- syncing 1
- syncing 10
- syncing 100
- syncing 1000
- syncing 2000
- ...
- syncing disconnecting
- syncing disconnected 
- syncing complete 4321 events received    (wait for 5+ seconds for user to see

Although normally this stuff (except the last message) will just flash by,
it is very helpful when there is a problem especially if it is intermittent.

Maybe an  additional diagnostic card with LOG.DEBUG, LOG.INFO, LOG.WARNING, LOG.ERROR.
When customers are having problems this will be even more important and helpful.

This applies to GATT sync as well mutteri [ ruuvi cloud  :-)  ]

This applies to both android and IOS.

**Comment by markoaamunkajo** [comment]
1.1.0(280)

Let's fix minor inconsistencies @priyonto 

1. GATT Sync ending screen reports Disconnected before success message and it's on top of other items.
![IMG_8462](https://user-images.githubusercontent.com/50437378/162664618-91c552c4-f694-4a4d-bc38-4864f280e883.PNG)

2. On Android GATT sync fetches full data on first sync and then only adds new data on consecutive syncs. Full sync is only done when chart is cleared or empty.

**Comment by DG12** [comment]
Great.

Interesting starts blinding fast then at about 800, it goes into "chunk " mode, updating ever few seconds.
Continuing like that for several seconds then returns 'blinding fast" mode
878,,921, 966,990, 1005,1035, 1065,1101,1125,11145,1679........,,.,,,,.,.,.,complete

Ruuvi is .5 meters away
