### ISSUE TITLE
File name for export could be shorter - improvement 

### ISSUE THREAD

**Issue by DG12** [ruuvi/com.ruuvi.station.ios#32]
File name for export could be shorter like tagName-yymmdd-hhmm
Most significant units first,  cc unnecessary ,  ss also unnecessary

**Comment by rinat-enikeev** [comment]
@DG12 please check latest build

**Comment by DG12** [comment]
latest build 0.4(47)? created 
Garage 20BC_28-12-2019-17-05-04
Is that a change?

**Comment by rinat-enikeev** [comment]
@DG12 please check build 0.5(14) from TestFlight

**Comment by DG12** [comment]
Much better!  "tag name-yymmdd-hhmm"

Thanks
