### ISSUE TITLE
Alert , air pressure : minimum 300  is too low  - 0.7(73) - improvement

### ISSUE THREAD

**Issue by DG12** [ruuvi/com.ruuvi.station.ios#321]
Having a very low minimum makes it very difficult to set a lower/upper limit

"The lowest non-tornadic atmospheric pressure ever measured was 870 hPa (0.858 atm; 25.69 inHg), set on 12 October 1979, during Typhoon Tip in the western Pacific Ocean."

Not sure that an alert on air pressure limit is useful anyway!

**Comment by rinat-enikeev** [comment]
in the future we will improve the UX and we will consider ways on how to do it better
