### ISSUE TITLE
Alert notification automatically disappears too soon - 0.7(73) - defect

### ISSUE THREAD

**Issue by DG12** [ruuvi/com.ruuvi.station.ios#323]
When an alert is triggered a  notification is triggered. 
By the time the user picks up their iPhone it has already disappeared.
 
If there are multiple alerts that have triggered it seems that each pops up and then is replaced by the next one and  only the last one displayed remains for several seconds.
Consider a sensor array of 10 sensors, perhaps several of them exceed the temperature limit at various times and the user's phone is off or out o range.

Can the notification require that the user clear it manually?

**Comment by rinat-enikeev** [comment]
no it's system behaviour
