### ISSUE TITLE
Sensor receiving Bluetooth advertisements cannot set alerts - 0.7(73) - defect

### ISSUE THREAD

**Issue by DG12** [ruuvi/com.ruuvi.station.ios#326]
Attempting to set an alert to a sensor which is advertising packets displays:

> Alerts are disabled 
> because you are not
> connected to the device.

Should be able to set alerts on unconnected sensor.

**Comment by rinat-enikeev** [comment]
its just not possible on iOS (no way to listen in background without connection)
