### ISSUE TITLE
virtual sensor picked from map "not a place" indicates "Location Your location" - 0.7(73) - minor defect

### ISSUE THREAD

**Issue by DG12** [ruuvi/com.ruuvi.station.ios#327]
If a location is chosen which is not identified   name displayed "PICK FROM THE MAP" and Virtual sensor settings Location displays "Your Location"

<img width="677" alt="PickFromMap_yourLocation" src="https://user-images.githubusercontent.com/2365961/120078767-19227400-c07f-11eb-82d2-3a4287184b14.png">

**Comment by laurijamsa** [comment]
Closing as we've plans of not deprecating the virtual sensor feature later in the future and not making it better than it's already.
