### ISSUE TITLE
virtual sensor picked from map indicates alarms silenced - 0.7(73) - minor 

### ISSUE THREAD

**Issue by DG12** [ruuvi/com.ruuvi.station.ios#328]
Picking a virtual sensor for the map displays alert (bell) 
<img width="778" alt="PickedFromMap_indicatesSilencedAlert" src="https://user-images.githubusercontent.com/2365961/120079232-f5602d80-c080-11eb-81de-65b21cfb9c4e.png">

**Comment by rinat-enikeev** [comment]
it's expected icon. we have 3 states - for `not set`, `set` and `firing`. This is `not set`
