### ISSUE TITLE
Make Tag Settings same as on Android

### ISSUE THREAD

**Issue by rinat-enikeev** [ruuvi/com.ruuvi.station.ios#334]
![photo_2021-05-31 13 49 06](https://user-images.githubusercontent.com/722716/120167382-1bb7d180-c217-11eb-8ac9-39557fdf39da.jpeg)

Keep `Data Received Via` 
Remove `Movement Counter` 
Put `RSSI` to bottom

**Comment by markoaamunkajo** [comment]
QA passed
