### ISSUE TITLE
Can be done with one-liner via contains

### ISSUE THREAD

**Issue by YaMirok** [ruuvi/com.ruuvi.station.ios#34]
![snapshot](https://user-images.githubusercontent.com/11839694/70215407-3a8ef200-175f-11ea-946c-c6f92bbd2131.png)

return AlertType.allCases.contains(where: { isOn(type: $0, for: uuid) } )

**Comment by rinat-enikeev** [comment]
done https://github.com/ruuvi/com.ruuvi.station.ios/commit/f4f0dbc13d3c484c74ebdd951244f3a1973ba5dc
