### ISSUE TITLE
Cloud management functions: suspend/reactivate & delete 

### ISSUE THREAD

**Issue by DG12** [ruuvi/com.ruuvi.station.ios#344]
There needs to be a means to delete a tag that is lost, broken etc.

There needs to be a means to suspend a tag (in particular related to subscription plan).
Scenario is I have 10 active(max free subscription). I deploy 3 to the field i.e. out of range. 
I buy 3 more. I retrieve 1 from the field and suspend  (at least 1) etc, etc

See also network-serverless issue #85.

**Comment by rinat-enikeev** [comment]
deleting the tag from app will open a slot for you
