### ISSUE TITLE
tag not seen recently has "bad" history - 0.7(78)

### ISSUE THREAD

**Issue by DG12** [ruuvi/com.ruuvi.station.ios#347]
I wish I could provide more information on how this happened but...

Selected this tag at 11:14  06/01 choose chart, no x-axis label; y-axis is very "odd", i.e.for
temperature max at 66.6000714 , min 66.6000704;
humidity max 35.5001428 min 35.5001408;
air pressure 994.1622180,994.1622150

Switch to overview(?) card shows last update 'Mon May 24 2021 13:26:53' (May be correct)
No icon for update by gateway or bluetooth.

switch back to chart view looks "reasonable" however shows x-axis min is 2:00PM 05/22.

Export contains 4,590 entries firs entry from 05-20 14:17, last from 05-24 13:26.

gateway history (curl  http://192.168.1.63/history ) does not include this tag 
gateway metrics (curl  http://192.168.1.63/metrics) show up time_us uptime_us 318770019076 WHENEVER that was! 

<img width="1170" alt="06DC_badHistory" src="https://user-images.githubusercontent.com/2365961/120354227-444fd200-c2d0-11eb-99e2-60fd3b38c0c4.png">

Serverless /get returns:
{
    "result": "success",
    "data": {
        "sensor": "D0:FD:6D:65:06:DC",
        "name": "Ruuvi_06DC",
        "offsetTemperature": 0,
        "offsetHumidity": 0,
        "offsetPressure": 0,
        "measurements": [
            {
                "coordinates": "N/A",
                "data": "0201041BFF99040511615022C789009CFFD403E08836153EB3D0FD6D6506DC",
                "gwmac": "24:0A:C4:E2:D8:28",
                "timestamp": 1621869796,
                "rssi": -83
            },
            {
                "coordinates": "N/A",
                "data": "0201041BFF990405100F5018C79200CC007803C48756103E7AD0FD6D6506DC",
                "gwmac": "24:0A:C4:E2:D8:28",
                "timestamp": 1621869722,
                "rssi": -56
            },
following entries coordinates N/A and gwmac deleted and edited for brevity

data: ...0FFC4C49C79C0030001003FC87560F3E41..., timestamp: 1621869649, rssi: -72
 data: ...0FFC4C49C79B002C001803F387560F3E06..., timestamp: 1621869574, rssi: -82
 data: ...0FFB4C4DC79F0030001403FC86D60F3DCE..., timestamp: 1621869502, rssi: -70
 data: ...0FFC4C45C7990028001803F887B60F3D95..., timestamp: 1621869428, rssi: -70
 data: ...0FFC4C49C7960030001403FC88360F3D5C..., timestamp: 1621869355, rssi: -70
 data: ...0FFD4C45C793002C001803EB87560F3D22..., timestamp: 1621869281, rssi: -70
 data: ...0FFD4C4BC78F002C001403F887560F3CE4..., timestamp: 1621869201, rssi: -70
 data: ...0FFD4C45C792002C001803F887B60F3CB0..., timestamp: 1621869134, rssi: -70
 data: ...0FFE4C41C7920038001403F888360F3C77..., timestamp: 1621869061, rssi: -70
 data: ...0FFE4C3CC7910030001403F387B60F3C3E..., timestamp: 1621868987, rssi: -69
 data: ...0FFE4C41C7980030001003F888360F3C04..., timestamp: 1621868914, rssi: -70
 data: ...0FFF4C3FC7950030001403F888360F3BCB..., timestamp: 1621868840, rssi: -70
 data: ...0FFE4C3CC79400280014040087560F3B91..., timestamp: 1621868765, rssi: -71
        ],
        "total": 15,
        "public": 0,
        "table": "prod-SensorDataReduced",
        "resolvedMode": "sparse"
    }
}

**Comment by rinat-enikeev** [comment]
I need more information, let's discuss

**Comment by DG12** [comment]
I haven't seen this in. a while.
