### ISSUE TITLE
0.7(86) Network sync error in FI language popup (airplane mode)

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station.ios#368]
Description:

FI language user is shown error when trying network sync, popup says "Virhe Unknown error."

Expected: "Virhe Tuntematon virhe."

![IMG_5695](https://user-images.githubusercontent.com/50437378/120802079-34ecb500-c56c-11eb-97e7-863946c814f2.PNG)

**Comment by rinat-enikeev** [comment]
this guy is somewhere deeply from iOS or dependencies. Can't reproduce reproduce and fix...

**Comment by markoaamunkajo** [comment]
I'm always happy to find one of these <3 Ok ignoring
