### ISSUE TITLE
You could use NSURLComponents with query items for beauty and reliability. 

### ISSUE THREAD

**Issue by YaMirok** [ruuvi/com.ruuvi.station.ios#37]
![snapshot](https://user-images.githubusercontent.com/11839694/70215759-fea85c80-175f-11ea-8102-5b1656fdd3de.png)

**Comment by rinat-enikeev** [comment]
done in https://github.com/ruuvi/com.ruuvi.station.ios/commit/b564bfa2d8c8ee9462da9c599eb24061c68c5c0f
