### ISSUE TITLE
add card with delta movements - feature request

### ISSUE THREAD

**Issue by DG12** [ruuvi/com.ruuvi.station.ios#370]
It would be helpful if the movement delta, i.e. change from previous, was presented on a graph.
something like:
<pre style=font-family:monospace>
         ,            |
----'--'-'---'------- '-------
      11:00  12:00. 13:00
      06/04.   06/04 06/04</pre>
(It's really hard to show example because of variable width font)

data was 
124,124,124,128,128,128,130,130,130,130,160,160,160,160,160,170,170,170,170,170,170,172,173,173,173,174,180,181,182
Beware of change from LargeNumber to SmallNumber should display positive(( ( 255-LargeNumber ) + smallNumber ))

**Comment by rinat-enikeev** [comment]
@laurijamsa it's a good UX of showing the movement spikes on charts. Do we want this UX?

**Comment by laurijamsa** [comment]
Movement counter values are not currently saved to RuuviTag's internal memory, so this feature wouldn't work for users without Ruuvi Gateway and cloud. However, we do have plans to store movement counter values in the future. Closing this issue for now.
