### ISSUE TITLE
restoring background image must timeout - 0.7(86) - defect

### ISSUE THREAD

**Issue by DG12** [ruuvi/com.ruuvi.station.ios#371]
With no or intermittent cell service, downloading the background image can get stuck A timeout for the entire down load (not just a image packet) should be implemented.
 
I suggest station send small checksum(or date) of current background image for cloud to compare and cloud could report "not-modified" rather that download the image.

**Comment by rinat-enikeev** [comment]
is it downloading the image on every sync? Shouldn't, I'm storing the cache with URL as a key

**Comment by andreevdenis** [comment]
Same in Android: I only compare URL on every sync.

**Comment by DG12** [comment]
I don't know how often. Today I was in the swamp (more on that in next issue) and IOS kept "spinning" one background image in sensor settings.  In fact it's still spinning now.  
Killed/ restarted , still spinning .
 with wifi connection

**Comment by rinat-enikeev** [comment]
you mean not downloading but uploading the image. 

Tap on it!

**Comment by DG12** [comment]
Image was set last week. Image displayed is same as set last week.
Shutdown phone , restart. Still spinning. 
Tapped  on it and it gave up.

**Comment by DG12** [comment]
Yuck. tapped on reload (?) circle  next to camera icon and scrolls through various default backgrounds.

**Comment by DG12** [comment]
Don't get too hung up on this, (I think) only change needs to be made is timeout.

**Comment by DG12** [comment]
PS camera icon "target area" for tapping could be bigger.

**Comment by markoaamunkajo** [comment]
Cannot replicate, closing
