### ISSUE TITLE
reduce size of background image file - enhancement

### ISSUE THREAD

**Issue by DG12** [ruuvi/com.ruuvi.station.ios#372]
When cell service is poor AND image on phone does not match cloud it may take a long time to down a large image.

The cloud should shrink-to-fit the image in the same way that the phone will which would significantly reduce image size.

Beware if user has multiple phones or any shared user

**Comment by rinat-enikeev** [comment]
we are cropping image to 1080p on iOS

**Comment by DG12** [comment]
Oops , check  out for iPad landscape orientation
New iPad has Retina display, 2048 x 1536 resolution

**Comment by rinat-enikeev** [comment]
UX designer would kill us for making images blurry...

**Comment by DG12** [comment]
For sure.
Closing for now
