### ISSUE TITLE
Sensor Settings: rearrange - 0.7(86) improvement 

### ISSUE THREAD

**Issue by DG12** [ruuvi/com.ruuvi.station.ios#373]
The sensor Settings  [[ Is this the best title with MORE INFO? Maybe addition details ?]],  
should have items arranged in (probably) the most interesting order. Especially since there are now quite a few items.
 The number of lines for a given item should also be reduced example "CONNECTION\keep connection\Disconnected" should take only 1 line. Space between lines could also be reduced to show as many items as possible  and still be able to tap on/off sliders when they are present.

**My** preference would be:

sensor name. [[ no need for heading NAME with only one item, maybe have name in heading with Sensor Settings]]

Signal strength(RSS)[[ interesting if you are looking for the tag]]
Acceleration X , Y, Z. -0.488, 0.912, 0.051  [[Acceleration could all be on 1 line ]]
Keep connection [[ no need for a separate line to should connected/disconnected use the same line
Data received Via 

Alerts
Connection  [[ there is enough room to keep the current status i.e. on/off on the same line. slide button already indicates this anyway]]
Movement
Temp
Hum
Air Pressure [[ really ? an alert for change in air pressure? Not sure what this might be useful for]]

Offset Corrections
Temp
Hum
Press

Background image

Battery Voltage
MAC
UUID  [[ not sure why this is even shown]]
tx power. [[ not sure why this is even shown]]
data format  [[ not sure why this is even shown]]

Then again there is a lot of room on the main card without getting too noisy, like for both movement and RSSI.

Your actual milage may vary ( Say what?). :-)

**Comment by rinat-enikeev** [comment]
we are drafting a new UI and we will consider this proposal
