### ISSUE TITLE
temperature offset : various - 0.7(86) - defect 

### ISSUE THREAD

**Issue by DG12** [ruuvi/com.ruuvi.station.ios#375]
Calibration
WOW!!  was 74.55F  enter temperature value expected [[ I like it]]
 Entered 75 
Corrected Value [[ Correction value?]]  167.00 F [[ should be **.45**  ]]  [[ Corrected value]] (92.45F) [[Should be 75.00]]

Inactive tag  still shows uncorrected value

Calibration tips are available on ruuvi.com/support [[ terrible color contrast]]

Link should not go to general support page but to a page explaining about temperature correction.

CALIBRATE . [[ is  'voorboden', should be correction]]

**Comment by rinat-enikeev** [comment]
this was fixed in latest build
