### ISSUE TITLE
humidity offset :  0.7(86) -  improvement

### ISSUE THREAD

**Issue by DG12** [ruuvi/com.ruuvi.station.ios#376]
Shows corrected value although nor correction offset was ever set.

was 75.61% entered 80

Corrected value 80.xx% [[well if you use show hundredths for a sensor that is +/- 2% OK]] "

There is also (5.62%) which needs "correction value/ factor"

User should not be permitted to enter out of range numbers for example 5000.

link to support should. be more specific, and link color contrast is poor.

word Calibrate verboten

**Comment by rinat-enikeev** [comment]
please check the latest build and if still relevant - reopen
