### ISSUE TITLE
New install (with existing tags ) issues - 0.7(88) - defects

### ISSUE THREAD

**Issue by DG12** [ruuvi/com.ruuvi.station.ios#379]
Before installing 0.7(88)
I deleted previous version.

Now, as expected, no tags are present .

Take note of (@) which flag errors
++++++++
E4:D5:6D:EC:6E:29 is advertising as seen by station android but not available to add.
++++++++
Ruuvi E4CE and
Ruuvi FB19 are available to be added.

quit app and restart now
======================
C4:D8:A4:A9:09:81 is present (although I did not add it) from gateway Mon May 31 2021 12:48:16 (@) Android displays 5/31/21  12:48 I like day-o-week, Mon dd hh:mm:ss best!, RSSI -, data received via network,  not named.
Replaced battery :-) 3.164 volts! , new background photo(upload took longer than I would have expected), named it Ruuvi_0981. now shows RSSI -43, data received via advertisement.
owner dgerman...  
Received  messages earlier including: henri@ruuvi.com removed shared sensor "C4:D8:A4:A9:09:81".
Revised app settings F, inHg
Tap chart: Seems like you are running connectable..."Keep Connection" although this sounds clear, except for the word **histograms** which charts are not (@) FixMe .
Choose keep connection 
chart appears showing data  from 05/28/2021 19:29:53 , 221 rows, through now at intervals of **15minutes and 43 seconds**  (@) what's that??
most recent entries are 1 minute 14 seconds apart ??
Tag heartbeat is ever second (Hmmm)
BLE  icon now sometimes overlaid by 3 dots. 

Alert icon indicates no alerts triggered i.e. includes diagonal (not).
++++++++ Following were not added 
C8:76:E5:96:B2:C3 is present with NO data, empty chart, export shows MAC with name replaced by  slash although exported file appears named with colons but is actually (@) poorly named with slashes instead. . Export contains only 2 header rows. owner dgerman...
++++++++
D6:F3:DA:DA:C8:5E similar to B2c# name preserved but no data
++++++++
D0:FD:6D:65:06:DC similar to B2C3 however it is named Ruuvi_06DC . set background image.
++++++++
DC:48:59:6E:D1:8B similar to B2C3 named RUUVID1:8B updating via advertisements BUT No Chart available (@) 
++++++++
E4:D5:6D:EC:6E:29  similar to B2C3 named Ruuvi 6E29
++++++++
D3:51:78:72:EC:0F named P:51:PL78:72:EC:0  (@) Really? , really!  data via Advertisement , RSSI -96, BLE icon has no dots updates very 2,3 seconds ( RSSI is -96 after all) 
Tap chart suggests keep connection , OK. export has data since 05/25/2021 15:47:42 through now, 1,596 rows
Sync sensor data now export has 2,619 rows ! between rows 1,193 and xxx 3 of 4 rows have no X-Y-Z as they are down loaded from sensor history(log) as expected.
Beginning 06/04/2021 15:59:56 (just a little while ago) 1 of 7 rows are from sensor history (@)??

+++++++++++++

Periodic Ruuvi icon (network connecting ?) is distracting, but not too bad. Perhaps a little too frequently.

++++++++

OK that was cool, after ALL THIS TIME, pick sensor from map, choose Houston, Texas, USA and cute little blue sliding finger appears.
++++++++
And another tag shows up. 
F2:C0:C6:43:AD:03 One from the before time in the Fridge which is only "seen" infrequently. RSSI -96
I'm sure there was a background image there it's gone now. set new image.
After several minutes no chart icon available (@).
++++++++
add pick from map, Tallinn 
++++++++
remove Houston (too hot there anyway)
++++++++
2 sensors still available to add!
E4CE
FB19 Gawk! tap FB19 and Tallinn shows up?  Swipe right to left and FB19 is there. RSSI -94 data format 4 ( Hmmm?) I'll have to go find that one and flash it. Shows 55.4F, 90.00% 28.47 inHg updating by advertisements every second 
++++++++
last one!!
E4CE tap it, correctly slides to new card, RSSI -77, movement 176, 67.75F,, 96.77% (WOW!) (@) no chart icon.  Now owned by dgerman... tap claim Sensor already claimed! oops.

 
Feel free to create a separate Issue for any one of these.

**Comment by rinat-enikeev** [comment]
don't forget to unify with android

**Comment by DG12** [comment]
Sorry too much junk in one issue. Perhaps I'll post separate issues if they are still a problem
