### ISSUE TITLE
Check on thread-safety

### ISSUE THREAD

**Issue by YaMirok** [ruuvi/com.ruuvi.station.ios#39]
Is it possible subscribing and notifying subscriber simultaneously?
Can it be done in a thread-safe manner? 
![Snapshot](https://user-images.githubusercontent.com/11839694/70216065-99a13680-1760-11ea-864b-42c47f239dc7.png)

**Comment by rinat-enikeev** [comment]
for the first question: you can subscribe and notify on any NSObject - see https://github.com/ruuvi/com.ruuvi.station.ios/blob/alerts/station/Classes/Presentation/Binding/NSObject%2BObservable.swift. 

For thread safety - it can be done later, atm it's not a priority.
