### ISSUE TITLE
0.7(94) Sharing sensor - validate email

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station.ios#396]
Description:

User has added sensor to Ruuvi Network and goes to Share sensor page in Sensor Settings, where he can share sensor to a friend by email address.

There is no friendly error if user fails to add valid email address. Example: marko@aamunkajo , markoaamunkajo.com

Expected:
Show error - Please check email address

**Comment by rinat-enikeev** [comment]
will do next week

**Comment by markoaamunkajo** [comment]
QA passed
