### ISSUE TITLE
Configuration option: tag timeout

### ISSUE THREAD

**Issue by DG12** [ruuvi/com.ruuvi.station.ios#4]
It would be a nice option to be able to specify a number of minutes, for which, if no data was received from a tag within that timeout period  the "updated CCYY-MM-DD hh:mm:ss +0000" is highlighted, as well as the values should be dimmed(grayed).

For example a tag is expected to be in range of the iPhone at least every 4 hours.

Note that since the "Bluetooth not enabled" is only presented once(?) at startup(?) ,
 if bluetooth gets turned off no updating will be done at all and although the updated message will indicate no updates it would be nice to have a "warning"

**Comment by rinat-enikeev** [comment]
Hey @DG12 ! Thanks for you proposal, if you understand iOS code and have a developer certificate - I can help you to build and run custom app with this feature on your device. But for regular users we don't think it is worth adding a lot of features. Apple ecosystem product must be simple :)
