### ISSUE TITLE
This can be merged with UIApplication+ViewController.swift topViewController logic. 

### ISSUE THREAD

**Issue by YaMirok** [ruuvi/com.ruuvi.station.ios#40]
![snapshot](https://user-images.githubusercontent.com/11839694/70216353-2b10a880-1761-11ea-99b5-5d8eb4d97d02.png)

**Comment by rinat-enikeev** [comment]
https://github.com/ruuvi/com.ruuvi.station.ios/commit/5365cfe5cf0b2d104cbbcb65097758ddcab73139
