### ISSUE TITLE
Remember translations for DFU

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station.ios#409]
Reminder to add translations for DFU

Sensor settings FIRMWARE - Update Firmware
Also when read FW update package I see some language

**Comment by markoaamunkajo** [comment]
Here are examples to look for:
![4](https://user-images.githubusercontent.com/50437378/121632366-12e2bd80-caab-11eb-8358-c675635a8908.jpg)
![3](https://user-images.githubusercontent.com/50437378/121632374-16764480-caab-11eb-97c9-4d0fcf696c9d.jpg)
![2](https://user-images.githubusercontent.com/50437378/121632377-170edb00-caab-11eb-8cb6-6de1f7617fa9.jpg)
![1](https://user-images.githubusercontent.com/50437378/121632381-17a77180-caab-11eb-85d4-47143f2bd97b.jpg)

**Comment by rinat-enikeev** [comment]
please add translations (Suomi, Swedish, French) for DFU 2.0

**Comment by markoaamunkajo** [comment]
FI strings done
@io53 updates for Sverige

**Comment by io53** [comment]
Swedish added here https://github.com/ruuvi/station.localization/pull/46

**Comment by markoaamunkajo** [comment]
France is not on Github I assume so moving this to done, Rinat has notified.
