### ISSUE TITLE
0.7(96) dB reading updating speed on DFU page

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station.ios#410]
Description:

User selects Update Firmware, sets his RuuviTag to DFU mode and continues to pick sensor from the list
Actual: dB reading is updating super fast
Expected: relaaax

**Comment by rinat-enikeev** [comment]
candidate for closing because we have DFU 2.0

**Comment by markoaamunkajo** [comment]
Moving to done
