### ISSUE TITLE
Retry DFU update in certain scenarios

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station.ios#411]
Description:

Question: should we show user to finish FW update or rerun FW update if his app was killed during update process?
Steps:
1. Start DFU
2. Kill app in middle of process
3. See sensor is still in open update status (green led)
4. User is able to open app and redo the firmware update process successfully

Otso Jousimaa, [11. Jun 2021 at 11.58.30]:
Automatic retry sounds like good solution to me

Scenarios that come to mind:
App was killed
iDevice run out of battery
Sensor out of range
Sensor out of battery

Also maybe would be useful to make sure it's not possible to start updating another sensor after app was killed.

**Comment by laurijamsa** [comment]
I'm not so sure if it is worth to add such logics without knowing if anyone actually even had these issues. And if adding on iOS, should add also to Android. Assigning to Marko. Please try to reproduce these problems on iOS and Android and share your thoughts after.

**Comment by markoaamunkajo** [comment]
Agreed in the meeting that improving logic in this case is not needed. Closing this card.
