### ISSUE TITLE
0.7(97) There is no connected/disconnected alert on Android

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station.ios#418]
Description:

For discussion: Android doesn't have connected/disconnected alert

**Comment by rinat-enikeev** [comment]
This is super useful to know when you are out of range of RuuviTag and the `local alert notifications` are not expected to be delivered. I propose to keep this alert.

**Comment by rinat-enikeev** [comment]
I mean the following scenario: 
1. user did set temperature alert and `connection` alert
2. user went out of range 
3. he received `disconnected` alert and he understands that he won't get temperature alerts until he get's in range

**Comment by markoaamunkajo** [comment]
Ok now that I know the usage I'm wondering should this alert be brought to Android or not.
@laurijamsa

**Comment by markoaamunkajo** [comment]
Moving to done
