### ISSUE TITLE
Keep connection / dismiss unclear

### ISSUE THREAD

**Issue by DG12** [ruuvi/com.ruuvi.station.ios#42]
The response to the message "Seems like you are running..."
**Keep Connection** is OK
**Dismiss** is unclear (at least to me)
 Does this mean "release connection" when RuuviStation is in background?

**Comment by rinat-enikeev** [comment]
renamed to "Cancel" in dev branch (0.5) https://github.com/ruuvi/com.ruuvi.station.ios/commit/40647cba98ff9286c93dc12f6eda1c09ad133bfb
