### ISSUE TITLE
0.7(98) Adding FW 2.5.9 df3 sensor doesn't record MAC address

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station.ios#423]
Description

User has single local 2.5.9 sensor running in data format 3 and he adds it to Ruuvi Station.
Actual: no MAC address appearing. MAC is added only when user rotates sensor through other data modes.

**Comment by markoaamunkajo** [comment]
![IMG_5759](https://user-images.githubusercontent.com/50437378/121779505-351d2e00-cbc6-11eb-9cd2-10c6f87f4d2e.PNG)

**Comment by rinat-enikeev** [comment]
this is limitation of iOS. iOS doesn't listen to MAC addresses, the only way to know MAC is via data format 5 advertisement.

**Comment by rinat-enikeev** [comment]
so this is expected behaviour

**Comment by markoaamunkajo** [comment]
Ok moving to done
