### ISSUE TITLE
0.7(98) Minor issues syncing network alerts

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station.ios#424]
Description:

User claims 2 new network sensors, a 3.30.2 and 2.5.9 firmware sensors, 3.30.2 sensor in set to connected mode

He names them
Activates all available alerts
Adds custom alert descriptions
Syncs with network
Uninstalls App
Reinstalls App, signs into network, sensors cards are created

Actual:
FW 3.30.2

Connected mode is disabled when syncing cards from network
Air Humidity g/m3 alert is disabled, when enabled threshold is lost and description is lost
Air Humidity Dew Point alert is disabled, when enabled threshold is lost and description is lost
Connection Alert is switched to off, description is lost
Movement Alert description is lost

FW 2.5.9

Connection Alert is switched off, description is lost

**Comment by rinat-enikeev** [comment]
> Connected mode is disabled when syncing cards from network
expected, wait a bit until the tag receives UUID. Also `connection` alert is not stored on the cloud, it's per-device. 

> Air Humidity g/m3 alert is disabled, when enabled threshold is lost and description is lost
expected, not a Cloud alert yet

> Air Humidity Dew Point alert is disabled, when enabled threshold is lost and description is lost
expected, not a Cloud alert

> Connection Alert is switched to off, description is lost
expected, `connection` is not a Cloud alert

> Movement Alert description is lost 
**Awesome catch! Fixed.** 

> Connection Alert is switched off, description is lost
`connection` is per-device alert.

**Comment by rinat-enikeev** [comment]
movement alert description saving to cloud was fixed in 100 build

**Comment by markoaamunkajo** [comment]
QA passed
