### ISSUE TITLE
0.7(100) User set Humidity custom alert description and shows for wrong alert type on iOS

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station.ios#431]
Description:

User on Android app set Humidity units to g/m3, then set humidity alert for g/m3 and custom description.
User on iOS 0.7(100) installed Ruuvi Station app, logged in, went to check alerts on this sensor and sees Humidity % alert is set to enabled with same description.

Expected:
Should enable and show description only if Humidity % alert was activated?

**Comment by andreevdenis** [comment]
You can't set humidity alerts on g/m3 in Android. It's always in % for relative humidity

**Comment by andreevdenis** [comment]
![Screenshot_20210613-113330.png](https://user-images.githubusercontent.com/24788772/121800546-3f2d4400-cc3b-11eb-80c8-11e043455501.png)

Error in displaying unit. It will be fixed

**Comment by rinat-enikeev** [comment]
it's android issue, minor bug with displaying humidity unit. Can't be fixed on iOS side

**Comment by markoaamunkajo** [comment]
Gotcha, moving to done
