### ISSUE TITLE
0.7(101) Wrong chart name shown for network sensor

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station.ios#435]
Description:

User makes clean install of app, signs into network and syncs 2 network sensors to Ruuvi Station
1. fw 3.20.2 Sensor
2. fw 2.5.9 Sensor

User checks charts on first sensor, cancels keeping connection
Actual: he is seeing second sensor name on charts screen. If he visits second sensor screen he will then see correct charts screen

Note: I'm not 100% sure but it could be possible that network sync is not completed at this point yet.

**Comment by markoaamunkajo** [comment]
https://user-images.githubusercontent.com/50437378/121808303-fb116200-cc81-11eb-88f0-40ecd704e4c8.mov

**Comment by rinat-enikeev** [comment]
brilliant catch, fixed

**Comment by markoaamunkajo** [comment]
QA passed
