### ISSUE TITLE
Syncing already in process

### ISSUE THREAD

**Issue by DG12** [ruuvi/com.ruuvi.station.ios#44]
After attempting to SYNC app reports:"Error App is already in process of syncing logs with this sensor"
OK will dismiss popup, but next attempt repeats Error immediately.
CLEAR clears existing data but attempt to sync still produces Error.
EXPORT exports a file with titles only ( hey what do you expect since clear!)
TAG version v3.28.13
Ruuvi Station version 0.5(14)

Anything you want me to do before I remove / add this tag??

Just a thought, maybe export could include some diagnostic information at least until no longer beta. This could then be forwarded to you for analysis!

**Comment by rinat-enikeev** [comment]
Hi @DG12. I believe this can be fixed with force kill app, no need to remove/add tag. 

I'm trying to reproduce.

**Comment by rinat-enikeev** [comment]
@DG12 can you reproduce the issue after kill/restart app?

**Comment by DG12** [comment]
I am not able to reproduce this, so closing.
