### ISSUE TITLE
0.7(102) TestFlight Network Update - issues

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station.ios#440]
Description:

I'm having trouble with Testflight version
What I did

Installed App Store version
added 1 local tag with background image, name, alerts, gatt sync

Then updated to Testflight
Signed into network, synced

I am not getting network sensor cards created and lost background photo for the local sensor card

**Comment by markoaamunkajo** [comment]
Update: network cards have been downloaded. It just took a long long time.

**Comment by rinat-enikeev** [comment]
brilliant catch, fixed. Build 0.7(104)

**Comment by markoaamunkajo** [comment]
QA passed
