### ISSUE TITLE
Only 14 entries after 24 hours

### ISSUE THREAD

**Issue by DG12** [ruuvi/com.ruuvi.station.ios#45]
I am confused :-(.
Ruuvi 06DC was outside in the cold (34F) then in the car (55F) then outside then inside for a total of nearly 24 hours.
I did a sync then export. Only 14 entries were exported.
App 0.5(16), Ruuvi v3.28.13 ( I had deleted the app and added this and Ruuvi 1a96 before 1/18/20)
PS Maybe adding the time of sync (not export) to the first(heading) row would be interesting?

Here are (what I thought) were the intestering columns:
> 

Ruuvi 06DC |   |   |   |   |   |  
-- | -- | -- | -- | -- | -- | --
Date | Celsius | Acceleration X | Voltage | Movement Counter | Measurement Sequence Number | TX Power
01/18/20 08:39 AM | 22.27 | - | - | - | - | -
01/18/20 10:45 AM | 12.56 | -0.008 | 2.735 | 4 | 5890 | 4
01/18/20 10:45 AM | 12.51 | -0.004 | 2.735 | 4 | 5892 | 4
01/18/20 10:50 AM | 5.69 | 0.032 | 2.58 | 31 | 6125 | 4
01/18/20 11:03 AM | 0.67 | 0.02 | 2.675 | 125 | 6761 | 4
01/18/20 11:24 AM | 13.26 | 0.012 | 2.805 | 209 | 7741 | 4
01/18/20 07:19 PM | -0.18 | -0.012 | 2.682 | 12 | 29904 | 4
01/18/20 07:24 PM | 12.35 | -0.008 | 2.735 | 12 | 30139 | 4
01/18/20 07:29 PM | 16.11 | -0.004 | 2.826 | 12 | 30374 | 4
01/18/20 07:34 PM | 17.93 | 0.008 | 2.847 | 12 | 30608 | 4
01/18/20 08:10 PM | 20.88 | 0 | 2.865 | 12 | 31680 | 4
01/18/20 08:15 PM | 21.55 | -0.008 | 2.875 | 12 | 32525 | 4
01/18/20 08:39 PM | 21.91 | - | - | - | - | -
01/19/20 08:11 AM | 21.55 | -0.008 | 2.875 | 12 | 32525 | 4

**Comment by DG12** [comment]
PS in addition to the date/time of sync the MAC should be included in the heading row

**Comment by DG12** [comment]
I think I understand what's going on.
Is this correct:
 Due to the way Apple has implemented bluetooth, an app can only receive packets when it is in the foreground.
This means that if the lock screen timer expires ruuvistation will no longer receive packets.

**Comment by rinat-enikeev** [comment]
I believe the tag rebooted and cleared logs...

**Comment by rinat-enikeev** [comment]
@DG12 Is this issue still relevant? Most probably the tag rebooted and the logs were cleared.

**Comment by DG12** [comment]
Based on measurement sequence numbers I don't think the tag restarted. I will check this again and update with additional info.

**Comment by rinat-enikeev** [comment]
Please feel free to reopen if still relevant.
