### ISSUE TITLE
Fail gracefully on verify Email if incorrect address was tapped

### ISSUE THREAD

**Issue by rinat-enikeev** [ruuvi/com.ruuvi.station.ios#455]
Currently it's possible to request code for `email1` and `email2`. 
If later tap on `email1` verification link, the app is in state: 
- shows `email2` in Menu but is actually authorised by `email1`.

**Comment by rinat-enikeev** [comment]
![IMG_95B211D9F0AC-1](https://user-images.githubusercontent.com/722716/125162729-e3ef6280-e1a2-11eb-849c-d46c7436738f.jpeg)

**Comment by markoaamunkajo** [comment]
QA passed
