### ISSUE TITLE
Clear leaves 2 odd entries

### ISSUE THREAD

**Issue by DG12** [ruuvi/com.ruuvi.station.ios#46]
On 1/19/20 08:36  I did. clear(Clear the historical data from the app) 
Good wording
Then a sync, then export.
2 entries were exported! No Voltage movement or sequence values!

> 

Ruuvi 06DC |   |   |   |   |  
-- | -- | -- | -- | -- | --
Date | ISO8601 | Celsius | Fahrenheit | Kelvin | Relative Humidity (%)
01/18/20 08:39 AM | 2020-01-18T13:39:02.000Z | 22.27 | 72.09 | 295.42 | 18.69
01/18/20 08:39 PM | 2020-01-19T01:39:02.000Z | 21.91 | 71.44 | 295.06 | 25.58

**Comment by rinat-enikeev** [comment]
this seems to be logs from the tag and it's expected to be without Voltage etc.
