### ISSUE TITLE
Straight lines instead of synced logs on 3 tags

### ISSUE THREAD

**Issue by rinat-enikeev** [ruuvi/com.ruuvi.station.ios#460]
If this happens with one tag, it happens with others.

**Comment by priyonto** [comment]
@rinat-enikeev Would you please share more details on this issue? Thank you.

**Comment by priyonto** [comment]
Discussed with @rinat-enikeev and decided to close it since this issue doesn’t have enough background information. We will open new issue in the future if we find anything.
