### ISSUE TITLE
Apply offsets to existing history data

### ISSUE THREAD

**Issue by andreevdenis** [ruuvi/com.ruuvi.station.ios#468]
For example when user change offset for temperature we should apply new offset to existing history. I don't know how you store it in iOS but I store every point in history as: 
sensor_mac
history_date
temp (after calibration)
temp_applied_offset
humidity (after_calibration)
humi_applied_offset
.. same for pressure

So to apply new temp offset I do this for every point:
```
temp = temp - temp_applied_offset + new_offset   // temp - temp_applied_offset - this is the original temp that was received from sensor
temp_applied_offset = new_offset
```

**Comment by priyonto** [comment]
I need a bit more context and feature explanation in this issue/s. What we are expecting here? 
I am also wondering about the differences in this screen on both of the platforms. There are no offset settings in the Android app. 

**iOS:**
![IMG_4961](https://user-images.githubusercontent.com/24395776/148998145-9244c68e-bae3-42f4-a686-e7a469a770c1.PNG)

**Android:**
![Screenshot_20220111-190853_Ruuvi Station](https://user-images.githubusercontent.com/24395776/148998155-85423f4b-031a-42d3-a66e-186cfa2fa428.png)

**Comment by laurijamsa** [comment]
Actually, those offset settings should not be visible on iOS. Reason for this is that you are looking for a shared sensor. Only owner of the senaor can adjust offsets. Offsets are applied on sensor data by the client software, and databasea (local and cloud) are raw data without offsets.

**Comment by priyonto** [comment]
So, the way I understand is - if I am the owner of the sensors I will be able to adjust the offsets from the app and they should reflect on the app, right now in iOS it just shows zero as values. But, if I am not the owner I should not be seeing these items at all just like the android app. Is that correct?

**Comment by andreevdenis** [comment]
Yes, correct

**Comment by andreevdenis** [comment]
I've updated task description

**Comment by priyonto** [comment]
> Actually, those offset settings should not be visible on iOS.

Is there any issue already opened for this part specifically? I can't find one.

**Comment by laurijamsa** [comment]
I think there is no issue yet about that, let's open one

**Comment by priyonto** [comment]
Thanks. I have created one. #670

**Comment by markoaamunkajo** [comment]
I believe this is broken due to https://github.com/ruuvi/com.ruuvi.station.ios/issues/547

**Comment by markoaamunkajo** [comment]
QA passed
