### ISSUE TITLE
Sync should report first, last and number of entries - enhancment - 0.6.1(18)

### ISSUE THREAD

**Issue by DG12** [ruuvi/com.ruuvi.station.ios#47]
Sync needs to be more talkative.
Currently 0.5(16) only reports:"connecting, syncing" quickly. (or not)
It should report progress as it goes.
On completion should report number of entries received, time of first and last and wait for acknowledgment.

**Comment by rinat-enikeev** [comment]
unreachable, idk from start how long will it take to download all data

**Comment by DG12** [comment]
Nice would be  something like 
100,200,300 ...

**Comment by rinat-enikeev** [comment]
closing as duplicate of https://github.com/ruuvi/com.ruuvi.station.ios/issues/317
