### ISSUE TITLE
New UX for DFU update

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station.ios#471]
Description:

Here are the screens for DFU update process.
We will not make the dynamic content option this time for DFU steps, just  simple update process.

Please assume that user will set SINGLE RuuviTag to RuuviBoot mode and process will automatically choose closest RuuviBoot device to be used in DFU.

![photo_2021-06-27 11 14 57](https://user-images.githubusercontent.com/50437378/123532623-1e83e480-d739-11eb-850f-4c589c07c1f0.jpeg)
![photo_2021-06-27 11 15 00](https://user-images.githubusercontent.com/50437378/123532625-217ed500-d739-11eb-8d2f-a7abb0b9a6e6.jpeg)
![photo_2021-06-27 11 15 03](https://user-images.githubusercontent.com/50437378/123532628-23e12f00-d739-11eb-96e1-818416093d69.jpeg)

**Comment by markoaamunkajo** [comment]
Waiting for languages build

**Comment by markoaamunkajo** [comment]
0.7.2(118) looks like menu is not using language string
![fr](https://user-images.githubusercontent.com/50437378/126519347-6c618199-f0b3-41ae-9474-3f3533c2befc.jpg)
![fi](https://user-images.githubusercontent.com/50437378/126519362-4092d770-a537-402b-b318-8df6b8d11aed.jpg)

**Comment by rinat-enikeev** [comment]
"FIRMWARE" in French is "FIRMWARE"

**Comment by markoaamunkajo** [comment]
QA passed
