### ISSUE TITLE
Unification: add Pa units to Ruuvi Station iOS

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station.ios#472]
Description:

Please add Pa units to Ruuvi Station iOS app, same as Android.
Make sure that listing units on settings page is same, also charts, alerts, calibration, network and csv export reflect changing this unit.

**Comment by laurijamsa** [comment]
We have agreed not to do this at this time as it's not supported by the standard unit library thingy provided by Apple SDK. Closing.
