### ISSUE TITLE
Add firebase analytics

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station.ios#481]
Add firebase analytics

virtual_tags - exact number of virtual sensors
added_tags - exact number of added sensors
claimed_tags - exact number of sensors claimed by user
offline_tags - not claimed and not shared to user (Bluetooth only sensors)
signed_in - (true/false) user signed in to cloud or not

**Comment by laurijamsa** [comment]
Add also is_signed_in

**Comment by priyonto** [comment]
This is noted. Thank you.

**Comment by laurijamsa** [comment]
Seems that signed in was already listed on the original description :)

**Comment by priyonto** [comment]
Yes, Just noticed. I will move it up as soon as we finish the current list. This is an important one.

**Comment by andreevdenis** [comment]
Use "signed_in", same as in Android app

**Comment by priyonto** [comment]
> Use "signed_in", same as in Android app

Noted, Thank you :)

**Comment by markoaamunkajo** [comment]
Nothing to QA moving to done
