### ISSUE TITLE
Unification: Dashboard

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station.ios#487]
Description:

Please add Dashboard view to iOS app, like Android

**Comment by ojousima** [comment]
When this is completed, let's update the feedback topic here as [Completed] https://feedback.ruuvi.com/posts/84/in-progress-one-page-overview

**Comment by ariwakio** [comment]
Any progress on this?

**Comment by laurijamsa** [comment]
We unfortunately had to pause the dashboard development until the new spec got released and various performance issues got sorted out. We'll have this style of a dashboard: https://github.com/ruuvi/com.ruuvi.station/issues/854 

Sorry about the delay on this.

**Comment by markoaamunkajo** [comment]
Main card is completed, bell indicators will be improved during TF period.
