### ISSUE TITLE
Unification: Use same background for menu as Android

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station.ios#488]
Description:
Use same background for menu as Android

**Comment by priyonto** [comment]
@markoaamunkajo Is this issue already fixed? I am not sure whether it's referring to the side menu background, but in the current build, I do not find any mismatch between Android and iOS app. Please reconfirm? Thank you.

**Comment by markoaamunkajo** [comment]
Moving to done
