### ISSUE TITLE
Unification: Remove Foreground scan settings on iOS

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station.ios#490]
Description:

Please remove Foreground scan settings on iOS
Use same foreground scan settings than on Android
Move Load and save from web to Defaults just in case if ever needed for QA purposes

**Comment by priyonto** [comment]
@markoaamunkajo Would you mind sharing a bit more details on this issue?

**Comment by markoaamunkajo** [comment]
https://github.com/ruuvi/com.ruuvi.station.ios/issues/473 closed as duplicate

**Comment by markoaamunkajo** [comment]
QA passed
