### ISSUE TITLE
Unification: Background Scanning Settings

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station.ios#491]
Description:

Please bring Background Scanning Settings to iOS same as on Android
Let's use iOS Data Logging Interval style
Steps, all, 1 min steps until 60 min

Default interval: 5 minutes

**Comment by priyonto** [comment]
![IMG_4D5F31F44126-1](https://user-images.githubusercontent.com/24395776/161716601-74ceaf0b-b4c6-4304-ae37-765e36021c51.jpeg)

@markoaamunkajoI think this is already available on the current version of the app?

**Comment by markoaamunkajo** [comment]
Yes, this is completed
