### ISSUE TITLE
Temperature Alert is not shown even when owner is logged in - defect 0.7.2(113)

### ISSUE THREAD

**Issue by DG12** [ruuvi/com.ruuvi.station.ios#494]
Sorry about the confusion. I thought I had made a mistake by being signed in as a different user than owner.
Now that I logged in as the owner the alert icon does NOT show.

![ruuuviIOSnoAlertShown](https://user-images.githubusercontent.com/2365961/124495023-94193180-dd85-11eb-9272-9a96df7f20c0.JPG)
.

**Comment by markoaamunkajo** [comment]
QA passed
