### ISSUE TITLE
Make labels are readable on Dark Theme (Tag Settings) 

### ISSUE THREAD

**Issue by rinat-enikeev** [ruuvi/com.ruuvi.station.ios#495]
https://f.ruuvi.com/t/ruuvi-station-ios/4871

**Comment by rinat-enikeev** [comment]
was ![IMG_5E9879E07D9B-1](https://user-images.githubusercontent.com/722716/126622237-1f3f205c-45b4-4a88-8f89-67aaa87efc94.jpeg)

**Comment by rinat-enikeev** [comment]
is ![IMG_0DC0AA563613-1](https://user-images.githubusercontent.com/722716/126622280-e3fb2223-aed3-400e-8cd9-f94d1974dfab.jpeg)

**Comment by markoaamunkajo** [comment]
QA passed
