### ISSUE TITLE
Offset correction for data format 3 tags

### ISSUE THREAD

**Issue by rinat-enikeev** [ruuvi/com.ruuvi.station.ios#498]
STR: 
0. prepare two tags in df3
1. clean install app
3. add 2 tags
4. set offset calibration on one tag

Expected: offset is applied to only one tag
Actual: offset is applied to two tags

**Comment by rinat-enikeev** [comment]
also did fixes for the following STR: 
0. prepare tag with df3
1. clean install app
2. add sensor
3. set offsets
4. tap `B` on sensor

Internally sensor data migrates from Realm to SQLite, and settings are also migrated now.

**Comment by markoaamunkajo** [comment]
QA passed
