### ISSUE TITLE
Migrate Alert Settings for Relative Humidity

### ISSUE THREAD

**Issue by rinat-enikeev** [ruuvi/com.ruuvi.station.ios#499]

**Comment by markoaamunkajo** [comment]
0.7.2(116)
User installs clean build, adds local sensor, then signs into network and brings few other sensors to app, then sets app settings humidity units to relative humidity.

After doing so he then sets up humidity alert to first local sensor and checks other sensors.
The connectable sensors have alerts disabled but if he now views charts on any of those tags he will see alert bell blinking.

https://user-images.githubusercontent.com/50437378/125496814-5af7b4aa-fe96-4fa9-b74d-7442a2696c3a.mov

**Comment by markoaamunkajo** [comment]
QA passed
