### ISSUE TITLE
Tag name incorrectly displayed In all caps

### ISSUE THREAD

**Issue by DG12** [ruuvi/com.ruuvi.station.ios#5]
Although the edit rename tag entry shows mixed case, the display of the tag values show all upper case

**Comment by DG12** [comment]
Although the edit rename tag entry shows mixed case, the display of the tag values show all upper case.

**Comment by io53** [comment]
This is by design :)

**Comment by DG12** [comment]
Sorry to hear that.
If I wanted the name I chose to be in caps I would have entered it in caps.
I am opposed to the over use of cap every where. When always shouting loud it becomes the norm and looses its meaning.

Oh well. :-(

**Comment by DG12** [comment]
I's like to reopen this
