### ISSUE TITLE
Atmospheric pressure needs rising/falling indicator

### ISSUE THREAD

**Issue by DG12** [ruuvi/com.ruuvi.station.ios#51]
Considering the Ruuvi tag, as displayed by station, is mostly considered a weather display device, the Atmospheric pressure emulates an aneroid barometer. Many home barometers include a manually settable needle so the user can observe the change in pressure.
It would be helpful to include an indicator of the sign of a signifiant change in Atmospheric pressure over the last 12(?) hours. For example an up arrow indicating rising.

I had suggested this be included in the packet https://f.ruuvi.com/t/rfc-format-5-1-i-e-6/3274 and I still believe it is better calculated in the tag.

I realize this can only be done when the ruuvi station has a, somewhat recent, value available.

**Comment by rinat-enikeev** [comment]
@laurijamsa what do you think about UX proposal?

**Comment by laurijamsa** [comment]
Thanks for the idea. We're going to consider this again after more basic functionality is implemented on the new UX. Closing this for now.
