### ISSUE TITLE
Hide DFU option for non-local network sensors?

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station.ios#516]
Description:

Current DFU feature is shown both to local and network sensors, but non-local network sensors cannot be obviously updated. Should we hide update menu item from these sensors?

**Comment by laurijamsa** [comment]
Ig hiding it, there should probably be some timeout logic like "show it under sensor settings if a broadcast message of this sensor has been received within thr last 10 minutes". And it should be hidden always for shared sensors, of course.

**Comment by rinat-enikeev** [comment]
The most straightforward logic is: after opening Tag Settings, if the app has heard either advertisement or heartbeat - enable the DFU section. I did that way, I hope it's acceptable

**Comment by markoaamunkajo** [comment]
I have one sensor that is bolted outdoors that I see it's not showing Firmware update. All other sensors showed it and network sensors were hiding it correctly. I still didn't figure out why though. Will check firmware on this device.

![IMG_5975](https://user-images.githubusercontent.com/50437378/126728148-01dfb371-8c8f-41ae-9210-3d97234fbe75.PNG)

**Comment by markoaamunkajo** [comment]
Ah I went out of range apparently. Now I see fw update and everything works perfectly.
QA passed
