### ISSUE TITLE
DFU unsuccessful 0.7.2(120

### ISSUE THREAD

**Issue by DG12** [ruuvi/com.ruuvi.station.ios#529]
" Latest available Ruuvi Firmware version: V3.30.2"
Current version:Ruuvi FW v3.30.2-RC3+default
updating 0% Device failed to connect

current version: Ruuvi FW v3.30.3+RC1+default.
DFU Service not found

Ruuvi FW v3.30+default
Device failed to connect

Maybe it would be a good idea to display some initial interchanges until DFU gets into actually sending the update.

**Comment by rinat-enikeev** [comment]
> Ruuvi FW v3.30.2-RC3+default

can't find this one on GitHub

> Ruuvi FW v3.30.3+RC1+default

also only source code is available [here](https://github.com/ruuvi/ruuvi.firmware.c/releases/tag/v3.30.3%2BRC1)

> Ruuvi FW v3.30+default

updated successfully

**Comment by rinat-enikeev** [comment]
downgrading from pre-release `3.30.3` to `3.30.2` works well also

**Comment by markoaamunkajo** [comment]
No action required from QA. Moving to done.
