### ISSUE TITLE
README.md needs updates 

### ISSUE THREAD

**Issue by DG12** [ruuvi/com.ruuvi.station.ios#53]
Tag settings image needs update.

Is this the best place to include how it works and how to us it?

Like 
RuuviStation IOS : when receiving updates via advertisement, data points are logged every 5 minutes ONLY while the app is in the foreground i.e. visible

setting alerts

update by advertisement / connection

**Comment by rinat-enikeev** [comment]
the support page for Ruuvi Station apps needs improvement, and README is mostly for Developers. Thanks for feedback, we will try to make it more user-friendly. Please check https://ruuvi.com/support/
