### ISSUE TITLE
Modify sensor settings page to make it easier to use the new cloud features

### ISSUE THREAD

**Issue by laurijamsa** [ruuvi/com.ruuvi.station.ios#530]
Okay, I'm updating this issue now. Earlier the plan was to add more popup messages to help with the cloud features, but then we came to a conclusion that it'd be better that user would see the instructions before tapping the buttons. So, let's add more sub-pages where a feature is explained first and then user can act on it if wanted.

This is layout how those features (offsets, owner, sharing, remove) should approximately look like on the sensor settings page:

![image](https://user-images.githubusercontent.com/1311912/129333873-db015262-ea26-42e2-be59-9276f024c9d6.png)

.
.
.
.

Order of the sensor settings page:

GENERAL
Name
Owner
Share

ALERTS
Temperature
Air Humidity
Air Pressure
Signal Strength (RSS)
Movement

OFFSET CORRECTION
Temperature
Humidity
Pressure

MORE INFO
MAC address
Data format
Battery voltage
Acceleration X
Acceleration Y
Acceleration Z
TX power
Signal strength (RSSI)
Measurement sequence number

REMOVE
Remove this sensor

.
.
.
.

This is layout for all the sub-pages (offsets, ownership, sharing, remove) that are accessible under sensor settings: 

![image](https://user-images.githubusercontent.com/1311912/129333946-b6a99fb9-4b69-4663-8b2d-c7d4985e9032.png)

.
.
.
.

OWNER sub-page content (show on sensor settings page only if logged in, possible values shown on sensor settings page: Not set / Someone else / email of the one who shared the sensor with you / You):

Do you own this sensor? If yes, please claim ownership of the sensor and it'll be added to your Ruuvi account. Every Ruuvi sensor can have only one owner.

Benefits:

- Sensor names, background images, offsets and alert settings will be securely stored in the cloud
- Access sensors remotely over the Internet (requires a Ruuvi Gateway)
- Share sensors with friends and family (requires a Ruuvi Gateway)
- Browse up to 2 years of history on **station.ruuvi.com** (requires a Ruuvi Gateway)

CLAIM OWNERSHIP

.
.
.
.

SHARE sub-page content (show on sensor settings page only if logged in and if sensor is claimed by the logged in user, possible values on sensor settings page: Not shared, Shared):

You can share the sensor with friends and family if it's in range of a Ruuvi Gateway.

Receiver will be notified by email. If the receiver doesn't have a Ruuvi account, a free Ruuvi account will be automatically created at first log in.

Note that sensor's custom name and background image will be shared. The name and image sync is one time and they can be customised by the receiver. Offset values (if any) will be automatically synced, and the receiver will always see the corrected values.

**Add a friend:**

SHARE

**Already shared with:**

friend1@email.com          X
friend2@email.com          X

.
.
.
.

REMOVE sub-page content (show always but depending on if user has logged in and claimed the ownership, show different texts):

Option 1: Sensor is claimed by the user

By removing the sensor, your sensor ownership status will be revoked. After removal, someone else can claim ownership of the sensor. Every Ruuvi sensor can have only one owner.

Option 2: Sensor is a shared sensor

If you remove the sensor, owner of the sensor will be notified and you cannot access the sensor anymore.

Option 3: User hasn't logged in or hasn't claimed the ownership

Do you want to remove the sensor? You can add it again later, if needed.

REMOVE

**Comment by rinat-enikeev** [comment]
0.7.3(183)

**Comment by markoaamunkajo** [comment]
There is a styling mismatch in sensor claiming page compared to for example calibration page. Let's fix these soon.

![styling_mismatch](https://user-images.githubusercontent.com/50437378/131272533-c216d0ed-859c-4d76-8751-f79682e42487.jpg)

**Comment by markoaamunkajo** [comment]
Similary styling mismatch on Share page. Also there is no feedback when sensor has been shared on Share page and the email field doesn't get cleared after successfully sharing sensor.

![IMG_6236](https://user-images.githubusercontent.com/50437378/131272766-2a769317-8193-4d55-85f4-fe9615f5f45f.PNG)

**Comment by markoaamunkajo** [comment]
Share page shows no new long description for FI language although strings are in language file
![IMG_A7DE20485588-1](https://user-images.githubusercontent.com/50437378/131273991-07ef617a-5d7e-4663-a1c9-9f53fcae2e4a.jpeg)

**Comment by markoaamunkajo** [comment]
QA passed
