### ISSUE TITLE
Sync without Bluetooth enabled = "Both callback result and error are nil"

### ISSUE THREAD

**Issue by laurijamsa** [ruuvi/com.ruuvi.station.ios#531]
By pressing SYNC on a cloud sensor when Bluetooth is disabled is giving an Error popup like this. I would expect it to ask to enable Bluetooth instead.

Edit: Seems that this also happens if the sensor is only out of range. Please unify all GATT sync related things with Android. Android also shows during the sync process that how many datapoints are read.

**Comment by priyonto** [comment]
The issue from the title is fixed.  And, the issues on the edit already have separate cards - #725 & #317

**Comment by markoaamunkajo** [comment]
QA passed
