### ISSUE TITLE
Remove the gesture that shows graphs

### ISSUE THREAD

**Issue by laurijamsa** [ruuvi/com.ruuvi.station.ios#535]
Currently seems that iOS shows graphs if user touches a sensor card and swipes up.

Android does not have that feature. To toggle between graphs and live data we have the graph icon / thermometer icon.

Let's remove the gesture as it's not really needed and at least I found that feature by mistake and wondered that what the heck just happened and how to get back.

**Comment by markoaamunkajo** [comment]
QA passed
