### ISSUE TITLE
Remove claimed and shared sensors when on logging out

### ISSUE THREAD

**Issue by laurijamsa** [ruuvi/com.ruuvi.station.ios#536]
After user logs out, claimed sensors and sensors someone else shared to you should be removed from the app.

A story behind this:

A friend registered a user account, claimed a sensor and configured some alerts for the sensor. Then he shared the sensor with another email account he owns. Then he logged out (and the claimed sensor didn't get automatically removed from the app) and registered and logged in using the other email address. Instantly after logged in, the alert settings got automatically applied to the shared sensor and he started to receive email alerts. That was really confusing and that shouldn't have happened because alert settings aren't shared during sensor sharing.

**Comment by rinat-enikeev** [comment]
0.7.6 (194)

**Comment by markoaamunkajo** [comment]
QA passed
