### ISSUE TITLE
Unification: Remove options to configure how often to automatically fetch data from web

### ISSUE THREAD

**Issue by laurijamsa** [ruuvi/com.ruuvi.station.ios#537]
Update virtual sensors only when the app is opened manually. This configuration option is causing confusion for users that are using also Ruuvi's cloud services. If the weather service isn't polled in the background, this means that also alerts aren't working (in the background), so possibility to set alerts for virtual sensors should be removed too.

![image](https://user-images.githubusercontent.com/1311912/130318868-6561d3e5-ce9b-4563-b550-70021e9eff27.png)

Also, remove this "poll Ruuvi cloud periodically" setting and don't poll the cloud periodically (update only when the app is opened manually):

![image](https://user-images.githubusercontent.com/1311912/130319309-01c34c89-65fb-49f9-81d3-4700c811b1da.png)

**Comment by priyonto** [comment]
@markoaamunkajo Would you please have a look at this issue and add more details to it? Thank you very much.

**Comment by markoaamunkajo** [comment]
@priyonto 

Virtual sensor foreground setting (Save and load from web)
unnecessary feature for user, comment in card https://github.com/ruuvi/com.ruuvi.station.ios/issues/490

Network pull interval
redundant feature, this option doesn't exist anymore

I will move this card to done because no action required.

**Comment by laurijamsa** [comment]
I think this issue cannot be closed yet as it has points that are not completed yet.

**Comment by markoaamunkajo** [comment]
Alerts removed
Update when app opened manually
Save and load from web removed

QA passed
