### ISSUE TITLE
iPhone cannot disconnect bt-connection with RuuviTag 

### ISSUE THREAD

**Issue by N1CKQ10** [ruuvi/com.ruuvi.station.ios#538]
When first time pairing RuuviStation app with RuuviTag the RuuviStation app cannot disconnect the tag: it still keep connected after "Keep Connection" is turned off (can seen from the RuuviStation app).

NOTE: Restarting the RuuviStation app fix this.

**Comment by priyonto** [comment]
I am not sure whether this issue still persists. 
@markoaamunkajo Would you please try to reproduce it? Thank you.

**Comment by markoaamunkajo** [comment]
Reproduced on iOS 14.8, 0.7.7(252) fw 3.31.1 local sensor with user logged in to Ruuvi Cloud. Flicking the switch doesn't do anything. Killing app fixes this issue.

https://user-images.githubusercontent.com/50437378/157365756-ce01c2e9-2270-45c3-b4b5-96ae7c92d742.mov

![IMG_8286](https://user-images.githubusercontent.com/50437378/157365788-426df270-b782-4550-917e-d62b32959d75.PNG)

**Comment by markoaamunkajo** [comment]
0.7.7(256) Reproduced
https://user-images.githubusercontent.com/50437378/158603062-d09f3779-8f1d-49b3-87dc-585c7e507a3c.mov

**Comment by markoaamunkajo** [comment]
@priyonto Perfectly normal for me ha! 
I see Connected forever if I flick the switch like I do so user has possibility to set it like this by accident, which should be avoided. If it was able to resolve itself over period of time then this case would be dismissed. Ideas?

**Comment by markoaamunkajo** [comment]
That sounds like a good and straightforward plan to me.

**Comment by priyonto** [comment]
Thank you. I will try to implement that.

**Comment by markoaamunkajo** [comment]
QA passed
