### ISSUE TITLE
iPhone doesn't upload sensor settings (name, bg image, others) to the cloud when claiming a sensor

### ISSUE THREAD

**Issue by N1CKQ10** [ruuvi/com.ruuvi.station.ios#539]
When RuuviTags are renamed in the RuuviStation App before claiming Tags to the RuuviCloud those renamed Tags names doesn't move to RuuviCloud. There is only MAC addresses at the Cloud.

NOTE: Renaming Tags again after claiming at the app will work as workaround.

This maybe have huge impact when users have more than one RuuviTag before purchase RuuviGW/RuuviCloud.

**Comment by rinat-enikeev** [comment]
0.7.3 (121)

**Comment by rinat-enikeev** [comment]
this was a hot fix build that stores only name. If bg image and `others` needs to be synced on first claim - I'll do. 
@andreevdenis what do you save to cloud on `claim` - only name?

**Comment by andreevdenis** [comment]
Currently I save only name on claim. It will be fixed. We should sync offsets, bg. images and alarms too.

**Comment by rinat-enikeev** [comment]
0.7.3 (124)

**Comment by markoaamunkajo** [comment]
Waiting for other clients

**Comment by laurijamsa** [comment]
> Waiting for other clients

Hmm, but why? I have tested this and it seems to work as expected. Adding a new sensor, configuring these things and then claimed it and after that checked the result in the webui.

**Comment by markoaamunkajo** [comment]
It didn't work for me at the time, testing now.

**Comment by markoaamunkajo** [comment]
Works. QA passed.
