### ISSUE TITLE
charting: if less than 4 data points sample VERY frequently (enhancement)

### ISSUE THREAD

**Issue by DG12** [ruuvi/com.ruuvi.station.ios#54]
The app only logs samples every 5 minutes (may be that should be a tunable user setting).

After the local data is cleared (and when initially starting a tag) the chart cannot be shown because of the lack of data points.

Increasing the frequency of collecting packets(?) to a high frequency (like 10 seconds) when there were less than 4 data points would present a chart and let the user know that the app is working

**Comment by ojousima** [comment]
Logging interval from transmissions is tunable in the app, logging inside the tags is not yet tunable due to firmware limitations. In general I'd prefer avoid complexity for edge cases where it's not absolutely necessary.

**Comment by DG12** [comment]
Otso: I think you misunderstand the intent. It is not to change the interval rather to collect a few (like 3 ) points as soon as possible only where there are insufficient points to display a chart which otherwise seems to indicate that the app is not collecting data.

**Comment by DG12** [comment]
PS I don't see an option to tune the app regarding the logging interval in IOS version 0.5(19).
"Background scan interval" setting  is available in Android however this seems to be regarding the detection of new beacons.

**Comment by rinat-enikeev** [comment]
should be unified with @andreevdenis's implementation on Android side

**Comment by DG12** [comment]
Closed as duplicate of #91
