### ISSUE TITLE
Dataformat 3 tags shared to iOS shows up but does not receive any data

### ISSUE THREAD

**Issue by io53** [ruuvi/com.ruuvi.station.ios#546]
All values are "-"

**Comment by markoaamunkajo** [comment]
@priyonto 0.7.7(247) Shared 2.5.9 df3 sensor from other cloud profile and I see data so this issue is likely not valid anymore.

**Comment by markoaamunkajo** [comment]
I replicated this with original "-" description it looked like sensor hanged in df3 mode.

**Comment by markoaamunkajo** [comment]
df3 claimed sensor was shared to Cloud from Android and iOS user sees the sensor card after sync.
- There is no data appearing to card
- Card shows as df5, but this is not true



![Image](https://github.com/ruuvi/com.ruuvi.station.ios/assets/50437378/e7550307-4b73-4aec-8495-1eef62be2ff5)



![Image](https://github.com/ruuvi/com.ruuvi.station.ios/assets/50437378/9e250bb6-80bd-41ad-9bea-f4890955ff62)

**Comment by priyonto** [comment]
Not sure if this is alive anymore. Will check.

**Comment by markoaamunkajo** [comment]
We improved nagging about updating firmware on df3 mode sensor when accessing sensor settings page. This card is redundant in that sense, not many users will experience this.
