### ISSUE TITLE
0.7.3(124) Charts x-axis values and used units are clashing in UI

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station.ios#548]
Description:

This happens because we show values for X-axis both sides of chart.
Not sure what would be easy improvement, this screen is iPhone 7. Not high priority.

![iPhone7](https://user-images.githubusercontent.com/50437378/130468922-41a02154-d393-4a51-953f-c3b0135ab281.jpg)

**Comment by markoaamunkajo** [comment]
Hi Chris,

Thank you for the report. Marko cc'd will check this and we'll take some actions to fix these issues.

Lauri Jämsä
Founder and CEO, Ruuvi Innovations Ltd (Oy)
ruuvi.com / LinkedIn / Twitter


On Mon, 1 Nov 2021 at 16:57, Gmail <chris350@gmail.com> wrote:
See the arrrows below, spacing for graphs and text are skewed and going off the screen
![image0](https://user-images.githubusercontent.com/50437378/139783594-7e2cbb88-da62-4bc2-aa83-56337f8e3baa.jpeg)

**Comment by laurijamsa** [comment]
I believe we already removed the y-axis numbers from the right hand side and I believe this is not a problem anymore. Closing.
