### ISSUE TITLE
git clone fails due to "Permission denied"

### ISSUE THREAD

**Issue by pentzin** [ruuvi/com.ruuvi.station.ios#552]
git clone --recursive and github desktop fail when cloning the repo first time due to "Permission denied" while it's trying to pull the submodules. It seems that the submodule URLs in .gitmodules are not HTTPS (which is recommended by Github).

```
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by pentzin** [comment]
created PR #553

**Comment by priyonto** [comment]
Not being able to reproduce. Closing.
