### ISSUE TITLE
Unification: rename Ruuvi Network to Ruuvi cloud

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station.ios#554]
Description:

Please remove mentions of Ruuvi Network and simply refer to "Ruuvi cloud" in network related items in app including

Sign In email screen
Sign In code screen
Menu:  Ruuvi network status -> "Ruuvi cloud status"
Sensor settings: Data Received via "Cloud"
Sensor settings: Network info -> "Cloud info"

Android with card: https://github.com/ruuvi/com.ruuvi.station/issues/452

**Comment by rinat-enikeev** [comment]
@markoaamunkajo seems you've started changing Network to Cloud here: https://github.com/ruuvi/station.localization/pull/55/files

Shall we wait for French and Swedish changes?

**Comment by rinat-enikeev** [comment]
Also I can see "Sensor settings: Data Received via "Cloud" is not changed yet. We decided to skip it?

**Comment by laurijamsa** [comment]
> Shall we wait for French and Swedish changes?

Yeah we can add them later, no problem. I have commented the pull request too. https://github.com/ruuvi/station.localization/pull/55#issuecomment-909350818

**Comment by rinat-enikeev** [comment]
I've pulled fresh translations, please check if something Is missing

**Comment by markoaamunkajo** [comment]
QA passed
