### ISSUE TITLE
 bluetooth enabled detection needs revision 0.7.3(125) - defect - medium

### ISSUE THREAD

**Issue by DG12** [ruuvi/com.ruuvi.station.ios#555]
1) With app running, wifi available, logged into cloud, and bluetooth OFF:  no message is presented.
Cloud active RuuviTags seem to only update infrequently. As long  7 minutes with no iPhone activity! 
Seems that ANY iPhone activity initiates sync.
Are there any logs created for internal problem determination?

3) At startup RuuviStation IOS cannot get to bluetooth it states:
"Bluetooth is not enabled. as 
Ruuvi Station needs bluetooth
to be able to listen for sensors.
Go to Settings and turn
Bluetooth on."

In. addition, under settings/RuuviStation must have
 ALLOW RUUVII STATION TO ACCESS
Bluetooth

+++++++++++
Seems that there needs to be a test suite of several cases needs to set up including
At startup BLE out of range  Wifi in range
At startup BLE out of range  Wifi out of range
After startup  BLE out of range  Wifi in range
After startup  BLE out of range  Wifi out of range
cloud only tags
BLE persistent connected / not connected
etc

**Comment by laurijamsa** [comment]
I believe this is fixed in the latest build. If not, please reopen the issue. Closing.
