### ISSUE TITLE
Claiming error doesn't have FI translation

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station.ios#567]
Description:

Build 840 claiming error for already claimed sensor doesn't have FI translation string in language file.

Actual:
Virhe
Sensor already claimed by e***l@r****i.com

Expected:
Virhe
Anturilla on jo omistaja e***l@r****i.com

![IMG_6237](https://user-images.githubusercontent.com/50437378/131272208-939d745a-53e3-44f7-bca7-4cef1c1174cb.PNG)

**Comment by rinat-enikeev** [comment]
I guess this is not implemented both on Android and iOS. Current Response is: 

```
{
  "result" : "error",
  "error" : "Sensor already claimed by r***t@v*******y.org."
}
```

I believe we need to introduce ER_ALREADY_CLAIMED error code on Cloud side with prefix and email in different json values.

**Comment by rinat-enikeev** [comment]
we need Sami here :)

**Comment by rinat-enikeev** [comment]
Can we invite Sami to this repo so we are able to mention him?

**Comment by rinat-enikeev** [comment]
I propose the following format: 
```
{
  "result" : "error",
  "error" : "Sensor already claimed by ", 
  "email" : "r****t@v****y.org",
  "code" : "ER_SENSOR_ALREADY_CLAIMED"
}
```

@andreevdenis

**Comment by markoaamunkajo** [comment]
Waiting for resolution from clients. Remember to add translation strings for new error.

**Comment by markoaamunkajo** [comment]
No FI translation for this error

**Comment by markoaamunkajo** [comment]
QA passed
