### ISSUE TITLE
Alert notification should be disabled while in tag settings

### ISSUE THREAD

**Issue by DG12** [ruuvi/com.ruuvi.station.ios#57]
While in "tag settings" alert notification should be disabled. For example if current temperature is 25C and you momentarily slide the low alert above 25 a notification pops up before you get a chance to slide it below 25.

**Comment by rinat-enikeev** [comment]
but why? This will introduce a lot of complexity in the code, but the UX will change slightly. 
@laurijamsa what do you think?

**Comment by laurijamsa** [comment]
Let's consider again when implementing the new UX that is this still an issue on it or not. Let's don't use resources on this thing right now as it would slow down other development. Closing this issue.

**Comment by DG12** [comment]
This no longer seems to be a problem
