### ISSUE TITLE
Refresh cloud data automatically and simplify the menu

### ISSUE THREAD

**Issue by laurijamsa** [ruuvi/com.ruuvi.station.ios#574]
If data of any of the cloud sensor's (claimed or shared) is older than 1 minute and 1 second, update automatically if app is on foreground.

Simplify the menu like this:

![image](https://user-images.githubusercontent.com/1311912/131483404-1148a30c-e7cc-4c8b-891c-d9d83e9f4be8.png)

If not logged in, do not show anything on the bottom of the menu drawer.

With the auto update feature, the refresh button becomes pretty much useless because settings are stored instantly when modified and sensors are updated when new data is expected to be available. And data is also updated on app open. We've received also comments that users didn't even understand that the refresh icon could be pressed.

We can worry about extended bandwidth usage later if it'll grow too much at some point.

**Comment by rinat-enikeev** [comment]
Note! I'm not refreshing as per spec (when any sensor has 1m1s). I'm just refreshing every minute same as on Android.

**Comment by markoaamunkajo** [comment]
Something is wrong with syncing from cloud it's not fetching data from previous days from the cloud.

![IMG_A51F65333E97-1](https://user-images.githubusercontent.com/50437378/132148884-1b26930f-eef2-4529-af69-f822f005fd1d.jpeg)
![Screenshot 2021-09-06 at 8 40 19](https://user-images.githubusercontent.com/50437378/132148895-678e68d2-488a-471e-b421-e75ad0b650a9.png)

**Comment by laurijamsa** [comment]
@markoaamunkajo is this still valid? How to preproduce? Seem that the issue is assigned to you.

**Comment by markoaamunkajo** [comment]
Original passed review, moving this to done
