### ISSUE TITLE
Removing shared cloud sensor popup text is incorrect

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station.ios#582]
Description:

0.7.6 (195)
User is removing shared sensor from app that he has received from other user, he is shown confirmation popup

Actual: Remove sensor   Do you want to remove the sensor? You can add it again later, if needed. Cancel Confirm

Expected: Remove sensor   If you remove the sensor, the owner of the sensor will be notified and you cannot access the sensor anymore. Cancel OK

![IMG_6284](https://user-images.githubusercontent.com/50437378/132149479-9336c428-0941-472c-989e-0677a5589bff.PNG)

**Comment by priyonto** [comment]
Changing the localizable text with identifier "TagSettings.confirmTagRemovalDialog.message" should solve this issue. 
File path: station/Resources/Strings/Localizable

**Comment by andreevdenis** [comment]
Message text should vary depending on the type of sensor. In this case special text for removing sensor that was shared to user.

Also origin of all strings should be this repository: https://github.com/ruuvi/station.localization

![image](https://user-images.githubusercontent.com/24788772/148786471-f97465fa-4f6b-46b4-af31-8ddc7de7f770.png)

There is already existing string for this case. Just need to put unique ios identifier, do some magic to convert to iOS localization and use it in suitable situation.

**Comment by andreevdenis** [comment]
No problem. @rinat-enikeev should know how to convert localization file to iOS format.

**Comment by laurijamsa** [comment]
If there is no documentation available on this, please make sure that there will be :)

**Comment by markoaamunkajo** [comment]
0.7.7(237) Popup shows code but not the text we wanna see.
![IMG_7881](https://user-images.githubusercontent.com/50437378/150523104-2cd4bb1d-0c85-4425-8174-c4f6f59a0deb.PNG)

**Comment by markoaamunkajo** [comment]
QA passed
