### ISSUE TITLE
Do not override existing last measurement from Cloud if newer data was received via Bluetooth already - check if issue exist for iOS

### ISSUE THREAD

**Issue by andreevdenis** [ruuvi/com.ruuvi.station.ios#586]
![image](https://user-images.githubusercontent.com/24788772/133058603-86ea86a7-ab5c-4bd7-b12f-933e7a7ab1ae.png)

**Comment by andreevdenis** [comment]
@markoaamunkajo can you check if some work needed for iOS app?

**Comment by priyonto** [comment]
@laurijamsa Is it related to the cloud mode (#704)?

**Comment by laurijamsa** [comment]
Not really. @markoaamunkajo Denis asked before if iOS is working correctly or not, please check and report. Assigning to you.

**Comment by markoaamunkajo** [comment]
0.7.7(244)
I cannot confirm this after testing some time, but I found that I got 2 of the same readings added at the end of my csv export for the sensor when I connected gateway back and disabled bluetooth on my phone. I don't see this as a bug imo.

[Ruuvi D5E9-220203-2044.csv](https://github.com/ruuvi/com.ruuvi.station.ios/files/7995034/Ruuvi.D5E9-220203-2044.csv)

**Comment by markoaamunkajo** [comment]
QA passed
