### ISSUE TITLE
Display firmware version of tag in settings

### ISSUE THREAD

**Issue by ojousima** [ruuvi/com.ruuvi.station.ios#594]
e.g. under MAC address,

MAC Address:       AA:BB:CC:DD:EE:FF
Firmware version: v3.30.4+default
Data Format:         5
Firmware version is the same as read from Device Information Service through GATT. It should be stored when logs are read, and when firmware is updated through app. Maybe a button for "refresh" should be added?

[Android version of issue](https://github.com/ruuvi/com.ruuvi.station/issues/508)

**Comment by markoaamunkajo** [comment]
0.7.7(250) for 2.5.9 sensor this shows "-" because fw version cannot be read. Maybe it should show Legacy version or Please update @laurijamsa what do you think? Incentive for user to update.

**Comment by laurijamsa** [comment]
Yeah that's a good idea. I think it could say on Android and iOS simply: "Very old" "Fin: Hyvin vanha" and because under this string there is a button to initiate updating, everyone will understand what to do.

**Comment by priyonto** [comment]
Sounds good to me. Thank you.

**Comment by markoaamunkajo** [comment]
QA passed
