### ISSUE TITLE
Synchronizing... text shown on all sensor chart pages when single sensor is GATT syncing

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station.ios#597]
Description:

3 sensors with latest firmware

User has 3 sensors. He then synchronises their data to app. When first sensor is synchronised the other sensors are claiming that synchronisation was successfully completed although it has not been completed yet. It's clearly visible in charts. If user wants to be able to synchronise all of them he needs to close and restart app in between sync.

"Minulla on 3 tagiä käytössä. Kun synkronoin niiden tiedot appiin, niin ensimmäisen anturin synkronoinnin jälkeen muidenkin kohdalla lukee ”synkronointi onnistui” vaikka sitä ei ole vielä tehty (käyristä näkee tämän selvästi). Jotta muutkin saa synkronoitua pitää joka välissä sulkea ja käynnistää appi uudestaan.

Tageissä on muutama viikko sitten uusimpaan päivitetty firmware.

Device: iPhone 11

OS: iOS 14.7.1

App: Ruuvi Station 0.7.6(206)

Location: denied

Photo Library: not determined

Camera: not determined

Notifications: authorized"

**Comment by markoaamunkajo** [comment]
0.7.6(206)

Steps:

1. Start sync on one sensor in chart view
2. You will see synchronizing... text on all other sensor chart pages although this is not true

**Comment by priyonto** [comment]
This is a duplicate of #643. I am closing this one.
