### ISSUE TITLE
Tags not in Bluetooth range cannot be removed from app

### ISSUE THREAD

**Issue by ojousima** [ruuvi/com.ruuvi.station.ios#599]

**Comment by laurijamsa** [comment]
This is related: https://github.com/ruuvi/com.ruuvi.station.ios/issues/403

**Comment by markoaamunkajo** [comment]
QA passed

**Comment by laurijamsa** [comment]
Received a customer feedback:

"Miten saan poistettua aiemmin tekemäni näyttösivut eri antureille?
Olen yrittänyt ”Poista tämä anturi”- toiminnolla, mutta ei vaan toimi?
Timo

------------------------------------------
Device: iPhone 12 Pro
OS: iOS 15.4.1
App: Ruuvi Station 1.0.0(278)
Location: when in use
Photo Library: authorized
Camera: authorized
Notifications: authorized"

"How can I remove sensors from the app? I have tried with "Remove this sensor" but it doesn't work."

**Comment by priyonto** [comment]
Is it possible to get more information on this? like firmware version and especially if it's df3 tag or other?

**Comment by laurijamsa** [comment]
Not possible at least not yet. But is it really needed? User should always be able to remove sensors from the app, no matter what (old fw, uuid changed by the phone and therefore differentiating sensors not possible on df3, etc)

**Comment by priyonto** [comment]
It's not really needed. When I made the last fix on this issue the tag removal part kept pretty straight forward, just check on the db and remove it, nothing else needed. I am wondering what could possibly stopping it from being removed. The reason of asking more info is I came across an issue where df3 tags were sometime causing issue while removing and adding back. But, that was also fixed long ago.  Either way I will look into it soon.

**Comment by laurijamsa** [comment]
One scenario that crossed my mind that may have happened is that RuuviTag is on DF3 (no MAC address in payload) and then user's phone has decided to change RuuviTag's UUID. And then 10 days passed and measurements from database got flushed.  And then when trying to remove the RuuviTag, an error occurs because no data in the database.

**Comment by priyonto** [comment]
Thank you for the input. This might be a potential flaw. As far I can see the latest version is supporting these scenarios too while removing the tag. What I can confirm now - to remove tag it is not required to have BT connection, or in range. But, I will have to look into deeply I guess.

**Comment by priyonto** [comment]
I have investigated this issue. Tested with different tags but could not reproduce it on my end.

**Comment by priyonto** [comment]
@markoaamunkajo Please try to reproduce it. Thank you.

**Comment by markoaamunkajo** [comment]
1.1.3(299) I cannot reproduce this issue yet.

**Comment by markoaamunkajo** [comment]
Tested

2.5.9 df3 updated to 3.31.1
Cloud
Removing battery

In all cases I am able to delete sensor.
