### ISSUE TITLE
"updated ccyy-mm-dd hh:mm:ss +0000" should be more "friendly"

### ISSUE THREAD

**Issue by DG12** [ruuvi/com.ruuvi.station.ios#6]
After 24 hours the time updated switches from _m_ minutes _s_ seconds ago to  ccyy-mm-dd hh:mm:ss +zzzz format.
It seems unnecessary to display ccyy but more importantly the timezone is displayed as +0000

Perhaps simply mm-dd hh:mm would be better.

**Comment by rinat-enikeev** [comment]
@DG12 please check with 0.3(24)

**Comment by DG12** [comment]
Timezone is now correct(although unnecessary IMHO).
I know it's easiest to just show result from formatting. 
I'd like to see : if (updated year==current year) suppress CCYY.
I am not sure it is necessary or "friendly" to show seconds when last update was days ago.

label: enhancement (Or I think it's would be nicer if...)
Thanks for your work.

**Comment by rinat-enikeev** [comment]
@DG12 please check the 0.4(30)

**Comment by DG12** [comment]
Updated dow mon dd ccyy hh:mm:ss is much nicer. Thanks
