### ISSUE TITLE
Ask user to rate app and write a review

### ISSUE THREAD

**Issue by andreevdenis** [ruuvi/com.ruuvi.station.ios#600]
Use recommended use-flow from Apple
https://developer.apple.com/app-store/ratings-and-reviews/

Other requirements: 

1) it should pass at least 7 days since app install before asking for review
2) user should have at least 1 sensor added before asking for review
3) if user cancelled review flow - wait another 50 days before asking for review again (not sure if Apple recommendations have it or not)

**Comment by priyonto** [comment]
<img width="653" alt="Screenshot 2022-06-17 at 3 38 08 PM" src="https://user-images.githubusercontent.com/24395776/174309479-c5735948-f40d-4b46-a74e-82f884552a5e.png">

We can ask up to 3 times a year for review. The normal standard approach is asking based on app launch. For example, in the 50th, 100, and 200th launches of the app.

**Comment by priyonto** [comment]
> Other requirements:
> 
> 1. it should pass at least 7 days since app install before asking for review
> 2. user should have at least 1 sensor added before asking for review
> 3. if user cancelled review flow - wait another 50 days before asking for review again (not sure if Apple recommendations have it or not)

The implementation of 1 and 2 can be done. But, no 3 can't be done as Apple control this and we can't really trigger this. 

Here's what is currently implemented:
1. Check whether 7 days passed after app installation. 
2. Check whether 1 or more sensors are added. 
3. Ask for the review on the 50th, 100th, and 200th launches if 1 and 2 are satisfied. 

We can modify this later if needed. But for now, this seems like a good way to do it.

**Comment by markoaamunkajo** [comment]
I should see this next wednesday

**Comment by markoaamunkajo** [comment]
Moving to done no time to waste
