### ISSUE TITLE
Add German language to the app

### ISSUE THREAD

**Issue by andreevdenis** [ruuvi/com.ruuvi.station.ios#601]

**Comment by markoaamunkajo** [comment]
@priyonto It looks like it's possible that some strings might be missing.

![photo_2022-03-16 21 26 23](https://user-images.githubusercontent.com/50437378/158612533-380a7e22-682a-468a-a95a-2668214c416e.jpeg)

**Comment by markoaamunkajo** [comment]
QA passed
