### ISSUE TITLE
In claim sensor pop-up verify ownership button not visible on iPhone SE.

### ISSUE THREAD

**Issue by hakunti** [ruuvi/com.ruuvi.station.ios#602]

**Comment by markoaamunkajo** [comment]
Cannot reproduce on iPhone 7 with larger font used, this is likely SE specific.

**Comment by andreevdenis** [comment]
Can confirm for SE while Finnish language selected. With English language button stays clickable.

**Comment by markoaamunkajo** [comment]
Thanks for the help @andreevdenis !

**Comment by markoaamunkajo** [comment]
@andreevdenis could you help rechecking this issue?

**Comment by andreevdenis** [comment]
@markoaamunkajo not fixed in 214.

**Comment by Iikeli** [comment]
@markoaamunkajo @andreevdenis new build in firebase now.

**Comment by Iikeli** [comment]
@markoaamunkajo @andreevdenis can you re check this? The fix should now be in the firebase build.

**Comment by andreevdenis** [comment]
Button is fully operational. But can't scroll deep enough to see full last string in description.

![IMG_20211216_200745_135.jpg](https://user-images.githubusercontent.com/24788772/146416808-b586f795-c6d2-4906-8ea0-638701b776d4.jpg)

**Comment by Iikeli** [comment]
@andreevdenis fixed the truncation mode and added some extra spacing between the button and text. Could you check again with the new Firebase build?

**Comment by andreevdenis** [comment]
224:

https://user-images.githubusercontent.com/24788772/146570571-da54dcb0-3a7f-4bb1-bdbf-abfde520977f.mp4

**Comment by andreevdenis** [comment]
Button text should be "Vahvista Omistajuus". Maybe setting smaller inner padding for button will help?

**Comment by laurijamsa** [comment]
Build with this partial fix is available in TestFlight. Let's fix it better and then release asap to TestFlight and Production. Moving to In Progress.

**Comment by markoaamunkajo** [comment]
@andreevdenis could you check with your iPhone SE?

**Comment by andreevdenis** [comment]
Everything is good now
