### ISSUE TITLE
Ruuvi cloud error - Sensor already claimed

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station.ios#604]
Description:

If you try to add a sensor which is already added, it gives you a nice SQL error about it. Maybe it could be smart enough to not even offer you the opportunity to add it again (without deleting it first).

Steps:
1. User adds sensor and claimed it to cloud on other device
2. Then installs Ruuvi Station to iPhone and adds sensor first locally
3. Then signs into network and tries to claim this sensor

Error shown: sensor_already_claimed
![IMG_6553](https://user-images.githubusercontent.com/50437378/139784832-e509a88e-9c12-4b0d-8f25-58b84f431dec.PNG)

**Comment by priyonto** [comment]
@markoaamunkajo @laurijamsa I have encountered the issue when a sensor is claimed by someone, and another user added this locally and tries to claim.  What is the expected result here?

**Comment by andreevdenis** [comment]
In this case you'll get error from backend. Error field will contain masked email of sensor owner. 

You need to parse and extract this email from server error message and put it to sensor owner field. Also show message for user: 
Sensor already claimed by %masked_email%

Actually I was sure we have localized string for this, but it looks like we don't. And I'm just showing error from server as is. This part should be fixed for Android side too.

![image](https://user-images.githubusercontent.com/24788772/151425375-2358950c-a0b5-4510-b16f-af0d455976f7.png)
![image](https://user-images.githubusercontent.com/24788772/151425399-85aaafe2-ded7-495d-b006-a312204390c4.png)

**Comment by priyonto** [comment]
@andreevdenis Thank you for the comment. I was wondering how you showed the masked email on the sensor settings owner field. For example, I have added a local sensor in the device, how do I get the owner of that sensor without hitting the claim API that returns the owner email in the "error" key.

**Comment by markoaamunkajo** [comment]
QA passed
