### ISSUE TITLE
Allow firmware downgrade (when latest released version is lesser than currently installed)

### ISSUE THREAD

**Issue by andreevdenis** [ruuvi/com.ruuvi.station.ios#605]
It may already work this way - needs to be checked.

**Comment by priyonto** [comment]
@andreevdenis Is this actually possible? I thought downgrading was not "normally" possible?

**Comment by laurijamsa** [comment]
Downgrading is possible over the air but not from 3.x to 2.x firmware. This issue is mostly about 3.2.x to 3.1.x for example.

**Comment by priyonto** [comment]
I see. So, it's possible to downgrade to minor versions. May I know the process of the downgrade?

**Comment by priyonto** [comment]
@markoaamunkajo  Would you please do a double check to confirm whether this is already implemented or not? Thank you.

**Comment by andreevdenis** [comment]
Process of downgrading is the same as when you just updating fw. But there can be some logic that prevents from downgrading. See the code after checking current sensor fw. Expected logic: if current fw version != Latest available FW then you can update.

**Comment by priyonto** [comment]
Thank you @andreevdenis :) I will check on it.

**Comment by DG12** [comment]
There is always the erase and flash (I one has the POWER!). :-)

**Comment by priyonto** [comment]
@andreevdenis How this screen is handled in the android app? Is it showing "Downgrade" instead of the update if the current version is higher than the latest release? 

![IMG_5256](https://user-images.githubusercontent.com/24395776/155878676-3ce702f8-ad82-466a-acc3-f2a7c2b26f43.PNG)

**Comment by andreevdenis** [comment]
No. Update as usual

**Comment by priyonto** [comment]
Thank you. :)

**Comment by priyonto** [comment]
This is already taken care of here. If the current release version is not the same as the latest release it is showing the update option. I believe we can close this issue thereby.
https://github.com/ruuvi/com.ruuvi.station.ios/blob/758d7ccae9fb4229f0287798b2a0c91b48b896d0/station/Classes/Presentation/Modules/TagSettings/Submodules/DFU/View/DFUViewModel.swift#L251
