### ISSUE TITLE
A global view to display all the values on one screen

### ISSUE THREAD

**Issue by GregOriol** [ruuvi/com.ruuvi.station.ios#62]
The current layout of the app is nice as a display, but not very practical when we want to check all the values: scrolling full pages is long and you'd have to remember the other values you already saw to compare them.

The use case is: "is it colder in one room than in the other?"

A global view, maybe like the iOS's world clocks[1], could be more practical for this.

[1] on the iPhone => https://media.idownloadblog.com/wp-content/uploads/2014/04/iOS-7-Clock-app-World-Clocks.gif
on the iPad => https://s.aolcdn.com/hss/storage/midas/fb0efed9a0d0b08bb5161987a9eccfe8/200162350/clock-weather-ipad.jpg

**Comment by rinat-enikeev** [comment]
@laurijamsa could you please review the UX proposal?

**Comment by laurijamsa** [comment]
This feature is coming with the new UX. Closing this issue.
