### ISSUE TITLE
Graph shows many datapoints but export is empty - defect 0.7.6(212)

### ISSUE THREAD

**Issue by DG12** [ruuvi/com.ruuvi.station.ios#622]
After installing 0.7.6 (212) login in and EFEB has many many datapoints on the graph.
Export only exports heading(using 200 bytes!)
![EFEBgraph](https://user-images.githubusercontent.com/2365961/145244750-48036ddf-0cb2-46dc-a7c4-74e77f8dc00c.PNG)
![EFEB-export-200bytesNG](https://user-images.githubusercontent.com/2365961/145244761-8118317f-c035-4d42-a133-c2354463988c.jpeg)

**Comment by laurijamsa** [comment]
@markoaamunkajo please try to reproduce.

**Comment by DG12** [comment]
unable to reproduce at this time.  Version 0.7.6(224)
I will try again in a few hours.

**Comment by priyonto** [comment]
I was unable to reproduce this after several tries.
Device: iPhone 11 Pro Max, iOS 15.1
Simulator: iPhone 13, iOS 15.0
Ruuvi version: 0.7.6(206)

**Comment by DG12** [comment]
As ov version 0.7.7 After logging in, This sensor appears station IOS shows no data. 
It has been inactive since 10/30/21 as per android and webui
Until next time

![ruuviEFEB_no_last_data](https://user-images.githubusercontent.com/2365961/148836519-88190af3-d64e-4a81-b12d-426ceb0e87ad.jpeg)
e

removed EFEB, sign out, sign in.

Of course now it's REMOVED! 

until next time...
