### ISSUE TITLE
0.7.6(214) Sensor cards not removed when logging out from cloud

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station.ios#627]
Note to self: Check if this exists in new build

https://user-images.githubusercontent.com/50437378/145741233-63f8abb5-057b-4c3b-8760-e40d78392ce1.mov

**Comment by DG12** [comment]
version 0.7.7(256)
Worse  , All sensors now removed when logging out from cloud even those being updated  by bluetooth
![Logout-remove-all](https://user-images.githubusercontent.com/2365961/158664484-75684739-352c-425f-ac7c-a01268fbf6ab.jpeg)
.

**Comment by laurijamsa** [comment]
If you have claimed ownerships of those sensors that got removed, all is working according to the specification. And same way as on Androidd. Or did the app remove also those offline only sensors that are not owned by you?

**Comment by priyonto** [comment]
I believe this issue has been fixed a while back. Closing it.
