### ISSUE TITLE
0.7.6(223) Gatt sync is stuck at Success message

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station.ios#643]
Description:

User signed in to cloud and synced 3 sensors from cloud to Ruuvi Station.
Then he manually started GATT sync on charts page for 2 sensors.

Actual: when sync was completed it shows Success message with no way to reveal the clear and sync buttons.
Expected: message should be shown briefly. Syncronizing and Success statuses should also be per sensor, looks like if I sync one sensor synchronizing message is shown on all sensor pages.

![IMG_6893](https://user-images.githubusercontent.com/50437378/146183290-40290147-6ede-439d-ba7f-a643dc37b06d.PNG)

**Comment by priyonto** [comment]
@markoaamunkajo Is it allowed to sync multiple sensors at the same time? For example, click sync on sensor A, then closed that page, and then click sync on sensor B, and so on. Will the sync operation be concurrent? or only one at a time?

**Comment by markoaamunkajo** [comment]
@priyonto Yes user can sync multiple sensors at the same time independently.

**Comment by priyonto** [comment]
@markoaamunkajo Noted. The first issue about being stuck on the success message should be fixed on the current dev build 0.7.7(237). However, the second one is a bit tricky and complicated considering how it's currently built. Right now if sync is started and the page is closed, that sync affects all the sensors. What easily can be done is make it not affect other sensors and force "once sensor sync" at a time. To make concurrent sync will need more time and attention.

**Comment by laurijamsa** [comment]
Concurrent sync is something we can worry about later I would say. Let's make solo syncing work as well as possible first.

**Comment by priyonto** [comment]
Agreed. Thank you :)

**Comment by markoaamunkajo** [comment]
0.7.7(241) I have one BT sensor in my scooter outdoors it's signal is about -85dB

User taps sync button and Synchronising... status goes on for at least 1 minute before showing error
BTKit: failed to connect to peripheral in desired interval, button OK

Expected: Timeout is too long for user to understand what is going on. Can timeout be shortened? And show formatted error instead of code.

**Comment by priyonto** [comment]
@markoaamunkajo , The issue with showing the wrong message is rectified. However, the issue which sometimes being stuck "connecting" state if the tag is out of range has to be investigated more. I have been testing for a few hours today and it's not reproducible consistently. Hence, I advise creating a separate issue for that and keeping eye on that. #657

**Comment by markoaamunkajo** [comment]
Agreed
QA passed
