### ISSUE TITLE
0.7.6(223) On second device cloud sensor charts are only showing 2 days

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station.ios#644]
Description:

Device 1: iPhone 7, iOS 14.8
Device 2: iPhone 6 Plus, iOS 15.2

Second device shows 2 days history with same cloud account

Steps:
I logged into same cloud account on two phones.
The first phone was fresh install and synced me 10 days. Second phone was logged out from cloud, I signed in again. importing didn't add me any sensors just showed me empty background, I killed app. After restart I see sensors but history only shows 2 days.

Update:
Retried with GATT sync on second phone after disconnecting connected mode on first phone, then synced. Gatt sync is successful but it syncs only 3 days for me.

![IMG_6889](https://user-images.githubusercontent.com/50437378/146183752-0d659c40-29dd-44c1-8191-cea762cb1d85.PNG)

**Comment by markoaamunkajo** [comment]
I think I might understand what happened.

Steps:
I logged into same cloud account on two phones.
The first phone was fresh install and synced me 10 days. Second phone was logged out from cloud, I signed in again. importing didn't add me any sensors just showed me empty background, I killed app. After restart I see sensors but history only shows 2 days.

**Comment by markoaamunkajo** [comment]
I am seeing this error when trying to GATT sync on second device now:
![IMG_2445](https://user-images.githubusercontent.com/50437378/146186086-4e0becd7-e11a-4518-ab1e-f6a2f0b587c8.PNG)

**Comment by priyonto** [comment]
In my testing, only a fresh install retains 10 days history. As soon as the user logs out the persistent storage is cleaned out. And when the user logs back into the app, the cloud data is not being stored to the persistent storage as like the fresh install. I am unsure why.

**Comment by markoaamunkajo** [comment]
QA passed
