### ISSUE TITLE
Updating tag make others nonupdated

### ISSUE THREAD

**Issue by Bysmyyr** [ruuvi/com.ruuvi.station.ios#650]
I updated one tag from some old version to v3.31.1

All other tags went silent (in another phone too)

Trying to read them gives this error and updates that tag reading once but go back to silent.
![image](https://user-images.githubusercontent.com/3306756/146729728-c40f649c-86f5-4c49-bc2e-27bc28561ae6.png)

Removing tag and adding it back fixes the issue(also without updating tag)

**Comment by laurijamsa** [comment]
Thanks for the report. @markoaamunkajo please try to reproduce and provide more information if successful.

**Comment by priyonto** [comment]
I was unable to reproduce this after several tries. 
Device: iPhone 11 Pro Max, iOS 15.1
Ruuvi version: 0.7.6(206)

**Comment by priyonto** [comment]
I was unable to reproduce this on cloud sensors.
Device: iPhone 11 Pro Max, iOS 15.1
Ruuvi version: 0.7.6(206)

**Comment by priyonto** [comment]
I have updated the firmware to v3.33.1 on version 0.7.6(206) and was unable to reproduce this issue. 
Device: iPhone 11 Pro Max, iOS 15.1

**Comment by priyonto** [comment]
@markoaamunkajo Would you please try to reproduce it? Thank you.

**Comment by markoaamunkajo** [comment]
I cannot reproduce this issue either but I have a feeling this could be related and arises from some older app version https://github.com/ruuvi/com.ruuvi.station.ios/issues/679

Will move this one to done and continue with the mentioned card.
