### ISSUE TITLE
Unknown sensor RUUVI FB19 

### ISSUE THREAD

**Issue by DG12** [ruuvi/com.ruuvi.station.ios#651]
Ruuvi FB19, 38.00C 8.00% 1012.00 hpa
Updates every few seconds.
UUID FB19AEC7-DD87-4AC7-AD27-68C7D18
Not known by ruuviStation android.
Never seen by ruuviCollector
Don't know full MAC
My notes show I saw this previously on 2021-07-22 also  2021-05-29

**Comment by laurijamsa** [comment]
How is this issue related to the iOS mobile app?

Sounds like a RuuviTag with some really old firmware that your Android phone cannot hear for some reason right now.

**Comment by DG12** [comment]
I have pretty good records and I don't have any notes about FB19 other than the odd appearance on dates mentioned.
RSSI varies -90,-91,-93,-95,-89,-97 without moving the iPhone. I will walk around and see if I can get closer.

Note it has never shown up on station android that I noticed and with 2 years of history in ruuviCollector no entries for any MAC ending in FB19 is in the database.

I have FLEX available. Is there any information it can display that might help.
FLEX attempting to display system logs crashes.
whoops, on restart no FLEX. 
How do I get it to show up?

**Comment by laurijamsa** [comment]
I'm closing this as this seems not to be a bug in the iOS app.
