### ISSUE TITLE
If logged in using account 1, clicking login email link sent to account 2 doesn't do anything

### ISSUE THREAD

**Issue by andreevdenis** [ruuvi/com.ruuvi.station.ios#653]
Reproduce:

login in the app with account 1
request a login code for an account 2 (on station.ruuvi.com)
click the email login link on the phone that has account 1 logged in on the app
the app opens but nothing happens and account 1 stays logged in
I would expect the account 2 to login. But that could cause some confusion for the user because the logout confirmation message would not be shown. So maybe safer and more simple would be just to show a note with an OK button:

Strings already exist in localization:
      "en": "User %1$s is already signed in. If you'd like to use a different account, please sign out first and then try again.",
      "fi": "Käyttäjä %1$s on jo kirjautuneena sisälle. Mikäli haluat käyttää toista tiliä, kirjaudu ensin ulos ja yritä sitten uudelleen."

Android issue: https://github.com/ruuvi/com.ruuvi.station/issues/548

**Comment by markoaamunkajo** [comment]
QA passed
