### ISSUE TITLE
Sync button is not available after syncing

### ISSUE THREAD

**Issue by laurijamsa** [ruuvi/com.ruuvi.station.ios#657]
This is a user report.

"I changed the app language to French. After pressing synchronisation below the graphs it synchronized indeed but got stuck displaying 'Succés'. Changing the language back to English does not change this (status displayed on picture) The buttons Clear/Synchronize do not come back. I guess I have to reinstall the app ?"

![image](https://user-images.githubusercontent.com/1311912/148367991-7ba8f1bf-18cc-42bc-8ca5-b148585349a1.png)

Let's try to replicate this issue before start working on it.

**Comment by priyonto** [comment]
@laurijamsa Android does not have the sync and clear button but the iOS app has. Which one is intended?  Please share your thoughts on this.

**Comment by andreevdenis** [comment]
I hide sync and clear if last measurement was from the cloud. Use local sensors to compare behavior.

**Comment by priyonto** [comment]
Thank you @andreevdenis .

**Comment by laurijamsa** [comment]
Android has clear/sync button available on those nearby Bluetooth sensors that are advertising themselves as connectable ones. If your iOS device is in connected mode with a nearby Bluetooth sensor, I think Android doesn't show the sync/clear buttons on that sensor.

These clear/sync buttons are a bit confusing right now after we have introduced the Ruuvi Cloud. Before, users knew that syncing would deginitely mean syncing via Bluetooth. The clear button has not been easy to understand to users ever, because we explain nowhere what it will clear (it does clear only local history from the app, not history stored in the sensor). But making these buttons more user friendly will be a topic of another issue. This issue is about that those buttons will be hidden after successful Bluetooth sync in some cases on iOS.

**Comment by priyonto** [comment]
@laurijamsa , Thank you for your detailed insight about the whole thing. This is helpful. I was able to reproduce the issue. However, as my tags are connected through iOS, the android app was not showing them and that raised the question from my side. But, it's now clear.

**Comment by markoaamunkajo** [comment]
0.7.7(237) User has a sensor that is shared by a friend and showing the Ruuvi Gateway as source

However on charts page I see a sync button. If I try to sync it I get following error:

![IMG_1243DF076940-1](https://user-images.githubusercontent.com/50437378/150522586-9509a81f-1a3a-4921-9299-367f99c67bbc.jpeg)

**Comment by priyonto** [comment]
@markoaamunkajo , should we keep these clear and sync buttons for shared sensors?

**Comment by markoaamunkajo** [comment]
Android has logic to hide sync and clear if last update was from cloud. Maybe that is sufficient?
In my case my shared cloud sensor hasn't been seen for weeks btw, so there is no data available neither way.

**Comment by priyonto** [comment]
Yes, in iOS this issue occurs only for the shared sensor. And, I think we can hide these buttons if the sensor is shared because they are could data anyway.

**Comment by markoaamunkajo** [comment]
0.7.7(241)
@priyonto in case of cloud sensor that is owned by signed in user but signal is not in BT range we are not getting a clean timeout message.

Actual:
1. Sync button pressed
2. Connecting... (extended period of time)
3. BTKit Error shown

![IMG_3898538279E3-1](https://user-images.githubusercontent.com/50437378/150668450-563464c7-c957-4037-8f74-89c15e1c360f.jpeg)

Expected:
Show disconnected error or timeout error (if exists)

**Comment by markoaamunkajo** [comment]
QA passed
