### ISSUE TITLE
Sensor name is not showing fully

### ISSUE THREAD

**Issue by priyonto** [ruuvi/com.ruuvi.station.ios#662]
Issue: The sensor name is "Mökin serveriräkin yläosa" but on the homepage, the name only shows a partial part. 

Expected: Full name i.e. "Mökin serveriräkin yläosa" should be shown. 

![IMG_4957](https://user-images.githubusercontent.com/24395776/148826372-17d7bc86-6da1-4766-9dcf-75e0a5120891.PNG)

**Comment by laurijamsa** [comment]
Seems that we had a related issue: https://github.com/ruuvi/com.ruuvi.station.ios/issues/147

**Comment by priyonto** [comment]
Yes, this one is basically the same as the one I worked on yesterday.  Should I close the other one?

**Comment by laurijamsa** [comment]
Yes, the other one can be closed. Also Andtoid has one, please make sure with Denis that both iOS and Android UI/UX will be unified. https://github.com/ruuvi/com.ruuvi.station/issues/406

**Comment by priyonto** [comment]
@laurijamsa I think the issue needs a bit of discussion. Especially the UI is currently slightly different on both platforms[There are underlines on the sensor names on the Android, but that's not available on the iOS]. Do we need to consider that as well now or we will just focus on the multilabel tag name?

**Comment by priyonto** [comment]
@andreevdenis Is there any character limitation for the sensor names? If so, how many characters are allowed? For the record, the iOS app does not have any limitations. Please confirm what is the intended feature? Limited or unlimited?

**Comment by andreevdenis** [comment]
32 chars is the limit in Android app

**Comment by priyonto** [comment]
@andreevdenis  Is it the intended limit? Should we implement that on iOS too?

**Comment by laurijamsa** [comment]
Let's remove the underlining from Android. Sini-Maaria just confirmed this to me. Please create a ticket on the Android repo about this.

**Comment by priyonto** [comment]
@andreevdenis  I have created an issue on the android repo. 
https://github.com/ruuvi/com.ruuvi.station/issues/570

**Comment by andreevdenis** [comment]
Yes, limit should be implemented in iOS too.

**Comment by priyonto** [comment]
Thank you. I have created a new issue and will take care of it.

**Comment by markoaamunkajo** [comment]
QA passed on this card, limiting handled on other card
