### ISSUE TITLE
Add 32 characters limit on the sensor name similar to android and webUI

### ISSUE THREAD

**Issue by priyonto** [ruuvi/com.ruuvi.station.ios#668]
Related to #662

**Comment by laurijamsa** [comment]
On Android the limit is 32 characters, not 40

**Comment by priyonto** [comment]
@laurijamsa Thank you for the correction. :)

**Comment by laurijamsa** [comment]
There was a duplicate: https://github.com/ruuvi/com.ruuvi.station.ios/issues/590

I have closed it now.

**Comment by markoaamunkajo** [comment]
QA passed
