### ISSUE TITLE
Tag settings screen showing offset correction section for the users who is not the owner of the sensor

### ISSUE THREAD

**Issue by priyonto** [ruuvi/com.ruuvi.station.ios#670]
Issue: 
The offset correction section is showing for the user who is not the owner. 

Expected:
The offset correction section should be only visible to the owner. 

![IMG_708834D3C74C-1](https://user-images.githubusercontent.com/24395776/149124262-deb0c21a-0f72-4370-b811-89813ed991c4.jpeg)

**Comment by markoaamunkajo** [comment]
QA passed
