### ISSUE TITLE
Signing out does not remove the local sensors

### ISSUE THREAD

**Issue by priyonto** [ruuvi/com.ruuvi.station.ios#675]
Actual: Signing out does not remove the local sensors

Expected: Signing out should remove all claimed offline sensors, the sensors that have been updated from the cloud, and sensors someone shared with the user.

**Comment by laurijamsa** [comment]
No. Not necessary. We also don't want to start building cloud support for storing information of users' virtual sensors.

**Comment by priyonto** [comment]
Noted, Thank you.

**Comment by markoaamunkajo** [comment]
QA passed
