### ISSUE TITLE
0.7.6(206) Sensor not showing as connectable immediately after firmware update

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station.ios#679]
Description:

User updated sensor from 2.5.9 df 3 to 3.31.1
Sensor page doesn't update to show sensor is now connectable

User will need to either 1. kill app 2. remove battery from sensor and re-add it to see it's connectable and sensor page showing charts icon.

**Comment by ojousima** [comment]
As a background:
Sensors can send two type of advertisement packets: connectable or non-connectable. These packets further can include a "scan response" data which the phone can request after primary advertisement.

Connectable packets have two flags set: Connectable and Scan Response available. If the device scans the sensor advertisement, connectable sensor will send a scan response. Primary advertisement has the actual data payload, scan response has human-readable device name "Ruuvi 12AB" and UUID of Nordic UART Service.

Sensor sends a connectable advertisement if nothing is connected to sensor. After one device establishes a connection, sensor sends non-connectable advertisements as only one device can be connected at a time. The non-connectable advertisements let other devices, such as a Ruuvi Gateway, still pick up the data from the sensors.

**Comment by priyonto** [comment]
@ojousima Thank you for sharing the insights of internal signal processing. This is definitely helpful. :)

**Comment by markoaamunkajo** [comment]
0.7.7(257) iOS 15.4.

Looks like sensor is trying to show in new format after updating fw from 2.5.9 but the sensor settings page is stuck somewhere in between. The sensor page itself shows no icon for chart. See video:

https://user-images.githubusercontent.com/50437378/159200880-1d007df6-226d-4190-a1d1-6fabf0fc0d1c.mov

**Comment by markoaamunkajo** [comment]
1.0.0(262)
The firmware update process seems to be successful until I get shown this screen and the whole app is stuck here.

![IMG_8402](https://user-images.githubusercontent.com/50437378/160727922-94a88733-4868-416e-abb6-7faa20406329.PNG)

**Comment by priyonto** [comment]
@markoaamunkajo 

This popup is not configured to show on this page at all. I am wondering how this is visible in the firmware update screen. 
Would you please share the steps to reproduce this? Also, from which firmware you are trying to update? 2.5.9 DF 3? 

I have tried to update several times on my side with 2.5.9 DF3, and DF5 to the latest one and could not reproduce it yet.

**Comment by markoaamunkajo** [comment]
Now I had full success with update and sensor update was completed with sensor card updated correctly.
QA passed
