### ISSUE TITLE
0.7.7(233) Virtual sensor resets its values when other sensors added or removed

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station.ios#680]
Description:

User on iOS 15.2. added virtual sensor to Ruuvi Station.
He then adds a local sensor.

Actual: when he now goes to view his virtual sensor all values are showing "-". If he minimizes app values reappear. If he removes any sensor (local or cloud or sign out from cloud) virtual sensor will again show "-" values.

 Same happens on iOS 14.8 device.

https://user-images.githubusercontent.com/50437378/149446251-6f4fb311-d322-4ae8-8aea-5096b8f2402b.mov

**Comment by markoaamunkajo** [comment]
Should be fixed before release @priyonto

**Comment by priyonto** [comment]
Thank you for the reporting. Android does not have the virtual tags though. What will be the eventual step about this, remove virtual tags from iOS or adding virtual tags on android?

**Comment by laurijamsa** [comment]
We haven't decided yet if this feature will be deprecated eventually or not. Our original reason to launch this feature back in the days was to allow users to try out the app before purchasing physical sensors. But now when we have the Ruuvi Cloud, we could automatically share a couple of demo sensors to new users when they sign in first time.

**Comment by priyonto** [comment]
I understand. This makes complete sense. If that was the case I believe we can omit this from iOS and make the experience similar to Android. This is pretty big difference in experience.

**Comment by laurijamsa** [comment]
We have a separate task about adding some missing statistics endpoints. I'm not sure if we currently know how many of out users are actually using these virtual sensors.

**Comment by priyonto** [comment]
Good point. Then let's fix it and continue this feature until we have those data and make a decision?

**Comment by laurijamsa** [comment]
Yeah, let's fix this and get back to this decision about possible feature removal later on.

**Comment by priyonto** [comment]
Perfect. Thank you.

**Comment by markoaamunkajo** [comment]
QA passed
