### ISSUE TITLE
If Bluetooth is off many messages are annoying

### ISSUE THREAD

**Issue by DG12** [ruuvi/com.ruuvi.station.ios#7]
As of version0.1.7(0) , if bluetooth is not on, message is presented.
"Turn On Bluetooth to allow "Ruuvi Station " to Connect to Accessories" (accessories??)
Many, Many times.

Once is quite enough!

and
"Bluetooth is not enabled
Ruuvi Station need _(sp)_ to be able to listen for RuuviTags. Make sue that your bluetooth is turned on"

**Comment by rinat-enikeev** [comment]
Hi @DG12! Is this issue still actual?

**Comment by DG12** [comment]
I can no longer reproduce this issue. Consider it fixed.
Thanks
