### ISSUE TITLE
Unification: Cloud Mode

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station.ios#704]
Description:

We have added a new Cloud Mode toggle to App Settings in Android app based on customer feedback, and now need to add this to iOS app too.

This toggle is visible in App Settings only when user is signed in to Ruuvi cloud and at least one sensor was getting data from the cloud. (It's possible to sign in without Gateway and in this case Cloud mode is useless)

Switching Cloud Mode to enabled will stop listening Bluetooth messages from local Ruuvi sensors that are assigned to current users Ruuvi cloud account and instead will read and sync data only from cloud service. Ignore Bluetooth only for sensors that had synced data from the cloud.

Cloud Mode (toggle)
Explainer: Refresh nearby cloud sensors only from the cloud by ignoring their Bluetooth messages. Requires a Ruuvi Gateway router.

Localization strings exist in localization repo.

**Comment by andreevdenis** [comment]
I've made some corrections to task description.

**Comment by markoaamunkajo** [comment]
QA passed
