### ISSUE TITLE
Number of shared sensors doesn't format correctly

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station.ios#705]
Description:

User has signed to Ruuvi cloud and wants to share sensor. List showing number of sensors shared is formatting incorrectly.
![IMG_7886](https://user-images.githubusercontent.com/50437378/150753544-49a7df0d-5c3e-405a-84af-ff0a760e1709.PNG)

Expected:
Already Shared X/10 (X = number of shared sensors)

**Comment by DG12** [comment]
Please see same #701

**Comment by markoaamunkajo** [comment]
QA passed
