### ISSUE TITLE
Attempt to export sensor with no owner  hangs - 0.7.7(247)

### ISSUE THREAD

**Issue by DG12** [ruuvi/com.ruuvi.station.ios#710]
Pro sensor Ruuvi 9FE9: graph shows temperature and humidity from 01/20 through 01/27.

added 2/15/22:   "WIth no owner"

From Sensor Settings tap export.
Animated ruuvi eyecon spins until user aborts app
![RuuviProCantExport](https://user-images.githubusercontent.com/2365961/151427771-e74cb0b6-ddb2-4c0b-84ee-60c8ef605597.jpg)
.
originally submitted against version (244)

**Comment by priyonto** [comment]
@DG12 Is this sensor using DF3?

**Comment by DG12** [comment]
I just removed ad03 and added it , synced with it and attempt to upload.

hangs!

Revised issue title

**Comment by priyonto** [comment]
@DG12 Thank you for testing it and reporting it. Does it work if you claim the sensor?

**Comment by DG12** [comment]
Logout of dg@cccu.us, login to dgerman@real-world-systems.com, shows no owner, claim:'already claimed'

**Comment by DG12** [comment]
Logout of dgerman@real-world-systems.com , back to dg@cccu.us.shows no owner, claim:'already claimed'

**Comment by priyonto** [comment]
Fixed on #760
