### ISSUE TITLE
CSV export exports more than 10 days of data

### ISSUE THREAD

**Issue by laurijamsa** [ruuvi/com.ruuvi.station.ios#711]
The local database should be a 10 days FIFO, but it seems that in all scenarios it's not.

This is a sample export file that has more than 10 days of data:

[sample-export.csv](https://github.com/ruuvi/com.ruuvi.station.ios/files/7969644/sample-export.csv)

**Comment by DG12** [comment]
Interesting note . last few days have very few entries. 
WHY restrict to 10 days? Would it  be better to restrict to nnnn datapoints
"2022-01-19 18:56:29",2022-01-19T16:56:29.000Z,33.64,12.34,988.97,-0.368,-0.960,0.088,2.974,45,35356,4
"2022-01-19 19:11:31",2022-01-19T17:11:31.000Z,33.60,12.36,988.73,-0.372,-0.960,0.080,2.967,45,35707,4
"2022-01-20 08:53:26",2022-01-20T06:53:26.000Z,37.38,10.12,977.68,-0.368,-0.956,0.092,2.971,45,54896,4
"2022-01-20 09:54:24",2022-01-20T07:54:24.000Z,36.39,10.73,978.78,-0.364,-0.960,0.084,2.957,45,56319,4
"2022-01-22 17:19:54",2022-01-22T15:19:54.000Z,33.22,11.26,1018.91,-0.368,-0.952,0.084,2.939,45,2889,4
"2022-01-24 09:36:13",2022-01-24T07:36:13.000Z,36.45,10.22,1013.68,-0.360,-0.960,0.088,2.911,45,59301,4
"2022-01-24 09:56:57",2022-01-24T07:56:57.000Z,36.14,10.40,1013.83,-0.368,-0.960,0.092,2.911,45,59785,4
"2022-01-24 15:48:20",2022-01-24T13:48:20.000Z,33.92,11.93,1011.32,-0.364,-0.956,0.084,2.900,45,2454,4
"2022-01-28 22:27:04",2022-01-28T20:27:04.000Z,34.85,12.16,1008.66,-0.372,-0.960,0.080,2.925,47,15170,4
"2022-01-28 23:40:18",2022-01-28T21:40:18.000Z,40.35,9.00,1008.77,-0.364,-0.960,0.084,2.950,47,16879,4
"2022-01-29 03:08:34",2022-01-29T01:08:34.000Z,39.91,8.69,1005.84,-0.364,-0.960,0.080,2.950,47,21742,4
"2022-01-29 04:11:12",2022-01-29T02:11:12.000Z,39.82,8.71,1004.43,-0.364,-0.956,0.092,2.950,47,23204,4
"2022-01-29 05:00:35",2022-01-29T03:00:35.000Z,39.77,8.72,1003.56,-0.356,-0.956,0.092,2.953,47,24357,4
"2022-01-29 06:15:31",2022-01-29T04:15:31.000Z,39.56,8.80,1001.49,-0.364,-0.960,0.088,2.950,47,26106,4

**Comment by laurijamsa** [comment]
Restrict to 10 days because we have decided that the mobile apps support 10 days history and longer history browsing from the Ruuvi Cloud is possible with the web interface on station.ruuvi.com 

This decision may change later at some point, but for now, this seems like a bug with the database pruning.

**Comment by DG12** [comment]
Please consider:
I have a remote sensor 
[swampFlood](http://mybeacons.info/swampFlood.html)
Which I only visit once a week and ruuvistation.IOS only collects 7 samples during my visit (which are basically the same, i.e. ONE sample). I would really like to see more than the data from one visit.

**Comment by laurijamsa** [comment]
In this case, it would be a solid solution to download 7 days full local history from the sensor and after that export its CSV file if you'd like to store the history. We're considering if mobile devices could store data to the Ruuvi Cloud in the future, but right now, only Ruuvi Gateways are allowed to do so.

**Comment by DG12** [comment]
Thanks. Good idea. 
alternate/additional to mobile device -> cloud 
could be CSV -> cloud

**Comment by DG12** [comment]
Requiring a gateway to have access to more than 10 days for graphing or export seems unnecessary.

**Comment by markoaamunkajo** [comment]
Reproduced, this is a RuuviTag Pro.

[Ruuvi 636A_20220309-0953.csv](https://github.com/ruuvi/com.ruuvi.station.ios/files/8211310/Ruuvi.636A_20220309-0953.csv)

**Comment by markoaamunkajo** [comment]
QA passed
