### ISSUE TITLE
Firmware update popups for data format <5 users

### ISSUE THREAD

**Issue by laurijamsa** [ruuvi/com.ruuvi.station.ios#739]
Show the popup in these scenarios:

1) When user browses first time to a sensor that is broadcasting in older than 5 data format. Remember selection if user cancelled.
2) When user tries to claim the ownership and sensor is broadcasting in older than 5 data format. Do not remember selection if user cancelled.

Popup content:

**Seems that your sensor is using an old firmware software version. To access new features such as history graphs, alerts and cloud services, updating is mandatory.**

Show updating instructions (this forwards to the DFU process)
Cancel (this shows the second popup)

Another popup that is shown only if user taps Cancel on the first one:

**Are you sure? Without updating, you won't be able to claim ownership of the sensor, download history graphs and set alerts. The update includes also bug fixes. If you cancel now, you can start the update process again from the sensor's settings page.**

Show updating instructions (this forwards to the DFU process)
Cancel (this cancels and selection is stored locally until app uninstall (in the case 1 only))

**Comment by priyonto** [comment]
I agree with this implementation. However, a long message like these especially the second one will not look good in iOS default popup/alert.

**Comment by laurijamsa** [comment]
But it works and it seems to be scrollable:

![image](https://user-images.githubusercontent.com/1311912/154099597-05c9cbf9-1d47-4f45-a75b-ad595bda365c.png)

**Comment by priyonto** [comment]
Yes, it will work. I was referring to how it might look. :)

**Comment by DG12** [comment]
It might be a good idea to store the version and data format in the cloud.
several reasons including not having to ask user as well a send periodic ( careful there only one per user not per sensor) email explaining new version available.
Actually is there another way for a user tom know about "new and improved" version?

**Comment by priyonto** [comment]
@laurijamsa If a user has for example 5 cards with data format less than 5, are we going to show the popup for all the cards? 
For example:
On the card page, I swiped to Card A, show the popup there, user taps Cancel, and swipe right to go to Card B, which is also a tag with DF < 5. Are we going to show the alert again?

**Comment by laurijamsa** [comment]
> Are we going to show the alert again?

I think yes, we can keep this specification. But let's make this feature it so that we can enable the feature (the popups on <DF5 sensors) remotely, like discussed mutually. And before enabling this, we also decided to see first how many of our users actually have <DF5 sensors in their app.

**Comment by priyonto** [comment]
Agreed. The plan is to implement this and enable this from remote based on the taken data from analytics.

**Comment by markoaamunkajo** [comment]
Worked me like a charm. QA passed.
