### ISSUE TITLE
Sensor sends unrealistic values must not be displayed 

### ISSUE THREAD

**Issue by DG12** [ruuvi/com.ruuvi.station.ios#741]
Sensor 6e29 was working find UNTIL
I dropped it in the snow and an evil cord chewing monster grabbed it :-)

Hex values  943C°C 9C40% FFFFkpa

I suggest that ANY value outside the environmental range be surpassed (including humidity > 100%)
![6e29_broken](https://user-images.githubusercontent.com/2365961/154273761-a705d722-26fa-477a-b44f-4689dc9e0cee.PNG)

![MollyWithCord copy](https://user-images.githubusercontent.com/2365961/154272538-30e0c052-535d-422c-83ea-d92e8562a674.JPG)

**Comment by ojousima** [comment]
This seems like N/A values are getting rendered as physical values

**Comment by laurijamsa** [comment]
I believe this is not valid in the latest build anymore because it includes an enhanced support for those sensor that have no all sensors on board. Assigning to Marko to recheck. Please close if not valid anymore.

**Comment by markoaamunkajo** [comment]
Correct, these issues seem solved to me. Closing card.

**Comment by DG12** [comment]
This ruuvi  6e29 has a broken(?) BME280 and advertises:

7FFF for temp and 0000 for air pressure 

version 1.0.0(278)
Please reopen this issue
![Ruuvi 6E29 bad values](https://user-images.githubusercontent.com/2365961/162431181-e8d43322-74b3-406b-9fed-7d98b4804c04.png)
e

**Comment by laurijamsa** [comment]
If a sensor advertises 00000 as air pressure, it is a valid value. Also 7FFF for temp is a valid reading.

See: https://docs.ruuvi.com/communication/bluetooth-advertisements/data-format-5-rawv2

**Comment by DG12** [comment]
Even if a (broken) sensor sends values outside or real-world reasonable values, station should ignore them, otherwise credibility is lost on other values and other ruuvis.

FYI 
"Lowest non-tornadic atmospheric pressure ever measured was 870 hPa (0.858 atm; 25.69 inHg)
highest was 1083.8mb = hPa (32.00 inHg) at Agata, Siberia, Russia (alt. 262m , 862ft) corresponds to being at 600 m (2,000 ft) below sea level!"

Currently station "corrects" values sent by sensors "at the users discretion"

**Comment by laurijamsa** [comment]
I dont't agree that it would be client app's job to limit the measurement scale that we have specified in the datasheet. If a sensor is broken, it should broadcast "not defined" like the dataformat specification states.

However, seems that in some rare cases like yours, the firmware application didn't manage to know if the IC chip sensor was ok or not. And in this case it didn't return not defined like it was supposed to. If there is a possibility to enhance the firmware app to understand better if the measurement results are valid, that would be something we could look into. But trying to guess this on the client side by limiting the scale we promise users they can measure, is not a good approach IMO. Tagging @ojousima in case he would like to open a fw issue ticket about this.
