### ISSUE TITLE
Improve cloud sync queue 

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station.ios#746]
Discuss with Denis about sync queue related to syncing settings changes between app and cloud

**Comment by priyonto** [comment]
@andreevdenis May I ask you to summarize your approach on the android app regarding this, please? Thank you.

**Comment by andreevdenis** [comment]
My approach here is simple: user shouldn't care if he got troubles with internet or AWS is down when he does some actions in app. If some action in app require to do the same in the cloud we shouldn't show errors to user when he got no Internet. (For example removing sensor require unclaiming it in the cloud)

I've created new table to store network requests in case we need to repeat them.

Fields:
id autoincrement
type of request
status of request
unique key specific to this type of request
request date
success date
atempts counter
request data (JSON)

Types of request: 
    UNCLAIM(1),
    UPDATE_SENSOR(2),
    UPLOAD_IMAGE(3),
    SETTINGS(4),
    UNSHARE(5),
    RESET_IMAGE(6),
    SET_ALERT(7);

Status of request:
    READY(0),
    SUCCESS(1),
    OVERRIDDEN(2),
    PARSE_FAIL(3),
    FAILED(4);

So if user is deleting claimed sensor we should delete sensor from local db as usual and also register request of type UNCLAIM and try to execute this request right away. We create request with status READY. If request is exequted successfully we change status to SUCCESS (or just delete it from requests table).

You can implement something similar.

**Comment by andreevdenis** [comment]
We call it "to invent bicycle" among developers in Russia. Not sure if it's international or not. I was trying to find ready to use solution but wasn't successfull

**Comment by priyonto** [comment]
Thank you so much @andreevdenis for explaining the workflow. I believe we can do exact same implementation on iOS too. I will ask you though if there's anything when working on it. For now the idea is pretty clear.

**Comment by markoaamunkajo** [comment]
@priyonto This is still an issue with 2.0

Tested with internet connection disabled
Changed background photo and offset
Locally settings were stored correctly

When internet connection returned app returned wrong values from the cloud and old background photo was synced to app.

**Comment by priyonto** [comment]
This was never implemented due to other urgent issues and this will take good amount of time to implement. This will affect the whole app :) 

> @priyonto This is still an issue with 2.0

**Comment by markoaamunkajo** [comment]
@priyonto 

Tested with this one by adding a Bluetooth sensor when in Cloud mode and phone in airplane mode

I added calibration setting
The updated counter went crazy
And then I'm clearing the local history
Chart looks weird

https://drive.google.com/file/d/1r2JH-q5Zt78nWqE_28AwgvI-2vAz2fG2/view?usp=share_link

**Comment by markoaamunkajo** [comment]
Discussed in dm, moving to done

**Comment by priyonto** [comment]
Reopened as I noticed some minor issues.

**Comment by markoaamunkajo** [comment]
QA passed
