### ISSUE TITLE
Unify rounding values with Android and WebUI

### ISSUE THREAD

**Issue by priyonto** [ruuvi/com.ruuvi.station.ios#748]
The rounding approach of values is not the same as the Android and WebUI. It should be the same and the dissimilarities in the values should be eliminated. 
<img width="367" alt="Screenshot 2022-02-22 at 4 48 43 PM" src="https://user-images.githubusercontent.com/24395776/155117420-5b81d0c7-967f-4366-bf72-817532e23280.png">

**Comment by markoaamunkajo** [comment]
QA passed
