### ISSUE TITLE
Remove/Enhance vertical synchronization behavior  of chart

### ISSUE THREAD

**Issue by priyonto** [ruuvi/com.ruuvi.station.ios#750]
The charts for temperature, pressure and humidity are vertically and horizontally synced. And right now trying to align a particular property e.g temperature, humidity or pressure chart horizontally affects other properties as well due to the lock behavior. 

https://user-images.githubusercontent.com/24395776/155272538-86b44556-8188-4aca-b87a-8328100583d9.MOV

**Comment by markoaamunkajo** [comment]
QA passed
