### ISSUE TITLE
Hide charts for missing sensors (pressure for example)

### ISSUE THREAD

**Issue by andreevdenis** [ruuvi/com.ruuvi.station.ios#751]
![image](https://user-images.githubusercontent.com/24788772/155284581-54c02332-57cf-4e6c-8284-c8165ba2d511.png)
![image](https://user-images.githubusercontent.com/24788772/155284605-a0cf7c25-e755-4d26-853c-c0354b837d22.png)

**Comment by DG12** [comment]
Looks good to me, only graphs for temperature and humidity on Pro sensor.

Perhaps icon on main card should be suppressed  as well?

**Comment by markoaamunkajo** [comment]
0.7.7(250) We should also hide Offset Correction for missing sensor, this is currently visible in Sensor Settings

**Comment by markoaamunkajo** [comment]
Sorry I still spotted it in CSV export and it's showing -0.01. I'm guessing we should either remove this column or show "-" instead @laurijamsa ?

**Comment by markoaamunkajo** [comment]
[Ruuvi 636A_20220309-0953.csv](https://github.com/ruuvi/com.ruuvi.station.ios/files/8211302/Ruuvi.636A_20220309-0953.csv)

**Comment by laurijamsa** [comment]
> I'm guessing we should either remove this column or show \"-\" instead @laurijamsa ?

Removing the column sounds good to me. Make sure that Android and iOS will behave the same.

**Comment by priyonto** [comment]
> Removing the column sounds good to me. Make sure that Android and iOS will behave the same.

I have used '-' in the current build to keep it similar to other fields with empty values on iOS. But, on android empty values show as '0'. 
We have to either make iOS '0' or android to '-' if we want to make it similar.

**Comment by andreevdenis** [comment]
I vote for showing empty value instead of hiding column. Changing columns count may interrupt some logic that users have: they may upload these csv's somewhere.

**Comment by priyonto** [comment]
> I vote for showing empty value instead of hiding column. Changing columns count may interrupt some logic that users have: they may upload these csv's somewhere.

I agree with this.

**Comment by laurijamsa** [comment]
Yes it is a good point. It is all right to keep it there but fix the values.

**Comment by markoaamunkajo** [comment]
"-" used in iOS and GATT synced data also showing this for pressure, QA passed.
