### ISSUE TITLE
Improve timeline for graphs (dates and time) 

### ISSUE THREAD

**Issue by priyonto** [ruuvi/com.ruuvi.station.ios#753]
Android issue: https://github.com/ruuvi/com.ruuvi.station/issues/241

**Comment by laurijamsa** [comment]
A user feedback (build 0.7.7 255)

![image](https://user-images.githubusercontent.com/1311912/158495830-6cb724e9-33c0-44ef-ab81-6c66a5e666d5.png)

**Comment by priyonto** [comment]
Thank you for reporting. I believe it is showing 48 hours data on the chart. However, the x-axis date time label is causing the confusion since it is showing six minutes less. I will investigate to improve this UX.

**Comment by markoaamunkajo** [comment]
@priyonto 1.0.0(273)

Not at all optimal behavior on iPhone 6S Plus OS 15.4


![IMG_CB9CA2A7E9F1-1](https://user-images.githubusercontent.com/50437378/161738633-7261bf67-56f7-4aa4-a3e2-f87a3172f8a1.jpeg)

https://user-images.githubusercontent.com/50437378/161738668-637a94b9-9af3-4fec-90a1-42685cf5eb32.mov

**Comment by markoaamunkajo** [comment]
QA passed
