### ISSUE TITLE
Rounding issue when plotting charts (all units)

### ISSUE THREAD

**Issue by priyonto** [ruuvi/com.ruuvi.station.ios#754]
The data points storing algorithm is not probably similar to android and it's causing unexpected behavior in charts and showing not showing similar charts. 

![154664260-a239613d-8dec-4740-a17e-9280e17da4ca](https://user-images.githubusercontent.com/24395776/155389795-54c6486c-b7c3-4299-87a2-b9224e0ab15a.jpeg)

Expected: The chart should look the same on both apps and iOS should adopt the android app approach.

**Comment by laurijamsa** [comment]
Something weird is going on. If you compare the graphs, only the air pressure graph on iOS is looking like some of its data has been pruned when plotting. Could this be a rounding issue when calculating inHg from the Pascals? Can you reproduce this by using hPa setting?

**Comment by priyonto** [comment]
Yes, that's a good observation. I also noticed that but I was not sure what is exactly causing this issue. That's why opened this separate card to investigate this with setting up different units.

**Comment by markoaamunkajo** [comment]
QA passed
