### ISSUE TITLE
Check  conversions with Android and WebUI

### ISSUE THREAD

**Issue by priyonto** [ruuvi/com.ruuvi.station.ios#759]
To make a unified user experience it is essential to show the same value on all the platforms (iOS, Android & WebUI). 
Recently an issue (#748) has been discovered where the temperature value was not matching with the Android and WebUI due to a rounding problem. That issue has been rectified, however, double-checking other units are needed as well.

**Comment by priyonto** [comment]
@markoaamunkajo Would you please do some testing on this? Thank you.

**Comment by markoaamunkajo** [comment]
QA passed
