### ISSUE TITLE
sign in login screen nits  0.7.7(2560

### ISSUE THREAD

**Issue by DG12** [ruuvi/com.ruuvi.station.ios#798]
color:black Sign in
color:white Login to 
font-family:?? Ruuvi. S.B rUUVi   ??
Station

... existing Ruuvi account

![login-signin](https://user-images.githubusercontent.com/2365961/158667767-396e4852-294f-41b0-85c4-1fd3ce396c3f.PNG)

**Comment by laurijamsa** [comment]
We already had an issue about this and it passed QA ok. Its implementation specification was: "unify with Android".  If you find differences with Android or other bugs related to this, please let us know. Closing this one.

The original issue: https://github.com/ruuvi/com.ruuvi.station.ios/issues/480
