### ISSUE TITLE
After signout all sensors are removed

### ISSUE THREAD

**Issue by DG12** [ruuvi/com.ruuvi.station.ios#799]
Signed in.
Most sensors are updated via Bluetooth.
Sign out.
All sensors are removed. Showing "blank" screen.
Add a "new" sensor. (perhaps "new" should be removed in general)

**Comment by laurijamsa** [comment]
Thanks for the suggestion. However, I think it is the same on Android, so this is not an iOS issue. Let's open new string suggestions over here: https://github.com/ruuvi/station.localization
