### ISSUE TITLE
Improve the performance of cards screen

### ISSUE THREAD

**Issue by priyonto** [ruuvi/com.ruuvi.station.ios#802]
**Current:** A UI glitch/lag is noticed when the app is performing cloud sync in the background. 
Build 0.7.7 (257)
Device: iPhone XS Max 
iOS: 15.3.1

**Expected:** There should be no lag. 

**Reference:**

https://user-images.githubusercontent.com/24395776/158957160-55fadbbc-2c10-4e5c-91d8-52df1b5137e6.MP4

**Comment by priyonto** [comment]
We have decided to rewrite the Cards page with SwiftUI to make it better and future-proof.

**Comment by markoaamunkajo** [comment]
Asked more feedback on iOS channel

**Comment by markoaamunkajo** [comment]
QA passed
