### ISSUE TITLE
0.7.7(257) one shared sensor showing not smooth chart

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station.ios#805]
0.7.7(257), ios 15.4.

One shared sensor from Elias is showing me not smooth chart, export seems to show different resolution than other sensors.

It's smooth on android and web. It seems like iOS rounds graph values to 0.1 resolution. The temp is relatively stable where that sensors it so that's why you can notice it.

![photo_2022-03-21 13 02 23](https://user-images.githubusercontent.com/50437378/159212001-a536a4bd-9e2b-4d83-9201-69738f59b54e.jpeg)
[BrewTag_20220321-0913.csv](https://github.com/ruuvi/com.ruuvi.station.ios/files/8313382/BrewTag_20220321-0913.csv)

**Comment by laurijamsa** [comment]
Seems that we already had an issue about this but we just didn't know that it's not only the inHg but with all units. Closing this one as a duplicate.

https://github.com/ruuvi/com.ruuvi.station.ios/issues/754
