### ISSUE TITLE
Add unit detail for movement icon

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station.ios#815]
Description:

Add unit detail for movement icon on sensor card (currently only has icon).
Unit: movements

Web already uses string "times" which will be renamed.

<img width="352" alt="Screenshot 2022-03-29 at 8 04 35" src="https://user-images.githubusercontent.com/50437378/160511915-ab0a1f43-c29a-4909-9d88-fa53beba4816.png">

Card for Android: https://github.com/ruuvi/com.ruuvi.station/issues/642

**Comment by markoaamunkajo** [comment]
@priyonto Fixed unnecessary capitalization for French https://github.com/ruuvi/station.localization/pull/95
When this merged can move to done

**Comment by priyonto** [comment]
@markoaamunkajo  Done merging, and will be affected on the next build. Closing this one.
