### ISSUE TITLE
Onboarding: Ruuvi Cloud

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station.ios#817]
Description:

Please add Ruuvi Cloud page to Onboarding screens after Set Alerts and before Let's Get Started.

![ruuvi-cloud-design](https://user-images.githubusercontent.com/50437378/160521150-052b71f9-be06-4c69-bb06-dc64a9ea8336.jpg)

"Sign in" button opens Ruuvi Cloud sign in. When user completed sign in user will be forwarded to Let's Get Started page.

"Details" button will open popup with title "Ruuvi Cloud".

Benefits:
● Sensor names, background images, offsets and alert settings will be securely stored in the cloud
● Access sensors remotely over the Internet (requires a Ruuvi Gateway)
● Share sensors with friends and family (requires a Ruuvi Gateway)
● Browse up to 2 years of history on station.ruuvi.com (requires a Ruuvi Gateway)

Buttons: Close

"Skip" button will open popup with title "Are you sure?" 

Benefits:
● Sensor names, background images, offsets and alert settings will be securely stored in the cloud
● Access sensors remotely over the Internet (requires a Ruuvi Gateway)
● Share sensors with friends and family (requires a Ruuvi Gateway)
● Browse up to 2 years of history on station.ruuvi.com (requires a Ruuvi Gateway)

Buttons: "Yes, skip" "Go back"
Yes, skip will move forward to Let's Get Started screen.

Card for Android: https://github.com/ruuvi/com.ruuvi.station/issues/644

**Comment by markoaamunkajo** [comment]
1.1.0 (282) @priyonto 

1. Details popup text is hopelessly small to read on my iPhone7 and sad old eyes. Let's make font bigger maybe try +2 and see if it still fits on iPhone SE screen

2. There should be new language string used specifically for button Sign in, since button is small and here we could use separate more correct and shorter string. Current: "Kirjaudu sisään" New: "Kirjaudu"

3. FI translations have been already added to dev

4. Re-align Ruuvi Cloud, see photo below
![realign](https://user-images.githubusercontent.com/50437378/163673093-1d815098-3ff3-41de-b68c-fb0ffa222cd8.jpg)

**Comment by markoaamunkajo** [comment]
@priyonto  One more thing we have overlooked. When user already signed in but he decides to skip back pages on onboarding the sign in button should be a sign out button and user would be able to restart signin process.

**Comment by priyonto** [comment]
> @priyonto One more thing we have overlooked. When user already signed in but he decides to skip back pages on onboarding the sign in button should be a sign out button and user would be able to restart signin process.

Thank you for all the feedbacks. However, if user taps on sign out what will happen? Should we show any popup for sign out or just sign out the user and show sign in button? 

Right now on the iOS app after user sign in, the sign in button is hidden.

**Comment by markoaamunkajo** [comment]
@priyonto we should use same process as when choosing main menu item "sign out", which shows confirmation popup and removes sensor cards if user chooses "OK".

**Comment by priyonto** [comment]
@markoaamunkajo This is noted. That's going to add quite some work. 😅

**Comment by andreevdenis** [comment]
> @priyonto One more thing we have overlooked. When user already signed in but he decides to skip back pages on onboarding the sign in button should be a sign out button and user would be able to restart signin process.

@markoaamunkajo I don't like this idea. This is really strange UI/UX for onboarding.

**Comment by priyonto** [comment]
I somewhat agree with this. This seems a lot for the onboarding.

**Comment by andreevdenis** [comment]
Maybe it will be better to hide buttons if user already signed in and show text: "Great! You already signed in!"

**Comment by priyonto** [comment]
I kept the details button now but hide the sign in button. But this sounds like a good plan to me.

**Comment by markoaamunkajo** [comment]
"Great! You already signed in!" let's do this, easy and straightforward @andreevdenis @priyonto

**Comment by priyonto** [comment]
Should we also hide the "Details" button too?

**Comment by markoaamunkajo** [comment]
It's fine no need to hide.

**Comment by priyonto** [comment]
Also, where should we show the message?

**Comment by markoaamunkajo** [comment]
I think replace the texts is probably best

**Comment by priyonto** [comment]
I was also thinking the same. But, probably we should hide both of the texts and just show the text: "Great! You already signed in!"

**Comment by markoaamunkajo** [comment]
Lets go with showing the top text and replacing bottom text and see how it looks like, I think this likely gives idea what to do on the page and informs user that this is done already.

**Comment by priyonto** [comment]
Sure. Let's see how it turns out.

**Comment by markoaamunkajo** [comment]
QA passed
