### ISSUE TITLE
Unify chart downsampling behaviour with android app

### ISSUE THREAD

**Issue by priyonto** [ruuvi/com.ruuvi.station.ios#827]
Base discussion:
https://github.com/ruuvi/com.ruuvi.station/issues/369

**Comment by markoaamunkajo** [comment]
Those are some fine big dots you got there @priyonto ! Can we make them small like in normal situation? It seems to normalise after over a minute has been recorded.

https://user-images.githubusercontent.com/50437378/195967912-d767703b-048e-48ae-bc97-bbcc1dbfda4e.MP4

**Comment by priyonto** [comment]
This is a bug. I have fixed it, and should not be seen in the next dev build. At this moment, we decided to disable the dots completely for all the devices until we figure out a better way to do it.

**Comment by markoaamunkajo** [comment]
QA passed
