### ISSUE TITLE
1.0.0(271) GATT sync is telling me Bluetooth is off

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station.ios#833]
Description:
Clean install, added couple of local BT sensors

This build version is telling me when trying to GATT sync on charts page that Bluetooth is switched off. It happens on all sensor cards.

https://user-images.githubusercontent.com/50437378/161666384-a08ea66b-c7b8-4baa-8dec-c16e3d3baa74.MP4

**Comment by priyonto** [comment]
Thank you for the feedback. I think I know why is this happening. Looking into it.

**Comment by markoaamunkajo** [comment]
QA passed
