### ISSUE TITLE
Attempt to share with owner : internal error 1.1.0(280)

### ISSUE THREAD

**Issue by DG12** [ruuvi/com.ruuvi.station.ios#858]
Mistakenly attempted to share with owner causes 
Error
Internal error
OK
![ShareWithOwner](https://user-images.githubusercontent.com/2365961/162581898-d301f8d3-1e1f-427c-beb8-a8a1fbff0cec.PNG)

**Comment by laurijamsa** [comment]
Also Android gives an internal error, I assume it's coming from the backend. Better to aim to "fix" this server side instead client side. Closing this one.
