### ISSUE TITLE
Sensor usually out of range of station, not within range of gateway now displays nothing  1.1.0(280)

### ISSUE THREAD

**Issue by DG12** [ruuvi/com.ruuvi.station.ios#861]
Swamp 22AB is within range of the station only about 15 minutes one a week. 
Previously station displayed the most recent data, including the graph.
As of version 1.1.0(280)  now displays:

_F

And no recent values for battery's,y,z ...

This may be due to the fact that firebase required deinstall of app and data before installing new version.

cloud query reports:
"result": "success",
    "data": {
        "sensor": "F7:B7:74:47:22:AB",
        "name": "Swamp 22AB",
        "offsetTemperature": 0,
        "offsetHumidity": 0,
        "offsetPressure": 0,
        "picture": "https://prod-sensor-profile-pictures.s3.eu-central-1.amazonaws.com/8b1dad36-7fb9-4fe3-ba1a-dccc7cdd02bc.jpg",
        "measurements": [],
        "total": 0,
        "public": 0,
        "table": "prod-SensorDataReduced",
        "resolvedMode": "sparse"

**Comment by DG12** [comment]
![22AB_nodata](https://user-images.githubusercontent.com/2365961/162593277-78af7a9e-d3f2-42be-b7e9-dae901bc9e89.PNG)
![22AB_Fonly](https://user-images.githubusercontent.com/2365961/162593278-8e827a07-1eed-4394-8724-f5489f4bd033.PNG)
![22AB_nograph](https://user-images.githubusercontent.com/2365961/162593279-559874a6-7ad7-43a6-938c-2fb11aaf0644.PNG)

**Comment by markoaamunkajo** [comment]
QA passed
