### ISSUE TITLE
First card from the list doesn't update data until second card is visited

### ISSUE THREAD

**Issue by priyonto** [ruuvi/com.ruuvi.station.ios#873]

**Comment by markoaamunkajo** [comment]
Replicated iOS14.8 1.1.0(283), only first sensor card not updating even though it looks like synchronizing with cloud no new sensor data is fetched.

**Comment by markoaamunkajo** [comment]
Discussed in dm, issue seems to persist in build 1.1.0(284) @priyonto

**Comment by markoaamunkajo** [comment]
Discussed in dm, issue seems to persist in build 1.1.0(285) @priyonto

**Comment by markoaamunkajo** [comment]
Ignore my previous comment. Discussed more on dm and it looks like Android and iOS behavior is very similar now. At least I don't see any single card update getting stuck.
