### ISSUE TITLE
Implement a battery capacity indicator

### ISSUE THREAD

**Issue by laurijamsa** [ruuvi/com.ruuvi.station.ios#886]
Same description as on Android: https://github.com/ruuvi/com.ruuvi.station/issues/335

Let's finally implement this simple low battery indicator using the same logic we are using when updating the firmware, it's described here: #538 

The message should be shown next to the voltage reading in the sensor settings page:

<img width="316" alt="image" src="https://user-images.githubusercontent.com/1311912/164592558-cddd974a-f71c-4dcd-83b8-0a3ac6f21be8.png">

English strings: "(Replace battery!)" "(Battery OK)"
Finnish strings: "(Vaihda paristo!)" "(Paristo OK)"

It would look like this basically then:

**Battery Voltage** _____________ (Replace battery!) 2.152 V
**Battery Voltage** _____________ (Battery OK) 2.752 V

**Comment by markoaamunkajo** [comment]
1.3.0(307) @priyonto 

Specs from this card
https://github.com/ruuvi/com.ruuvi.station/issues/538

if temp is less than -20C, low battery threshold = 2V
else if temp is less than 0C, low battery threshold = 2,3V
else low battery threshold = 2,5V

![IMG_8881](https://user-images.githubusercontent.com/50437378/177063480-e63d3b6b-0013-43cf-99e2-c6edeb4fe391.PNG)
https://github.com/ruuvi/com.ruuvi.station/issues/538

Looks like low temperature -20C battery warning is not working correctly.
![IMG_8882](https://user-images.githubusercontent.com/50437378/177063475-7cab6233-b0c3-4cf2-bbe3-cc5a0d1577fe.PNG)

**Comment by markoaamunkajo** [comment]
![IMG_B39DE62A6BCA-1](https://user-images.githubusercontent.com/50437378/178181527-09044b37-783a-4b1c-b87a-c7213c1dd10e.jpeg)

@priyonto I'm guessing battery is not known to be ok or not ok if sensor was seen long time ago. Expected: Don't show battery status when last known value is "-"

**Comment by markoaamunkajo** [comment]
QA passed
