### ISSUE TITLE
Calibrated values not shown on sensor page

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station.ios#887]
Description:

Ticket source: feedback email

Wondering if there is some sort of bug, since Ruuvi app doesn't show custom humidity on the sensor page, instead it's showing me the uncalibrated one. Looks like it's updating value to the calibrated one with few seconds delay and sometimes update doesn't happen at all. Charts view shows the readings correctly all the time.

(user has also Ruuvi Gateway)

------------------------------------------
Device: iPhone 8
OS: iOS 15.4.1
App: Ruuvi Station 0.7.7(255)
Ruuvi Gateway myös käytössä
Location: not determined
Photo Library: authorized
Camera: not determined
Notifications: authorized
------------------------------------------

**Comment by markoaamunkajo** [comment]
@priyonto 
Tested with App store and Test Flight builds. Both are not updating calibrated values when Cloud Mode is on.

**Comment by priyonto** [comment]
Thanks @markoaamunkajo. I will check into this tomorrow hopefully.

**Comment by markoaamunkajo** [comment]
QA passed
