### ISSUE TITLE
Configuration option : choose readings on main screen - enhancement

### ISSUE THREAD

**Issue by DG12** [ruuvi/com.ruuvi.station.ios#89]
The current display of temperature, humidity, Air Pressure and RSSI are interesting but it would be much nicer if the user could choose which readings are displayed.

My personal experience is that once a tag is established the RSSI is not really interesting and AirPressure is too difficult to interpret meaningfully.

Many of the use cases  I have found are dependent on the orientation of the tag. See:
https://f.ruuvi.com/t/door-position-monitor-stock-tag-stock-firmware/4045
https://f.ruuvi.com/t/monitor-varmit-trap/4213
https://f.ruuvi.com/t/sump-pump-failure-alert/4127
https://f.ruuvi.com/t/garage-door-monitor/3800

It would be helpful if the user could choose which readings were presented on the main screen for example not showing RSSI, air pressure rather showing X, Y, Z, movement Counter.

Additionally choosing more than one to be "highlighted" as the current temperature is now.

A really cute idea for displaying the Z acceleration would be an arrow pointing the orientation of the tag. X/Y acceleration might be displayable as a clock face like dial.

**Comment by rinat-enikeev** [comment]
@laurijamsa could you please review the UX proposal?

**Comment by laurijamsa** [comment]
This feature is coming on the new UX. Closing this issue.
