### ISSUE TITLE
Querying for firmware version doesn't always timeout - 1.1.1(291)- outlier

### ISSUE THREAD

**Issue by DG12** [ruuvi/com.ruuvi.station.ios#901]
230E, user not signed in,
Sensor Settings FIRMWARE
shows
Current Version bfb837c+default

tap update

Seems that station queries tag **again** and  
![image](https://user-images.githubusercontent.com/2365961/166575863-73e87a2a-d47e-4fd8-b7f6-a6ae5d0baecc.png)

**SOMETIMES** (Every other time? +/- ?) gets hung spinnering 
![image](https://user-images.githubusercontent.com/2365961/166575062-6e303659-b032-41d1-adbc-a99803aa9f21.png)

tap go back, update, shows Current version.
tap go back, update, spins
tap go back, update, spins
tap go back, update, spins
tap go back, update, shows Current version.
tap go back, update, shows Current version.
tap go back, update, spins
tap go back, update, spins

**Comment by priyonto** [comment]
When the firmware update page is opened the current version is fetched again from the bluetooth. The timeout period is 30 seconds. But, probably we can improve this experience by not fetching the firmware version while it's already fetched on the tag settings page.

**Comment by DG12** [comment]
Somehow most sensors time out after   10(?) seconds but
230E , updating by advertisements ever few seconds, reports current Version v3.31.1
but doesn't time out after (at least ) 3 minutes .
tap go back,  tap update reports you are running the latest firmwareersion...
go back
tap update spinning spinning.

**Comment by priyonto** [comment]
Noted, will investigate. Thank you.

**Comment by priyonto** [comment]
@DG12 We recommend updating the tag to one of the official FWs with either DFU or nRF Connect. Updating the firmware should solve this issue.

**Comment by priyonto** [comment]
I am closing this one for now. If updating the firmware doesn't solve the issue, we will reopen this. Thank you.
