### ISSUE TITLE
Sensor now out of range cannot alter alerts 1.1.1(291) defect 

### ISSUE THREAD

**Issue by DG12** [ruuvi/com.ruuvi.station.ios#902]
Not signed in
While in range, set alert 450A alert range 47-89F
Now 46F 

Alert.on slider is and range controls are disabled.
"Alarms are disabled because you are not connected to device." Why must I be connected to device?
![image](https://user-images.githubusercontent.com/2365961/166584306-378b84a8-b392-46e5-94d5-93cd5d0c0bf1.png)

**Comment by priyonto** [comment]
FYI - iOS local sensor alerts only work while the tag is connected to the device. iOS can't scan in the background if tag is not connected. Therefore, for alerts to work on iOS the connection is a must.

**Comment by DG12** [comment]
This is not about the alerts working rather changing the settings.

**Comment by priyonto** [comment]
Exactly. That's what I wanted to answer. If alert is not available there's no point of keeping the alert settings enabled. Right?

**Comment by laurijamsa** [comment]
Maybe we could allow adjusting alerts but if yes, then some other problems could appear. Then user could for example happily assume that alerts are working, even if the keep connection mode wasn't turned on or no connection can be established (sensor connected to another phone at the same time for example). Ideas on how to avoid these types of issues but showing alert sliders are welcome.

**Comment by laurijamsa** [comment]
We're about to open another issue about not hiding alerts in any circumstances. Closing this one as a duplicate.
