### ISSUE TITLE
App freezes for 3-4 seconds when app is launched

### ISSUE THREAD

**Issue by priyonto** [ruuvi/com.ruuvi.station.ios#905]
- Disabling the bluetooth fixes the issue.

**Comment by laurijamsa** [comment]
User who reported this said that he suspects that the app gets too heavy load because he has 10 sensors updating from Ruuvi Cloud and additionally 10 Bluetooth sensors nearby the phone. Some loading event is not threaded properly, maybe.

**Comment by priyonto** [comment]
I remember discussing this with @io53 on our channel. When sensors number increased we noticed glitches in synchronisation. We have an issue on that already #802 . We can close one of these as duplicates.

**Comment by priyonto** [comment]
Closing as duplicate of #802
