### ISSUE TITLE
firmware update: doesn't report but said  v3.28.0 1.1.1(291) - outlier

### ISSUE THREAD

**Issue by DG12** [ruuvi/com.ruuvi.station.ios#906]
EC0F Sensor Settings Current Version says v3.28.0 but
tap on update reports in 3 seconds
 "Your sensor doesn't report its current firmware version"

**Comment by priyonto** [comment]
@DG12 Could you please try removing and re-adding the sensor? In my testing I couldn't reproduce it yet on my end. I tried on tags with new and very old firmware.

**Comment by priyonto** [comment]
I was unable to reproduce this issue. Another reason can be when tapping on the update the BT communication did not took place properly. I am handing it over to our QA @markoaamunkajo to test more.

**Comment by markoaamunkajo** [comment]
@priyonto this happens when I'm already in connected mode on another iOS device and checking the Firmware Update page on the device that is not connected.

**Comment by priyonto** [comment]
Thank you @markoaamunkajo

That's understandable. Probably shouldn't allow checking(disable the button or so?) firmware in such scenarios?

**Comment by priyonto** [comment]
Thanks. Please do update here once you are able to reproduce it. :)

**Comment by DG12** [comment]
Is there an easy way to see if RuuviTag is connected to a mobil?

**Comment by DG12** [comment]
I guess using the app on iOS,  battery dead on android, will charge

**Comment by markoaamunkajo** [comment]
Closing this card for now, nothing to do.
