### ISSUE TITLE
No new sensors in Bluetooth range  - 1.1.1(291) - nit

### ISSUE THREAD

**Issue by DG12** [ruuvi/com.ruuvi.station.ios#908]
Add a New Sensor reports:

**(** No sensors on Bluetooth range **)**

Should be:

No **new** sensors **in** Bluetooth range.

+++++
**NEARBY** RUUVI SENSORS

should be (?)

**NEW** RUUVI SENSORS

**Comment by priyonto** [comment]
Personally, I don't think the above suggested is a good idea. Adding the "new" word will make more confusion here and makes less sense. Please share your thoughts. @laurijamsa

**Comment by laurijamsa** [comment]
The grammar typo can be fixed for sure but other mods seem not to really important to me. This is a wrong repository for this issue too.

**Comment by DG12** [comment]
What repo should this be?

**Comment by laurijamsa** [comment]
https://github.com/ruuvi/station.localization
