### ISSUE TITLE
Offset corrected value is updated with next cloud sync or bluetooth measurement

### ISSUE THREAD

**Issue by priyonto** [ruuvi/com.ruuvi.station.ios#909]
- Probably an improvement of updating it immediately will make the experience better.

**Comment by markoaamunkajo** [comment]
1.3.0(305)

@priyonto Looks like not perfect for local BT.
In video I changed pressure to 900 and waited in charts view, but it didn't change until I exit charts view and reload view.

https://user-images.githubusercontent.com/50437378/176347585-98fef7d5-1374-4c80-903b-af66b7d01cc0.mov

**Comment by markoaamunkajo** [comment]
1.3.0(306)

Discussed in DM. The values are not changing immediately when in Cloud mode.

**Comment by markoaamunkajo** [comment]
1.3.0(307)

Testing in cloud mode. Looks like it has improved but the chart is still sometimes not updating correctly after calibration.

https://user-images.githubusercontent.com/50437378/176818484-799be4d6-6721-49d9-9fe3-f1ed2ca8aed8.mp4

**Comment by markoaamunkajo** [comment]
QA passed
