### ISSUE TITLE
Export filename only partial - 1.1.1 (291) nit

### ISSUE THREAD

**Issue by DG12** [ruuvi/com.ruuvi.station.ios#910]
Ruuvi BB12_20220513-1750.cvs

Should Be:
Ruuvi BB12 **water inlet**_20220513-1750.csv

**Comment by priyonto** [comment]
Could you please share more on this? preferably a screen record? I can see the export file contains the full name of the tag on the file in my testing. Thanks.

**Comment by DG12** [comment]
Oops.
The name on the android included **water inlet.**
As I was not logged in, IOS didn't;t get the same name.

**Comment by priyonto** [comment]
Okay. Closing.
