### ISSUE TITLE
Export voltage heading is "Voltage (V)" SB Voltage 1.1.1(291) - nit

### ISSUE THREAD

**Issue by DG12** [ruuvi/com.ruuvi.station.ios#911]
Android Is Voltage
IOS is   "Voltage (V)"
webui   Battery Voltage

Do all the text fields need to within quotes?
If they need quotes then android and IOS need fixing.

**Comment by priyonto** [comment]
@laurijamsa 

What should be the accurate header title for Voltage? Three platforms have three different tiles now. 

Also, should the headers and values be within double quotes?

**Comment by laurijamsa** [comment]
Export unifications are on @markoaamunkajo todo

**Comment by markoaamunkajo** [comment]
Moving this to done handled on other cards.
