### ISSUE TITLE
Tags not active no longer show last activity.  0.6(25) thru 0.6(36)

### ISSUE THREAD

**Issue by DG12** [ruuvi/com.ruuvi.station.ios#92]
Tags which remain from previous version but have not been active recently no longer display last time data received nor do they show last data received.
![ruuviBlank](https://user-images.githubusercontent.com/2365961/86070227-1fad0380-ba4a-11ea-8516-2ef0274983df.jpeg)

**Comment by DG12** [comment]
Is this due to a change in data store. Perhaps a mention in the announcment regarding this is all that is needed.

**Comment by DG12** [comment]
As of 0.6(36) this appears to be intentional. That is values, especially "Updated" , are nulled / initialized after a tag is not seen for a longer time. This is undesirable as it is no longer possible to determine when the tag was last nearby.

**Comment by rinat-enikeev** [comment]
@DG12 long time is 3 days or 72 hours. Yes, this is intentional to avoid overheating charts.

**Comment by DG12** [comment]
Could it somehow suppress chart, but leave values viewable?

**Comment by rinat-enikeev** [comment]
we can leave the last point, but... it will look ugly on charts. Consider you've left for 10 days. There will be one point at "10 days before" and lots of points starting the moment you've again in range of tag. But doable, thanks for the feedback, nice feature request.

**Comment by rinat-enikeev** [comment]
Any update?

**Comment by rinat-enikeev** [comment]
@DG12 is this issue still relevant?

**Comment by rinat-enikeev** [comment]
Please feel free to reopen if still relevant.
