### ISSUE TITLE
6 sensors in Bluetooth range only 2 gets read over BT and rest coming from cloud 

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station.ios#920]
Description:

1.0.0(278), cloud mode disabled

I noticed that when I have 6 RuuviTag sensors in Bluetooth range iOS app only reads 2 of them over BT and rest will come from the cloud. I wonder why that happens. Today same issue. Bluetooth scanner shows all sensors beautifully.

2/6 tags work via BT, doesn't matter if I take phone to few centimeters of tag, still it's fetched from the cloud.

Huomasin eilen että tässä kun on 6 kpl RuuviTageja BT-kantaman alueella, niin nyt ei jostain syystä IOS appsi lue kuin kahta suoraan BT:n yli ja loput tulee pilvestä, mistähän se johtuu? Tänään jatkuu sama homma. BT-skannereilla kaikki tagit näkyy kauniisti.

**Comment by markoaamunkajo** [comment]
@priyonto I have not been able to reproduce this issue with 1.2.0(296)

**Comment by priyonto** [comment]
Logging out and back in fixed the issue but further investigation will be carried out.

**Comment by markoaamunkajo** [comment]
1.1.3(299) iPhone 7 15.5, Reproduced. Updating sensors seems to get confused after switching Cloud mode toggle. See attached video.
The sensor sync should have moved all sensors to fetch last datapoint from cloud and update last source icon to cloud.

https://user-images.githubusercontent.com/50437378/171135195-81891fa1-6685-4ffb-989a-7f1a3e696fca.MP4

**Comment by priyonto** [comment]
@markoaamunkajo Thank you. I was able to reproduce it. The toggle transition is not smooth. One thing I noticed while checking the android app is - The toggle shows the latest point, I think but the source is the BT icon until the next cloud sync. Should we create an issue on that?

**Comment by markoaamunkajo** [comment]
QA passed
