### ISSUE TITLE
Investigate power consumption status when tags are in "Connected" state. 

### ISSUE THREAD

**Issue by priyonto** [ruuvi/com.ruuvi.station.ios#921]

**Comment by laurijamsa** [comment]
We've decided in the meeting just to modify the settings text part to tell that the bg scanning setting interval is only bg history saving interval and alerts still come through all the time.

**Comment by priyonto** [comment]
In addition- The investigation for several days on this card shows about 6-8% of battery consumption if several tags are used in the connected mode for 12 hours which is considered normal as Bluetooth scanning continues to run all the time in the background. Also, it should be noted that the consumption depends on the battery health of the device as well.

**Comment by priyonto** [comment]
We already have this mentioned on the background scanning that it's data logging interval. I am closing this issue, therefore.
