### ISSUE TITLE
Add critical alerts for iOS 15.0 and above

### ISSUE THREAD

**Issue by priyonto** [ruuvi/com.ruuvi.station.ios#937]
Ref: https://developer.apple.com/forums/thread/696552

**Comment by priyonto** [comment]
@DG12 https://developer.apple.com/forums/thread/696552. Please check this.

**Comment by DG12** [comment]
Thank you

**Comment by laurijamsa** [comment]
We're not going to implement this but instead will create sound alerts: https://github.com/ruuvi/com.ruuvi.station.ios/issues/1100

Closing this one.
