### ISSUE TITLE
1.1.3(299) Updating 2.5.9 sensor df3 didn't have expected result

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station.ios#941]
Description:

User added sensor with fw 2.5.9 df3 mode to Ruuvi Station, then updated fw to 3.31.1
Then he proceeds to claim it to cloud, but it says sensor already claimed with email aa**@gmail.com. This is the same account I'm logged in as. Then user deletes sensor and now he sees other sensors in Ruuvi Station go crazy.

See attached video. This is recorded after removing sensor D2D1.

https://user-images.githubusercontent.com/50437378/171782091-9e6fe9eb-dd90-4428-b795-d145b905b98a.mov

**Comment by markoaamunkajo** [comment]
2.5.9 issues are known so this in backlog for evaluation @priyonto

**Comment by markoaamunkajo** [comment]
![IMG_8717](https://user-images.githubusercontent.com/50437378/171782683-dfa67f81-fa27-4316-a683-3f2583c8e813.PNG)
Also after updating firmware update screen was stuck at this, only got out from it by killing app.

**Comment by priyonto** [comment]
Known issue:
DF3 Sensors go into connected mode after firmware update and can't be disconnected. To solve this, kill the app and reopen it.

**Comment by markoaamunkajo** [comment]
1.3.0(315)

First update test after adding tag gave me this error after reaching 50%. Sensor was in df3 mode.

![IMG_9183](https://user-images.githubusercontent.com/50437378/190935298-790ce730-01c4-4457-acf4-0eb9305a1d6b.PNG)

Second update was successful. I don't have this sensor with any other phone at the moment.

**Comment by priyonto** [comment]
This error is not related to DF3 tags or the changes made on the migration. This is an error thrown by the DFU library itself while updating the firmware. This is the error: https://github.com/NordicSemiconductor/IOS-DFU-Library/blob/5906bc522a3eb2040644b1063019e3516456fdb1/iOSDFULibrary/Classes/Implementation/SecureDFU/Characteristics/SecureDFUControlPoint.swift#L275

I have no idea why this was thrown. But, I would suggest you to run a couple of test runs and see how it goes.

**Comment by priyonto** [comment]
Decision: For these type of errors show an user understandable popup.

**Comment by priyonto** [comment]
Closing as completed.
