### ISSUE TITLE
Unify the font across the app

### ISSUE THREAD

**Issue by priyonto** [ruuvi/com.ruuvi.station.ios#949]
- Currently, font used on the sensor settings, app settings, and few other screens are not the same as the font used on the card. 
- Let's review and unify the font across the app.

**Comment by markoaamunkajo** [comment]
Sensor Settings: Alerts is written in small - should be caps
![IMG_C00BBCEB7A0C-1](https://user-images.githubusercontent.com/50437378/180356173-64c29572-f84d-4288-9e1a-6c05d7ff762f.jpeg)

**Comment by markoaamunkajo** [comment]
1.3(312)

Please recheck font size on titles, if my eyes are seeing correctly feels like GENERAL is different size to ALERTS

![IMG_4910497D10EA-1](https://user-images.githubusercontent.com/50437378/181729709-297de96c-4fd5-4b55-8ede-c05b3f81c42b.jpeg)

**Comment by priyonto** [comment]
@markoaamunkajo I have done extensive checking on this by recreating the UI. I don't think they are different.

**Comment by markoaamunkajo** [comment]
Ok moving to done
