### ISSUE TITLE
Correcting login code is awkward  1.2.0(303) - nuisance 

### ISSUE THREAD

**Issue by DG12** [ruuvi/com.ruuvi.station.ios#955]
If the incorrect login code is entered (for example the previous one, perhaps expired) 
when entering the new one, it is validated on every key presses.
Of course every one fails until the 4th character is entered.

**Comment by priyonto** [comment]
@DG12 would it be possible for you to share a screen record of this? I have tried but was not able to reproduce it on the latest version(v1.2.1) of the app. Thank you.

**Comment by DG12** [comment]
What do you experience if you enter the incorrect  login code?
I will try to record it but being in Alaska without my Android phone, I will have to beg my wife to borrow her phone. I'm guessing you don't know how that goes :-)

**Comment by priyonto** [comment]
@DG12 Please take your time to do this. 

So far, for me, the newly entered code after entering a wrong code only tries to verify at the last character, not on every keypress.

**Comment by DG12** [comment]
Please download and watch this video. http://mybeacons.info/loginErrorAckward.html

**Comment by markoaamunkajo** [comment]
1.3.0(307)
This is the mentioned behavior @priyonto . It works for second attempt but after that tap on any box sends code.

https://user-images.githubusercontent.com/50437378/176986053-e905ecfb-32e0-4a11-9631-dd5f8f7055b6.mov

**Comment by priyonto** [comment]
@markoaamunkajo Thank you for the video. It was very helpful.  I have modified the spec a little bit to unify with android and remove the issue reported. After a failed attempt the entered code is cleared and the full code has to be entered again which eliminated the issue of verification attempt on selection.

**Comment by markoaamunkajo** [comment]
QA passed
