### ISSUE TITLE
Updating from BT seems to frequent 

### ISSUE THREAD

**Issue by DG12** [ruuvi/com.ruuvi.station.ios#965]
It seems that the updating of BT data is too frequent.
I noticed that EC0F RSSI often updates but Measurement Sequence number does not increase.

Although this might be explained by multiple packets with same data, it seems to be too frequent for that.

Also I notice that  seconds ago frequently blinks  0 1 0  and stays 0 for a couple of seconds indicating that is has been updated more often than every second.

RSSI -79, -87,  -78, -87, -88,,-79,  -78, -92, -89,-96,-78 , -87

Neither the tag nor the iPhone are moving and in this short time span the environment isn't changing (i.e. no microWave, motor start/stop...)
Would a video help?

Perhaps this is related to excessive power usage?

**Comment by priyonto** [comment]
Please share the video if possible. That will be helpful. Thank you.

**Comment by laurijamsa** [comment]
Are we discarding duplicated packets and is Android doing so? If any differences, let's aim to unify the logics.

The latest RuuviTag firmware is measuring every ~2,5 seconds and is sending packets every ~1,25 seconds and every measurement is sent 2 times. This is for broadcasting. I'm not quite sure how this is when RuuviTag and phone are connected.

**Comment by DG12** [comment]
Did you get a change to view the video?

**Comment by priyonto** [comment]
@DG12 Was the tag "Connected"?

**Comment by priyonto** [comment]
Update:

I have made some improvements. So far the current situation is:
1. If the tag is not connected - advertisements are stored and visible on the card/tag settings page. The interval is ~1.25 as Lauri mentioned. Duplicates are ignored. 

2. If the tag is connected - both advertisements and heartbeats are stored and visible on the card/tag settings page. And, the interval here is also similar to the above. Measurements are stored only if the measurement sequence number is unique regardless of the source, which means duplicates are ignored. 

Note: Tags with data format 4 or less are storing all advertisements as they don't have measurement sequence numbers.

**Comment by DG12** [comment]
The tags are not connected.

**Comment by DG12** [comment]
Based on watching the "0s ago" blink, to 1 and very rapidly flip back to 0 and (appear to) stay on 0 for a few seconds,
As I am on a tour bus, movements (sometimes increments by 1 or more)  updates at sub second intervals

version 1.30.(307)

**Comment by markoaamunkajo** [comment]
@priyonto I think what DG12 means that counters and indicators are not ticking in sync

Ago indicator on sensor card can show 0 s ago for multiple seconds because it was considered seen twice under 1 second
RSSI indicator with Measurement Sequence Number also showed in video picking 2 values of RSSI but only 1 reading for measurement sequence.
