### ISSUE TITLE
Welcome says ... limits are hit, SB exceeded - minor

### ISSUE THREAD

**Issue by DG12** [ruuvi/com.ruuvi.station.ios#975]
or may even better .. 

"when current value is outside acceptable limits, and repeated hourly if still outside limits."

![image](https://user-images.githubusercontent.com/2365961/176340211-8e2fc728-b9bd-4acd-8cff-fb1ffa41f5ce.png)

**Comment by laurijamsa** [comment]
These onboarding screens are being redesigned. Closing.
