### ISSUE TITLE
Welcome shows bar CHART app use line GRAPH - defect -minor

### ISSUE THREAD

**Issue by DG12** [ruuvi/com.ruuvi.station.ios#983]
This is a bar CHART displayed during the welcome

![image](https://user-images.githubusercontent.com/2365961/176985066-712f4c1a-b762-4235-829a-a5258903320e.png)

The app uses a line GRAPH

![image](https://user-images.githubusercontent.com/2365961/176985114-e7ba8e4c-95ac-4a63-8a65-edfd22dfe145.png)

**Comment by laurijamsa** [comment]
The onboarding screens are being completely resigned. Closing.
