### ISSUE TITLE
iOS: The Great CSV Export unification

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station.ios#984]
Description:

Unify CSV export format same as attached file.
Notice row 1 is deleted (no filename on sheet)
Notice added units in parenthesis (g) (movements) (dBm)
Notice no value = empty field

[Ruuvi 636A_20220704-1817.csv](https://github.com/ruuvi/com.ruuvi.station.ios/files/9039577/Ruuvi.636A_20220704-1817.csv)

**Comment by markoaamunkajo** [comment]
@laurijamsa should we remove the ISO timestamp column on iOS too?

**Comment by laurijamsa** [comment]
Yes, that's what we agreed in the meeting and the golden sample CSV file doesn't have it.

**Comment by markoaamunkajo** [comment]
Moving back to @priyonto

**Comment by markoaamunkajo** [comment]
QA passed
