### ISSUE TITLE
Tapping simple widget not opening the correct card first time

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station.ios#989]
Description:

1.3.0(307)

User installed 1.3.0(307) and signed in to cloud, sensors were downloaded.
Then he added simple widget for 1 sensor, but no data is shown in widget after adding it.

https://user-images.githubusercontent.com/50437378/177231076-b9032112-36f1-4fc5-b86c-b8d6245728f3.mov

**Comment by markoaamunkajo** [comment]
Ok looks like rebooting phone fixed the empty widget issue. But there is another issue when user first time tap on sensor widget he is redirected to the Ruuvi Station app but not to correct sensor page. If he tries this again he will land to correct sensor page.

**Comment by priyonto** [comment]
@markoaamunkajo Thank you for the feedback. I am working on this.

**Comment by markoaamunkajo** [comment]
QA passed
