### ISSUE TITLE
Sync priority order is incorrect

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station.ios#990]
Description:

1.3.0(307)

User has RuuviTag added to freezer and temperature is dropping fast.
His sensor is added to cloud but Ruuvi Station is not running in Cloud mode, Bluetooth is giving new readings all the time.

But when sync from cloud occurs user is shown old reading briefly.

This is wrong, because newer data is available locally.

https://user-images.githubusercontent.com/50437378/177235826-62c5ac6f-40a3-4958-ad70-8d57f1969a67.mov

**Comment by priyonto** [comment]
@markoaamunkajo  Requesting checking on v1.3.0(308)

**Comment by markoaamunkajo** [comment]
1.3.0(308)
This is the experience still. I'm thinking the cloud sync logic is somewhat confusing here, will post to channel to discuss.


https://user-images.githubusercontent.com/50437378/179657736-bd27bd5c-9b70-4b1d-8cee-96d940cd620d.mov

**Comment by markoaamunkajo** [comment]
QA passed
