### ISSUE TITLE
Localise "Buy sensors" and "Buy Gateway" links

### ISSUE THREAD

**Issue by laurijamsa** [ruuvi/com.ruuvi.station.ios#994]
Make it so that if app language is something else than Finnish, link to the old URL but if app language is Finnish, link to Finnish URLs:

https://ruuvi.com/fi/tuotteet/

https://ruuvi.com/fi/gateway/

**Comment by andreevdenis** [comment]
Should be done similar way:
![image](https://user-images.githubusercontent.com/24788772/177561166-a6f401f3-fec0-4034-a9c6-056b08aa72aa.png)

**Comment by markoaamunkajo** [comment]
QA passed
