### ISSUE TITLE
1.3.0(308) Changing language breaks cloud functions

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station.ios#999]
Description:

Changing language can confuse cloud functions.

I have been able to login to Cloud and get 0 sensor cards created, also logging out from Cloud and leaving the sensor cards in app is possible. This seems to be related to app language before doing certain function. First I changed language right after onboarding and the logging into Cloud. Second time I made CSV export in one language and switched to another, made another export and then logged out from Cloud.

See attached video as example (sorry about failing to login on code screen couldn't see what I was writing lol):

https://user-images.githubusercontent.com/50437378/178183058-5932eae4-b1c3-4a2f-b801-9d0bc6e86d77.mov

**Comment by markoaamunkajo** [comment]
1.3.(309) @priyonto Looks like German people cannot log out from Ruuvi Cloud. 
Steps: Switch global language when using app.

![IMG_8961](https://user-images.githubusercontent.com/50437378/180128110-356becde-24e5-4ed6-8cda-ce2fafa554a3.PNG)

**Comment by markoaamunkajo** [comment]
QA passed

**Comment by markoaamunkajo** [comment]
Ooh noo too soon @priyonto 

1. I sign in to Ruuvi Cloud when using English system language

https://user-images.githubusercontent.com/50437378/181159990-9b47f9b1-b0a1-4403-a9e2-27f39042e9e2.mov

2. I switch system language to German during use, then log out from Ruuvi Cloud. Result!

https://user-images.githubusercontent.com/50437378/181160045-7b0ccf83-f18b-4286-b228-2d25cdeca98c.mov

**Comment by priyonto** [comment]
Something is telling me these issues were introduced when we implemented the apple recommended way of language settings but theoretically, I can't seem to find anything yet about that which could affect the functionalities. This needs some attention for sure.

**Comment by priyonto** [comment]
@markoaamunkajo I tried to reproduce the issue following the steps for a while, but I couldn't. I also tried switching between other languages. But, I am going to make a few underlying improvements and will push an update tonight.

**Comment by markoaamunkajo** [comment]
1.3.0(312)

User changed language from english to swedish after signing in to Ruuvi Cloud during onboarding, then immediately signed out and then changed system language to German.

Poof...sign in button from Menu has disappeared.
![IMG_8994](https://user-images.githubusercontent.com/50437378/181719531-7fe9dcef-f361-4e5b-92bb-b75eddbf3daa.PNG)

**Comment by markoaamunkajo** [comment]
QA passed for language change. Will open another issue for failing to remove all cloud cards on logout.
